### ISSUE TITLE
Read CA root from custom location

### ISSUE THREAD

**Issue by alexfd** [cloudflare/cloudflared#10]
Hi,

I'm trying to run the cloudflared on my RPI that runs Openelec. It acts as a media center box and it's always on, so it makes sense to transform it in a dhcp server + DoH.
`./cloudflared proxy-dns --address 0.0.0.0`
starts successfully, but when I do:
`dig @192.168.1.5 cloudflare.com`
I get:
`ERRO[0002] failed to connect to an HTTPS backend "https://1.1.1.1/dns-query"  error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: x509: failed to load system roots and no roots provided"`

Upon reading, seems that Go is looking in specific locations for the CA root file (see https://stackoverflow.com/questions/32631289/how-to-specify-custom-ssl-roots-with-go-on-linux).
On Openelec, /etc is mounted as readonly and it is not meant to be writable. I can only write to a specific directory.

Is there any way to provide tha CA root from a different file?

**Comment by dknecht** [comment]
We should probably include cfssl-trust

**Comment by alexfd** [comment]
Thinking a bit more on this and just had a _d'oh_ moment. 
As per https://github.com/OpenELEC/OpenELEC.tv/issues/4941, it seems this location is also queried:
```
// Possible directories with certificate files; stop after successfully
// reading at least one file from a directory.
var certDirectories = []string{
        "/etc/ssl/certs",               // SLES10/SLES11, https://golang.org/issue/12139
```

So as a workaround one can do:
```
mkdir -p ~/ssl/certs
wget https://curl.haxx.se/ca/cacert.pem -O ~/ssl/certs/cacert.pem
mount ~/ssl /etc/ssl    #no certs dir in /etc/ssl, thus created manually
```

`./cloudflared proxy-dns --address 0.0.0.0`

```
dig @192.168.1.5 cloudflare.com
cloudflare.com.         600     IN      A       198.41.215.162
;; Query time: 12 msec
```

COOL.

**Comment by sssilver** [comment]
Hi @alexfd,

We now support loading a custom CA out of a PEM-encoded file. [Here's how to use it](https://developers.cloudflare.com/argo-tunnel/reference/arguments/#origin-ca-pool).
