### ISSUE TITLE
💡Allow console access to the docker container

### ISSUE THREAD

**Issue by shadowjig** [cloudflare/cloudflared#1000]
**Describe the feature you'd like**
I would like to use the existing cloudflared docker container to configure my tunnel via a CLI.  But the container doesn't allow me to connect to it. 

Looking to run commands like these, in order to setup and configure the tunnel and run the tunnel all with one container.
cloudflared tunnel login
cloudflared tunnel create <NAME>

**Comment by obezuk** [comment]
Hi there,

The pre-built cloudflared image intentionally does not include an interactive shell as it designed to be as lightweight as possible and configured via inputs such as volume mounts and environment variables.

I recommend creating a separate container that supports an interactive shell, installing cloudflared and running commands there to manage tunnel configuration.
