### ISSUE TITLE
🐛 Checksum not match with provided on Github Releases

### ISSUE THREAD

**Issue by kamontat** [cloudflare/cloudflared#1004]
**Describe the bug**

Checksum on [Github Release v2023.6.1](https://github.com/cloudflare/cloudflared/releases/tag/2023.6.1) notes isn't matched with the actual output from shasum command on MacOS M1 [cloudflared-darwin-amd64.tgz](https://github.com/cloudflare/cloudflared/releases/download/2023.6.1/cloudflared-darwin-amd64.tgz).

**To Reproduce**
1. Download https://github.com/cloudflare/cloudflared/releases/download/2023.6.1/cloudflared-darwin-amd64.tgz
2. Run `sha256sum cloudflared-darwin-amd64.tgz`
3. The output doesn't matched with release note

The release notes version

```txt
2cf9474e82989455dc150b00324d188ec6fa4352be31901f4b7503a29b053237  cloudflared-darwin-amd64.tgz
```

The actual from command

```bash
$ sha256sum cloudflared-darwin-amd64.tgz
b2e8c01727bb7b1b8b974cf43651bee7e6c7e35470f0aea4fa67df0c0fcdaec8  cloudflared-darwin-amd64.tgz
```

**Expected behavior**

Same checksum value

**Environment and versions**
 - OS: MacOS M1
 - Architecture: ARM64
 - Version: 2023.6.1

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by obezuk** [comment]
Hi,

Thanks for letting us know. The sha256 is the hash of the compressed file inside the .tar.gz. I just extracted it and it matches:

```
tobezuk@laptop github-1004 % tar -zxvf cloudflared-darwin-amd64.tgz
x cloudflared
tobezuk@laptop github-1004 % shasum -a 256 cloudflared
2cf9474e82989455dc150b00324d188ec6fa4352be31901f4b7503a29b053237  cloudflared
```

I agree we can make this clearer in the release notes which we'll look in to.
