### ISSUE TITLE
cloudflared using more and more CPU the longer it's running (even when idle)

### ISSUE THREAD

**Issue by c0deright** [cloudflare/cloudflared#101]
Host: AWS EC2 t3.micro (2 Cores, 1 GB)
OS: Ubuntu GNU/Linux 16.04.6 LTS
Kernel: 4.4.0-1081-aws
libc6: 2.23-0ubuntu11

## Preface

I noticed in version `2019.4.1` (older versions too): the longer the `cloudflared` process is running (days/weeks) the more CPU the process is using even when idle.

For example, we had a docker host (AWS EC2 t3.micro) running 3 `cloudflared` processes to make 3 different ports available to the public. After some weeks the 3 `cloudflared` processes used so much CPU that they slowed down the applications running in the docker containers. Restarting all `cloudflared` processes solved the issue instantly while load dropped from ~0.5 to 0.01

Right now I do observe the same behaviour with `2019.4.1` on a different host running only one `cloudflared` process. The tunnel is 100% idle and not in use right now.

## top / constantly 5-6% CPU usage

```
top - 15:05:15 up 20 days, 21:02,  1 user,  load average: 0.13, 0.06, 0.01
Tasks: 115 total,   1 running, 114 sleeping,   0 stopped,   0 zombie
%Cpu0  :  1.0 us,  1.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  1.0 sy,  0.0 ni, 98.0 id,  0.0 wa,  0.0 hi,  0.0 si,  1.0 st
KiB Mem :   987552 total,    69252 free,   590028 used,   328272 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   237256 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                   
 3134 root      20   0  353624  21840   7356 S   5.0  2.2 987:47.40 cloudflared
    1 root      20   0  119720   4220   2368 S   0.0  0.4   0:08.24 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.16 kthreadd
```

## Running for almost 20 days

```
% ps f -o %cpu,%mem,start,etime,time,command -u root | grep -E '^%|cloud' ; echo ; date -R --utc
%CPU %MEM  STARTED     ELAPSED     TIME COMMAND
 0.0  0.1 15:15:07       00:00 00:00:00          \_ grep -E ^%|cloud
 3.4  2.2   May 09 19-23:05:46 16:28:22 /usr/local/bin/cloudflared --config /etc/cloudflared/config-foobar.yml --no-autoupdate

Wed, 29 May 2019 13:15:08 +0000
```

## Config

```
% cat /etc/cloudflared/config-foobar.yml
hostname: foobar.example.com
url: http://10.10.248.40:8080
logfile: /var/log/cloudflared-foobar.log
origincert: /etc/cloudflared/cert.pem
```

Any ideas what might cause this behaviour?

**Comment by sssilver** [comment]
Interesting.

Before we dive in further, do you happen to use a Cloudflare load balancer?

**Comment by c0deright** [comment]
No loadbalancer involved

**Comment by c0deright** [comment]
Did just reboot the ec2 instance and now cloudflared isn't constantly seen in `top`.
It shows itself rarely with 1% CPU.

**Comment by c0deright** [comment]
Just to give you an idea of what I'm talking about:

![cpu](https://user-images.githubusercontent.com/20477825/59045032-8d0a5700-887f-11e9-91f4-4503e62daf02.png)

**Comment by sodabrew** [comment]
Does this still happen with a newer release of cloudflared?

**Comment by c0deright** [comment]
Just checked the machine that was running 2019.4.1: `cloudflared` processes did use 1% each but Load was low. Seems to be a lot better.

Testing with 2019.7.0 now. Will report back in some time.

**Comment by c0deright** [comment]
Can't reproduce anymore with recent version.
