### ISSUE TITLE
📝2023.7.0 Changelog is confusing

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflared#1021]
**Available Documentation**
[Changes.md](https://github.com/cloudflare/cloudflared/blob/master/CHANGES.md) has
>  This feature is provided as **opt-out** and requires the flag to enable.

Which isn't consistent. It should probably be
>  This feature is provided as **opt-in** and requires the flag to enable.

**Comment by abelinkinbio** [comment]
Ah, thanks for flagging. We can help clarify that.

**Comment by DevinCarr** [comment]
Fixed here: https://github.com/cloudflare/cloudflared/commit/5abb90b5399be96e83112ff45fab5fc129226eb8
Thanks for the catch!
