### ISSUE TITLE
💡 Cloudflare custom user agent

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/cloudflared#1022]
**Describe the feature you'd like**
Currently, requests made by cloudflared use the standard Go HTTP user agent (`go-http-client`). This can be problematic if you want to block generic user agents while still wanting to use tunnels. It would be nice if there was a standard user-agent of something like `cloudflared` or `cloudflared/<version>` to be easier to allow those requests.

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?

**Additional context**
I can take a crack at this if it is something that is approved.

**Comment by DevinCarr** [comment]
Which requests are you referring to? Public Hostname requests from cloudflared to the origin (via ingress rules)? Or some other cloudflared operation?

I have recently tried to capture some of these (i.e. `cloudflared tail`) and make sure they are using the User-Agent of `cloudflared/<version>`: https://github.com/cloudflare/cloudflared/commit/b89c092c1b1cf843e59e6bb43f684efe3d263403#diff-b58953b1d451ae900c0e290e72052550c7a3245c8faca07f8117a7fd56e5eb50L181

**Comment by Cyb3r-Jak3** [comment]
@DevinCarr The ones I've noticed the most is for tcp specifically ssh access (not browser rendered ssh).

**Comment by DevinCarr** [comment]
I recently covered that one in this PR: https://github.com/cloudflare/cloudflared/commit/2b4815a9f50f4a39fe595df55f28706f58ad127e#diff-482f2c094f8b4fe0a3a6b1a6c2199a978805442f68f99dfb50067cf1b8b0b60bR87

**Comment by Cyb3r-Jak3** [comment]
Whelp, I feel silly. The client I was testing didn't have 2023.7.0 installed.
