### ISSUE TITLE
💡 Forward original http Host header to local service

### ISSUE THREAD

**Issue by SystemZ** [cloudflare/cloudflared#1036]
**Describe the feature you'd like**
Forward original `Host` header to local service.
It would allow a simple one rule catching of all hostnames and forwarding it to local proxy service which have all nitty gritty details configured that would be hard to do in cloudflared.

**Describe alternatives you've considered**
For massive deployments with many zones generating and maintaining big config file for cloudflared.
It includes a lot of duplicate entries with ` httpHostHeader` same name as hostnames it catches.
It's very cumbersome.

**Additional context**
Related issue which implemented overwriting `Host` header but it doesn't allow to forward original one yet:
https://github.com/cloudflare/cloudflared/issues/111

**Comment by jult** [comment]
Yep, I would very much like to see this implemented as well. Same issues arise with cloudflared tunnels (as reverse proxies to localhost devices and such). They show up as blank pages or the like..

**Comment by LunarN0v4** [comment]
heavy push on this  
for a project im currently working on, this is necessary and still not implemented

**Comment by 2manyvcos** [comment]
@LunarN0v4 This does in fact already work for me since at least April (since a related issue with SNI was fixed in #541).
I have cloudflared configured with a wildcard entry since then, which is working flawlessly with the reverse proxy that I put behind of cloudflared.

**Comment by LunarN0v4** [comment]
> @LunarN0v4 This does in fact already work for me since at least April (since a related issue with SNI was fixed in #541). I have cloudflared configured with a wildcard entry since then, which is working flawlessly with the reverse proxy that I put behind of cloudflared.

I'm using the Zero Trust dashboard and putting * in the HTTP host header field just causes the host to be set as "*:{serviceport}", so this doesn't work for me.

**Comment by LunarN0v4** [comment]
> > @LunarN0v4 This does in fact already work for me since at least April (since a related issue with SNI was fixed in #541). I have cloudflared configured with a wildcard entry since then, which is working flawlessly with the reverse proxy that I put behind of cloudflared.
> 
> I'm using the Zero Trust dashboard and putting * in the HTTP host header field just causes the host to be set as "*:{serviceport}", so this doesn't work for me.

Just had a read of the issue you mentioned and it seems to have a decent solution, I'll look into it and report my findings.

**Comment by SystemZ** [comment]
So time ago, I tested it again and I think it worked for my case described in first post, probably it was my fault at config or it was implemented already. With wildcard in DNS zone it works.

I'm closing this, if some of you have still same or similar problems, feel free to create separate issue.
