### ISSUE TITLE
can't load package

### ISSUE THREAD

**Issue by dodtsair** [cloudflare/cloudflared#105]
Instructions in main readme to install with go do not work on ubuntu 16.04

$ go install github.com/cloudflare/cloudflared/cmd/cloudflared
can't load package: package github.com/cloudflare/cloudflared/cmd/cloudflared: cannot find package "github.com/cloudflare/cloudflared/cmd/cloudflared" in any of:
	/usr/lib/go-1.6/src/github.com/cloudflare/cloudflared/cmd/cloudflared (from $GOROOT)
	($GOPATH not set)

**Comment by billthefarmer** [comment]
See https://github.com/cloudflare/cloudflared/issues/38#issuecomment-498166512.

**Comment by dodtsair** [comment]
@billthefarmer 

Are you referencing the build steps?

    pi@jennifer:~/gocode/src/github.com/cloudflare/cloudflared $ export PATH=$PATH:/usr/local/go/bin
    pi@jennifer:~/gocode/src/github.com/cloudflare/cloudflared $ export GOPATH=~/gocode
    pi@jennifer:~/gocode/src/github.com/cloudflare/cloudflared $ go clean
    pi@jennifer:~/gocode/src/github.com/cloudflare/cloudflared $ make cloudflared

Should this be run instead of go install?

**Comment by billthefarmer** [comment]
If you reference Go docs, you need the two export statements for `go install` to work.
```shell
$ export PATH=$PATH:/usr/local/go/bin
$ export GOPATH=~/gocode
```
I did `go clean` to tidy up the previous build which appeared to be buggy. Then used the makefile to build the latest release rather than the current master. You appear to have go-1.6 installed which won't build the latest release.

**Comment by dodtsair** [comment]
Yeah, that just makes my point more clear,

You google cloudflared and the first hit you get is the github link.  You click on that and the only instruction is
    go install github.com/cloudflare/cloudflared/cmd/cloudflared

Which will fail for the vast majority of users.  

With those two exports it still fails.  It fails for Mac as well:

    git clone https://github.com/cloudflare/cloudflared.git
    cd cloudflared/
    export GOPATH=/Users/michael.power/Workspace/go
    export PATH=$PATH:/usr/local/Cellar/go/1.12.5/bin/
    go clean
    make cloudflared
which results in

    go build -v -ldflags='-X "main.Version=2019.6.0" -X "main.BuildTime=2019-06-05-1812 UTC"' github.com/cloudflare/cloudflared/cmd/cloudflared
    can't load package: package github.com/cloudflare/cloudflared/cmd/cloudflared: cannot find package "github.com/cloudflare/cloudflared/cmd/cloudflared" in any of:
    	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/cloudflare/cloudflared/cmd/cloudflared (from $GOROOT)
    	/Users/michael.power/Workspace/go/src/github.com/cloudflare/cloudflared/cmd/cloudflared (from $GOPATH)
    make: *** [cloudflared] Error 1

**Comment by rennex** [comment]
I think I had to use `go get` instead of `go install` and it worked for me. If the env variables are not set, then I guess Go hasn't been properly installed?

But I agree that the readme is pretty bare-bones and may be more confusing than helpful :)

**Comment by dodtsair** [comment]
This worked for me:

    git clone https://github.com/cloudflare/cloudflared.git
    cd cloudflared/
    go clean
    go get github.com/cloudflare/cloudflared/cmd/cloudflared
    make cloudflared

**Comment by TownLake** [comment]
We've added [documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#build-from-source) on building `cloudflared` from source and are updating the readme; thanks again for the feedback.
