### ISSUE TITLE
Consider also installing a cloudflared@.service template

### ISSUE THREAD

**Issue by dodtsair** [cloudflare/cloudflared#106]
Since cloudflared supports a 1 to 1 relationship between the host and the cloudflared process I quickly found I wanted multiple cloudflared processes to be running on boot.

For systemd this can be accomplished with a cloudflared@.service template.  This provides the ability to run:
   sudo systemctl enable cloudflared@ssh

When called this way systemd will use the cloudflared@.service as a template file, providing a token %i and replacing it with, in this example, ssh.  

The template can be changed to the following:

    [Unit]
    Description=Argo Tunnel for %i
    After=network.target
    
    [Service]
    TimeoutStartSec=0
    Type=notify
    ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config.d/%i.yml --origincert     /etc/cloudflared/cert.pem --no-autoupdate
    Restart=on-failure
    RestartSec=5s
    
    [Install]
    WantedBy=multi-user.target

With this template file, I can create any number of new cloudflared instances by adding a corresponding file to the /etc/cloudflared/config.d directory.  

Something like: /etc/cloudflared/config.d/www.yml

    hostname:www.example.com
    url: http://localhost:80

Then you can enable it:

    sudo systemctl enable cloudflared@www

**Comment by sssilver** [comment]
Thanks for the detailed write-up!

Would you be able to submit a PR for this? We'd be happy to review it and get it merged!

**Comment by altmind** [comment]
ref: https://github.com/cloudflare/cloudflared/issues/59

**Comment by TownLake** [comment]
Thanks for the feedback and sorry for the delay [here](https://blog.cloudflare.com/many-services-one-cloudflared/). We recently launched support for this feature; you can read more about how it works here and a tutorial is available for the original use case [here](https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab). Let us know if you have any questions.
