### ISSUE TITLE
💡Docker environment variable for Metrics port

### ISSUE THREAD

**Issue by JvdMaat** [cloudflare/cloudflared#1061]
**Describe the feature you'd like**
I've scoured the web and found there is a command line option to enter -metrics localhost:12345 to set the metrics server port. However I am unable to find anything for a docker deployment. I tried the following, but that did not fix the metrics random listening port issue:
```
    environment:
      - TZ=${TZ}
      - TUNNEL_TOKEN=${CFTUNNELTOKEN}
      - METRICS=127.0.0.1:12345

```
**Describe alternatives you've considered**
No other options found to do this within docker. No docker-compose examples on the web that I was able to find.
Checked this GitHub repository and was unable to find any more info.
(And some documentation on how to run cloudflared in docker compose would be helpful, Aside from the basic one-liner on hub.docker.com there isn't anything available on what variables are supported)

**Comment by robsoncloud** [comment]
You should use the env variable TUNNEL_METRICS=192.168.1.17:12345.

**Comment by JvdMaat** [comment]
In case anyone else stumbles upon this. Fixed this by setting the TUNNEL_METRICS address to 0.0.0.0:12345 (ie, listening on all IPs).
It's now responding fine.
