### ISSUE TITLE
🐛Cloudflared service works fine on Debian 12, but not Fedora 38

### ISSUE THREAD

**Issue by bshor** [cloudflare/cloudflared#1065]
**Update**

This bug report below is my fault, or rather, the fault of Tailscale, which overwrote /etc/resolv.conf for me (since DNS settings are inherited from the host, which has tailscale installed). Why this affected Fedora and not Debian, not sure. But once [these steps](https://tailscale.com/kb/1188/linux-dns/#dhcp-dhclient-overwriting-etcresolvconf) from Tailscale are executed, everything worked again.

**Describe the bug**

I have absolutely new installations of Fedora 38 and Debian 12 into LXC containers within the Proxmox VE 8 (latest). I am unable to install the cloudflared service in the context of creating new (test) tunnels in Fedora, while in Debian it works perfectly.

**To Reproduce**

1. Create LXC container within Proxmox VE. It has built in templates for new installations of popular distros, like Debian and Fedora.
2. Create a (test) tunnel within the Cloudflare Tunnel Web UI. 
3. Use the correct command for the distribution.
4. In Debian, the service installs instantly:
```
2023-09-11T15:11:48Z INF Using Systemd
2023-09-11T15:11:48Z INF Linux service for cloudflared installed successfully
```
In Fedora, service installation times out:

```
2023-09-11T15:12:56Z INF Using Systemd
systemctl [start cloudflared.service] returned with error code exit status 1 due to: Job for cloudflared.service failed because the control process exited with error code.
See "systemctl status cloudflared.service" and "journalctl -xeu cloudflared.service" for details.
```

If it's an issue with Cloudflare Tunnel:
6. Tunnel ID : eb5f04b4-9f86-4f2a-bf2b-d4c7947e540a
7. cloudflared config: Not sure what this means. I am installing cloudflared from scratch. I'm a single user.

**Expected behavior**

The same easy installation in Fedora that I see in Debian

**Environment and versions**
 - OS: Linux test-f 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64 GNU/Linux
 - Architecture: AMD Ryzen 3700X
 - Version: 2023.8.2

**Logs and errors**
journalctl reveals:

```
Sep 11 15:19:18 test-f systemd[1]: Starting cloudflared.service - cloudflared...
░░ Subject: A start job for unit cloudflared.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit cloudflared.service has begun execution.
░░ 
░░ The job identifier is 8050.
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF Starting tunnel tunnelID=eb5f04b4-9f86-4f2a-bf2b-d4c7947e540a
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF Version 2023.8.2
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF GOOS: linux, GOVersion: go1.20.6, GoArch: amd64
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF Settings: map[no-autoupdate:true token:*****]
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF cloudflared will not automatically update if installed by a package ma>
Sep 11 15:19:18 test-f cloudflared[7577]: 2023-09-11T15:19:18Z INF Generated Connector ID: 7e388eac-1687-4fe8-8a0e-fdd9dbbeb07a
Sep 11 15:19:28 test-f cloudflared[7577]: 2023-09-11T15:19:28Z ERR Failed to fetch features, default to disable error="lookup cfd-feature>
Sep 11 15:19:38 test-f cloudflared[7577]: 2023-09-11T15:19:38Z ERR update check failed error="Get \"https://update.argotunnel.com?arch=am>
Sep 11 15:19:48 test-f cloudflared[7577]: 2023-09-11T15:19:48Z WRN Unable to lookup protocol percentage.
Sep 11 15:19:48 test-f cloudflared[7577]: 2023-09-11T15:19:48Z INF Initial protocol quic
Sep 11 15:19:48 test-f cloudflared[7577]: 2023-09-11T15:19:48Z INF ICMP proxy will use 192.168.68.106 as source for IPv4
Sep 11 15:19:48 test-f cloudflared[7577]: 2023-09-11T15:19:48Z INF ICMP proxy will use fe80::3c0a:9cff:feb2:fc0b in zone eth0 as source f>
Sep 11 15:20:18 test-f cloudflared[7577]: 2023-09-11T15:20:18Z INF Starting metrics server on 127.0.0.1:36419/metrics
```

**Additional context**
SELinux is disabled so that can't be an issue.

Note that in this install of Fedora I had added the cloudflare Fedora repo and installed using dnf. I have replicated the problem without using the package manager and just copying and pasting the command which uses curl to download the latest rpm package and installs that.

**Comment by himicoswilson** [comment]
how did you fix it, bro
