### ISSUE TITLE
proxy-dns IPv6 upstream does not work (macOS 10.14.5)

### ISSUE THREAD

**Issue by maugen** [cloudflare/cloudflared#107]
Configuring proxy-dns as follows:

`$ ./cloudflared proxy-dns --metrics localhost:5555 --port 5054 --upstream "https://[2606:4700:4700::1111]/dns-query"`

starts up fine:

```
INFO[0000] Adding DNS upstream                           url="https://[2606:4700:4700::1111]/dns-query"
INFO[0000] Starting metrics server                       addr="127.0.0.1:5555"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://localhost:5054"
```

but DNS queries fail with a 403:

```
ERRO[0011] failed to connect to an HTTPS backend "https://[2606:4700:4700::1111]/dns-query"  error="returned status code 403"
```

Looking at a pcap, it looks like the TLS connection is established OK, and that the dns-query request itself is denied by the server.

An example curl works as expected:

`$ curl -s -H 'accept: application/dns-message' 'https://[2606:4700:4700::1111]/dns-query?dns=q80BAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB' | hexdump`

```0000000 ab cd 81 a0 00 01 00 01 00 00 00 01 03 77 77 77
0000010 07 65 78 61 6d 70 6c 65 03 63 6f 6d 00 00 01 00
0000020 01 c0 0c 00 01 00 01 00 00 1a 0d 00 04 5d b8 d8
0000030 22 00 00 29 05 ac 00 00 00 00 00 44 00 0c 00 40
0000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
0000080
```

**Comment by maugen** [comment]
[proxy-dns-error.pcap.zip](https://github.com/cloudflare/cloudflared/files/3269054/proxy-dns-error.pcap.zip)

**Comment by Tugzrida** [comment]
Seeing the same results on my mac when using cloudflared with `https://[2606:4700:4700::1111]/dns-query` and `https://[2606:4700:4700::1001]/dns-query`. Error 403 would suggest a server error, yes.

I've done testing with cloudflared and my own DoH server and was able to resolve via v4 and v6 with no issue, so at this point, it looks like an issue with cloudflare's servers.

Looking at the captured DoH traffic on my server(after decryption), there's no difference(at the http and dns level) between requests coming in over v4 and v6.

That being said, I also haven't been able to reproduce the error with curl, with either GET or POST.

**Comment by nathang21** [comment]
Seeing the similar results with my config file on mac OS.

Commenting out this line, and dns resolution works fine. But trying to enable ipv6 with that line and I can no longer resolve any DNS. 

```
logfile: /var/log/cloudflared.log
proxy-dns: true
# proxy-dns-address: "::1" # 
proxy-dns-upstream:
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
```

**Comment by maugen** [comment]
I just wanted to confirm that cloudflared is working as expected with IPv6 upstream.  Thank you!
