### ISSUE TITLE
Unable to create any tunnel. cloudflared fails with `API call to create tunnel failed with status 503` and Zero Trust Dashboard displays an error.

### ISSUE THREAD

**Issue by furquan-lp** [cloudflare/cloudflared#1079]
**Describe the bug**
I'm unable to create any Cloudflare tunnels for either of my two domains after deleting my old tunnel (which was functioning fine yesterday). Both the cli and the Zero Trust dashboard don't seem to work.

**To Reproduce**
1. Login to cloudflared cli using `cloudflared tunnel login` and select any domain
2. Create a tunnel, for example `cloudflared tunnel create mytunnel`
3. An error is displayed: `failed to create tunnel: Create Tunnel API call failed: API call to create tunnel failed with status 503: Service Unavailable`

**Expected behavior**
The tunnel should be created.

**Environment and versions**
 - OS: Debian GNU/Linux
 - Architecture: AMD Ryzen 3
 - Version: 2023.8.2 (built 2023-08-31-1506 UTC)

**Logs and errors**
Error:
```
$ cloudflared tunnel create mytunnel
failed to create tunnel: Create Tunnel API call failed: API call to create tunnel failed with status 503: Service Unavailable
```
```
$ cloudflared tunnel list
API call to list tunnels failed with status 503: Service Unavailable
```

**Additional context**
Screenshot of the error on the Zero Trust dashboard while attempting to create a tunnel: https://i.postimg.cc/T2L806kF/Snapshot-2023-10-09-02-33-06.png

**Comment by sudarshan-reddy** [comment]
We're aware. 

See https://cloudflarestatus.com/

**Comment by furquan-lp** [comment]
Ah I see, thanks. I'll keep an eye on that, and look for alternatives in the meantime.

**Comment by furquan-lp** [comment]
Tunnels seem to be working again. Both through the cli and the Zero Trust dashboard so I'm closing this issue.
