### ISSUE TITLE
Websockets much slower than proxied DNS

### ISSUE THREAD

**Issue by Lansenou** [cloudflare/cloudflared#1093]
**Describe the bug**
My websockets are really slow to connect when using cloudflared. This currently for me is a issue when using Home Assistant, since this uses a websocket to load the homepage.

I tracked down the issue to the cloudflared tunnel. When I use a DNS record that is proxied, it is handled by the same system and then everything works fast. When I remove this record and setup the tunnel again, it takes over 8 seconds to setup a websocket connection.

I've got a nginx proxy manager handling all connections, however even when I tried to point the tunnel straight to my home assistant the websocket was still slow to load.

**To Reproduce**
1. Configure a websocket server
2. Connect to it via a proxied DNS record.
3. Connect a websocket client directly to the server and notice it's connecting fast (enough)
4. Replace the DNS record for a tunnel entry.
5. Connect a websocket client directly to the server and notice how it's much slower to connect now.

6. Tunnel ID: 7da72734-fa3a-44d6-95ef-de5e51e6f8fe
7. cloudflared config: 
I've got 2 connectors, to test wether it had anything to do with what machine cloudflared was running on.
Version:  2023.10.0
Platform: linux_amd64

**Expected behavior**
I'd expect a websocket to connect just as fast without cloudflared as with a proxied dns record.

**Environment and versions**
 - OS: Ubuntu & Synology Nas
 - Architecture: AMD
 - Version: Ubuntu 22.04.2 LTS & DSM 7.2

**Logs and errors**
Using the slow setup with my program I get the following results:
Connection wss://ha.example.com/api/websocket took: 00:00:**08.2229584** to establish (8 secs)
Connection wss://ha.local.example.com/api/websocket took: 00:00:**00.0754235** to establish (0.08 secs)

Using the proxied dns variant I get the following results:
Connection wss://ha.local.example.com/api/websocket took: 00:00:**00.0784335** to establish (0.08 secs)
Connection wss://ha.example.com/api/websocket took: 00:00:**00.4935984** to establish (0.5 secs)

**Additional context**
The c# code I used to test it, pretty much came down to this:

```csharp
void Test()
{
    WebsocketTest("wss://ha.example.com/api/websocket"); // Via cloudflare
    WebsocketTest("wss://ha.local.example.com/api/websocket"); // e.g. 192.168.1.1
}

async void WebsocketTest(string url)
{
    using (var ws = new ClientWebSocket())
    {
        var sw = Stopwatch.StartNew();
        await ws.ConnectAsync(new Uri(url), CancellationToken.None);
        sw.Stop();

        var elapsed = sw.Elapsed;

        Debug.WriteLine($"Connection {url} took: {elapsed} to establish");

        await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, CancellationToken.None);
    }
}
```

**Comment by Geczy** [comment]
i have this issue right now :(
