### ISSUE TITLE
🐛 No macOS/Darwin binaries

### ISSUE THREAD

**Issue by nikolay** [cloudflare/cloudflared#1094]
**Describe the bug**
The latest release lacks macOS binaries.

**Comment by sudarshan-reddy** [comment]
Indeed. We’re aware of this and working on a fix.

**Comment by nikolay** [comment]
Any luck, @sudarshan-reddy? You broke a lot of package managers such as asdf, aqua, etc.

**Comment by sudarshan-reddy** [comment]
Should be fixed now. Let me know if you still have problems.
