### ISSUE TITLE
🐛 2023.10.0 Release is missing SHA256 sums

### ISSUE THREAD

**Issue by xarses** [cloudflare/cloudflared#1096]
The latest [release](https://github.com/cloudflare/cloudflared/releases/tag/2023.10.0) is missing the SHA256 sums that the prior releases such as [2023.8.2](https://github.com/cloudflare/cloudflared/releases/tag/2023.8.2) had.

**Comment by leandrodlr-bmc** [comment]
In this version the link to mac is broken

**Comment by Naveennb18** [comment]
Hi, Do we have any update on this? would someone be so kind to provide any ETA please?

**Comment by sudarshan-reddy** [comment]
Apologies for the delay.  I'm looking into this and will provide an update soon.

**Comment by sudarshan-reddy** [comment]
Should be fixed now. Let me know if you still have issues.
