### ISSUE TITLE
Make cloudflared -> cloudflare connect over http proxy

### ISSUE THREAD

**Issue by davidkarlsen** [cloudflare/cloudflared#110]
We need to be able to connect to cloudflare via http proxy in order to use cloudflared.

**Comment by davidkarlsen** [comment]
Or is it already supported? https://github.com/cloudflare/cloudflared/issues/87 Maybe some docs are needed?

**Comment by moderation** [comment]
I'm proxying cloudflared through Envoy proxy successfully.
```
---
proxy-dns: true
proxy-dns-upstream:
  - "http://127.0.0.1:5353/dns-query"
```

**Comment by davidkarlsen** [comment]
how about the http traffic? e.g. to create the normal cloudflared argo tunnel?

**Comment by hazcod** [comment]
I'm having issues using `cloudflared` behind a corporate web proxy as wel.
Altough I see references to `http.ProxyFromEnvironment`, it is still trying to dial to the edge directly on port 7844.

**Comment by davidkarlsen** [comment]
`time="2020-02-03T18:40:08Z" level=error msg="Unable to dial edge" connectionID=0 error="DialContext error: dial tcp 198.41.192.47:7844: i/o timeout"`

**Comment by davidkarlsen** [comment]
I got response from support now:

```
XXX (Cloudflare) Feb 21, 12:42 AM PST Hi David,After checking with our product team, I am afraid to confirm that Argo tunnel is available only on port 7844. It is fixed and unchangeable.I will go ahead and mark this ticket as resolved. However, if you have any further questions or concerns simply respond to this email and we will be happy to assist further.Best regards, 
XXX
```

So I guess this is not going to happen. https://ngrok.com/ will work though.

**Comment by hazcod** [comment]
@davidkarlsen Why would the port matter? The problem is that they do not honor HTTP_PROXY for their edge dialing.

**Comment by davidkarlsen** [comment]
Yeah - that's what in the support ticket, to funnel this traffic through proxy - which they don't support - hence we see the direct traffic attempt in the log (which fails).

**Comment by hazcod** [comment]
Related: https://github.com/cloudflare/cloudflared/issues/170

**Comment by tjb900** [comment]
> So I guess this is not going to happen. https://ngrok.com/ will work though.

Just to save anyone else some time who sees this and thinks it might solve their problem, using a proxy is an "enterprise" feature for ngrok.
