### ISSUE TITLE
🐛 `latest` no longer published on Docker hub

### ISSUE THREAD

**Issue by ruurtjan** [cloudflare/cloudflared#1145]
**Describe the bug**
There is currently no Docker image on Docker Hub tagged `latest`. If this is intended, then the readme in the Docker Hub page should be updated, as that still contains a reference to that tag.

**To Reproduce**
```docker run cloudflare/cloudflared:latest tunnel --no-autoupdate --hello-world```

**Comment by ruurtjan** [comment]
It appears that images are not published to Hub at all anymore.

The most recent image is from October last year: https://hub.docker.com/r/cloudflare/cloudflared/tags

**Comment by jcsf** [comment]
Hi,
We are aware that the docker image is currently broken. We are fixing it and will provide a new release with all binaries and docker images fixed ASAP.

**Comment by jcsf** [comment]
#1143 #1132 #1144

**Comment by FunkEngine2023** [comment]
They rolled back to 23.10 just a few moments ago...  2024.1.0 was very severely under-baked when the latest tag got applied to it about 5 hours ago...

![Monday2.png](https://github.com/cloudflare/cloudflared/assets/123712145/6468abff-8cec-4739-9fba-0a8fc6efd8ec)

![engfeh.png](https://github.com/cloudflare/cloudflared/assets/123712145/c0e13f63-cc93-4e06-b43f-dabf4eb2d0eb)

![Monday.png](https://github.com/cloudflare/cloudflared/assets/123712145/a287872b-ba8e-4136-b741-1d6f38b486f8)

![Release-2024.1.0-cloudflared.png](https://github.com/cloudflare/cloudflared/assets/123712145/878c91de-fdaa-477d-b9b3-afc2d5c6d844)

![Sighh.png](https://github.com/cloudflare/cloudflared/assets/123712145/0b055bed-18cc-4b44-818a-5c6bcc0dfd9a)

![Premature-Release.png](https://github.com/cloudflare/cloudflared/assets/123712145/d334700c-4a28-4abb-8a35-a6c9f8c7ecf9)

**Comment by jcsf** [comment]
latest tags are available again. Will close the issue.

**Comment by ruurtjan** [comment]
Thanks for the quick replies and the fix :)
