### ISSUE TITLE
`--edge-bind-port`💡

### ISSUE THREAD

**Issue by Manouchehri** [cloudflare/cloudflared#1157]
**Describe the feature you'd like**
Similar to `--edge-bind-address`, I'd like `--edge-bind-port`.

**Additional context**
This is useful for firewalling as I can specify the exact source and destination ports.

**Comment by joliveirinha** [comment]
Unfortunately this is something we can't do because we rely on the 4 tuple being used to have some fine grained control on how the traffic is ingressed into our DCs. 
So, having the capability of changing the source port being used is something that cloudflared actually does on purpose.
