### ISSUE TITLE
💡Anyway to enable TCP L4 Proxy with protocol_proxy over Cloudflared Tunnel？

### ISSUE THREAD

**Issue by Zerorigin** [cloudflare/cloudflared#1159]
**Describe the feature you'd like**
The same as title, it's to expose some special TCP services directly to the public network, rather than using them only within the team private network.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
These services are load-balanced on the intranet through a proxy_protocol. There are no corresponding encryption and decryption certificates on the load servers, it's only in the endpoint-server and user endpoints.

**Comment by jcsf** [comment]
Cloudflare has support for it using [Cloudflare Spectrum](https://developers.cloudflare.com/spectrum/). So, for now, we are not considering having Cloudflare Tunnel doing that.
