### ISSUE TITLE
🐛 Cloudflare tunnel fails to come up when re-deploying

### ISSUE THREAD

**Issue by mike12806** [cloudflare/cloudflared#1165]
**Describe the bug**
When I attempt to re-deploy an existing container with latest image (after initially deploying from the cloudflare script), I get the following error:

“'Network-scoped alias is supported only for containers in user defined networks'

**To Reproduce**
1. Configure '...'
2. Run '....'
3. See error

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 618e5748-220a-44f2-8a02-42f556a8582c
5. cloudflared config: Docker 

**Expected behavior**

**Environment and versions**
 - OS: [e.g. MacOS] Ubuntu 22.04
 - Architecture: [e.g. AMD, ARM] Docker
 - Version: [e.g. 2022.02.0] Docker 20.10.17

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by mike12806** [comment]
> **Describe the bug** When I attempt to re-deploy an existing container with latest image (after initially deploying from the cloudflare script), I get the following error:
> 
> “'Network-scoped alias is supported only for containers in user defined networks'
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Configure '...'
> 2. Run '....'
> 3. See error
> 
> If it's an issue with Cloudflare Tunnel: 4. Tunnel ID : 618e5748-220a-44f2-8a02-42f556a8582c 5. cloudflared config: Docker
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Environment and versions**
> 
> * OS: [e.g. MacOS] Ubuntu 22.04
> * Architecture: [e.g. AMD, ARM] Docker
> * Version: [e.g. 2022.02.0] Docker 20.10.17
> 
> **Logs and errors** If applicable, add logs or errors to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

Note: version 2024.1.3 is fine; issue occurs with 2024.1.4

**Comment by jcsf** [comment]
Hi, that error seems to come from docker compose (look at https://github.com/docker/compose/issues/3012) and doesn't seem related with cloudflared, can you explain better your setup, for example docker compose version and docker compose file.

**Comment by mike12806** [comment]
> Hi, that error seems to come from docker compose (look at [docker/compose#3012](https://github.com/docker/compose/issues/3012)) and doesn't seem related with cloudflared, can you explain better your setup, for example docker compose version and docker compose file.

Hi - thanks for taking a look. So the error was occurring on an install I had configured using the docker run command in the zero trust portal. After I reinstalled using a docker compose file, all seems fine?

**Comment by mike12806** [comment]
> > Hi, that error seems to come from docker compose (look at [docker/compose#3012](https://github.com/docker/compose/issues/3012)) and doesn't seem related with cloudflared, can you explain better your setup, for example docker compose version and docker compose file.
> 
> Hi - thanks for taking a look. So the error was occurring on an install I had configured using the docker run command in the zero trust portal. After I reinstalled using a docker compose file, all seems fine?

Would be awesome if the docker-compose file was provided in the cloudflare zero access UI for ease of install
