### ISSUE TITLE
The latest version that can be installed on Windows 7 x86 is 2023.10.0

### ISSUE THREAD

**Issue by donnimsipa** [cloudflare/cloudflared#1174]
**Describe the bug**
The x86 Cloudflared version 2024.1.1 and above cannot be run on Windows 7 x86, but version 2023.10.0 can.

**To Reproduce**
1. Install a fresh copy of Windows 7 Ultimate SP1 x86 along with the latest updates.
2. Install the latest version of x86 Cloudflared (version 2024.2.0 in this post).
3. Successfully install Cloudflare, but encounter an error when attempting to run Cloudflared.
4. Uninstall Cloudflare, then try installing version 2023.10.0. It proves to be functional.
5. Uninstall Cloudflare again, then attempt installation with version 2024.1.1. Unfortunately, it also fails to run.

**Environment and versions**
 - OS: Microsoft Windows 7 Ultimate
 - Architecture: x86
 - Version: 6.1.7601 Service Pack 1 Build 7601

**Logs and errors**

```
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        c:/Program Files/Cloudflare Go/go/src/runtime/sys_windows_386.s:35 +0x25 fp=0x12fe68 sp=0x12fe64 pc=0x4769d5
eax     0x8
ebx     0x1aa8dac
ecx     0x0
edx     0x12fe90
edi     0x12fe6c
esi     0x12fec4
ebp     0x12fe6c
esp     0x12fe60
eip     0x0
eflags  0x10202
cs      0x1b
fs      0x3b
gs      0x0
PS C:\Users\Administrator> cloudflared
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0
```

**Additional context**
Users with Windows 7 x86 systems are unable to install Cloudflare versions starting from 2024.1.1 onward. It seems that version 2024.1.1 is specifically designed for compatibility with Windows 10 x86. However, I'm unsure about its compatibility with Windows 7 x64, Windows Server, or Windows 8 on both x86 and x64 architectures.

**Comment by donnimsipa** [comment]
[Go 1.20 is the last release that will run on any release of Windows 7, 8, Server 2008 and Server 2012. Go 1.21 will require at least Windows 10 or Server 2016.](https://go.dev/doc/go1.20#windows)

[As announced in the Go 1.20 release notes, Go 1.21 requires at least Windows 10 or Windows Server 2016; support for previous versions has been discontinued.](https://go.dev/doc/go1.21#windows)

**Comment by madocter** [comment]
> [Go 1.20 is the last release that will run on any release of Windows 7, 8, Server 2008 and Server 2012. Go 1.21 will require at least Windows 10 or Server 2016.](https://go.dev/doc/go1.20#windows)
> 
> [As announced in the Go 1.20 release notes, Go 1.21 requires at least Windows 10 or Windows Server 2016; support for previous versions has been discontinued.](https://go.dev/doc/go1.21#windows)

Then why launch version for Windows ? who is using windows 11 as server ? NOBODY. Then after 6 months windows will stop supporting windows 11 etc ... worthless software then, can at least specify version that works with windows 7 ?
