### ISSUE TITLE
Can this be used as an anticensorship tool? 💡

### ISSUE THREAD

**Issue by amin616** [cloudflare/cloudflared#1186]
**Describe the feature you'd like**
I don't know much about expert coding stuff and I have this on my manjaro linux now I was wondering if it could be used as an anti-censorship tool? 

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?

**Additional context**

**Comment by jcsf** [comment]
Not sure what you mean by anti-censorship tool. But cloudflared is a daemon to run Cloudflare Tunnels and access your resources thought Cloudflare CDN network. Anything else falls out of the scope of this project.
