### ISSUE TITLE
📝

### ISSUE THREAD

**Issue by FStefanni** [cloudflare/cloudflared#1198]
**Available Documentation**

https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/

**Suggested Documentation**

Requisites for running cloudflared successfully with all its features.
These includes, but are not limited to:
* Chiphers
* Ports
* Protocols
* Which feature requires what

**Additional context**

I am trying to create a tunnel from a NixOS instance, and it works fine (rendereing of an http page, ssh via console, etc.) except for the SSH rendered via browser. The command I use is:
```bash
cloudflared tunnel --loglevel debug --no-autoupdate run --token=mysupertoken
```

If I try to use the same command and token from Debian, everything works.
So what I suppose is that there is a difference in the NixOS configuration (maybe about sshd) that create the issue, but since no documentation about the setup is truly available, I am unable to understand what the issue truly is.

Just to let you know the error, this is what the browser console prints:
```text
aaa@11223344556677889900abcdef
POST https://ssh.mydomain.it/cert_sign [HTTP/3 400 Bad Request 223ms]
[libssh2] 0.247000 Failure Event: -5 - Unable to exchange encryption keys JZ4D45Y6.js:1:3543
Uncaught (in promise) Error: [FATAL] ../../src/ssh/session.cc(230): libssh2_session_handshake(session_, 0 ) rc=-5
```

And this is the error that `cloudflared` prints:
```text
2024-03-06T10:44:48Z DBG downstream->upstream copy: stream 5 canceled by local with error code 0 connIndex=0 destAddr=ssh://localhost:22 event=1 ingressRule=1 originService=ssh://localhost:22
```

Regards

**Comment by jcsf** [comment]
We don't support NixOS distribution. Therefore, we can't exactly tell what is missing. Feel free to propose a list of requirements if you are able to get it working.

**Comment by uceumice** [comment]
I am having the same issue whenever trying to access SSH via a Browser Rendered Terminal feature. 



Whenever I try to access the browser rendered terminal, I am greeted with the following view:
![image](https://github.com/cloudflare/cloudflared/assets/65486851/e690268b-996c-469c-8da7-b8bae54c678b)

After ommiting CORS errors (caused by minification, I suppose, but probably irrelevant to the issue), I am left with the following console output:
```
Uncaught (in promise) Error: [FATAL] ../../src/ssh/session.cc(230): libssh2_session_handshake(session_, 0 ) rc=-5
    a https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:1
    poll https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    initialize https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    onopen https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    Co https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    create https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    createTransport https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    componentDidMount https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    an https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    bd https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:1
    H0 https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:27
    <anonymous> https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    <anonymous> https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
JZ4D45Y6.js:1:3263
    onopen https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    Co https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    create https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    AsyncFunctionNext self-hosted:852
    (Async: async)
    createTransport https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    componentDidMount https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    some self-hosted:137
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    some self-hosted:137
    Kp https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    an https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:8
    bd https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:1
    H0 https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:27
    <anonymous> https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
    <anonymous> https://ssh-beidou-sus.ueuie.dev/JZ4D45Y6.js:65
```

Here is a `cert_sign` request, reporting all good:
![image](https://github.com/cloudflare/cloudflared/assets/65486851/92bfba77-942a-4364-975a-de19481cfe11)

**Comment by joegoldin** [comment]
Also experiencing this same issue on NixOS... :(

**Comment by bsheline** [comment]
I was able to resolve it with `services.openssh.settings.Macs = ["hmac-sha2-256"];`
