### ISSUE TITLE
💡amd64 for Darwin and Windows please

### ISSUE THREAD

**Issue by gedw99** [cloudflare/cloudflared#1199]
**Describe the feature you'd like**

We need this for WARP to Warp and tunnels on ARM64 desktops and iot.

**Describe alternatives you've considered**

pull code and do myself. Not idea if the Team has not released ARM64 desktop versions because of dev blockers or not. Would be happy to help...

**Additional context**

The Warp GUI client is built on .NET I believe ?

**Comment by jcsf** [comment]
Hi,
The WARP client is not managed by the team that manages cloudflared, please send your request through our support channels.
