### ISSUE TITLE
🐛 Can't set up a tunnel on macOS in 2024.2.1

### ISSUE THREAD

**Issue by AdamLearns** [cloudflare/cloudflared#1200]
**Describe the bug**
I can't seem to get a tunnel up and running on macOS.

**To Reproduce**
1. Go to the Cloudflare dashboard
2. Navigate to the "Tunnels" page
3. Click "Create a tunnel"
4. Choose "Cloudflared"
5. Name the tunnel
6. On the next page, regardless of which option is used, `cloudflared` fails.

If it's an issue with Cloudflare Tunnel:
7. Tunnel ID: `499bb7009dc1079f674a3b8bb68649a3` (I think)
8. cloudflared config: I deleted `~/.cloudflared` and started from scratch for this

**Expected behavior**
I'm able to start a tunnel.

**Environment and versions**
 - OS: macOS 14.2.1
 - Architecture: ARM
 - Version: 2024.2.1

**Logs and errors**
When I run the `cloudflared service install` command, I get this output:

```
2024-03-08T22:25:02Z INF Installing cloudflared client as a system launch daemon. cloudflared client will run at boot
2024-03-08T22:25:02Z ERR error generating launchd template error="cloudflared service is already installed at /Library/LaunchDaemons/com.cloudflare.cloudflared.plist; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command"
```

When I try to run `cloudflared service uninstall`, I get this error:

```
2024-03-08T22:28:50Z INF Uninstalling cloudflared as a user launch agent
error deleting /Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist: remove /Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist: no such file or directory
```

If I `touch /Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist` and re-run that command, it seemingly works, but I keep getting into the same problem on installation the next time around.

**Additional context**
I tried completely uninstalling via `brew` and also deleting `~/.cloudflared`, but that didn't seem to work. I don't have any other tunnels running on this machine. This all worked for me a few weeks ago, which was presumably a previous version (although I'm not sure which).

UPDATE (+19 hours after posting): I did a reboot to see if that would help, but it didn't. 😢

**Comment by luckman212** [comment]
It's working for me... M1 Mac Mini on macOS 14.4

You're installing with `sudo` right? (You need to)

```
sudo cloudflared service install (very long key ~180 chars)...
```

**Comment by AdamLearns** [comment]
> You're installing with sudo right? (You need to)

Yeah, I'm just pasting the commands right from the dashboard, and they include `sudo`. I'm on a Mac Studio M2 Ultra.

**Comment by luckman212** [comment]
Why is the daemon plist under your user account? (/Users/...)

Shouldn't it be in /Library/LaunchDaemons (that's where mine is)

I would try manually deleting that plist and then running the install command again.

**Comment by AdamLearns** [comment]
> Why is the daemon plist under your user account? (/Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist)

It isn't actually there though; the error just says that it can't delete a file at that location since it doesn't exist. I don't know why it's looking in that location in the first place though, nor do I know where it used to look a few weeks ago when this was working. 😢

Like I said though, if I `touch` that file and then run the `uninstall` command, then the uninstallation goes from failing to passing:

```
2024-03-09T21:24:59Z INF Uninstalling cloudflared as a user launch agent
2024-03-09T21:24:59Z INF Launchd for cloudflared was uninstalled successfully
```

...but then the _installation_ still fails:

```
sudo cloudflared service install [omitted the token]
2024-03-09T21:25:12Z INF Installing cloudflared client as a system launch daemon. cloudflared client will run at boot
2024-03-09T21:25:12Z ERR error generating launchd template error="cloudflared service is already installed at /Library/LaunchDaemons/com.cloudflare.cloudflared.plist; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command"
cloudflared service is already installed at /Library/LaunchDaemons/com.cloudflare.cloudflared.plist; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command
```

**Comment by luckman212** [comment]
Ok. That's really odd. And, even if you become root, there's no corresponding file at /Library/LaunchDaemons ?

**Comment by AdamLearns** [comment]
> And, even if you become root, there's no corresponding file at /Library/LaunchDaemons

_That_ file exists, and deleting it and then running the `install` command worked! 🎉

So maybe the _real_ issue here is that `cloudflared service uninstall` is trying to delete the wrong file? Even after verifying that my tunnel is up and running, I still get this:

```
╰─❯ cloudflared service uninstall
2024-03-10T03:44:34Z INF Uninstalling cloudflared as a user launch agent
error deleting /Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist: remove /Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist: no such file or directory
```

I'm just not sure how that could happen. Is there any configuration that I can look into...?

(P.S. thank you very much for the help! 🙏)

**Comment by luckman212** [comment]
Not sure either, but glad you got it working!

According to the source code

https://github.com/cloudflare/cloudflared/blob/47ad3238dd35dcc4566b846afb3c53d9d2f8f407/cmd/cloudflared/macos_service.go#L175-L179

It seems that somehow the program is not properly detecting that you're running as root. I would troubleshoot it from that angle.

The code is just checking if your EUID is 0

https://github.com/cloudflare/cloudflared/blob/47ad3238dd35dcc4566b846afb3c53d9d2f8f407/cmd/cloudflared/macos_service.go#L74-L76

What does the command below yield on your system?

```
sudo bash -c 'echo $EUID'
```

**Comment by AdamLearns** [comment]
Ahh, this is embarrassing. 😳 I had been running the uninstallation command by copy/pasting it from the output of `sudo cloudflared service install`, which means I was running `cloudflared service uninstall` and not `sudo cloudflared service uninstall` that whole time. Sorry to waste your time on an issue that ended up being user error! 🤦‍♂️

**Comment by ifnull** [comment]
I had a similar issue and the issue was that my email had not been verified. When authorizing the tunnel with my custom domain I noticed a toast message at the bottom of the screen telling me I need to verify my email. After verifying my email I was able to establish a tunnel connection.

**Comment by my-johnlee** [comment]
> > Why is the daemon plist under your user account? (/Users/adam/Library/LaunchAgents/com.cloudflare.cloudflared.plist)
> 
> It isn't actually there though; the error just says that it can't delete a file at that location since it doesn't exist. I don't know why it's looking in that location in the first place though, nor do I know where it used to look a few weeks ago when this was working. 😢
> 
> Like I said though, if I `touch` that file and then run the `uninstall` command, then the uninstallation goes from failing to passing:
> 
> ```
> 2024-03-09T21:24:59Z INF Uninstalling cloudflared as a user launch agent
> 2024-03-09T21:24:59Z INF Launchd for cloudflared was uninstalled successfully
> ```
> 
> ...but then the _installation_ still fails:
> 
> ```
> sudo cloudflared service install [omitted the token]
> 2024-03-09T21:25:12Z INF Installing cloudflared client as a system launch daemon. cloudflared client will run at boot
> 2024-03-09T21:25:12Z ERR error generating launchd template error="cloudflared service is already installed at /Library/LaunchDaemons/com.cloudflare.cloudflared.plist; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command"
> cloudflared service is already installed at /Library/LaunchDaemons/com.cloudflare.cloudflared.plist; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command
> ```

That's because you're running cloudflared service uninstall instead of sudo cloudflared service uninstall
Hence it is looking for the plist in your user folder instead of system folder
