### ISSUE TITLE
🐛WARP Installer permission issue, impossible to install/update on Windows 11

### ISSUE THREAD

**Issue by hong620** [cloudflare/cloudflared#1204]
**Describe the bug**
Cloudflare Installer Error 2503 and Error 2502.
in envirorment already Cloudflare WARP app installed, it progress the updater just fine, but actually update doesn't done at all.

**To Reproduce**
1. clean install windows 11 pro with all the default security value 
2. download cloudflare warp installer from cloudflare or ms app center / click the update from WARP app for Windows
3. Excute WARP installer / wait for updater install the new version
4. installer shows 2503 and 2502 error that WINDOWS %TEMP% directory permission, either trough MS Installer or update from WARP itself.

**Expected behavior**
installer or updater must excute and installer TEMP 

**Environment and versions**
 - OS: Windows 11 (all the Win11 Build since it launch with new security/intergrity functions)
 - Architecture: AMD64, exactly on me, it's Intel i7-13700k
 - Version: all the WARP for Windows build as far as tested

**Logs and errors**
MSI error 2503 and 2502, that typically happen on some old softwares installer require C:\windows\temp\ directory permission as 'EVERYONE' or demand manually excute installer as 'Administrator permission'

**Additional context**

not like previous windows allowed to user trigger the excute installer as administrator permission to workaround these old installer issues,
since windows 11 launch, Microsoft's policy on these are stricted 'not allowed to use administrator permission on installer'
if you try to trigger administrator permission from system account log on to installer those in quite janky pro level powershell command or install it in safe modes, security integrity on windows defender become invalid just like KNOX warrenty broken on the phone.
that impossible to rollback unless you re-install entire windows 11 again.

since this issue is exist over a decade and many windows 10/11 users asking on cloudflare forum but there's no proper workaround without massive security risk to user,
so as conclude, (not advanced) ordinary users try to install WARP on windows 11 is impossible.

as far as i can guess about workaround these issues are, just deliver WARP as Microsoft Store app to avoid permission issue.
or just asking to microsoft for fix the installer to newer one for windows 11.

**Comment by jcsf** [comment]
Cloudflare WARP is not managed by this team. Please reach the right owners through our support system.

**Comment by hong620** [comment]
> Cloudflare WARP is not managed by this team. Please reach the right owners through our support system.

how to i reach team does working on those?
i've seens many issue report on those in WARP category in Cloudflare Forum,
but no one support team in those reply on bug report posts.
many years people report about this issue but nothing fixed, any other method to address them or fetch this bug on they're issue lists?
seems support system only targeting enterprise and expert, issue report on WARP mobile apps seems only actived at early days, and nothing much seems team they working on windows WARP.

**Comment by jcsf** [comment]
I have reached out to the team, will let you know once I have an answer from them.

**Comment by janani-cr** [comment]
@hong620 Please leverage https://community.cloudflare.com/ for reporting any issues related to WARP client. As @jcsf we have shared this issue with the relevant team.
