### ISSUE TITLE
🐛WebSocket does not work with --protocol http2

### ISSUE THREAD

**Issue by WinLinux1028** [cloudflare/cloudflared#1208]
**Describe the bug**
When I start cloudflared with `--protocol http2` and try to start a WebSocket connection, it returns a HTTP 502.
The request does not seem to have reached the application server.
This problem occurs only with http2 and not with quic.

**To Reproduce**
1. Set `--protocol http2` to the command line argument of cloudflared.
2. Start cloudflared.
3. Try to start a WebSocket connection.
4. Returned HTTP 502.

If it's an issue with Cloudflare Tunnel:
5. Tunnel ID : 084011a6-4fb3-421f-b173-58cad6dc8942

**Expected behavior**
WebSocket works.

**Environment and versions**
 - OS: Debian
 - Architecture: AMD64
 - Version: 2024.2.1

**Comment by jcsf** [comment]
Hi,
Can you share the cloudflared logs when using http2 and quic so that we can better understand what is happening? Also, can you test an older version of cloudflared just to see if the issue is present there as well?

**Comment by f0re1gnKey** [comment]
> Closed due to no answer

Unable to reach the origin service. The service may be down or it may not be responding to traffic froo reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: http: no Host in request URL

switch to quic protocol is normal

**Comment by Roki100** [comment]
still an issue

**Comment by tsvico** [comment]
still an issue

**Comment by tsvico** [comment]
still an issue，switch to quic protocol is normal，Using http2 protocol will always trigger 1006

![Image](https://github.com/user-attachments/assets/26676b65-a247-4b0b-9982-8c4bc6a2f3f9)
