### ISSUE TITLE
Addition of a NTP proxy.

### ISSUE THREAD

**Issue by LogalDeveloper** [cloudflare/cloudflared#121]
At the moment, cloudflared makes a nice addition to a server or desktop since you can quickly install it and then point the system's DNS servers to cloudflared to easily get secure DNS requests. I think a nice addition would be a NTP proxy that can convert NTP requests to roughtime or NTS requests. This can allow users to point their system's timesyncd or ntpd to cloudflared to get secure time syncing just as easily.

**Comment by abelinkinbio** [comment]
This is a great suggestion. Thanks for the feature request, we've made a note of this and will circle back with more information in the future.
