### ISSUE TITLE
🐛 Cannot delete Argo tunnel via API using documented method

### ISSUE THREAD

**Issue by luckman212** [cloudflare/cloudflared#1210]
**Describe the bug**

`DELETE` method described at https://developers.cloudflare.com/api/operations/argo-tunnel-delete-an-argo-tunnel reports success, but in actuality, fails.

**To Reproduce**

Attempt to call `DELETE` method for an existing tunnel, e.g.
```
curl --request DELETE \
--header 'Content-Type: application/json' \
--header 'Pragma: no-cache' \
--header 'Cache-Control: no-cache' \
--header "Authorization: Bearer <my_api_token> \
--url https://api.cloudflare.com/client/v4/accounts/{acct_id}/tunnels/{tun_id}
```

**Expected behavior**

Tunnel is deleted.

**Environment and versions**

OS: macOS (irrelevant)

**Logs and errors**

result (appears to indicate success):

```
{
  "success": true,
  "errors": [],
  "messages": [],
  "result": null
}
```

Yet, calling the [list endpoint](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-list-cloudflare-tunnels) (`https://api.cloudflare.com/client/v4/accounts/{acct_id}/cfd_tunnel`) again, the tunnel still exists...

**Comment by luckman212** [comment]
Hmm. Adding `is_deleted=false` to the request parameters seems to filter them out. But, how can we fully purge/delete the tunnels?

**Comment by luckman212** [comment]
Seems I was using a deprecated API method.

The updated docs are https://developers.cloudflare.com/api/operations/cloudflare-tunnel-list-cloudflare-tunnels

**Comment by jcsf** [comment]
The tunnels are purged by an internal job. You can't force the purge. If you want to list tunnels that are not deleted, you should always add the query parameter: `is_deleted=false`.

**Comment by luckman212** [comment]
What is the periodicity of this internal purge job? The deleted tunnels I see listed in my results were removed months ago...

**Comment by jcsf** [comment]
Can't share that. But they will eventually disappear. Regardless, if you use the argument above the fact that they are still there should not be an issue for what you want to do, since we don't count them as active.
