### ISSUE TITLE
🐛 Unable to establish tunnel connection with an OVH VPS if Edge Network Firewall is enabled

### ISSUE THREAD

**Issue by fastily** [cloudflare/cloudflared#1223]
**Describe the bug**
I'm unable to setup or use `cloudflared` on an [OVH VPS](https://us.ovhcloud.com/vps/) if I have also enabled the OVH [Edge Network Firewall](https://help.ovhcloud.com/csm/en-dedicated-servers-firewall-network?id=kb_article_view&sysparm_article=KB0043448).

**To Reproduce**
1. Setup a new ubuntu VPS from OVH
2. Enable the Edge Network Firewall ([instructions](https://help.ovhcloud.com/csm/en-dedicated-servers-firewall-network?id=kb_article_view&sysparm_article=KB0043448#instructions)) and create the Authorize ICMP, Refuse IPv4, and Authorize TCP rules in the example.
3. Create a new Cloudflare tunnel using the Zero Trust dashboard
4. Install cloudflared (either with [the deb](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/#linux) or with the [apt repo](https://pkg.cloudflare.com/index.html)) on the VPS
5. Run the `sudo cloudflared service install <YOUR_TOKEN>` command generated by the dashboard when you created your Cloudflare tunnel.
6. Observe that the aforementioned command hangs indefinitely.

If it's an issue with Cloudflare Tunnel:
7. Tunnel ID : n/a
8. cloudflared config: n/a

**Expected behavior**
`cloudflared service install` should successfully configure the tunnel and exit

**Environment and versions**
 - OS: Ubuntu
 - Architecture: amd64
 - Version: 22.04

**Logs and errors**
None, because the above command hangs

**Additional context**
Workaround is to disable the OVH Edge Network Firewall when setting up the Cloudflare tunnel service for the first time.  Once the command exits, edit `/etc/systemd/system/cloudflared.service` so that the `ExecStart` line includes the `--protocol http2` argument when starting `cloudflared`.  Example line with the changes:
```
ExecStart=/usr/bin/cloudflared --no-autoupdate tunnel --protocol http2 run --token <YOUR_TOKEN>
```
Be sure to reload the daemon (`sudo systemctl daemon-reload`) and restart the systemd cloudflared service after making this change.  

* [Discussion on the community forum](https://community.cloudflare.com/t/tunnel-not-working-when-behind-ovh-public-cloud-firewall/544886)
* [Possibly related comment](https://github.com/cloudflare/cloudflared/issues/632#issuecomment-1114716597)

**Comment by jcsf** [comment]
Hi,
The issue you are describing seems to be related with the OVH Edge Firewall blocking the requests of cloudflared to Cloudflare API's. There is probably some rule that you need to add to the firewall to allow the traffic to passthrough. Most of the discussions you linked are reaching the same conclusion. Since this isn't a bug with cloudflared I will close the issue. If you discover the solution, feel free to share it with the community.

**Comment by fastily** [comment]
> If you discover the solution

@jcsf I guess I should clarify.  The solution is already known: run cloudflare tunnel with `--protocol http2`.  I'm not interested in opening up more ports on my firewall; that's not great for security and increases my maintenance overhead, *especially* when we already know this isn't necessary.

Based on the docs, it seems like cloudflared defaults to QUIC, but falls back to http2 if QUIC isn't working.  This automatic fallback behavior doesn't seem to be working on OVH hosts for some reason, I was hoping you could look into that.  Thanks

**Comment by l0ukai** [comment]
Hello, 
If you're using OVH’s Edge Network Firewall, you may want to add or allow Cloudflare’s IPv4 address list. 
You can find the list of Cloudflare IP addresses here: 
[https://www.cloudflare.com/ips/](url)
Hope this helps!
