### ISSUE TITLE
Connection terminated error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=0🐛

### ISSUE THREAD

**Issue by peyman72** [cloudflare/cloudflared#1227]
this error cause stop all network connections such as ping,ssh,vpn,...  on ubuntu every few minutes!

Apr  6 07:20:21 TaxiApps cloudflared[477]: 2024-04-06T07:20:21Z INF Unregistered tunnel connection connIndex=0 event=0 
ip=198.41.200.23
Apr  6 07:20:21 TaxiApps cloudflared[477]: 2024-04-06T07:20:21Z ERR Failed to serve quic connection error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.23
Apr  6 07:20:21 TaxiApps cloudflared[477]: 2024-04-06T07:20:21Z ERR Serve tunnel error error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.23
Apr  6 07:20:21 TaxiApps cloudflared[477]: 2024-04-06T07:20:21Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=198.41.200.23
Apr  6 07:20:22 TaxiApps cloudflared[477]: 2024-04-06T07:20:22Z ERR Connection terminated error="failed to accept QUIC stream: timeout: no recent network activity" connIndex=0
Apr  6 07:20:42 TaxiApps systemd[1]: session-19.scope: Succeeded.
Apr  6 07:20:46 TaxiApps cloudflared[477]: 2024-04-06T07:20:46Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 event=0 ip=198.41.200.23
Apr  6 07:20:46 TaxiApps cloudflared[477]: 2024-04-06T07:20:46Z INF Retrying connection in up to 4s connIndex=0 event=0 ip=198.41.200.23
Apr  6 07:20:50 TaxiApps cloudflared[477]: 2024-04-06T07:20:50Z ERR Connection terminated error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0

**Comment by jcsf** [comment]
Duplicates https://github.com/cloudflare/cloudflared/issues/1228
