### ISSUE TITLE
Unable to tunnel Concourse

### ISSUE THREAD

**Issue by analytically** [cloudflare/cloudflared#123]
Experimenting with tunnelling Concourse (https://concourse-ci.org/) but it seems like the WebSocket is never closed and thus the eventstream of build events never comes through.

**Comment by abelinkinbio** [comment]
We've released a few major enhancements namely the one documented here: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/create-tunnel

Check it out and let us know if this is a sufficient workaround.
