### ISSUE TITLE
Argo Tunnel - Latest release 2019.8.0 url encoding broken

### ISSUE THREAD

**Issue by Wrhector** [cloudflare/cloudflared#124]
The latest version of cloudflared (2019.8.0) is erroneously applying a urlencode to the path which breaks most requests

Using a simple echo server:

Version 2018.7.3:
```
curl "https://testcloudflared.X.com/test?get=somthing%20a"
GET /test?get=somthing%20a HTTP/1.1
Host: testcloudflared.X.com
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
Cdn-Loop: cloudflare
Cf-Ipcountry: US
Cf-Visitor: {"scheme":"https"}
X-Forwarded-Proto: https
```
_Some headers removed for privacy_

Version 2019.8.0:
```
curl "https://testcloudflared.X.com/test?get=somthing%20a"
GET /test%3Fget=somthing%2520a HTTP/1.1
Host: testcloudflared.X.com
User-Agent: curl/7.47.0
Accept: */*
Accept-Encoding: gzip
Cdn-Loop: cloudflare
Cf-Ipcountry: US
Cf-Visitor: {"scheme":"https"}
X-Forwarded-Proto: https
```

Notice the whole path has been urlencoded, essentially meaning that all requests with a get parameter will fail.

Debug lines from cloudflared:
```
DEBU[0009] GET http://localhost:3246/test%3Fget=somthing%2520a HTTP/1.1  CF-RAY=5023cff76cd57940-LAX
DEBU[0009] Request Headers map[Accept:[*/*] Accept-Encoding:[gzip] Cdn-Loop:[cloudflare] Cf-Connecting-Ip:[XX] Cf-Ipcountry:[US] Cf-Ray:[5023cff76cd57940-LAX] Cf-Visitor:[{"scheme":"https"}] Cf-Warp-Tag-Id:[XX] True-Client-Ip:[XX] User-Agent:[curl/7.47.0] X-Forwarded-For:[XX] X-Forwarded-Proto:[https]]  CF-RAY=5023cff76cd57940-LAX
DEBU[0009] Request content length 0                      CF-RAY=5023cff76cd57940-LAX
DEBU[0009] 200 OK                                        CF-RAY=5023cff76cd57940-LAX
DEBU[0009] Response Headers map[Access-Control-Allow-Origin:[*]]  CF-RAY=5023cff76cd57940-LAX
DEBU[0009] Response content length unknown               CF-RAY=5023cff76cd57940-LAX
```

I'm working on finding the lines that's doing this.

**Comment by nickvollmar** [comment]
We recently made this change to the URL logic: https://github.com/cloudflare/cloudflared/commit/3c93d9b300de99c6906ce8799971fa347cf684e6

Previously we had been setting h1.URL to a new URL object, constructed via url.Parse(). The resulting object apparently had `Path` and `RawPath` in the correct state, so we avoided the second layer of encoding that happened here: https://golang.org/src/net/url/url.go?s=19909:19943#L689

**Comment by sssilver** [comment]
2018.8.1 has rolled this change back to its old behavior
2018.8.2 will contain a proper bugfix

**Comment by Wrhector** [comment]
Thanks, the new release fixes it

**Comment by eyalmamo** [comment]
Still happening with version 2019.8.4.
Is there any place I can find previous version binaries?

**Comment by sssilver** [comment]
@eyalmamo can you help us reproduce the problem in the current version?

**Comment by eyalmamo** [comment]
Absolutely. It's pretty straight forward - Any URL that is URL encoded (therefor has % in it for escaping) is being encoded again by cloudflared. Just as the example shown in the original report here, a URL with %20 will result in a URL with %2520.
Once I downgraded to 2019.8.1 this stopped happenning.

Attached is the [cloudflared log](https://github.com/cloudflare/cloudflared/files/3570839/cloudflared.log). (redacted for obvious reasons)
And the configuration:
> hostname: XXX.XXX.com 
> url: http://localhost:8080 
> logfile: /var/log/cloudflared.log

**Comment by TownLake** [comment]
@eyalmamo - we believe a handful of releases late last year and in early 2020 resolved this; thanks for the help with the repro. Can you confirm that it looks alright on your side?
