### ISSUE TITLE
🐛 Unable to install/update 2024.5.0 on Linux

### ISSUE THREAD

**Issue by a-pir1** [cloudflare/cloudflared#1248]
**Describe the bug**
It appears that in the latest release of Cloudflared, it may not have been packaged correctly.  There is no `cloudflared-linux-amd64.deb` uploaded with this release.

**To Reproduce**
1. `curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb`
2. `dpkg -i cloudflared.deb`

**Expected behavior**
It is supposed to unpack and install/update like normal.

**Environment and versions**
 - OS: Ubuntu Server
 - Architecture: AMD
 - Version: 23.10

**Logs and errors**
root@cloudflared ~# dpkg -i cloudflared.deb
dpkg-deb: error: 'cloudflared.deb' is not a Debian format archive
dpkg: error processing archive cloudflared.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 cloudflared.deb
root@cloudflared ~# 

**Additional context**

**Comment by jcsf** [comment]
We had an issue with the release pipelines, it should be fixed now.
