### ISSUE TITLE
Metric Type for UDP Total Sessions

### ISSUE THREAD

**Issue by tienhuynh5312** [cloudflare/cloudflared#1253]
https://github.com/cloudflare/cloudflared/blob/43446bc692344df4bd2ae8a0004feb819bbeaae8/datagramsession/metrics.go#L18
^ UDP Total Session: Gauge Type

https://github.com/cloudflare/cloudflared/blob/43446bc692344df4bd2ae8a0004feb819bbeaae8/proxy/metrics.go#L55
^ TCP Total Session: Counter Type

Usually, total indicates counter type. Is there a specific reason for this difference?

**Comment by DevinCarr** [comment]
I actually noticed this issue earlier this week too and I addressed it back to a counter. I'm pretty sure I just did a copy-paste typo with the introduction of the metric originally.

This should be fixed here: https://github.com/cloudflare/cloudflared/commit/44e6d1a313c4fc7565c85381572a8d4b58354cb2
