### ISSUE TITLE
ERRO[0011] failed to connect to an HTTPS backend "https://1.1.1.1/dns-query"  error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by RobertClarke** [cloudflare/cloudflared#127]
Following the out of the box directions for DoH on OSX using brew and 1.1.1.1: https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/

Mercury:~ robert$ brew install cloudflare/cloudflare/cloudflared
==> Installing cloudflared from cloudflare/cloudflare
==> Downloading https://developers.cloudflare.com/argo-tunnel/dl/cloudflared-2019.8.1-darwin-amd64.tgz
Already downloaded: /Users/robert/Library/Caches/Homebrew/downloads/051a4dbee1c705b796807e8b0631ff191a2bf2f575a7b2a5eeaa6ccd272ec983--cloudflared-2019.8.1-darwin-amd64.tgz
🍺  /usr/local/Cellar/cloudflared/2019.8.1: 3 files, 32.3MB, built in 1 second
Mercury:~ robert$ 

Mercury:~ robert$ sudo cloudflared proxy-dns
Password:
INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
INFO[0000] Adding DNS upstream                           url="https://1.0.0.1/dns-query"
INFO[0000] Starting metrics server                       addr="127.0.0.1:50195"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://localhost:53"

Mercury:~ robert$ dig +short @127.0.0.1 cloudflare.com AAAA

ERRO[0011] failed to connect to an HTTPS backend "https://1.1.1.1/dns-query"  error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: x509: certificate signed by unknown authority"
ERRO[0011] failed to connect to an HTTPS backend "https://1.0.0.1/dns-query"  error="failed to perform an HTTPS request: Post https://1.0.0.1/dns-query: x509: certificate signed by unknown authority"

**Comment by davebarrau** [comment]
Does

```
go get golang.org/x/exp/cmd/macos-roots-test
"$(go env GOPATH)/bin/macos-roots-test"
```

return "The test passed, no need to report the output. Thank you."?

**Comment by RobertClarke** [comment]
@davebarrau Yes the output is "The test passed, no need to report the output. Thank you."

**Comment by davebarrau** [comment]
> @davebarrau Yes the output is "The test passed, no need to report the output. Thank you."

How about `sudo GODEBUG="x509roots=1" cloudflared proxy-dns`?

**Comment by RobertClarke** [comment]
@davebarrau Mercury:~ robert$ sudo GODEBUG="x509roots=1" cloudflared proxy-dns
INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
INFO[0000] Starting metrics server                       addr="127.0.0.1:56070"
INFO[0000] Adding DNS upstream                           url="https://1.0.0.1/dns-query"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://localhost:53"
crypto/x509: kSecTrustSettingsResultInvalid = 0
crypto/x509: kSecTrustSettingsResultTrustRoot = 1
crypto/x509: kSecTrustSettingsResultTrustAsRoot = 2
crypto/x509: kSecTrustSettingsResultDeny = 3
crypto/x509: kSecTrustSettingsResultUnspecified = 4
crypto/x509: VeriSign Class 3 Public Primary Certification Authority - G5 returned 1
crypto/x509: DigiCert Global Root CA returned 1
crypto/x509: DigiCert SHA2 Secure Server CA returned 2

Mercury:~ robert$ dig +short @127.0.0.1 cloudflare.com AAAA
2606:4700::c629:d7a2
2606:4700::c629:d6a2
Mercury:~ robert$ 

Appears to fix the problem.

**Comment by davebarrau** [comment]
> Appears to fix the problem.

That's... odd.. x509roots=1 is supposed to be informational only according to the go source code. Does it work (reliably) without that now? 1.1.1.1/1.0.0.1 are anycast, but I would assume they would have the same certificate chain world wide.

**Comment by RobertClarke** [comment]
@davebarrau It appears to be mostly fine for now... will try this on my work comp and report back if there are further problems. Thanks for the help.
