### ISSUE TITLE
2019.8.1: Tunnel memory leak

### ISSUE THREAD

**Issue by felixbuenemann** [cloudflare/cloudflared#129]
Using cloudflared 2019.8.1 with a free argo tunnel and downloading a 1gb test file from a static file server used about 1.4 GB RSS for cloudflared which was then killed by the OOM killer, since this was on a 2GB DigitalOcean droplet.

Test Setup:

* Static file server from https://gist.github.com/paulmach/7271283
* 1 GB test file from http://speedtest-fra1.digitalocean.com/1gb.test

```sh
# on server
go build serve.go
# put 1gb.test in folder webroot
./serve -d webroot &
cloudflared tunnel --url http://localhost:8100
# on client
wget -O /dev/null https://example-tunnel.trycloudflare.com/1gb.test
```

System Info:
OS: Ubuntu 18.04.3 x86_64 Linux 5.0.0-25
CPU: Xeon E5-2650L v3 @ 1.80GHz (1 core)
RAM: 2GB
Cloudflated Version: 2019.8.1
GOOS: linux, GOVersion: go1.12.7, GoArch: amd64

Installed from official .deb package.

Problem might be related to #98.

**Comment by sanvit** [comment]
Had the same issue, so I tried a 8GB VM, and according to htop, cloudflared was eating up 41% of RAM when downloading a 1000MB testfile. It won't even release RAM after the download finished.

**Comment by felixbuenemann** [comment]
Yeah, I also tried with 2019.8.1 on a machine with 32 GB RAM and after a few days RSS was at over 4 GB for cloudflared.

**Comment by felixbuenemann** [comment]
I analyzed the code and found the main reason for memory bloat to be the following line:

https://github.com/cloudflare/cloudflared/blob/b836cb350a09e4ea6969a29212f5f67743200769/h2mux/h2mux.go#L22

This sets `h2mux.defaultWriteBufferMaxLen` to a whopping 512 MB per stream and each client connection creates a separate stream.

After changing this to `1024 * 1024` or 1 MB per connection, memory usage with a single streaming client is about 25 MB vs several gigabytes of RAM before the change.
