### ISSUE TITLE
🐛 Missing releases

### ISSUE THREAD

**Issue by nikolay** [cloudflare/cloudflared#1296]
Versions `2024.7.x` are missing from releases and Docker images.

**Comment by darth-pika-hu** [comment]
@nikolay It is not the first time. I guess they are still debugging.

**Comment by nikolay** [comment]
@darth-pika-hu Weeks pass, and still no release.

**Comment by janani-cr** [comment]
We are actively working on our release pipeline to start supporting arm64 builds, latest should be available soon.

**Comment by darth-pika-hu** [comment]
> @darth-pika-hu Weeks pass, and still no release.

I guess they won't release it until 7.4 or 7.5.

**Comment by kickouille** [comment]
Hello,

You can eventually build your own image, from the source code, checkout to desired version, and using `make container` once inside cloudflared directory.

For the time being, I did this procedure on three different platforms for version 2024.7.3 (amd64, arm64 which are officially provided under normal circumstances, and also armv7 which I needed.

Feel free to pull these multi-arch images from my repository:

Latest release: `docker image pull kickouille/cloudflared:latest`
Specific version: `docker image pull kickouille/cloudflared:2024.7.3`

This is manual process, I'm monitoring the releases and build them in best effort.

Regards,

Yanik

**Comment by kickouille** [comment]
Hello again,

2024.8.2 has just been released, and is available on Docker Hub Cloudflare repo as well.

I'm building a new armv7 version and create a Manifest composed of both official amd64 and arm64 and my armv7, available here:

Latest release: `docker image pull kickouille/cloudflared:latest`
Specific version: `docker image pull kickouille/cloudflared:2024.8.2`

Regards,

Yanik

**Comment by chungthuang** [comment]
There was an issue with the release pipeline, but 2024.8.2 should be good.
