### ISSUE TITLE
--logfile option not compatible with --proxy-dns mode

### ISSUE THREAD

**Issue by apnar** [cloudflare/cloudflared#13]
When using proxy-dns mode logging only seems to go to stdout.  Using logfile option doesn't redirect the logging, it only creates a log file with header that looks like it's intended for tunneling mode.

**Comment by pjao** [comment]
Any news about this?

**Comment by iot-operator** [comment]
Tracking this issue too...
--logfile param does not seem to work with proxy-dns mode properly.
Please fix this!

cloudflared proxy-dns --logfile /var/log/cf.log
Incorrect Usage: flag provided but not defined: -logfile

cloudflared proxy-dns -logfile /var/log/cf.log
Incorrect Usage: bad flag syntax: -logfile

cloudflared proxy-dns ---logfile /var/log/cf.log
Incorrect Usage: bad flag syntax: ---logfile

This is weird...

**Comment by nmldiegues** [comment]
This seems to be working fine these days. You just need to put the flags before the action command:
```
cloudflared --logfile /tmp/log.out proxy-dns
```
