### ISSUE TITLE
Supporting Protocols Other than HTTP(s) & RDP

### ISSUE THREAD

**Issue by mustafakirimli** [cloudflare/cloudflared#130]
Cloudflared should support protocols other than RDP to get rid of VPN requirements completely on infra.

As an example; we require having tunneling for management console/purpose on MySQL, PostgreSQL, RabbitMq, Redis and other tools/resources.

**Comment by mustafakirimli** [comment]
To achieve this, I have an idea to replace RDP to TCP to remove confusion and allow everyone to use other protocols. https://github.com/cloudflare/cloudflared/pull/125

**Comment by rennex** [comment]
Since the SSH and RDP tunnels are already just plain TCP tunnels in reality, I agree that users should be able to specify `tcp://host:port` as the target. But the current `rdp://` sets a default port of 3389, so it shouldn't be renamed, but instead add another name for tcp, and make it fail if no port is specified.

**Comment by AustinCorridor** [comment]
Thanks for the PR and opening the issue! Argo Tunnel does support RDP, and several teams use it right now, and I don’t want to disrupt their current configuration or workflow by renaming it.

Rennex makes a good point - we can add the arbitrary TCP support without renaming the RDP command. Would you change your PR to follow that convention instead?

**Comment by mustafakirimli** [comment]
It valid point and 100% agreed should not break current users. I am not a Go developer but will try to do it update PR.

Thanks for feedbacks.

**Comment by mustafakirimli** [comment]
I have updated the merge request as per decision. Kindly check and update/advice the code if required.

**Comment by sodabrew** [comment]
I commented on #125 but realized the discussion moved over here. https://github.com/cloudflare/cloudflared/pull/125#issuecomment-529492336

As a fellow user, this now makes total sense and I agree with @mustafakirimli

**Comment by daltoniam** [comment]
This is now officially supported: https://developers.cloudflare.com/access/other-protocols/tcp-guide/
