### ISSUE TITLE
how to uninstall cloudflared on mac

### ISSUE THREAD

**Issue by iceloon** [cloudflare/cloudflared#1305]
![iShot_2024-08-06_15 43 09](https://github.com/user-attachments/assets/55bfd9a9-a88d-41b5-80b5-331ac0c50364)

**Comment by shmick** [comment]
what is the output of `which cloudflared`?

**Comment by codenoid** [comment]
```
sudo launchctl stop com.cloudflare.cloudflared
brew uninstall cloudflared
sudo rm -rf $(which cloudflared)
```

anyway, how do you install it?

**Comment by iceloon** [comment]
> ```
> sudo launchctl stop com.cloudflare.cloudflared
> brew uninstall cloudflared
> sudo rm -rf $(which cloudflared)
> ```
> 
> anyway, how do you install it?

cloudflared.pkg

**Comment by at15** [comment]
Found this issue from google. For me, the builtin `cloudflared service uninstall` does not work because I installed it as launch daemon when following instructions in cloudflare dashboard to install via brew and run via token.

You can find and remove the system service via the following

```bash
sudo launchctl print system/com.cloudflare.cloudflared
sudo launchctl bootout system/com.cloudflare.cloudflared
sudo rm /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
```
