### ISSUE TITLE
No release hashes or GPG signatures

### ISSUE THREAD

**Issue by mihaifm** [cloudflare/cloudflared#131]
Releases on Github or on https://bin.equinox.io don't contain any sort of hashes or signatures that can be used to check the downloads.

Surprised to see this with a company that values security.

**Comment by abeluck** [comment]
Came here to report this same issue. This prevents adoption in security-paranoid enterprises.

Ideally the [official download page](https://developers.cloudflare.com/argo-tunnel/downloads/) would offer checksums of all releases with a PGP signed signaure for the checksum file.

I recommend emulating what Hashicorp does here for their products (terraform, packer, vault, etc): Example terraform download page: https://www.terraform.io/downloads.html

**Comment by TownLake** [comment]
Thanks for the feedback - we have since added checksums to our GitHub releases:
https://github.com/cloudflare/cloudflared/releases
