### ISSUE TITLE
🐛QUIC tunnels unstabe, torn with  error="Incoming request ended abruptly: context canceled" error

### ISSUE THREAD

**Issue by Sahok1** [cloudflare/cloudflared#1313]
**Describe the bug**
When running the quic tunnel, I get that the websocket is constantly tearing. I checked one of the generated links via pingplotter and one of the Cloudflare servers loses almost all packets. I'm not sure where to write about this, since https://www.cloudflare status.com  declares that everything is fine
![11](https://github.com/user-attachments/assets/5837cbae-2b9d-4ce9-8802-03b39d10c13a)

At the same time, I get errors such as:
ERR Request failed error="Incoming request ended abruptly: context canceled"
ERR Request failed error="stream 821 canceled by remote with error code 0"

At the same time, the network graph in the browser says that all requests were completed successfully with code 200, although this is not the case and some of the data is never loaded

**To Reproduce**
1. run cloudflared tunnel --url http://localhost:port
2. Watch how the site is half working or not working at all when you need to upload or download some data

**Environment and versions
 - OS: WIN10
 - Architecture: X86
 - Version: 2024.8.3 (built 2024-08-22-1347 UTC)

**Additional context**
I am in Russia location

UPD Some information:

I have nothing to do with Shopify and am a novice independent developer. I used cloudflare's quick tunnels to share my developments for my team. I noticed that tunnels broke down when our team leader informed me that my microservice was not working correctly. It was only a few hours later that it became clear that the tunnels were no longer working properly. 

Now we have switched to alternative, more complex and less convenient tunneling methods, mainly ngrok, but the peculiarity of our small project is that the services exchange relatively large amounts of data and only cloudflare could provide a good data exchange rate.

Quick tunnels are an excellent and convenient tool for novice developers, I would like the work of tunnels to return to its usual course. It's amazing that cloudflare doesn't have decent alternatives in this regard.

**Comment by lakshmanpasala** [comment]
Happening with all anonymous tunnels wherein websocket upgrade is failing.

**Comment by kinngh** [comment]
Can confirm this is an issue - this breaks HMR in frameworks like Remix and Next.js - constantly pinging the `/_next/webpack-hmr` endpoint that results in a `404`.

![Screenshot 2024-08-23 at 4 12 57 PM](https://github.com/user-attachments/assets/afa9c8dc-0374-4f10-b638-99fc38a3edfa)

**Comment by shauns** [comment]
We're getting many reports of this via Shopify app developers. Websockets appear to be unusable via Cloudflare tunnels at present.

**Comment by syskn** [comment]
Having this issue on my end as well since 22 Aug 13:00 PST (about 16 hours ago). Both ws and wss protocls are unreachable via Cloudflared tunnels.

**Comment by yhc44** [comment]
Same here (Shopify App Developer).

Whats going on here?

**Comment by janani-cr** [comment]
This issue is specific to [Quick Tunnels ](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/), a zero-step tool to experiment with Cloudflare Tunnel. This was designed only to support web traffic. We are working with Shopify team to find a better solution here.

**Comment by key88sf** [comment]
@janani-cr Are you guys able to restore the functionality until finding a better long term solution with Shopify?

**Comment by janani-cr** [comment]
We have restored the functionality for now, while we work with shopify to identify a secure and sustainable solution.

**Comment by Sahok1** [comment]
I confirm it! The tunnels are working properly, the websocket is stable again
