### ISSUE TITLE
Still logging warning when loglevel is error

### ISSUE THREAD

**Issue by analytically** [cloudflare/cloudflared#134]
When started with `--loglevel error` I'm still seeing 

```
time="2019-09-18T17:45:36Z" level=warning msg="Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /usr/local/etc/cloudflared /etc/cloudflared]"
```

**Comment by daltoniam** [comment]
Hi @analytically, what version of cloudflared are you running? There has been some improvements to the cloudflared's logging system in the most recent version that may have fixed this. Can you confirm if this is still happening for you in the latest version? (2020.7.3)

**Comment by analytically** [comment]
Fixed, thanks.

**Comment by analytically** [comment]
Would be good if the logging system would output date and time tho :-)
