### ISSUE TITLE
💡only 1 tunel?

### ISSUE THREAD

**Issue by eunaotenhoid** [cloudflare/cloudflared#1359]
I have a question, I'm using Cloudflare via Truenas, and I'd like to know if it's only possible to use 1 tunnel at a time, isn't it possible to add multiple tunnels? on the website I know it is possible, but I would like to know on the app

**Comment by mlanies** [comment]
> I have a question, I'm using Cloudflare via Truenas, and I'd like to know if it's only possible to use 1 tunnel at a time, isn't it possible to add multiple tunnels? on the website I know it is possible, but I would like to know on the app


Yes, you can use multiple Cloudflare tunnels in TrueNAS. Here are two approaches.

1 way
1. Install multiple instances of the Cloudflared app, giving each a unique name.
2. Add a specific tunnel token to each instance from Cloudflare.
3. Start and verify each instance to ensure the tunnels work properly.

Pros: Independent management of tunnels.
Cons: Becomes cumbersome if there are many tunnels.

2 way
1. Set up a single Cloudflare tunnel pointing to an Nginx Proxy Manager.
2. Configure routes in the proxy for your services (based on subdomains or paths).
3. All services are managed through a single tunnel.

Pros: Simplifies management for multiple services, lower system load.
Cons: Requires setting up and configuring a reverse proxy.

**Comment by eunaotenhoid** [comment]
It worked perfectly, thank you very much for the tips
