### ISSUE TITLE
Cloudflared Throughput Performance

### ISSUE THREAD

**Issue by victorstewart** [cloudflare/cloudflared#136]
Do ya'll have any benchmarks on what kind of throughput cloudflared is capable of handling?

I have a very high performance c++ application server that handles millions of generally idle websocket connections with high periodic bursts of traffic. And really want to switch over to using Argo routing to gain the benefits of quicker network routing, but worried cloudflared might become a bottleneck.

It currently runs natively on bare metal, and forks to the number of hyperthreads. Also happen to be considering moving to docker containers... and running a container per hyperthread, and a single instance per container. So maybe under that container model, running a cloudfared within each, might not suffer much penalty?

Any insights would be much appreciated!

**Comment by Tugzrida** [comment]
If you're just looking to improve routing, Argo can be enabled without the need for cloudflared and Argo tunnel - Argo tunnel(via cloudflared) is dependant on Argo Smart Routing, but not vice-versa.

**Comment by abelinkinbio** [comment]
We don't have hard benchmarks for Tunnel as we support a myriad of use cases and each varies significantly from another. 

One thing that may be beneficial in your environment specifically though is the release of multi-instance `cloudflared` which would help address some of the constraints with your deployment: https://blog.cloudflare.com/highly-available-and-highly-scalable-cloudflare-tunnels/
