### ISSUE TITLE
package architecture (arm) does not match system (arm64)

### ISSUE THREAD

**Issue by UnderwearWarrior** [cloudflare/cloudflared#140]
I'm running [Ubuntu Server 18.04.3 LTS](http://cdimage.ubuntu.com/releases/bionic/release/ubuntu-18.04.3-preinstalled-server-arm64+raspi3.img.xz) on a [Raspberry Pi 3 Model B v1.2](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/)

Unfortunately, I received an error during an attempt running [cloudflared-stable-linux-arm.deb](https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.deb):

    dpkg: error processing archive /tmp/cloudflared-stable-linux-arm.deb (--unpack): package architecture (arm) does not match system (arm64)

Any assistance would be very much appreciated. Thanks.

**Comment by j0n17** [comment]
You'll need to compile it yourself, it's pretty simple see this link:
https://github.com/cloudflare/cloudflared/issues/115#issuecomment-521092436

**Comment by sodabrew** [comment]
edc6969 was merged in time for the 2020.8.0 release, please see https://github.com/cloudflare/cloudflared/releases for recent releases with an arm64 build. There may not be Debian packages yet.
