### ISSUE TITLE
Feature: K8s Operator to inject sidecar

### ISSUE THREAD

**Issue by msnelling** [cloudflare/cloudflared#144]
Given that the Ingress controller project seems dead and that the [recommended ](https://github.com/cloudflare/cloudflare-ingress-controller/issues/172#issuecomment-541230988) way to use Argo tunnels with Kubernetes is with the sidecar model, providing an [Operator ](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) to automatically inject the sidecar would make integrating Argo tunnels into Kubernetes trivial.

For example, an Operator that watched for deployments with specific annotations and then updated the deployment so that it also starts the cloudflared tunnel container.
#### Other projects doing something similar...
* https://www.jaegertracing.io/docs/1.13/operator/#auto-injecting-jaeger-agent-sidecars
* https://github.com/Kong/kubernetes-sidecar-injector
* https://istio.io/docs/setup/additional-setup/sidecar-injection/#automatic-sidecar-injection

**Comment by jamie-34254** [comment]
@AustinCorridor Are there any plans on releasing an operator for this? We're using the ingress controller at the moment and although it's not ideal it's much more preferable to manually adding a sidecar to each of our deployments using an Argo Ingress.

**Comment by AustinCorridor** [comment]
We don't have short-term plans for releasing an Operator, but that's not because we don't plan to - we're still trying to figure out the best way to help teams deploy the sidecar model at scale. Releasing an Operator is a good option and one that we're evaluating.

**Comment by Maxpain177** [comment]
Any news?

**Comment by TownLake** [comment]
Not yet - still getting through some other packaging goals, but will update here when we have news. Thanks for the patience.

**Comment by abelinkinbio** [comment]
We recently released multi-instance `cloudflared` with this use case in mind. Check it out and let us know what you think: https://blog.cloudflare.com/highly-available-and-highly-scalable-cloudflare-tunnels/

We also made a tutorial to get started: https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel

**Comment by adyanth** [comment]
Something like this might help? Still very much in alpha, but i use it for my homelab.

https://github.com/adyanth/cloudflare-operator
