### ISSUE TITLE
FreeBSD binary

### ISSUE THREAD

**Issue by skhaz** [cloudflare/cloudflared#145]
Hi,

Is there an official binary for FreeBSD? (enable Linux binary compatibility is not an option at the moment.)

Thanks!

**Comment by egypcio** [comment]
@skhaz,

if you need to install it on a _FreeBSD_ machine, you can do it now using its [ports tree](https://www.freebsd.org/doc/handbook/ports-using.html). we added it with a slightly license restriction because it's not 100% clear if it may be redistributed; that means it will not be available as a package till we get the permission to do it.

the current port uses an unmodified version of the source code tagged as **2019.11.0**

https://svnweb.freebsd.org/ports?view=revision&revision=517872

**Comment by neo-neo1** [comment]
I see you can download every binary at this github page except for FreeBSD. Why?

It's irrelevant if it's in the ports tree or not since appliances such as pfsense do not have it. Guess I'll go to another product. Unfortunate.

**Comment by egypcio** [comment]
hello there! it's me again 👋 

hi @neo-neo1,

I'm still maintaining the [port](https://cgit.freebsd.org/ports/commit/?id=7a4b2a44e61fab5298e49ee428fac4e86f681cca) (currently following [2022.2.0](https://github.com/cloudflare/cloudflared/tree/2022.2.0) source as is).

on top of that, the port still respects **cloudflared**'s [LICENSE](https://github.com/cloudflare/cloudflared/blob/master/LICENSE#L32) in a way we are still _not_ offering any binary package.

here we have a bugzilla ticket that also tracks the way we work that out: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247047#c1 -- the comment expresses that publicly, that we are not even allowed to modify the source and such changes must be approved by **cloudflared**'s development team, so patches _MUST_ go to the upstream repository and not to the FreeBSD port itself.

back in 2019 I indeed mentioned the interest on serving binary packages for FreeBSD to [Cloudflare](https://www.cloudflare.com/). I also asked about doing it on IRC (and from time to time I still hang around); today it resides on _libera.chat_ as #cloudflare

sadly it's far from clear if we are allowed to serve the FreeBSD binary package for **cloudflared**. once it's clear that we are allowed to serve its binary, I would be happy to "flip that switch" and make it happen.

CC: @skhaz @TownLake

**Comment by abelinkinbio** [comment]
Adding support for FreeBSD is on our radar and we're looking to do so in a limited capacity this quarter. We still have a few challenges to sort out on our side however. 

As for our license, stay tuned to #464 for more updates.

**Comment by ralphshep** [comment]
Hello,
I'm also looking to install Cloudflared on FreeBSD (TrueNAS to be specific). Any future support for the platform would be greatly appreciated. I just tried using the port and didn't any success.

**Comment by egypcio** [comment]
> Adding support for FreeBSD is on our radar and we're looking to do so in a limited capacity this quarter. We still have a few challenges to sort out on our side however.
> 
> As for our license, stay tuned to #464 for more updates.

@abelinkinbio,

after [2022.2.1](https://github.com/cloudflare/cloudflared/tree/2022.2.1) was released and #464 was resolved, we now have an official FreeBSD port that allows the distribution of a binary package for **cloudflared**!

thank you and all the others behind the scenes (including @skhaz, @neo-neo1 and many more).

here's the official commit on FreeBSD's git repository that tracks and documents the change: https://cgit.freebsd.org/ports/commit/?id=90f6b25ceeea305630ceb5e09ce7c4391e761096

now we just need to wait until the package is built, and soon it will be available under the _latest_ branch of **pkg**; it will take longer to land on the _quarterly_ branch still.

* for those not familiar with the _"latest"_  branch, when we're talking about FreeBSD's **pkg**:

```
FreeBSD: {
    url: "pkg+https://pkg.freebsd.org/${ABI}/latest"
}
```

that's it! good luck and have fun 😈 

obrigado

**Comment by neo-neo1** [comment]
> > Adding support for FreeBSD is on our radar and we're looking to do so in a limited capacity this quarter. We still have a few challenges to sort out on our side however.
> > As for our license, stay tuned to #464 for more updates.
> 
> @abelinkinbio,
> 
> after [2022.2.1](https://github.com/cloudflare/cloudflared/tree/2022.2.1) was released and #464 was resolved, we now have an official FreeBSD port that allows the distribution of a binary package for **cloudflared**!
> 
> thank you and all the others behind the scenes (including @skhaz, @neo-neo1 and many more).
> 
> here's the official commit on FreeBSD's git repository that tracks and documents the change: https://cgit.freebsd.org/ports/commit/?id=90f6b25ceeea305630ceb5e09ce7c4391e761096
> 
> now we just need to wait until the package is built, and soon it will be available under the _latest_ branch of **pkg**; it will take longer to land on the _quarterly_ branch still.
> 
> * for those not familiar with the _"latest"_  branch, when we're talking about FreeBSD's **pkg**:
> 
> ```
> FreeBSD: {
>     url: "pkg+https://pkg.freebsd.org/${ABI}/latest"
> }
> ```
> 
> that's it! good luck and have fun 😈
> 
> obrigado

Awesome, excellent work. Can’t wait to install it soon

**Comment by neo-neo1** [comment]
@egypcio Any estimate when the pkg will be made available? I’ve been checking everyday since the announcement. Thanks in advance!

**Comment by egypcio** [comment]
> @egypcio Any estimate when the pkg will be made available? I’ve been checking everyday since the announcement. Thanks in advance!

@neo-neo1,
there's a package available already.

```
root@tak:~ # date ; uname -rmsUK ; pkg update -f ; pkg search -U cloudflared
Sun Feb 27 11:21:19 UTC 2022
FreeBSD 14.0-CURRENT amd64 1400053 1400053
Updating FreeBSD repository catalogue...
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01
Fetching packagesite.pkg: 100%    6 MiB   6.7MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 30955 packages processed.
All repositories are up to date.
cloudflared-2022.2.1           Cloudflare's Argo Tunnel client
```

though I'm running 14.0-CURRENT, I can confirm that packages for 12 and 13 are also available.

worth mentioning _(again)_ that it's on the **latest** branch of `pkg`'s repositories, as described before.

```
root@tak:~ # cat /usr/local/etc/pkg/repos/FreeBSD.conf
FreeBSD: {
  url: "pkg+https://pkg.freebsd.org/${ABI}/latest",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
```

to get a bit more information about how things work with `pkg` and its official repositories, you can jump into [this forum thread here](https://forums.freebsd.org/threads/is-freebsd-pkg-command-pointing-to-latest-repository.67571/). if you are already sure about the decision of changing branches there, you might want to ready only [this post](https://forums.freebsd.org/threads/is-freebsd-pkg-command-pointing-to-latest-repository.67571/#post-401256).

⚠️ please be aware that modifying those settings will affect how other packages receive patches and updates as a whole too. this is that well-known _"do at your own risk"_ advice 😅 just in case.

PS: I'd say this issue can be closed, right? 🤔 //ping @skhaz @abelinkinbio

**Comment by Marietto2008** [comment]
I tried to install cloudflare warp for Linux on the Linuxulator for FreeBSD 14,but it failed :

```
unable to set CAP_SETFCAP effective capability: Operation not permitted
setcap failed on /bin/warp-svc
E: Sub-process /usr/bin/dpkg returned an error code (1)
# cloudflare-warp
bash: cloudflare-warp: command not found
```

can be fixed ?
