### ISSUE TITLE
Error proxying request to origin with Tinyproxy

### ISSUE THREAD

**Issue by greg5678** [cloudflare/cloudflared#146]
I'm using Tinyproxy and `cloudflared` to try and access Tinyproxy from outside my home network. I'm running on a CGNAT so I don't have my own public ip address. To solve this issue I thought of using [`cloudflared`](https://blog.cloudflare.com/a-free-argo-tunnel-for-your-next-project/), but when I looked at cloudflared's logs I kept seeing `ERRO[0174] HTTP request error                            error="Error proxying request to origin: read tcp xxx.xxx.xxx.xxx:36484->xxx.xxx.xxx.xxx:8888: read: connection reset by peer"`?

**Comment by greg5678** [comment]
Okay so I think I understand what the problem is. I keep getting Error 1000, which in my case has to do with Cloudflare having issues with reverse proxies. For Tinyproxy I disabled the Via header, but for some reason I still keep getting error 1000.

**Comment by abelinkinbio** [comment]
This isn't currently a supported use case for Tunnel and unfortunately, we do not plan to support it in the near term. However, we've noted this request and will open this thread back up if we work on this in the future.
