### ISSUE TITLE
How to use dns over tls

### ISSUE THREAD

**Issue by f4nff** [cloudflare/cloudflared#147]
```
proxy-dns: true
proxy-dns-port: 53
proxy-dns-address: 0.0.0.0
proxy-dns-upstream:
 - https://dns.google/dns-query
 - https://cloudflare-dns.com/dns-query

```

I only know that this can be dns over https

But does not support dns over tls

help me

**Comment by daltoniam** [comment]
Hi, not sure what you mean by not "support dns over tls"? What exactly are you looking for the dns resolver to do?

**Comment by seamooose** [comment]
Possibly looking for an alternative to DoH (similar query: https://github.com/cloudflare/cloudflared/issues/61)

**Comment by TownLake** [comment]
Closing while waiting on reply; please feel free to reopen.

**Comment by ahmed-sigmalux** [comment]
I'd also like to use DNS-over-TLS instead of DNS-over-HTTPS in cloudflared.
