### ISSUE TITLE
Access caches JWT Token, resulting in 302 when it is expired

### ISSUE THREAD

**Issue by patrobinson** [cloudflare/cloudflared#150]
When using `cloudflared access curl` we are seeing issues when we issue a command with the same path. It appears the token is cached, in `~/.cloudflared/`, based on the path we use.
But after a period of time that token expires.
Once the token is expired a call to the same endpoint results in a 302, which cloudflared doesn't handle correctly

```
cloudflared access curl https://my.access.protected.domain/some-path
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   143    0   143    0     0    123      0 --:--:--  0:00:01 --:--<html>  0
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

Once I remove the cached token at `~/.cloudflared/my.access.protected.domain-some-path-token` it goes through the authentication flow and works again.

**Comment by visago** [comment]
Fixed in https://github.com/cloudflare/cloudflared/commit/6d63f84a75b63ae31a30474bfcc6aac46507e3e3
