### ISSUE TITLE
The ability of allocating memory thresholds the tunnel throughput

### ISSUE THREAD

**Issue by rueian** [cloudflare/cloudflared#160]
Hi, I am interested in using cloudflared tunnel in production. While trying to find the maximum throughput of a single tunnel, I notice that it will keep allocating huge amount of memory while serving requests and lead to the speed of allocating memory being a bottleneck of throughput.

There is a screenshot taken from my test cluster on GCP:
![截圖 2019-12-12 下午5 17 36](https://user-images.githubusercontent.com/2727535/70792777-eaee9d00-1dd4-11ea-819b-a25f49eb93ef.png)

There are 3 waves on the graph, from left to right. The only change I made to get these different waves is scaling the machine where the cloudflared running on:
`1st wave is generated from cloudflared running on n1-highcpu-4 machine`
`2nd wave is generated from cloudflared running on n1-highcpu-8 machine`
`3rd wave is generated from cloudflared running on n1-highcpu-16 machine`

The 1st wave shows that, when running on `n1-highcpu-4`, cloudflared keeps allocating `~1GB/s` memory to serve maximum `~2.5K/s` request with `~75ms` latency collected by my client tool.

The 2nd wave shows that, after switching to `n1-highcpu-8`, cloudflared keeps allocating `~2GB/s` memory to serve maximum `~4K/s` request with `~50ms` latency collected by my client tool.

The 3rd wave shows that, after switching to `n1-highcpu-16`, cloudflared keeps allocating `~2.8GB/s` memory to serve maximum `~5K/s` request with `~48ms` latency collected by my client tool.

However the top-left chart shows that the total memory keeps around 190MB.
So, It seems that cloudflared is quite busy on allocating memory and releasing memory. And it seems that if cloudflared can allocate memory faster, the latency will be slower and the throughput will be higher.

Luckily, after collecting the profiling graph, it does shows where is the cause.

<img width="1620" alt="截圖 2019-12-18 下午6 20 43" src="https://user-images.githubusercontent.com/2727535/71080161-9463d300-21c7-11ea-9aed-b8eb8e33324d.png">

It shows that almost all allocations come from the `TunnelHandler.serveHTTP`. I believed it is this line of code doing the allocation, and can be optimized with a buffer pool mechanism: 
https://github.com/cloudflare/cloudflared/blob/789ca6f6f46a72b5138a1700e476e8c1d04528bf/origin/tunnel.go#L645

**Comment by rueian** [comment]
The PR https://github.com/cloudflare/cloudflared/pull/161 try to replace https://github.com/cloudflare/cloudflared/blob/789ca6f6f46a72b5138a1700e476e8c1d04528bf/origin/tunnel.go#L645 with a buffer pool mechanism.


The result of the PR on `n1-highcpu-4` machine:
<img width="1578" alt="截圖 2019-12-18 下午6 51 20" src="https://user-images.githubusercontent.com/2727535/71081548-6764ef80-21ca-11ea-8478-2835aac6c0ff.png">

After applying buffer pool mechanism:

* The memory allocating rate drops to 70MB/s, which can be ~2.8GB/s in previous version.
* The P99 latency collected by clients keeps under 50ms.
* I can now achieve 5K+ throughput on `n1-highcpu-4` machine, which can only be achieved on `n1-highcpu-16` in my previous test (the Top Right graph is NOT stacked).

Please take a look on the PR  https://github.com/cloudflare/cloudflared/pull/161 🙏

**Comment by TownLake** [comment]
Closing after PR has been merged but please let us know if you observe additional issues.
