### ISSUE TITLE
Facilitate automation for trycloudflare.com free service

### ISSUE THREAD

**Issue by awakecoding** [cloudflare/cloudflared#169]
I have a documented "getting started" procedure for a product I am working on that leverages the free cloudflare argo tunnel service in order to avoid dealing with TLS certificates and external access: https://github.com/Devolutions/WaykDen-ps/blob/master/docs/getting-started-argo.adoc

It works well for quick testing, and I have no problem recommending that users consider getting the paid cloudflare argo tunnel service for a production deployment. In an effort to reduce the number of steps required to get something minimally functional to experiment with, I have even added a special demo mode in my application that checks for *.trycloudflare.com URLs to function is if a license was installed, skipping the step of requesting a trial license and installing it.

This being said, I found some pain points that required adding a few extra steps to my getting started guide:

1) cloudflared won't launch if the provided url (--url http://localhost:4000 in my case) cannot be reached. However, if I have something listening at the provided URL when creating the tunnel, I can terminate and restart my application without problem, even if cloudflared won't be able to tunnel the traffic to http://localhost:4000 during my application restart. This is problematic because of the next point.

2) Since the randomly-generated URL cannot be known ahead of time, I have to launch my application to listen on http://localhost:4000, create the argo tunnel, wait for the URL to be displayed, stop my application, configure my application with a new external URL, then restart my application. However, if I could create the tunnel first and disable the startup check for reachability of the given URL, I would be able to launch the tunnel, wait for the randomly-generated URL, then configure my application with it and then launch it once.

3) Last but not least, since the URL is randomly-generated and displayed in the terminal, it is not possible for a script to pass a known URL value to the cloudflared executable, and it is also not very easy to find a way to write a script that would launch cloudflared, wait for the tunnel to be ready, extract the generated URL and then automatically inject it into my application's configuration.

If points 1-2-3 could be handled better, I would be able to provide a special command to bootstrap my application with a ready-made argo tunnel and prepopulated application data for demo purposes. It would always remain a one-time demo environment, but it would drastically reduce the number of steps to get something up and running that a user can interact with.

Simple improvements could be made:

1) Add a --skip-url-check option to intentionally disable the url check on startup. I understand why it is there, so it should remain enabled by default, but in this special case I would disable it.

2) As for extracting the generated URL, an elaborate solution would be to add an HTTP listener with a REST API inside cloudflared such that it could be repeatedly polled for status. However, I would be fine with a much "dumber" approach: cloudflared could simply update a json file with tunnel status information. It would be relatively simple for me to poll-read that file, even if it's not the most elegant solution.

Let me know what you think could be made! I'd be glad to get the word out about Cloudflare's Argo tunnel service by using it as part of a quick getting started guide for my application.

**Comment by felixbuenemann** [comment]
The first point is an unrelated issue and deserves its own bug report.

The automation can kind of be hacked around by querying the prometheus metrics. Run the tunnel with a known port for metric, eg. `--metrics localhost:8081` and then use a prometheus lib or string search to find the url in the `userHostname` label in `cloudflared_tunnel_user_hostnames_counts`. 

Your app should poll the endpoint, since the sample will only be available once the tunnel is up.

To set what metrics are rovided just do a `curl -s http://localhost:8081/metrics`.

If you do not manually specify a port for the metrics, it will run on a random high port, which makes it tricky to discover, so you'll have to make your users or automation deal with finding a free port.

Also since this isn't an official API, it can break at any time.

**Comment by sssilver** [comment]
Point #1 has been addressed. See https://github.com/cloudflare/cloudflared/pull/177

**Comment by sssilver** [comment]
For points #2 and #3, the idiomatic solution is to use the metrics endpoint, as pointed out by @felixbuenemann above.

**Comment by awakecoding** [comment]
Thanks, this answers my original question, we can close this issue.

**Comment by ABCDEjsjs** [comment]
![1675131972397](https://github.com/cloudflare/cloudflared/assets/140861737/a48bbe63-fddb-432b-9432-1aedc86ddf9b)
