### ISSUE TITLE
reconnect to origin

### ISSUE THREAD

**Issue by riuvshyn** [cloudflare/cloudflared#175]
hello, is there a way to not stop execution and try to reconnect to the origin?
having running cloudflared as a sidecar that relies on another sidecar (service mesh) is a pain and causes issues with deployments. 
Basically expected behavior is keep cloudflared running and trying to reconnect also reporting that origin is not available and reflect that in health status an 
🙏

**Comment by dozortsev** [comment]
hello @sssilver maybe you could help/advise us here?

**Comment by sssilver** [comment]
Hi!

The intended behavior is that _cloudflared_ would _not_ stop execution, but rather constantly try to reconnect. Do you have logs that show how it terminates?

Thanks!

**Comment by riuvshyn** [comment]
@sssilver yeah it fails with this:
```
ERRO[0000] unable to connect to the origin               error="Get http://localhost:10110: dial tcp 127.0.0.1:10110: connect: connection refused"
```
https://github.com/cloudflare/cloudflared/blob/a60c0273f5b4b51c57e7e3faa0ac5076e9ff8747/cmd/cloudflared/tunnel/configuration.go#L239

**Comment by sssilver** [comment]
Ahh, I see, do you want it to _not_ give up when you're starting the cloudflared process up from scratch?

**Comment by riuvshyn** [comment]
@sssilver yes exactly.

**Comment by riuvshyn** [comment]
@sssilver WDYT https://github.com/cloudflare/cloudflared/pull/177 ?
