### ISSUE TITLE
Go Build Fails

### ISSUE THREAD

**Issue by TXS380** [cloudflare/cloudflared#176]
## Problem 
Due to #115 I tried building from source. I followed bcatubig's instructions but building fails. 
## Building on Ubuntu 18.04
go version is:
`go version go1.10.4 linux/amd64`

i ran:
`GOOS=linux GOARCH=arm64 go build github.com/cloudflare/cloudflared/cmd/cloudflared`
Output:
```
# github.com/cloudflare/cloudflared/dbconnect
go/src/github.com/cloudflare/cloudflared/dbconnect/sql.go:225:40: iso.String undefined (type sql.IsolationLevel has no field or method String)
go/src/github.com/cloudflare/cloudflared/dbconnect/sql.go:225:51: undefined: strings.ReplaceAll
# github.com/cloudflare/cloudflared/sshserver
go/src/github.com/cloudflare/cloudflared/sshserver/host_keys.go:30:19: undefined: os.UserHomeDir
```

I never user Golang for programming, apologies in advance if that issues is caused on my side.

**Comment by dougnukem** [comment]
It appears argo depends on `>= go1.12` 

https://github.com/cloudflare/cloudflared/blob/master/go.mod#L3

**Comment by TXS380** [comment]
Thank you so much @dougnukem, works like a charm. Closing issue.
