### ISSUE TITLE
Binary for arm hangs up

### ISSUE THREAD

**Issue by adamski234** [cloudflare/cloudflared#182]
Cloudflared 2019.12.0 running on Raspberry pi 3B+, Raspbian 10, alongside pihole. Sometimes the daemon simply stops responding. When trying to restart it with `systemctl restart cloudflared.service` the command hangs for a few seconds and then timeouts and kills it
```
cloudflared.service: State 'stop-sigterm' timed out. Killing.
cloudflared.service: Killing process 24950 (cloudflared) with signal SIGKILL
Main process exited, code=killed, status=9/KILL
Failed with result 'timeout'.
```
Before the restart, logs show `Timeout while awaiting headers` and `network is unreachable` errors. My network tends to lose connection pretty often but I don't know if it's related

**Comment by XhmikosR** [comment]
@adamski234 did you try the latest version? Just wondering since personally I've been using it on Raspbian 10 with pi 4 without any issues.

**Comment by adamski234** [comment]
I'm pretty sure I did, I downloaded the newest release the day I opened the issue

**Comment by XhmikosR** [comment]
Apparently it wasn't the latest at the time though. https://github.com/cloudflare/cloudflared/releases

**Comment by TownLake** [comment]
@adamski234 could you update and try again? The release that you mention in your post would have been a few months old at the time. We've added some improvements since then that might address this issue.
