### ISSUE TITLE
ArgoTunnel Tcp Support

### ISSUE THREAD

**Issue by WoodProgrammer** [cloudflare/cloudflared#183]
Hi,
I have a database instance that located on a private network and I want to access it via TCP tunnel with `cloudflared`. 

I have checked the latest commit but I cannot create a connection as TCP between my client. 

Latest commit on repository: https://github.com/cloudflare/cloudflared/commit/a368fbbe9b4ec7ebe2bd81b0c4903ab444a35ba5, look TCP is supported on protocols alias of ssh? 

How can I handle that? If this is possible to do or not.

**Comment by brain2002** [comment]
You could use a syntax like this. _(RDP is a TCP tunnel)_

> cloudflared access rdp --hostname [your-cloudflare-dns-entry] --url rdp://127.0.0.1:[free-port-on-your-pc]

Maybe in the future there will be an alias. If you use 'tcp://' in version 2.2.x or 2.3.x it will throw an error _"Currently Argo Tunnel does not support tcp protocol."_

In your database tool you can use 127.0.0.1:[free-port-on-your-pc].

If you want both SSH and database access on the same server you'll have to setup 2 tunnels. Meaning two systemd services. I solved it by copying the default created systemd service and changing the config.

> [Unit]
> Description=Argo Tunnel MySQL
> After=network.target
> 
> [Service]
> TimeoutStartSec=0
> Type=notify
> ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config-mysql.yml --origincert /etc/cloudflared/cert.pem --no-autoupdate
> Restart=on-failure
> RestartSec=5s
> 
> [Install]
> WantedBy=multi-user.target

And in the config-mysql.yml

> hostname: [your-cloudflare-dns-entry] 
> url: rdp://127.0.0.1:3306
> logfile: /var/log/cloudflared-mysql.log

**Comment by Maef** [comment]
You could use a syntax like this. _(RDP is a TCP tunnel)_

> cloudflared access rdp --hostname [your-cloudflare-dns-entry] --url rdp://127.0.0.1:[free-port-on-your-pc]

Maybe in the future there will be an alias. If you use 'tcp://' in version 2.2.x or 2.3.x it will throw an error _"Currently Argo Tunnel does not support tcp protocol."_

In your database tool you can use 127.0.0.1:[free-port-on-your-pc].

If you want both SSH and database access on the same server you'll have to setup 2 tunnels. Meaning two systemd services. I solved it by copying the default created systemd service and changing the config.

> [Unit]
> Description=Argo Tunnel MySQL
> After=network.target
> 
> [Service]
> TimeoutStartSec=0
> Type=notify
> ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config-mysql.yml --origincert /etc/cloudflared/cert.pem --no-autoupdate
> Restart=on-failure
> RestartSec=5s
> 
> [Install]
> WantedBy=multi-user.target

And in the config-mysql.yml

> hostname: [your-cloudflare-dns-entry] 
> url: rdp://127.0.0.1:3306
> logfile: /var/log/cloudflared-mysql.log

**Comment by mustafakirimli** [comment]
We sould ask team to just add following changes to be able to specify tcp://host:port

https://github.com/cloudflare/cloudflared/blob/3c9b700a52d371d6da220d3de55a27d63beb7c58/validation/validation.go#L19

**Comment by daltoniam** [comment]
This is now officially supported: https://developers.cloudflare.com/access/other-protocols/tcp-guide/

**Comment by ashutoshpw** [comment]
@daltoniam Mentioned link is giving 404 error, could you please share latest link?

**Comment by nmldiegues** [comment]
Hello @ashutoshpw ,

Since 1y ago we've had new developments. Today I'd say the recommended way to access private arbitrary TCP origins is by leveraging the WARP to Cloudflare Tunnel network capability. You can read more about it in:
- https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net
- https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel
- https://developers.cloudflare.com/cloudflare-one/tutorials/zero-trust-network-access 
- https://blog.cloudflare.com/private-networking/
- https://blog.cloudflare.com/network-based-policies-in-cloudflare-gateway/
- https://blog.cloudflare.com/build-your-own-private-network-on-cloudflare/

Alternatively, you can still use the old way mentioned in this thread. There are many equivalent/similar tutorials to using `cloudflared access` on the client side to wrap arbitrary TCP traffic and deliver it to a `cloudflared tunnel` on the server side that can then reach the origin TCP-based server:
 - https://developers.cloudflare.com/cloudflare-one/tutorials/kubectl
 - https://developers.cloudflare.com/cloudflare-one/tutorials/rdp

**Comment by ashutoshpw** [comment]
Thanks @nmldiegues 

I have tried implementing private networking using this tutorial
https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel

It is working fine with Desktop Warp Clients but not working on Android by using Warp through 1.1.1.1 app.
Is it compatible with Mobile app OR not? 

Posted on Community forum as well
https://community.cloudflare.com/t/private-network-on-warp-not-working-on-mobile/277518

**Comment by TownLake** [comment]
We haven't released mobile support for the private routing feature just yet, but we will as part of our WARP mobile app soon. We'll be sure to send an update once that is available.

**Comment by whalehub** [comment]
> We haven't released mobile support for the private routing feature just yet, but we will as part of our WARP mobile app soon. We'll be sure to send an update once that is available.

@TownLake Are there any updates on mobile support for the private routing feature via WARP?

**Comment by TownLake** [comment]
@whalehub - this is supported now, feel free to try it out and let us know how it goes.

**Comment by whalehub** [comment]
> @whalehub - this is supported now, feel free to try it out and let us know how it goes.

Just gave it a try and it works beautifully. This opens up so many new possibilities - exciting stuff!
