### ISSUE TITLE
Requests coming through Argo Tunnel are missing CloudFlare headers

### ISSUE THREAD

**Issue by Artamus** [cloudflare/cloudflared#187]
I apologize in advance if this is the wrong place to ask about this.

I have a web application that is connected via Argo Tunnel to CloudFlare (to facilitate usage of CloudFlare Access). I rely on the `Cf-Access-Authenticated-User-Email` header in this web application, but at some point one-three weeks ago this header stopped coming through. I ran some tests and noticed that it was a newer instance of Argo Tunnel that was causing this, i.e. rolling back to an image containing the older Tunnel everything works.

Is this a planned change, am I mistaken that the headers are being cut by Argo Tunnel?

As a side note, before there were a ton of different CloudFlare headers present, whereas now with the newest Tunnel I'm only seeing `cdn-loop, cf-warp-tag-id`.

**Comment by sssilver** [comment]
Hi @Artamus, thanks for reporting this!

Have you tried running the latest cloudflared (2020.3.2)? We fixed some header-related issues in that version, I'm curious if you still see problems in it?

**Comment by Artamus** [comment]
> Hi @Artamus, thanks for reporting this!
> 
> Have you tried running the latest cloudflared (2020.3.2)? We fixed some header-related issues in that version, I'm curious if you still see problems in it?

It seems it was indeed fixed by 2020.3.2!

Comparing the commit logs, I discovered the problems the very same day 2020.3.2 was released, I must have had my debugging adventures when `bin.equinox.io` was not yet serving the newest version at that point, but I had already seen headers related commits in this repository.

Thanks for the heads-up :)
