### ISSUE TITLE
notes for installing on a Ubiquiti Edgerouter 4

### ISSUE THREAD

**Issue by stephenjamieson** [cloudflare/cloudflared#19]
First, download and build cloudflared with mips64 (not covering go environment setup here)

Note: mips64 is used for the ER-4,  other routers may use different architectures 

```
# download src
go get -d github.com/cloudflare/cloudflared/cmd/cloudflared
# cross compile for linux and mips64
GOOS=linux GOARCH=mips64 go build github.com/cloudflare/cloudflared/cmd/cloudflared
# copy the binary to your router
scp <gobindir>/cloudflared <user>@<router>:
```

ssh to your router

```
# need root
sudo -i
# change ownersship of the binary
chown root:root cloudflared
# change permissions to allow execution
chmod +x cloudflared
# mv the binary to /usr/local/bin
mv cloudflared /usr/local/bin/
# create the cloudflared config directory
mkdir /etc/cloudflared
```

add `config.yml` to `/etc/cloudflared` (setting the proxy-dns-port to an available port on your router you know you won't use for anything else)

```
proxy-dns: true
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query
proxy-dns-port: 8853
```

install the default init script

```
/usr/local/bin/cloudflared service install
```

Since we are using mips64, you'll want to disable auto update by replacing the cmd line with

   ```
   cmd="/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --origincert /etc/cloudflared/cert.pem --pidfile /var/run/$name.pid --no-autoupdate"
   ```

Start the `cloudflared` service

```
/etc/init.d/cloudflared start
```

Finally for your router configuration,

```
# use dnsmasq (see https://help.ubnt.com/hc/en-us/articles/115002673188-EdgeRouter-Using-dnsmasq-for-DHCP-Server)
# enable the dnsmasq dhcp server
set service dhcp-server use-dnsmasq enable 
# set the router's name server
set system name-server 127.0.0.1
# set the default listen device
set service dns forwarding listen-on eth1
# set a default dns name for your local network
set system domain-name home.local 
# set your forwarding dns to the cloudflared port
set service dns forwarding options server=127.0.0.1#8853
commit
save
exit
```

Test if it works!

**Comment by stephenjamieson** [comment]
Just some notes, someone else should test!

**Comment by stephenjamieson** [comment]
Thanks @NixM0nk3y, fixed it in the first comment.

**Comment by gedw99** [comment]
Can someone help me out ?

If your main adsl is untouched and you plugin your own router with the cloudflare code running, does it serve the local webserver on that router ?

No messing with port forwarding on the adsl router ?

**Comment by rufoa** [comment]
@stephenjamieson works great, thank you!

**Comment by sssilver** [comment]
Great write-up, @stephenjamieson -- thanks!

Would it make sense to move this somewhere else (Github pages?), since it's not really an "issue" per se?

**Comment by stephenjamieson** [comment]
This issue was created by request from someone on the cloudflare side so it could be added to the instructions page on cloudflared.  I'm fine with whatever you want to do with it.

**Comment by trch15** [comment]
I realize I'm a little late to the game but there seems to be a long-standing issue with the mips64 build of cloudflared on EdgeOS/Unifi equipment. The cloudflared process, if started before Internet connectivity is established, pegs the CPU indefinitely and all queries fail with `*** Gateway can't find msn.com: Server failed`

**Comment by trch15** [comment]
This appears to be the actual issue
`time="2019-12-31T13:45:18-06:00" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: dial tcp 1.1.1.1:443: socket: too many open files"`
and
`time="2019-12-31T17:37:58-06:00" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: write tcp **MY IP:PORT**->1.1.1.1:443: write: broken pipe"`

**Comment by trch15** [comment]
This is with cloudflared working
```Gateway:~$ sudo lsof -p 6611
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF  NODE NAME
cloudflar 6611 root  cwd    DIR   0,11     4096     2 /
cloudflar 6611 root  rtd    DIR   0,11     4096     2 /
cloudflar 6611 root  txt    REG   0,11 41517789 10618 /usr/local/bin/cloudflared
cloudflar 6611 root    0r   CHR    1,3      0t0    86 /dev/null
cloudflar 6611 root    1w   REG   0,15        0 29853 /var/log/cloudflared.log
cloudflar 6611 root    2w   REG   0,15  1014022 29854 /var/log/cloudflared.err
cloudflar 6611 root    3u  IPv4  38916      0t0   UDP localhost:8853
cloudflar 6611 root    4u  0000    0,7        0  1025 anon_inode
cloudflar 6611 root    5u  IPv4  38917      0t0   TCP localhost:8853 (LISTEN)
cloudflar 6611 root    6u  IPv4  38918      0t0   TCP Gateway:8099 (LISTEN)
cloudflar 6611 root    7r   CHR    1,9      0t0  3433 /dev/urandom
cloudflar 6611 root   10u  IPv4  38538      0t0   TCP [MY LOCAL IP]:39373 ->one.one.one.one:https (ESTABLIS 
```
```
# ulimit -n
1024
```
After unplugging my WAN for a minute, then plugging back in I see the following repeated **many** times when running `lsof -p`
`cloudflar 6611 root   78u  IPv4  63949      0t0   TCP [MY IP]:38808->1.0.0.1:https (SYN_SENT)`
I gave it a minute and now I'm seeing this repeated over and over.
`cloudflar 6611 root  365u  sock    0,5      0t0 75628 can't identify protocol`

I unplugged the WAN cable and restarted the service with no connectivity. Measuring the count of open connections with netstat, most of them are in SYN_SENT.
```
# while [ 1 ]; do netstat -anp | grep cloudflared | wc -l; sleep 5; done
1019
1010
1016
1019
988
1019
1019
1018
1017
1010
1015
1018
991
1004
1001
1016
1016
1019
1019
```
Then, after plugging the cable back in CPU is pegged. and they're in ESTABLISHED or CLOSE_WAIT states. Functionality never returns
```
651
631
593
588
552
515
473
509
569
591
745
775
905
852
771
534
537
580
491
570
```
Starting cloudflared with Internet services shows the following
```
# while [ 1 ]; do netstat -anp | grep cloudflared | wc -l; sleep 5; done
35
43
5
5
5
5
5
5
```
