### ISSUE TITLE
Graceful shutdown (draining connections)

### ISSUE THREAD

**Issue by james-callahan** [cloudflare/cloudflared#198]
Could cloudflared have a graceful shutdown mode where no new requests are handled; but existing connections are allowed to complete?

**Comment by james-callahan** [comment]
I see in https://github.com/cloudflare/cloudflared/blob/c3fa4552aacf6a735667eb4b430a2a9624c017f6/cmd/cloudflared/tunnel/signal.go#L12 that there is already some graceful shutdown logic. 

I also found the command line argument `grace-period`:
> Duration to accept new requests after cloudflared receives first SIGINT/SIGTERM. A second SIGINT/SIGTERM will force cloudflared to shutdown immediately.

Is this usage correct: will it continue to accept connections during the grace period? I would have expected that it only drains existing connections rather than allowing new ones.

**Comment by james-callahan** [comment]
Testing out using a longer grace period, and it did not behave as expected.
The tunnel stays alive for the grace period, still accepting new connections:

```
time="2020-05-14T00:07:35Z" level=info msg="Initiating graceful shutdown..."
time="2020-05-14T00:09:20Z" level=error msg="HTTP request error" error="Error proxying request to origin: dial tcp 127.0.0.1:80: connect: connection refused"
time="2020-05-14T00:09:23Z" level=error msg="HTTP request error" error="Error proxying request to origin: dial tcp 127.0.0.1:80: connect: connection refused"
```

I was expecting it to exit as soon as all connections had drained, and not accept any additional connections while in the shutting down state.

**Comment by TownLake** [comment]
Hi James - recent changes in `cloudflared` should improve graceful shutdown handling; specifically these commits:
https://github.com/cloudflare/cloudflared/commit/6cdd20e820f8acc3d3575399fe92ee0499884688
https://github.com/cloudflare/cloudflared/commit/d503aeaf7702e4794c2766d6e6eaf2e3a91cc8f8

Let us know if you have a chance to test and confirm. Thanks for the report.

**Comment by james-callahan** [comment]
> Let us know if you have a chance to test and confirm. Thanks for the report.

I've tested locally and it seems to work!

I left a long running request going, and pressed ctrl+c to start a shutdown of cloudflared:
```
^C2021-02-24T05:15:22Z INF Initiating graceful shutdown due to signal interrupt ...
2021-02-24T05:15:22Z INF Unregistered tunnel connection connIndex=2
2021-02-24T05:15:22Z INF Unregistered tunnel connection connIndex=0
2021-02-24T05:15:22Z INF Unregistered tunnel connection connIndex=1
2021-02-24T05:15:22Z INF Unregistered tunnel connection connIndex=3
```

it then sat there waiting until the response occurred; it then completed shut down.

Similarly if I left a request running, signalled the tunnel, and tried to make another request, I correctly got the error:
```
503 Service Unavailable
The origin has been unregistered from Argo Tunnel
```
