### ISSUE TITLE
cloudflared wont resolve usbank.com

### ISSUE THREAD

**Issue by nimbius** [cloudflare/cloudflared#201]
cloudflared fails to resolve any usbank.com address (including api.usbank.com) with SRVFAIL.

[root@dunkel]# dig @1.1.1.1 usbank.com

; <<>> DiG 9.16.2 <<>> @1.1.1.1 usbank.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 5351
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;usbank.com.                    IN      A

;; Query time: 1503 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu May 21 20:31:00 PDT 2020
;; MSG SIZE  rcvd: 39

[root@dunkel]#

**Comment by vavrusa** [comment]
Sorry about that, tracking in https://community.cloudflare.com/t/servfail-with-u-s-bank-domains/168711/10

**Comment by nimbius** [comment]
@vavrusa 
thanks for picking this up! :) if you need, i can provide more data or join the thread on community.cloudflare.  this is from DiG 9.16.2 at 23.243.218.117/    2605:e000:130a:fb:bff0:a1f3:c9f9:9068/64  and vultr ranges around 2001:19f0:6001:449b:2395:969a:50c1:99b8/64 

resolution is performed very slowly for this TLD at a few ragingwire datacenter systems, although any other domain is lightning fast. :)

api.usbank.com is also affected.

**Comment by TownLake** [comment]
Moving resolver discussion to Cloudflare Community thread.
