### ISSUE TITLE
bug (?) with --id / --secret for `access ssh`

### ISSUE THREAD

**Issue by gnawhleinad** [cloudflare/cloudflared#202]
I'm struggling to understand how the `access ssh` command uses service tokens... I'm hoping to use service token so that machine users can SSH to a server behind argo tunnels.

I've confirmed that the `--id` / `--secret` flag (added in https://github.com/cloudflare/cloudflared/commit/58e5e9c9a4bb94538b9165b977573f687057bcf9) requires manual intervention to retrieve a token. Was this the intention...? I had _hoped_ service tokens could be used for [automated requests / login](https://developers.cloudflare.com/access/service-auth/service-token/).

Right now, the `ssh` command will [`BuildAccessRequest`](https://github.com/cloudflare/cloudflared/blob/a908453aa4e2455e1539b8441f4a9732aba16bac/carrier/carrier.go#L132) which requires a `transfer.Run`:

https://github.com/cloudflare/cloudflared/blob/a908453aa4e2455e1539b8441f4a9732aba16bac/cmd/cloudflared/transfer/transfer.go#L27-L33

**Comment by gnawhleinad** [comment]
https://github.com/cloudflare/cloudflared/commit/0d87279b2f545f282cbd1b85c12512869c625fc4 was pushed.

I tried it out but I'm still getting:

```
# cloudflared access ssh --service-token-id REDACTED --service-token-secret REDACTED --hostname REDACTED
Please open the following URL and log in with your Cloudflare account:
...
```

Do I have a misunderstanding on :point_up:'s usage...? Or, ...?!

**Comment by TownLake** [comment]
Hi @gnawhleinad - this will work, but the flags you'll need to use are `--id` and `--secret`. The command would then look ike this:

`# cloudflared access ssh --id VALUE --secret VALUE`

Let me know if that takes care of the issue.

https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/access/cmd.go#L149-L157

**Comment by gnawhleinad** [comment]
> Hi @gnawhleinad - this will work, but the flags you'll need to use are `--id` and `--secret`. The command would then look ike this:
> 
> `# cloudflared access ssh --id VALUE --secret VALUE`
> 
> Let me know if that takes care of the issue.

Unfortunately, it does not...

The `--id` / `--secret` are aliases for `--service-token-id` / `--service-token-secret` (respectively). Further, your example is missing the `--hostname` flag.

**Comment by TownLake** [comment]
Sorry about that. Could you upgrade to 2020.6.1 - that should work in that version. If not, we'll need to take a deeper look why not.

**Comment by jroyal** [comment]
I was able to get this working in 2020.6.1 from the command line by doing. 

```
ssh james@example.com -o ProxyCommand='/usr/local/bin/cloudflared access ssh --service-token-id <id> --service-token-secret <secret> --hostname %h'
```

I would just recommend sticking it in your ssh config though. 

If that still doesn't work then double check and make sure that you are using a `non-identity` or `service-auth` policy in Access.

**Comment by gnawhleinad** [comment]
> If that still doesn't work then double check and make sure that you are using a `non-identity` or `service-auth` policy in Access.

:bow:, thanks so much! :point_up: was the issue.
