### ISSUE TITLE
Cloudflared failed due to the update

### ISSUE THREAD

**Issue by ykydxT** [cloudflare/cloudflared#207]
Hi,
I'm a new user of Cloudflared, and I'm running Cloudflared in a docker container. The Cloudflared failed yesterday due to the latest update. After I reinstalled the Cloudflared, it's working again. I'm wondering how could I prevent it failing again when there's a new release. Maybe a cron job of updating Cloudflared? 

![image](https://user-images.githubusercontent.com/22582081/84339171-309fed00-abe1-11ea-8517-87f840a22685.png)
Sorry about the screenshot, my previous container was killed and I could not find the logs back.

Dex

**Comment by chungthuang** [comment]
Hi Dex, I'm sorry about your experience. When running cloudflared inside a container, we recommend running with autoupdate disabled by setting the --no-autoupdate flag, and update version manually.
