### ISSUE TITLE
version 2020.6.1. appears to have broken commands

### ISSUE THREAD

**Issue by kieraenns-boldcommerce** [cloudflare/cloudflared#208]
Cloudflared auto-updated to this version 2 days ago and ever since I haven't been able to start any tunnels or run any cloudflared commands-- they all just trigger the help options menu as seen in the screenshot:

![Screen Shot 2020-06-11 at 10 16 50 AM](https://user-images.githubusercontent.com/57495836/84413293-05fc6700-abd6-11ea-9aa4-8b821280f730.png)

Several of my coworkers are also experiencing this issue. The new release appears to have broken the commands. All of them trigger this except doing a `cloudflared --version`

**Comment by adamchalmers** [comment]
Hi, I'm sorry this is happening to y'all. I'm unable to reproduce this on my 2020.6.1 build, so let me try to reproduce your conditions. Which OS are you running this on, and how did you originally install cloudflared?

**Comment by chungthuang** [comment]
I'm very sorry about your experience. Do you have a config file cloudflared? They are usually in ~/.cloudflared/config.yaml, /usr/local/etc/cloudflared/config.yaml or /etc/cloudflared/config.yaml.

**Comment by chungthuang** [comment]
Can you also tell us more about the environment your cloudflared is running in?

**Comment by kieraenns-boldcommerce** [comment]
Hi, I'm running on MacOS, Specifically Mojave 10.14.6. I found the condig.yaml file and it appears to be empty

**Comment by adamchalmers** [comment]
OK. I know you said this command didn't work, but could you try running `cloudflared tunnel --hello-world` and show us the output?

**Comment by kieraenns-boldcommerce** [comment]
For sure, I get the same thing: 
![Screen Shot 2020-06-12 at 11 04 15 AM](https://user-images.githubusercontent.com/57495836/84522713-c3519200-ac9c-11ea-8b69-41764745d73a.png)

**Comment by adamchalmers** [comment]
OK. Could you check if there's any files in any of these locations:
~/.cloudflared
~/.cloudflare-warp
~/cloudflare-warp
/usr/local/etc/cloudflared
/etc/cloudflared

And if so, could you move them somewhere else and see if that resolves the problem?

**Comment by kieraenns-boldcommerce** [comment]
Inside of ~./cloudflared I have the following:
cert.pem
cloudflared.log
config.yaml (empty)

I do not have anything in any of the other locations

**Comment by adamchalmers** [comment]
What happens if you delete the config.yaml file?

**Comment by kieraenns-boldcommerce** [comment]
Hmmm, looks like same thing

**Comment by chungthuang** [comment]
Can you try to run this command cloudflared proxy-dns --port 80000?

**Comment by adamchalmers** [comment]
Sorry for how long this is taking us to debug. Two questions:

1. Does this problem occur for you in version 2020.5.1? You can download old packages from [equinox](https://dl.equinox.io/cloudflare/cloudflared/stable/archive)
2. Does this problm occur on latest master? You should be able to build this pretty easily from source, we do our development on Macs too.

**Comment by 99six** [comment]
FYI, Just building CentOS 7.7 today in Azure and am also unable to start argo tunnels.  Reverted to 2020.5.1 (the version on the last batch of servers) and with no change to config.yml the argo tunnels are again working.

cloudflared]# systemctl status cloudflared.service
● cloudflared.service - Argo Tunnel
   Loaded: loaded (/etc/systemd/system/cloudflared.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-06-15 06:11:03 UTC; 3s ago
  Process: 127571 ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --origincert /etc/cloudflared/cert.pem --no-autoupdate (code=exited, status=1/FAILURE)
 Main PID: 127571 (code=exited, status=1/FAILURE)

Jun 15 06:11:03 xxx-xxxx systemd[1]: Failed to start Argo Tunnel.
Jun 15 06:11:03 xxx-xxxx systemd[1]: Unit cloudflared.service entered failed state.
Jun 15 06:11:03 xxx-xxxx systemd[1]: cloudflared.service failed.

**Comment by kieraenns-boldcommerce** [comment]
Hi, running the command `cloudflared proxy-dns --port 8000` gives me the same help screen: 
![Screen Shot 2020-06-15 at 9 06 44 AM](https://user-images.githubusercontent.com/57495836/84667164-993fe000-aee7-11ea-80f1-c15a43d9bbc8.png)

The last version I had was 2020.2.0 which for sure was working. I have pulled down your repo locally and I do get this problem on master, yes. Currently I checked out 2020.2.0 locally and am running that to get my tunnels going and that version works. I will try 2020.5.1 and see if that version works as well.

**Comment by chungthuang** [comment]
We released 2020.6.3, please give that version a try, too.

**Comment by ProtoJazz** [comment]
2020.6.3 seems to have fixed it

**Comment by kieraenns-boldcommerce** [comment]
Confirmed 2020.6.3 appears to be working, thank you!
