### ISSUE TITLE
EOF Error

### ISSUE THREAD

**Issue by giusr** [cloudflare/cloudflared#21]
I am running the cloudflared DNS over HTTPS proxy with [pi-hole](https://github.com/pi-hole/pi-hole), every few hours i get the following error:

```
time="2018-04-19T20:46:26+02:00" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: EOF"
time="2018-04-19T20:46:34+02:00" level=error msg="failed to connect to an HTTPS backend \"https://1.0.0.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.0.0.1/dns-query: EOF"
```
Restarting the daemon fixes the problem for a while. This error also occurs right after rebooting, again restarting the daemon seems to work for a few hours.

**Comment by gnossen** [comment]
I've also been seeing this off and on. Oftentimes, I'll see it right after startup. Recently, we had a good run of about a week with no issues. Today, we saw the following error:
```
Apr 22 22:08:16 raspberrypi cloudflared[24544]: time="2018-04-22T22:08:16Z" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: write tcp 192.168.1.5:59494->1.1.1.1:443: write: broken pipe"

```
From that point on, `cloudflared` stopped returning responses. Periodically, it logged this message:
```
Apr 22 22:08:41 raspberrypi cloudflared[24544]: time="2018-04-22T22:08:41Z" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/dns-query: EOF"
```
Restarting `cloudflared` did not alleviate the issue. Things only went back to normal once a full reboot of the system was performed.

This was observed on
```
cloudflared version 2018.4.6 (built 2018-04-11-1516 UTC)
```

**Comment by yon2004** [comment]
#24

**Comment by wheelq** [comment]
same here, but I see this less often once moved to different platform
