### ISSUE TITLE
cloudflared 2020.6.1 no longer logs to logfile defined in config

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#210]
cloudflared 2020.6.1 no longer logs to logfile defined in config
Have a simple entry in the config file like this:
logfile: c:\cloudflared\cloudflared-tol.log

... no log files are created or updated after updating to 2020.6.1

**Comment by vidarak** [comment]
also console output in 2020.6.1 is packed with weird characters:
←[36m[INFO] ←[0mVersion 2020.6.1
←[36m[INFO] ←[0mGOOS: windows, GOVersion: go1.12.9, GoArch: amd64

**Comment by sssilver** [comment]
Hi @vidarak thanks for reporting this!

We are aware of this issue and are publishing a new version that fixes the problem as I am typing this reply.

Sorry about the snafu!

**Comment by chungthuang** [comment]
We released 2020.6.3, it should log to the logfile you defined. Please let us know if the release indeed resolve your issue.

**Comment by vidarak** [comment]
I tested 2020.6.3 now and it didn't fix the issue.

**Comment by daltoniam** [comment]
Thanks for the quick response! The fix in 2020.6.3 was apart of larger logging update in 2020.6.1 to add support for log file rolling. The logfile flag was updated to support a directory to roll the logs in, this option being named `log-directory`. An alias for the original logfile command was added, but wasn't properly supported in the config file. We have an update (version 2020.6.4) coming out today that will address the config file issue. Thank you again for the report and prompt responses!

**Comment by daltoniam** [comment]
version 2020.6.4 has been released. Please let us know if that fix the logging issue. Thanks!

**Comment by vidarak** [comment]
It did not

**Comment by XhmikosR** [comment]
@daltoniam FYI the git tag is missing.

**Comment by vidarak** [comment]
2020.6.5 fixed the issue. Thanks.
