### ISSUE TITLE
Add option for udp protocol in argo tunnel

### ISSUE THREAD

**Issue by gerardo-junior** [cloudflare/cloudflared#215]
Hello, I'm looking for products similar to the argo tunnel, but I haven't found one that supports udp. I would like to use [mosh](https://mosh.org/) on argo but or mosh runs on udp protocol. I think it would be very useful for various types of applications and games.

**Comment by gerardo-junior** [comment]
is there a plan to implement this? maybe QUIC (http/3) or tcp2udp?

**Comment by ChronoBrake** [comment]
UDP will be awesome for TeamSpeak or other softwarers

**Comment by Spunkie** [comment]
Similarly I've been keenly waiting to use tunnels for game servers.

Any updates on this @abelinkinbio? :eyes:

**Comment by abelinkinbio** [comment]
We're excited as well! We don't have anything to report back at the moment, but will be sure to update this thread as soon as we do 🚀

**Comment by ZaxLofful** [comment]
Does this apply to TCP connections outside of 80/443?

What about using cloudflare as host/client local host proxy, can I do UDP in that scenario?

**Comment by neo-neo1** [comment]
I have a dream. One day we will be able to send UDP through Cloudflared tunnels. Here’s hoping.

**Comment by nmldiegues** [comment]
For zero trust private networking, that dream is coming true: https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/

**Comment by navhits** [comment]
The first thing I wanted to try was run wireguard or openvpn, because I had those docker images to quickly launch one. But I can't get this working as expected.

**Comment by abelinkinbio** [comment]
@navhits what issues are you running into?

**Comment by aofei** [comment]
I actually thought the OP wanted something like this:

```bash
$ # server side
$ cloudflared tunnel --hostname udp.example.com --url udp://localhost:7870
```

```bash
$ # client side
$ cloudflared access udp --hostname udp.example.com --url localhost:9210
```

Diving into the [zero trust private networking](https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/) you mentioned is too much for this tiny need.

Should I open a new issue to file this FR since this issue has been closed?

**Comment by smashah** [comment]
I think the issue with implementing this with wiregaurd is the wireguard client requires a port - so `udp.example.com` by itself isn't going to work

**Comment by navhits** [comment]
Yes @smashah you're right. Plus I didn't add split tunnel rule since I run into connection  problems. @aofei I used warp instead of cloudflared acess on CLI. Its very specific to devices supporting the CLI tool. On android the problem is that you cannot  have concurrently multiple VPN connections active. I would also like to connect without warp too

**Comment by ReinisV** [comment]
So what is the current state of things? Why is it possible/impossible to tunnel UDP and other types of connections?

I've got a tunnel running with the following content:
![image](https://user-images.githubusercontent.com/10805335/151665592-8f984370-4cda-4d7d-bee9-a597cd50a94b.png)
![image](https://user-images.githubusercontent.com/10805335/151665613-8371de92-cf93-4b45-ad07-5c62b9e61ee7.png)

![image](https://user-images.githubusercontent.com/10805335/151665599-2f1fe01f-3d45-43ac-980f-aaa7cb7268be.png)


and it seems to tunnel the `www/http/80` subdomain correctly, but the `wireguard/udp/51820` and `ssh/ssh/22` are not reachable.

**Comment by navhits** [comment]
@ReinisV forwarding an internal service requires us to route IP through cloudflared. Once that's done and it's part of warp encryption, we could possibly access it externally. I first did this before realising this, since tunnels still route traffic via TCP afaik. Not sure what happens with quic

**Comment by ReinisV** [comment]
I dont really get it.

Why do I need WARP? Why can't I tunnel SSH and Wireguard traffic the same way I tunnel HTTP traffic?

**Comment by TownLake** [comment]
Hi @ReinisV - can you tell us a bit more about what you're trying to do? To your question, on the HTTP side your Tunnel has a public DNS record and your browser can send HTTP requests to the Tunnel after resolving the hostname.

Non-HTTP use cases vary a bit based on what you're trying to do and the client you want to use. How do you want to connect to the two non-HTTP resources you've added?

**Comment by ReinisV** [comment]
> Hi @ReinisV - can you tell us a bit more about what you're trying to do? 

My use case is (I think) relatively simple. I've got a RaspberryPi running on my local network. 
What I want to achieve is being able to VPN into my local network to access other devices, use DNS adblocking on the network, etc..

My provider provides a private NAT IP address, so DDNS is not going to work.

I have Wireguard installed and running via PiVpn on the RaspberryPi.

I want to tunnel the Wireguard packets to the public address the same way I am currently tunneling http packets.

With the configuration I showed in the previous comment, http tunnelling works, but wireguard, which is udp, and ssh tunneling doesnt work.

To connect to wireguard, I am using this config:
![image](https://user-images.githubusercontent.com/10805335/151698884-cef2c70c-d414-4681-a7e1-ecb9314ac54a.png)

To connect to SSH, I am trying to use this config:
![image](https://user-images.githubusercontent.com/10805335/151698817-0add0f82-091f-4dc3-a529-f15f3a993966.png)


Both SSH and wireguard seem to be reaching the host, but do not get responses:
![image](https://user-images.githubusercontent.com/10805335/151698967-e10b28c9-ae4a-4605-aaa8-d3a79f4021bf.png)

![image](https://user-images.githubusercontent.com/10805335/151699022-e92fd3bd-6153-4e9b-ac46-a766a22296fd.png)

**Comment by navhits** [comment]
I donot have problems with SSH and VNC. I have SSH on all my machines via cloudflare. What I couldn't achieve is routing internal network and routing wireguard

**Comment by Spunkie** [comment]
Requiring zero trust or warp is a complete nonstarter for ANY of my use cases as well. 

Offering ddos protected game server hosting for example, no one is going to want their players to need to download "some random vpn client", make a cloudflare account, or even verify an email just to join a game. As for pricing, paying per user is obviously not even remotely possible for public game servers.

**Comment by navhits** [comment]
I'm looking at some alternate options without warp routing. I'll keep this space updated

**Comment by A7610605** [comment]
> count, or even verify an email just to join a game. As for pricing, paying per user is obviously not even remotely possible for public game servers.
Reverse tunnelling raw TCP/UDP is impossible, even for tcp you need cloudflared as client. If such a product did exist. Who would still use the expensive Cloudflare Spectrum?

**Comment by A7610605** [comment]
> Reverse tunnelling raw TCP/UDP is impossible, even for tcp you need cloudflared as client. If such a product did exist. Who would still use the expensive Cloudflare Spectrum?

Reverse tunnelling raw TCP/UDP is impossible, even for tcp you need cloudflared as client. If such a product did exist. Who would still use the expensive Cloudflare Spectrum?

**Comment by A7610605** [comment]
> Requiring zero trust or warp is a complete nonstarter for ANY of my use cases as well.
> 
> Offering ddos protected game server hosting for example, no one is going to want their players to need to download "some random vpn client", make a cloudflare account, or even verify an email just to join a game. As for pricing, paying per user is obviously not even remotely possible for public game servers.

Reverse tunnelling raw TCP/UDP is impossible, even for tcp you need cloudflared as client. If such a product did exist. Who will buy the expensive Cloudflare Spectrum?

**Comment by Spunkie** [comment]
> Reverse tunnelling raw TCP/UDP is impossible, even for tcp you need cloudflared as client. 

?
> If such a product did exist. Who will buy the expensive Cloudflare Spectrum?

Cloudflare Spectrum is a joke of a product, priced into absolute obscenity, and restricted to only ssh/minecraft. It should sunset in favor of cf tunnels.

**Comment by timothystewart6** [comment]
I'd love raw TCP/UDP support.

**Comment by yalopov** [comment]
are there any alternatives to use udp with cloudflare tunnel? i'd like to expose wireguard too

**Comment by navhits** [comment]
What I understood is that UDP support is yet to come out. Initially this was being tested I assume. Because earlier when I ran `cloudflared tunnel run udp://localhost:1234 some-tunnel`, the tunnel started but failed to connect on UDP. Later after I updated the CLI I tried this and got an error like UDP is not a supported protocol. I didn't try after that.

**Comment by Dima-Kal** [comment]
Why is this closed? there is still no UDP support AFAIK

**Comment by sudarshan-reddy** [comment]
You can use UDP with warp routing to tunnel. 

https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/

**Comment by Dima-Kal** [comment]
> 

Does it require running WARP client + Wireguard client? if so, then what's the point? i don't want WARP client installed its just an extra overhead

**Comment by aofei** [comment]
> i don't want WARP client installed its just an extra overhead

Cloudflare WARP is pretty broken right now. Many problems are waiting to be solved. It's a smart choice to not use it for now.

If you do need to exchange UDP packets through Cloudflare Tunnel, then I recommend you use it with [UDPTunnel](http://www1.cs.columbia.edu/~lennox/udptunnel/) (old but usable). Or open a new issue for your FR, although it will most likely be marked as a duplicate.

**Comment by navhits** [comment]
You can possibly use Cloudflare tunnels to serve UDP. But to get it working you need to treat the UDP service as internal. This is why you need warp or cloudflared access. The problem solved here is correct. However the use case most of us are trying is different. We are trying to have a publicly exposed private network which is basically a UDP service. For this Cloudflare tunnel won't help. You need a still public IP. Maybe if CF tunnels support this feature someday you can use it. My experiment of setting up a Wireguard server won't work out with the current CF tunnels.

**Comment by eximius313** [comment]
I need to do exactly the same thing as @ReinisV described [here](https://github.com/cloudflare/cloudflared/issues/215#issuecomment-1024926424)

HTTP/HTTPS works fine via Tunnel, SSH and TCP works fine as well, but in order Wireguard to work, I need also UDP support.
I'd rather not to play with WARP, private networks or tunneling UDP via TCP - this is overkill for such simple use case.

Is adding "UDP" protocol in this dropdown:
![image](https://github.com/cloudflare/cloudflared/assets/5578017/4434dc26-1778-4c3f-8af1-1912a8abcf2d)
really impossible?

**Comment by n3me5is-git** [comment]
Maybe also TCP+UDP would be useful. I have to make a tunnel that use both TCP and UDP on the same port to access/program some IoT devices.
I would like to manage everything from the dashboard and then connect with cloudflared access.

**Comment by peixotorms** [comment]
why is this closed?

**Comment by ZaxLofful** [comment]
https://github.com/cloudflare/cloudflared/issues/964

They want us to submit it a different way, since this is technially not a bug...Its an unimplemented feature (intentionally). They say they are going to put it on the roadmap, but we should all go submit a new ticket on their website.

[feedback channel](https://community.cloudflare.com/c/feedback/25) of [community.cloudflare.com](https://community.cloudflare.com/).

**Comment by teohhanhui** [comment]
With WebTransport it will definitely be possible to encapsulate UDP datagrams over HTTP/3 (over QUIC):

https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-09.html

It seems like Cloudflare has not enabled support for that though:

https://community.cloudflare.com/t/unable-to-forward-webtransport-request-via-loadbalancer-to-origin/335218/5

(Unless something has changed in the meantime, but I can't find any indication of that...)

**Comment by niceEli** [comment]
there is no udp dropdown for selecting the types, there should be so i can run wireguard

**Comment by bandogora** [comment]
It's been almost 5 years, you have added new protocols, and somehow we still don't have UDP.

I need to use Syslog over UDP. I'd like to use a Cloudflare Tunnel. The devices sending the Syslog messages are embedded systems, they cannot install WARP or any other software. Is that such a big ask?

**Comment by sheiy** [comment]
Maybe reopen this?

**Comment by Cyb3rC3lt** [comment]
Yes please reopen gets my vote too.

**Comment by bloomberg21** [comment]
.... 5 years later ffs

![Image](https://github.com/user-attachments/assets/40a0bb45-6d3b-4a7d-bac8-34c22c7e8e7e)

**Comment by gerardo-junior** [comment]
@bloomberg21 

![Image](https://github.com/user-attachments/assets/2e6096b0-98e3-40af-a02a-db13ba2c2045)

**Comment by rafa-br34** [comment]
Maybe someday, kinda sucks I'll need to either use something to unpack UDP packets from a TCP connection or just to use TCP.

**Comment by perhago149-code** [comment]
Gracias, pero no entiendo que hacer, para acceder

**Comment by wjsw1781** [comment]
is there a plan to implement this? maybe QUIC (http/3) or tcp2udp?
