### ISSUE TITLE
go get in alpine fails

### ISSUE THREAD

**Issue by visibilityspots** [cloudflare/cloudflared#22]
When trying to get the cloudfared github.com repository through go in an alpine docker container I get this error;

```bash
$ go get -v github.com/cloudflare/cloudflared/cmd/cloudflared
...
# github.com/cloudflare/cloudflared/tunneldns
src/github.com/cloudflare/cloudflared/tunneldns/metrics.go:39:13: not enough arguments in call to vars.Report
	have (request.Request, string, string, int, time.Time)
	want ("context".Context, request.Request, string, string, int, time.Time)
The command '/bin/sh -c apk update; 	apk add git;	go get -v github.com/cloudflare/cloudflared/cmd/cloudflared' returned a non-zero code: 2
```

The full log can be found on https://travis-ci.org/visibilityspots/dockerfile-cloudflared/jobs/370010829

**Comment by moderation** [comment]
I'm getting this failure with Go 1.10.1 on ARM v8 Le Potato, MacOS and Xubuntu Linux 17.10 so it appears to be an issue on all platforms.

**Comment by miekg** [comment]
didn't know cloudflared is packing coredns underneath, anyway I consider anything that is not directly user visible as fair game, i.e. `vars.Metrics` just got changed to include a context for the per server label.

They should pin the version.

**Comment by HazCod** [comment]
I'm having issues compiling cloudflared. Ideas?

```
apk add --no-cache ca-certificates git
git clone https://github.com/cloudflare/cloudflared /go/src/app
cd /go/src/app/cmd/cloudflared
go get -u all
CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app -ldflags '-w -s -extldflags "-static"'
```

Returns when running:
```
/go/src/app/cmd/cloudflared # /go/bin/app -help
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x13edf20, 0xde6169, 0xf, 0xec8240, 0xe56da8)
	/usr/local/go/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x13edf20, 0xde6169, 0xf, 0xe56da8)
	/usr/local/go/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0xde6169, 0xf, 0xe56da8)
	/usr/local/go/src/net/http/server.go:2380 +0x4b
github.com/coredns/coredns/vendor/golang.org/x/net/trace.init.0()
	/go/src/github.com/coredns/coredns/vendor/golang.org/x/net/trace/trace.go:115 +0x42
```

**Comment by HazCod** [comment]
Are the releases statically compiled? Might have to do with musl?

**Comment by visibilityspots** [comment]
I got it running again by adding installing gcc and build-base before installing cloudflare using the golang:alpine docker container:
```
FROM golang:alpine
RUN apk update; 
         apk add git gcc build-base;     
         go get -v github.com/cloudflare/cloudflared/cmd/cloudflared
```

full log on [travis](https://travis-ci.org/visibilityspots/dockerfile-cloudflared/jobs/456881981)

**Comment by HazCod** [comment]
Thanks @visibilityspots ! Created a repo: https://github.com/HazCod/argo/blob/master/Dockerfile

**Comment by visibilityspots** [comment]
For me this issues is solved by installing gcc and build-base before building cloudflared:

```
apk add git gcc build-base;     
```
