### ISSUE TITLE
Tunnel support/limitations on HTTP/2 connections

### ISSUE THREAD

**Issue by luanmm** [cloudflare/cloudflared#226]
Hello, folks.

First of all, I'd like to thank you for all the effort regarding the daemon, which seems to be a great alternative in some situations.

I just can't migrate some services now because of the lack of support for HTTP/2 connections, for instance. There is any real limitations to some services be "blocked" or do not work over TCP connections in the tunnel?

My result trying to get working an gRPC service over the tunnel was this: "INTERNAL: Received unexpected EOS on DATA frame from server.". I checked up the logs and the surprise was that the incoming connection was handled with HTTP/1.1. Then, after digging the docs, I've found that Cloudflare handle all the HTTP/2 connections internally downgrading it to HTTP/1.1, as stated below:

![Screenshot from 2020-07-28 14-17-32](https://user-images.githubusercontent.com/1708808/88699219-70615c00-d0dd-11ea-9b8d-f031f79d5c0b.png)

This applies for tunneled connections aswell? Why it should really change the protocol? There are any limitations on this?

Thank you very much for your attention!

Best regards.

**Comment by sodabrew** [comment]
Would it work for your use case to proxy gRPC over HTTP/2 as a raw TCP socket? https://github.com/cloudflare/cloudflared/blob/8c870c19a635a8ca6fc5c46a102cd9d3845622cd/validation/validation.go#L26

**Comment by sodabrew** [comment]
Also take note that you are asking a question that is NOT about the cloudflared tool, but about Cloudflare CDN service itself. The forums are here. There are a number of threads about gRPC: https://community.cloudflare.com/search?q=grpc

**Comment by luanmm** [comment]
My setup (for development purposes) would use the Cloudflare Tunnel to bypass the network and avoid changes in NAT or other standard networking peripherals. But I will not be able to work over TCP directly seamlessly, because gRPC works over HTTP/2.

About the note, I'm not sure if the limitation is in the Cloudflare service or in the daemon. It was/is not clear to me which is the case. I just pointed out what I've found in Cloudflare service pages, to what may explain why it wasn't working in my scenario.

But if this is something that is not related with the daemon and is not a thing that might interest the team in a closer look, feel free to close the issue, as I'm not (currently) a directly supporter ($) of Cloudflare services and I wouldn't be comfortable asking anything for the development team besides this given hint about what can be improved.

**Comment by luanmm** [comment]
As stated by the team, in an email answering a direct question regarding this subject, gRPC is not supported at this time. The reference document is the following: https://support.cloudflare.com/hc/en-us/articles/360050483011. Maybe in the future this can be supported by the Cloudflare team.
