### ISSUE TITLE
HTTP request error: Error proxying request to origin: x509: cannot validate certificate for <<local ip>> because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by David19811** [cloudflare/cloudflared#228]
When using Cloudflare origin certificates and using the 443 https address when initiating a connection, the cloudflared daemon reports:

HTTP request error: Error proxying request to origin: x509: cannot validate certificate for <<local ip>> because it doesn't contain any IP SANs

**Comment by David19811** [comment]
--no-tls-verify solved the issue, because not using a address but ip.

**Comment by TownLake** [comment]
Thanks for the feedback - we can improve how we document this case, and the error messaging as well. We'll start by updating our developer docs to add this as a common error.

**Comment by David19811** [comment]
Used:

https://support.cloudflare.com/hc/en-us/articles/115000479507-Managing-Cloudflare-Origin-CA-certificates

And:

https://medium.com/@hasnat.saeed/setup-ssl-https-on-jboss-wildfly-application-server-fde6288a0f40

Standard ports can be editted using standalone.xml.

**Comment by rodrigopv** [comment]
Hi,

I'm trying to use Argo and got the same error.

I have a dokku deployment ( https://github.com/dokku/dokku ) on my home server and I would like to access it like dokku.domain.com .

I think Argo should make that subdomain (dokku). On dokku I have multiple dev deployments under the same domain (a.domain.com, b.domain.com).

Dokku implements an HTTPS load balancer where I have a self signed wildcard certificate for *.domain.com.

It seems that Argo doesn't allow me to use that setup. My current cloudflare setup consists on a A record to "server.domain.com" (which points to dokku load balancer) and then for each deployment (a.domain.com...) a CNAME record to it.

Just starting argo tunnel would throw a bad gateway error.
