### ISSUE TITLE
Tunnels loadbalancing weights are not respected?

### ISSUE THREAD

**Issue by riuvshyn** [cloudflare/cloudflared#229]
Hey guys is that a bug that loadbalancing weights are not respected and the preferred route every time even with a lower weight? 
Tried also a separate pool and including new lb ini the argo pool, both are never used.

**Comment by TownLake** [comment]
Hi @riuvshyn - we've noticed that as an issue with what we refer to as "classic" Argo Tunnels. Could you [migrate your configuration](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/create-tunnel) to use named Argo Tunnels?

The weights should be respected in that model with the added bonus of improved manageability - Argo Tunnels in the "named" model are treated more like regular origins by the Cloudflare Load Balancers.

**Comment by pirate** [comment]
We're seeing this issue the new named model as well, the first tunnel on each load balancer pool gets 90+% of the traffic, and the others within the pool get almost none.

**Comment by abelinkinbio** [comment]
Hi there - new Tunnel PM here 👋 Are you still experiencing this issue? If so, we will open up a support ticket so we can learn more about your configuration. Closing as timed-out and will re-open when we hear back.
