### ISSUE TITLE
Allow passing token id/secret using filesystem

### ISSUE THREAD

**Issue by rgdev** [cloudflare/cloudflared#232]
We use Argo Tunnel and Cloudflare to access protected resources and as a handy way to let our end users access said resources we packaged `cloudflared` in a container so opening a tunnel is as easy as starting the docker service.

We use individual tokens to automate authentification and therefore pass the ID and Token as command parameters which is not the most ideal thing to do as you could access it by listing the host's processes : 
`/bin/cloudflared access tcp --id ${CF_ID} --secret ${CF_SECRET} ...`

It would be better to have the ability to read those bits of information from the file system like this : 
`/bin/cloudflared access tcp --id-file /secrets/my_id --secret-file /secrets/my_secret ...`

What do you think ?

**Comment by Maartincm** [comment]
@TownLake 
Any news on this request?

It would be ideal to have `cloudflared` accept secrets through a file or at least environment variables.

As far as I can see you are using [urfave/cli](https://github.com/urfave/cli) and it has support for both:
* [Argument values from EnvVars](https://github.com/urfave/cli/blob/master/docs/v2/manual.md#values-from-the-environment)
* [Argument values from Files](https://github.com/urfave/cli/blob/master/docs/v2/manual.md#values-from-files)

I don't really have that much experience with Go, but I can try to open a Pull Request if that would be helpful.
