### ISSUE TITLE
Adding U2F for Argo Tunnel

### ISSUE THREAD

**Issue by blhagadorn** [cloudflare/cloudflared#233]
Hello all, I'm curious if anyone has seen any implementation of the argo tunnel which not only requires the certificate but also adds U2F (hardware token like Yubikey) in order for the tunnel to open. Any thoughts or suggestions would be appreciated!

**Comment by abelinkinbio** [comment]
Currently, we'd recommend enforcing U2F via the Cloudflare Dashboard which would be enforced when running the initial `cloudflared tunnel login` command. Then, for your end-users, you can also apply Cloudflare Access U2F policies as well. Would this be a sufficient solution?
