### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by morpig** [cloudflare/cloudflared#236]
Hi,

I'm currently running one argo tunnel (latest version) on a dedicated server setup (ubuntu 20.04, ryzen 7, 32gb ram) located in Europe and it is being used by two clients located in Southeast Asia. I noticed that when both clients are running, the server side starts spitting out:

```
ERROR[2020-09-12T10:32:16Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:17Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:17Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:17Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
ERROR[2020-09-12T10:32:22Z] HTTP request error: dial tcp 127.0.0.1:46481: socket: too many open files
```

This causes random disconnects to the client and even stops working at all. I've tried a temporary solution, which is by using ``ulimit -n 500000``. It works for 24+ hours, and starts spitting out that error again.

What I noticed is that this does not occur when I have the argo tunnel server near to each other (previsouly it was hosted in Southeast Asia, no problem at all). But when I move the argo tunnel server to Europe, it started spitting out those errors.

I'm wondering if this is caused by latency.. Any help?

**Comment by chungthuang** [comment]
Hi @morpig, have you tried named tunnel with latest version? I think some of the refactoring we did can help with the issue. If you haven't setup a named tunnel, here are the steps https://developers.cloudflare.com/argo-tunnel/create-tunnel.

**Comment by morpig** [comment]
Yup, not experiencing it anymore in the latest version. Thanks!
