### ISSUE TITLE
Please add macOS release in Github Releases

### ISSUE THREAD

**Issue by LcTrKiD** [cloudflare/cloudflared#239]
I use an automation tool to get new versions of different apps and It would be nice to have cloudflared listed as a release in the Github Releases page.

**Comment by abelinkinbio** [comment]
You can find this information here: https://github.com/cloudflare/cloudflared/releases

**Comment by LcTrKiD** [comment]
Hi @abelinkinbio, I meant macOS pkg

**Comment by nmldiegues** [comment]
@LcTrKiD  thanks for clarifying;  would https://dl.equinox.io/cloudflare/cloudflared/stable suffice?
