### ISSUE TITLE
Change hostname from server

### ISSUE THREAD

**Issue by mateusroveda** [cloudflare/cloudflared#241]
Hi, i had two servers. Last week, i change the applications from one server to another.
In Argo Tunnel, i deleted the DNS entry and destroy the old server.
In this new server, i had a hostname new-apps, but i change to apps, when i use the command
```
cloudflared tunnel login
```
the certificate is created and downloaded, but the DNS entry is not created. 
In the logs, i see this error:
```
Serve tunnel error: There is already an active tunnel for "hostname". To distribute requests between multiple origins, use Cloudflare Load Balancer. Existing tunnels not using the Load Balancer will need to be registered again
```
"hostname" is a example for my host.

What can I do? I've tried to reinstall, use another hostname and nothing has changed.

**Comment by mateusroveda** [comment]
Now, the cert is created but the DNS entry don't.
In the cloudflared.log i don't have new entrys, not even an error.

**Comment by TownLake** [comment]
Hey @mateusroveda - you can separate your Tunnel configuration from an associated hostname now with the [latest release of Argo Tunnel](https://blog.cloudflare.com/argo-tunnels-that-live-forever/). This will allow you to change hostnames in the Cloudflare dashboard without needing to reconfigure the Tunnel. Let us know if that solves it for you.

**Comment by mateusroveda** [comment]
Thanks.
I run:
```
cloudflared tunnel -v
```
and works.
