### ISSUE TITLE
Docker cloudflared:latest points to 2020.7.0 (12 versions behind!)

### ISSUE THREAD

**Issue by acrogenesis** [cloudflare/cloudflared#242]
If you pull cloudflare/cloudflared:latest you get the 2020.7.0 version.

```
docker pull cloudflare/cloudflared
Using default tag: latest
latest: Pulling from cloudflare/cloudflared
6729630f5ebf: Pull complete 
e2745900642c: Pull complete 
3c2cba919283: Pull complete 
eeff62bcf7a0: Pull complete 
Digest: sha256:3c7a338478d7c32f51d3455ff2be704f472fb2b45d430d156ed925f615eb0263
Status: Downloaded newer image for cloudflare/cloudflared:latest
docker.io/cloudflare/cloudflared:latest
```

Screenshot from docker hub:
<img width="247" alt="CleanShot 2020-09-28 at 17 44 51@2x" src="https://user-images.githubusercontent.com/1312687/94493485-5cf07100-01b2-11eb-8757-88ae8cda327a.png">

**Comment by TownLake** [comment]
Thanks for flagging this; we'll get it updated.

**Comment by acrogenesis** [comment]
> Thanks for flagging this; we'll get it updated.

No problem the PR is on #243 👍

**Comment by acrogenesis** [comment]
#243
> This Make target actually only builds images for local use and testing. We have internal infrastructure that is responsible for building, tagging, and publishing images for dockerhub. The PR is appreciated but unfortunately this is a change that is going to have to be made internally in a different place.

Hey, @Michael9127 would you mind updating this issue when it's resolved internally? Thanks!

**Comment by acrogenesis** [comment]
Hello @Michael9127 any updates on the internal update?

**Comment by Michael9127** [comment]
@acrogenesis, sorry about the delay. I took a closer look at our internal docker build pipeline and unfortunately there isnt currently support for overwriting existing tags, which is what would need to happen with latest. Thats the reason there was only one latest tag to begin with. We are going to just remove the tag for now and require a specific version to be pinned.

**Comment by acrogenesis** [comment]
Are there any plans on having the latest tag updated as part of the pipeline anytime soon? @Michael9127 @TownLake

**Comment by patricegautier** [comment]
Second that!

**Comment by sudarshan-reddy** [comment]
Its tracked here: https://github.com/cloudflare/cloudflared/issues/422

**Comment by pirate** [comment]
Getting this on Docker pulls today, is the `:latest` tag broken again?
```logs
Pulling argo     ... error

ERROR: for argo  manifest for cloudflare/cloudflared:latest not found: manifest unknown: manifest unknown
ERROR: manifest for cloudflare/cloudflared:latest not found: manifest unknown: manifest unknown
```
