### ISSUE TITLE
Does cloudflared auto-update?

### ISSUE THREAD

**Issue by swrobel** [cloudflare/cloudflared#245]
Reading [the docs](https://developers.cloudflare.com/argo-tunnel/reference/arguments/#no-autoupdate) leads me to believe that since there is a `--no-autoupdate` flag, that the default behavior is to auto-update, despite the fact that this isn't mentioned anywhere (that I can find). However, the instance of cloudflared running on my RPi is still on 2020.9.2 despite the fact that two newer versions have been released. To be clear, I have *not* used the `--no-autoupdate` flag.

So, I suppose my question is: should cloudflared auto-update, and if so, how do I troubleshoot the fact that it isn't?

**Comment by stefanogramm** [comment]
Hello @swrobel , `cloudflared` will not automatically update when run from the shell ( Id that's your queston. To enable auto-updates, run `cloudflared` as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/

**Comment by lumin888** [comment]
I'm also running a RPi with cloudflared installed as a service, but it doesn't auto-update.

The RPi install guide mentions that you can run the updater in a cron job. https://docs.pi-hole.net/guides/dns-over-https/

**Comment by TownLake** [comment]
Thanks for the report - glad we could answer the question on auto-update. The core problem seems to be the same as this:
https://github.com/cloudflare/cloudflared/issues/249
an issue we had with new updates timing out. Closing this question to move discussion to 249.

**Comment by KommX** [comment]
I don't think that these two bugs are related. I always could update fine manually before 2020.10.2. I guess #249 is only about updating to 2020.10.2 or from 2020.10.0.
But I never saw that cloudflared auto-updated itself.

**Comment by DATAPOWERELECTRICAL** [comment]
hi all,
I noticed Dockers connector isnt updating either.
I have it set as:
docker run cloudflare/cloudflared:latest tunnel --autoupdate-freq 24h0m0s run --token

A new version appeared and its not doing its auto update.
Version
2024.1.4 Outdated
any ideas ?
