### ISSUE TITLE
Package cloudflared-2020.10.0-1.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by ravesgard** [cloudflare/cloudflared#246]
Every time I run `yum install cloudflared` I get this `Package cloudflared-2020.10.0-1.x86_64.rpm is not signed` error. What do I have to do to install this the _right_ way?

**Comment by Michael9127** [comment]
Thanks for the report, I can reproduce this. We are looking into it.

**Comment by Michael9127** [comment]
@ravesgard It seems our build pipeline has an issue and we are investigating. In the mean time, that package has been signed manually and should now install. Thanks for catching this!

**Comment by sandoval** [comment]
I'm having the same issue trying to `yum install cloudflared` with updated version:
```
Package cloudflared-2020.10.2-1.x86_64.rpm is not signed
```

**Comment by leereichardt** [comment]
This is still happening on the latest `Package cloudflared-2021.1.5-1.x86_64.rpm is not signed`

**Comment by AndreiG6** [comment]
Why was this closed @Michael9127 ? This is still an ongoing issue
`Package cloudflared-2022.1.0-1.x86_64.rpm is not signed`

**Comment by Michael9127** [comment]
When I closed this ticket it should have been fixed, something must have gone wrong again. Not sure why I didnt get notifications for these messages before I was explicitly tagged, im sorry about that. We are going to look into this, thanks for the report.

**Comment by AndreiG6** [comment]
tyvm! Unfortunately, most of us fully understand regression and missing notifications :)

**Comment by nmldiegues** [comment]
We have signed the existing artifact that was problematic and identified the source of the regression. It should be fine in the next releases.

Thanks for the heads up.

**Comment by nmldiegues** [comment]
Should be good from now on

**Comment by AndreiG6** [comment]
Thanks guys!

**Comment by NotCoolKiwi** [comment]
Unfortunately, i'm having this problem again.

**Comment by NotCoolKiwi** [comment]
It looks like this is happening again @Michael9127
