### ISSUE TITLE
name parameter doesn't work

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#248]
Using the --name parameter (or similar element in the config file) makes the tunnel exit immediately without any error or reason on either console or log.

**Comment by TownLake** [comment]
Hi @vidarak - could you update to the latest release, 2020.10.1, we've added a fix that introduces `tunnel` into the config file to handle name or UUID. More information [here](https://developers.cloudflare.com/argo-tunnel/configuration/config).

**Comment by vidarak** [comment]
The one i tested with is running 2020.10.2 already. It is confusing if the argument is supposed to be "tunnel" while --help says the argument is "name". Even more confusing would it be if the command line argument is --name while the config file equivalent is "tunnel"...

**Comment by ipostelnik** [comment]
Can you share the log produced by cloudflarred? Here's what I tried and it worked for me (replacing example.com with my test zone name):

```
$ cloudflared --version
cloudflared version 2020.10.2 (built 2020-10-21-1908 UTC)
$ cloudflared tunnel --name adhoc --hostname adhoc.example.com --hello-world
....
INFO[2020-10-26T16:13:48-05:00] Created tunnel adhoc with id 516dc166-59da-4d90-bba3-d58ea7381f0d
....
```

With this running I can open `https://adhoc.example.com` in a browser window just fine.

**Comment by vidarak** [comment]
It doesn't produce output on console or in log. It just crashes. I start it with a config file and added a "name" parameter either on command line or in config file on top of previously working config.

**Comment by ipostelnik** [comment]
`name` and `tunnel` are used for different purposes, though I can see why it would be confusing. You should use `name` if you're running ad-hoc tunnel; we will create the tunnel if it doesn't exist and add a DNS record for it. `tunnel` should be used to run a pre-created tunnel, we recommend using UUID as the value, though it's possible to use a name if you have your origin cert handy. If you're running in production environment, we highly recommend pr-creating the tunnel and setting up DNS ahead of time.

As far as your specific issue - can you share your configuration file. Feel free to redact any sensitive parts, like your zone name. I've tried to recreate your problem, but haven't been unable to do so. You can also reach Cloudflare support at https://support.cloudflare.com

**Comment by vidarak** [comment]
![image](https://user-images.githubusercontent.com/4713602/97238162-02662700-17e9-11eb-9596-6f0686c8ab2b.png)
I'm using name parameter as the help parameter suggest to use to create, route and run a named tunnel. Since the tunnel parameters from --help are also the config file parameters I had expected the same config file parameter to work too.

**Comment by ipostelnik** [comment]
It looks like we're failing to parse `tag: [serverXXXX]` value. You should put the value in double quotes to make this valid YAML. Are you actually relying on the tag value? How do you use it? I suggest you completely remove it completely.

**Comment by ipostelnik** [comment]
It looks like your configuration sends all log messages to c:\cloudflared\cloudflared.log. You should check this file for errors. If it doesn't exist, make sure to create c:\cloudflared directory.

**Comment by vidarak** [comment]
![image](https://user-images.githubusercontent.com/4713602/97353077-dbb0fa80-1893-11eb-809d-bec72c5b1137.png)
![image](https://user-images.githubusercontent.com/4713602/97353091-e10e4500-1893-11eb-93b0-9d7c6e9a01ed.png)

After clearing previous log and trying to start it like before, it crashes like before and doesn't create log as before (while crashing). I'm used to cloudflared not creating log while crashing though. This isn't the first time for that.

After removing the --name parameter its starting fine again and also creating log (config.yml untouched):
![image](https://user-images.githubusercontent.com/4713602/97353444-567a1580-1894-11eb-9c5d-dbd674394cbd.png)

**Comment by ipostelnik** [comment]
How old is your origin cert? It looks like there's a bug in handling old certs in the adhoc tunnel mode, with `--name` flag. 

If you run `cloudflared --config CONFIG-FILE tunnel list`, replacing CONFIG-FILE with your config file path, do you get an error message about needing to login to refresh the cert?

Unrelated to the bug - if you care about tunnel reliability you should definitely use pre-created tunnels as described in https://developers.cloudflare.com/argo-tunnel/create-tunnel instead of using adhoc mode with --name.

**Comment by vidarak** [comment]
![image](https://user-images.githubusercontent.com/4713602/97359275-cb514d80-189c-11eb-8c5a-f56d36bc9b1a.png)

![image](https://user-images.githubusercontent.com/4713602/97359509-26834000-189d-11eb-8b00-98a05678cb4f.png)

**Comment by vidarak** [comment]
I've updated cert.pem by logging in again.
I've pre-created the tunnel with "tunnel create name".
The tunnel shows up on "tunnel list" (new cert apparently works).
The tunnel refuses to run and crashes like before without any error on either console or any log file getting created. I've tried adding tunnel name and uuid in config in "tunnel: " tag or the same with run command on command line.

**Comment by ipostelnik** [comment]
I'm unable to reproduce this at all. Can you share your latest config file again? Try adding `loglevel: debug` or adding `--loglevel debug` to the command line like this: `cloudflared --loglevel debug tunnel run NAME-OR-UUID`.

Maybe we can try a simpler setup to rule out some things, try moving config file out of the way, double-check that `%HOMEPATH%\.cloudflared\config.yml` doesn't exist and then run:

`cloudflared --loglevel debug tunnel run --hello-world NAME-OR-UUID`

**Comment by vidarak** [comment]
Looks like the whole issue was the certificate. Please fix so it fixes the certificate automatically or produces proper output explaining the requirement to renew the certificate to work with named tunnels.
Have ended up using "name:" tag in config on every instance after only ensuring certificate is updated

**Comment by ipostelnik** [comment]
On further debugging I've discovered that this is a bug in how we print errors in the the top-level command line handler. The error was generated correctly, but was never printed to screen. 

I strongly recommend using `cloudflared tunnel` and subcommands for managing tunnels for a more reliable experience.
