### ISSUE TITLE
Cloudflared no longer updating on raspberry pi: “failed to update cloudflared: no release found”

### ISSUE THREAD

**Issue by tommetje** [cloudflare/cloudflared#249]
I am running pihole + cloudflared on raspberry pi 3 B+.
I cannot update cloudflared anymore as I receive an error message. 

## Expected Behaviour:
_Being on cloudflared version 2020.10.0 I wanted to update to release 2020.10.2. After running "sudo cloudflared update" I expect cloudflared to update to the new release._

## Actual Behaviour:
_After running command "sudo cloudflared update" I get this error message: "failed to update cloudflared: no release found"_

I have tried reinstalling cloudflared. It installed version 2020.5.0, I could successfully update this to 2020.10.2. When I run the update command again I get the error message in the description above.

**Comment by derekschinke** [comment]
Same issue.

**Comment by bondskin** [comment]
works fine on my Pi

```
pi@raspberrypi:~ $ sudo cloudflared version
cloudflared version 2020.9.2 (built 2020-09-23-2058 UTC)
pi@raspberrypi:~ $ sudo cloudflared update
cloudflared has been updated to version 2020.10.2
```

**Comment by tommetje** [comment]
@bondskin Now you are on cloudflared version 2020.10.2 can you try updating again and see if you get an error message?

I noticed that updating from version 2020.5.0 to 2020.10.2 also worked for me. From version 2020.10.0 updating was not possible anymore.

**Comment by bondskin** [comment]
> @bondskin Now you are on cloudflared version 2020.10.2 can you try updating again and see if you get an error message?
> 
> I noticed that updating from version 2020.5.0 to 2020.10.2 also worked for me. From version 2020.10.0 updating was not possible anymore.

here you go:
pi@raspberrypi:~ $ sudo cloudflared update
failed to update cloudflared: no release found

**Comment by richaso** [comment]
Same!

pi@raspberrypi:~ $ sudo cloudflared update
failed to update cloudflared: no release found

**Comment by daltoniam** [comment]
Howdy everyone.  A `no release found` response points to the API not finding a match for the os/architecture. This is based on the `GOARCH` and `GOOS` variables. Can we confirm what these variables are on the raspberrypi's that aren't working?

We currently have a check for `linux` and `arm64` to return the `cloudflared-linux-arm64` build from the releases page. My understanding is this the os and architecture that many of the raspberrypi models used.

**Comment by tommetje** [comment]
Correct me if I am wrong but I think that most raspberry pi models are using a 32-bit OS, some are using a 64 bit version.
I guess that I need `cloudflared-linux-armv6` for my 32-bit Raspberry Pi Lite OS.

**Comment by daltoniam** [comment]
There is also a check for `armv6` and `linux` to return the `cloudflared-linux-armv6`. There might be a missing combo from different raspberry pi models, so I wanted to confirm what the GOARCH on the models that are having trouble updating to make sure the API accounted for the different cases.

**Comment by richaso** [comment]
Hi,

I hope this can help:

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
pi@raspberrypi:~ $ hostnamectl
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: bf0b79edaf494ce8b879ae2ee0870943
           Boot ID: 47b1c3516b174b0b8f20caf0fdc97030
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.51-v7l+
      Architecture: arm
pi@raspberrypi:~ $ cat /proc/version
Linux version 5.4.51-v7l+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1333 SMP Mon Aug 10 16:51:40 BST 2020

**Comment by richaso** [comment]
GOARCH:

pi@raspberrypi:~ $ go run test.go
os: linux
arch: arm
pi@raspberrypi:~ $

**Comment by tommetje** [comment]
Should `GOARM` not be checked?

If anyone has GO installed:
https://play.golang.org/p/ZfEtO84yvjm

**Comment by richaso** [comment]
> Should `GOARM` not be checked?
> 
> If anyone has GO installed:
> https://play.golang.org/p/ZfEtO84yvjm

pi@raspberrypi:~ $ sudo go run goarm.go
# command-line-arguments
./goarm.go:9:26: undefined: runtime.GOARM

**Comment by bondskin** [comment]
> GOARCH:
> 
> pi@raspberrypi:~ $ go run test.go
> os: linux
> arch: arm
> pi@raspberrypi:~ $

same here

**Comment by Mereks** [comment]
I am using an ODroid XU4 with the same error as OP. 

My output is:
```
os: linux
arch: arm
```

But more specifically my OS details are:

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
```

And my current CloudFlared version is:

`cloudflared version 2020.10.0 (built 2020-10-06-1530 UTC)`

**Comment by tzomb1e** [comment]
I am seeing this issue on two different Raspberry Pi models (Pi 2 B and Pi 4 B).  Both are running 32 bit versions of Raspbian (armv71) and return the output below from GOARCH:

```
os: linux
arch: arm
```

Both have the the following OS release:

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

They are also running the following CloudFlared version as well:

```
cloudflared version 2020.10.2 (built 2020-10-21-1858 UTC)
```

**Comment by daltoniam** [comment]
Thanks for the info everyone. I deployed an update that should match arm/linux combo. Should be able to just run the update command and it properly pull the 2020.10.2 update.

**Comment by Mereks** [comment]
> Thanks for the info everyone. I deployed an update that should match arm/linux combo. Should be able to just run the update command and it properly pull the 2020.10.2 update.

This solved the issue for me. Cheers!

**Comment by richaso** [comment]
Solved for me too. 

Thanks!!!

**Comment by Nas87** [comment]
I was previously seeing the same error on a Pi 3 running Buster ("failed to update cloudflared: no release found"), but now receiving this error:

`failed to update cloudflared: context deadline exceeded (Client.Timeout or context cancellation while reading body)`

I'm still on version 10.0:

`cloudflared version 2020.10.0 (built 2020-10-06-1530 UTC)`

**Comment by tzomb1e** [comment]
> Thanks for the info everyone. I deployed an update that should match arm/linux combo. Should be able to just run the update command and it properly pull the 2020.10.2 update.

This corrected the issue on my hosts.  Thank you!!!!

**Comment by richaso** [comment]
> I was previously seeing the same error on a Pi 3 running Buster ("failed to update cloudflared: no release found"), but now receiving this error:
> 
> `failed to update cloudflared: context deadline exceeded (Client.Timeout or context cancellation while reading body)`
> 
> I'm still on version 10.0:
> 
> `cloudflared version 2020.10.0 (built 2020-10-06-1530 UTC)`

Try again.

**Comment by KommX** [comment]
I also get the error @Nas87 is mentioning.

> Try again.

Didn't help, how should it?

**Comment by richaso** [comment]
I had the same error first time, second try works for me.

Regards.

**Comment by bondskin** [comment]
Works fine now on my Raspberry Pi 4
pi@raspberrypi:~ $ sudo cloudflared version
cloudflared version 2020.10.2 (built 2020-10-21-1858 UTC)
pi@raspberrypi:~ $ sudo cloudflared update
INFO[2020-10-26T19:51:34+01:00] cloudflared is up to date ()

**Comment by tommetje** [comment]
It works, thanks @daltoniam ! 

`INFO[2020-10-26T20:52:33+01:00] cloudflared is up to date ()`

**Comment by bucker00** [comment]
Is there any other way to update this thing (step by step) ?
I get this every single time on a 100Mbps connection:
failed to update cloudflared: context deadline exceeded (Client.Timeout or context cancellation while reading body).
I've tried a lot of times.

**Comment by Nas87** [comment]
> Is there any other way to update this thing (step by step) ?
> I get this every single time on a 100Mbps connection:
> failed to update cloudflared: context deadline exceeded (Client.Timeout or context cancellation while reading body).
> I've tried a lot of times.
> 
> I attempted reinstalling and ran into this issue: #251
> This resulted in a service that would not start ever again apparently - reimaged the thing and am now back where i was (2020.10.0)

Which OS are you on? I got stuck on this same error trying to update from version 10.0 to 10.2 and I ended up manually replacing the old binary with the new 10.2 version. The releases are listed [here](https://developers.cloudflare.com/argo-tunnel/downloads). I'm using a Raspberry Pi 3 running Raspbian Buster, so I needed to download the ARMv6 binary. I downloaded and extracted the new binary, stopped the cloudflared service, replaced the binary and then restarted the service.

**Comment by bucker00** [comment]
Mate!, thank you - worked perfectly this time - had to make it executable of course after copying but if anyone else is reading this then its the way to go :) Thanks man.

**Comment by dorianmariecom** [comment]
I'm getting:

```
2024-02-18T07:03:10Z ERR update check failed error="no release found"
```

My setup, installed with homebrew:

```
> cloudflared --version
cloudflared version 2024.2.0 (built 2024-02-08T10:20:02Z)
> uname -a
Darwin Dorians-MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 arm64
```
