### ISSUE TITLE
As of October 2020.10.2, installing service on Linux fails.

### ISSUE THREAD

**Issue by mcl21014** [cloudflare/cloudflared#251]
I have encountered no issues when upgrading the service on Windows 10. But on Ubuntu 20.10, I go to upgrade it manually using the proper binary, via `sudo ./cloudflared service install` (after sudo ./cloudflared service uninstall of course) and get terminal output as an error. The output is `Configuration file /etc/cloudflared/config.yml must contain entries for the tunnel to run and its associated credentials:
tunnel: TUNNEL-UUID
credentials-file: CREDENTIALS-FILE
`
I'm uncertain if additional logs or input is needed, I will update the ticket if so. Last time I checked, the documentation doesn't reflect these changes either.

**Comment by amanjuman** [comment]
Current CloudFlare Argo Tunnel Documentation on their site is no more working. All this information sometimes working sometimes not. We need clear documentation.

**Comment by TownLake** [comment]
Hi @mcl21014 thanks for the report. In the [documentation to run Argo Tunnel](https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service) as a service, you'll see the arguments to specify when using the latest version of Argo Tunnel. Let me know if that clears it up.

@amanjuman can you elaborate on what isn't working about our documentation site? We overhauled the docs last week, including these service instructions, so want to make sure we flag anything that has an issue.

**Comment by mcl21014** [comment]
Still getting the same error after following documentation.

**Comment by richstokes** [comment]
Started getting this too. Nothing changed in our set up, and the docs are terrible :(

**Comment by richstokes** [comment]
Here's a workaround: `sudo cloudflared service install --legacy`

**Comment by mcl21014** [comment]
Workaround works. But the documentation needs an update. I and others are clueless on what is needed to get rid of said error. Said error is Linux specific.

**Comment by ipostelnik** [comment]
As of 2020.10.2 release, service mode on linux defaults to statically created tunnels, see https://blog.cloudflare.com/argo-tunnels-that-live-forever/. You can still access previous functionality using `--legacy` flag. You should migrate to using pre-created tunnels.

**Comment by mcl21014** [comment]
Hmm. Still confused on how to get a valid certificate. I can login via the terminal, but how do I get a certificate? Can't find the correct documentation...

**Comment by ipostelnik** [comment]
What you need for `credentials-file` is the tunnel secret file generated by `cloudflared tunnel create` command. By default it is written to the same directory where cert.pem resides and is named `<tunnel-uuid>.json`. 

We have published updated documentation for running cloudflared as a service. See https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service#linux

**Comment by mcl21014** [comment]
Problem is, the cert file is blank. I do not know where to download the certificate from.

**Comment by ipostelnik** [comment]
Which file is blank? Can you run an `ls -l`on `~/.cloudflared` directory or where you keep your origin cert produced by `cloudflared login`. Also, a list of commands that your ran would help, as well.

**Comment by mcl21014** [comment]
Kind of short to bother with a paste site:
```
mike@mike-HP-ENVY-Notebook:~/.cloudflared$ ls -l
total 41472
-rwxrwxrwx 1 mike mike        0 Oct 26 09:20 cert.pem
-rwxrwxr-x 1 mike mike 42456072 Oct 26 14:31 cloudflared
-rw-rw-r-- 1 mike mike       94 Oct 26 16:22 config.yaml
-rw-rw-r-- 1 mike mike       94 Oct 26 16:22 config.yml

```
I copied cert.pem from /etc/cloudflared/cert.pem and changed the permissions to the current user. Both files are 0 bytes and blank. The command I tried running was:
`sudo ./cloudflared tunnel create default`
from the folder ~/.cloudflared got an error outputting:
`failed to create tunnel: couldn't create client to talk to Argo Tunnel backend: Error decoding origin cert: Cannot decode empty certificate`

**Comment by ipostelnik** [comment]
Cloudflare support is at https://support.cloudflare.com/, you can submit a ticket if you want or search through the community pages. If you end up filing a support ticket, reference this issue so they have context.

Your origin cert, which is normally produced by running `cloudfalred login`, is empty for some reason. You can double check `/etc/cloudflared/cert.pem` and see if's also 0 bytes. This is the root cause of your problems. Not sure why this would happen, but the simplest thing to do at this point is to delete it and run the login command again to get a new origin cert. Also, you have 2 copies of the config file. The one with `.yml` extension will be used by default. I suggest you delete `config.yaml`.

Once you get the new cert, run the create command again. It will output the UUID of the tunnel and the path to the credentials file. Take a note of these, edit `~/.cloudflared/config.yml` and add `tunnel: UUID` and `credentials-file: FILEPATH` to the config file. Now you can run service installation and start the service. If service starts ok, you can run `cloudflared tunnel list` and see your tunnel and where it's connected. At this point you're connected to Cloudflare, but you still need to expose your service to the internet. To do this, run `cloudflared tunnel route dns UUID-OR-NAME hostname`. This will add a CNAME from hostname to the tunnel's internal address on Cloudflare network. You may need to delete previous record for hostname if you have one.

You should only need to go through the setup process once. After that upgrade or service restarts should not require additional actions.

Hope this helps.

**Comment by mcl21014** [comment]
See https://community.cloudflare.com/t/unable-to-configure-new-cloudflared-version-on-linux/217145 for continued discussion. I will close the issue.

**Comment by mcl21014** [comment]
Reopened as my post to the community generated no response.
`mike@mike-pi4-ubuntumate-21:~/.cloudflared$ sudo ./cloudflared service install
Configuration file /etc/cloudflared/config.yml must contain entries for the tunnel to run and its associated credentials:
tunnel: TUNNEL-UUID
credentials-file: CREDENTIALS-FILE

`
I do not know how to enter in these credentials, as I do not know how to obtain the tunnel uuid or what to put in for the credentials file. Where can I find this info and how should it be formatted? If nobody is able to assist, I will submit a ticket. I will also request more newbie friendly documentation.

**Comment by TownLake** [comment]
Running [this command](https://developers.cloudflare.com/argo-tunnel/create-tunnel#create-a-tunnel) will create both the UUID and the credentials file; let us know if that sorts the issue.

Thanks for the feedback on updates to the documentation.

**Comment by mcl21014** [comment]
I get this output. Basically an error at the top and bottom and the help output:
`mike@mike-HP-ENVY-Notebook:~/.cloudflared$ ./cloudflared tunnel create default
yaml: line 4: did not find expected '-' indicator

NAME:
   cloudflared - Cloudflare's command-line tool and agent

USAGE:
   cloudflared [global options] [command] [command options]

VERSION:
   2020.10.2 (built 2020-10-21-1904 UTC)

DESCRIPTION:
   cloudflared connects your machine or user identity to Cloudflare's global network.
  You can use it to authenticate a session to reach an API behind Access, route web traffic to this machine,
  and configure access control.

COMMANDS:
   update     Update the agent if a new version exists
   version    Print the version
   proxy-dns  Run a DNS over HTTPS proxy server.
   service    Manages the Argo Tunnel system service
   help, h    Shows a list of commands or help for one command
   Access:
     access, forward  access <subcommand>
   Tunnel:
     tunnel  Make a locally-running web service accessible over the internet using Argo Tunnel.

GLOBAL OPTIONS:
   --name value, -n value  Stable name to identify the tunnel. Using this flag will create, route and run a tunnel. For production usage, execute each command separately [$TUNNEL_NAME]
   --help, -h              show help (default: false)
   --version, -v, -V       Print the version (default: false)

COPYRIGHT:
   (c) 2020 Cloudflare Inc.
   Your installation of cloudflared software constitutes a symbol of your signature indicating that you accept
   the terms of the Cloudflare License (https://developers.cloudflare.com/argo-tunnel/license/),
   Terms (https://www.cloudflare.com/terms/) and Privacy Policy (https://www.cloudflare.com/privacypolicy/).
yaml: line 4: did not find expected '-' indicator
`

**Comment by mcl21014** [comment]
Also when I try to login,
`mike@mike-HP-ENVY-Notebook:~/.cloudflared$ ./cloudflared tunnel login
A browser window should have opened at the following URL:

https://dash.cloudflare.com/argotunnel?callback=https%3A%2F%2Flogin.argotunnel.com%2F8p0wpVkjoz2X-ndmCRNP3G2ReIgg6WxyGQqfP9d_DFM%3D

If the browser failed to open, please visit the URL above directly in your browser.
INFO[2020-11-01T15:05:21-05:00] Waiting for login...
INFO[2020-11-01T15:05:52-05:00] Waiting for login...
`
It does not download the certificate file. It prompts me to input websites with the following text:
"Authorize Argo Tunnel

Argo Tunnel wishes to serve as an origin on one of your zones.

Please select the zone you want to add Argo Tunnel to.
"

**Comment by TownLake** [comment]
Thanks for the context. When you mention that it prompts you to input websites; do you have sites on Cloudflare? Or does it prompt you to pick one of the websites you have on Cloudflare and that is not downloading the cert file?

Can you also share a Gist with your config file as you have it set up? You can redact hostname or anything else that you'd prefer, but that way we can take a look at what would throw the error in line 4.

**Comment by mcl21014** [comment]
> Thanks for the context. When you mention that it prompts you to input websites; do you have sites on Cloudflare? Or does it prompt you to pick one of the websites you have on Cloudflare and that is not downloading the cert file?
> 
> Can you also share a Gist with your config file as you have it set up? You can redact hostname or anything else that you'd prefer, but that way we can take a look at what would throw the error in line 4.

I have no sites on Cloudflare itself. I am simply a user, not a site owner, and wish to get the tunnel running on my installations of Linux. The site gives me this exact prompt:
![Screenshot_2020-11-03 Argo Tunnel Cloudflare - Web Performance Security](https://user-images.githubusercontent.com/3611312/98013022-ce31ce00-1dc7-11eb-9f92-ad623ef32317.png)
No option to download a certificate I guess unless I put in a site which I don't have of course.

**Comment by mcl21014** [comment]
I cannot reproduce the original error so I just did everything as mentioned in step 5 [here](https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy). Also, here's new terminal output for that:
`mike@mike-HP-ENVY-Notebook:~/.cloudflared$ ./cloudflared tunnel create default
INFO[2020-11-03T11:32:02-05:00] Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
ERROR[2020-11-03T11:32:02-05:00] You need to specify the origin certificate path with --origincert option, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/arguments/ for more information.
failed to create tunnel: couldn't create client to talk to Argo Tunnel backend: Error locating origin cert: Client didn't specify origincert path when running from terminal
`
Gist: [https://gist.github.com/mcl21014/997ac01bbd778edd115e168ebc6284a1](https://gist.github.com/mcl21014/997ac01bbd778edd115e168ebc6284a1)

**Comment by TownLake** [comment]
Got it - thanks for that context. Sorry that we missed this earlier - but Argo Tunnel requires that you have an active hostname on Cloudflare (see [setup guide here](https://developers.cloudflare.com/argo-tunnel/getting-started/setup) on how to start that).

We don't have an option that doesn't rely on a hostname, but we're planning some improvements that will ideally remove that requirement.

**Comment by jwalton** [comment]
I'm trying to run cloudflared as a DNS proxy on a 64-bit ARM processor.  I don't want to create any tunnels.  I installed cloudflared:

```sh
wget https://github.com/cloudflare/cloudflared/releases/download/2020.10.2/cloudflared-linux-arm64
chmod 755 ./cloudflared-linux-arm64
sudo mv ./cloudflared-linux-arm64 /sbin/cloudflared
sudo chown root:root /sbin/cloudflared
```

I created a config file:

```yaml
proxy-dns: true
proxy-dns-port: 5053
proxy-dns-upstream:
 - https://protected.canadianshield.cira.ca/dns-query
```

When I run `cloudflared`, it says:

```
INFO[2020-11-07T02:20:08Z] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
```

Which tells me to run:

```sh
$ sudo ./cloudflared service install
```

Which fails, as has been mentioned above.

**Comment by jwalton** [comment]
This: https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service

Is much better documentation than the documentation that the cloudflared logs send you to: https://developers.cloudflare.com/argo-tunnel/reference/service/

**Comment by mcl21014** [comment]
Thanks. I've saw that page, but don't understand the syntax. Can you give an example of a config file for config.yml. The two parts that are missing are Configuration file /etc/cloudflared/config.yml must contain entries for the tunnel to run and its associated credentials:
```
tunnel: TUNNEL-UUID
credentials-file: CREDENTIALS-FILE
```
Currently the file reads as follows:
proxy-dns: true
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query

**Comment by jwalton** [comment]
My /etc/cloudflared/config.yml looks very similar to yours:

```yaml
proxy-dns: true
proxy-dns-port: 5053
proxy-dns-upstream:
 - https://protected.canadianshield.cira.ca/dns-query
```

And, as the instructions [here](https://developers.cloudflare.com/argo-tunnel/create-tunnel/run-as-service) say:

> If you do not want to create the tunnel in advance, you must install cloudflared with the --legacy flag.

So I ran:

```sh
sudo cloudflared service install --legacy
sudo systemctl start cloudflared
sudo systemctl status cloudflared
```

(Note I'm using [CIRA's "Canadian Shield"](https://www.cira.ca/cybersecurity-services/canadian-shield) instead of 1.1.1.1 - if you're in Canada I recommend it, but their HTTPS cert doesn't list their IP as an alt-name, so you'll need to run:

```sh
echo "149.112.121.20 protected.canadianshield.cira.ca" | sudo tee -a /etc/hosts
echo "149.112.122.20 protected.canadianshield.cira.ca" | sudo tee -a /etc/hosts
```

to get this working.)

**Comment by mcl21014** [comment]
Hm. I myself live in the US. Is there any way I can get certificates for Cloudflare just to use for DNS over HTTPS? Still do not know how to fill out the config file with the tunnel UUID and credentials file.

**Comment by jwalton** [comment]
You should be fine - the cloudflare certs are correct, and list 1.1.1.1 and 1.0.0.1 as altnames.  Try:

```
sudo cloudflared service install --legacy
sudo systemctl start cloudflared
sudo systemctl status cloudflared
```

And see where that gets you.

**Comment by mcl21014** [comment]
That will work. But why doesn't installing it the new way work? Are there any plans to remove the legacy flag before there's a way to get a certificate without actually owning a site on cloudflare for Linux users? For some reason it works on Windows.

**Comment by cleonte** [comment]
It's just me or cloudflared looks only in current directory for the credentials-file?  the service started to working only after i added this: WorkingDirectory=/etc/cloudflared

**Comment by abelinkinbio** [comment]
Hi there - new Tunnel PM here 👋 A lot of updates on this one: 

- Updated cloudflared permission [docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-permissions) 
- Updated [Tunnel Guide](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide)
- We've moved [Quick Tunnels](https://blog.cloudflare.com/quick-tunnels-anytime-anywhere/) to our Named Tunnel model (They do not require a Zone on Cloudflare) 
- Service Install command has been updated to the [proper link](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service)

See below.

```
abe@xxxxxxxxxx ~ % cloudflared service install 
2021-12-04T00:38:52Z INF Installing Cloudflare Tunnel client as an user launch agent. Note that Cloudflare Tunnel client will only run when the user is logged in. If you want to run Cloudflare Tunnel client at boot, install with root permission. For more information, visit https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service
```

**Comment by monomy001** [comment]
You know, actually reading through all the message here, plus encountering the same problem myself, this issue shouldntve been closed. To recap, I am following the tutorial here : 

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/ 

going from top to bottom, i setup the tunnel remotely.. it creates a tunnel on cloudflared locally, however it doesnt generate a <UUID>.json file. If I create the tunnel locally, yes this file will get generated, however I still cant figure out how to specify which SSL cert file to use on config.yml ingress rules. 

The documentation gets people confused if they follow the guide top to bottom.. coz there is no <UUID>.json file generated when setting up remotely.

Also Please help with how to specify the SSL file to use.
Thank you.

**Comment by wangziyao318** [comment]
I prefer to write a service instead of using cloudflared's `service install` command. Here is [a blog](https://blog.smittytone.net/2022/05/03/how-to-do-dns-over-https-on-a-raspberry-pi/) I found quite useful. A `cloudflared.service` file like this under /lib/systemd/system/ would work.

```sh
[Unit]
Description=DNS over HTTPS (DoH) proxy client
Wants=network-online.target nss-lookup.target
Before=nss-lookup.target
After=network-online.target syslog.target

[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
DynamicUser=yes
ExecStart=/usr/local/bin/cloudflared proxy-dns --upstream https://1.1.1.1/dns-query --upstream https://8.8.8.8/dns-query
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Comment by rajshahjahan** [comment]
Here’s my /etc/system/system/cloudflared.service file:

[Unit]
Description=cloudflared DNS over HTTPS proxy
After=syslog.target network-online.target

[Service]
Type=simple
User=cloudflared
EnvironmentFile=/etc/default/cloudflared
ExecStart=/usr/local/bin/cloudflared proxy-dns $CLOUDFLARED_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

Here’s the /etc/default/cloudflared:

# Commandline args for cloudflared, using CloudFlare DNS
CLOUDFLARED_OPTS=--port 5053 --upstream https://1.1.1.1/dns-query --metrics 127.0.0.1:5353 --max-upstream-conns 100

I noticed that you’re using two different DNS providers. If you’re using PiHole, you might want to run separate instances of CloudFlared for multiple DNS servers. However, that could cause issues. You may get different IP addresses for A record DNS queries. I’ve even noticed this with the same DNS provider with different DNS servers.

For the most part, both are very similar.

Thanks,

Rajiv Baxi
