### ISSUE TITLE
Update not working - context cancellation while reading body

### ISSUE THREAD

**Issue by BojanZelic** [cloudflare/cloudflared#255]
`cloudflare update` command is erroring out with the following error:
```
failed to update cloudflared: context deadline exceeded (Client.Timeout or context cancellation while reading body)
ERROR[2020-11-03T12:21:31-07:00] update check failed: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```
Steps to reproduce:
```
wget https://github.com/cloudflare/cloudflared/releases/download/2020.10.0/cloudflared-linux-amd64
chmod +x ./cloudflared-linux-amd64
./cloudflared-linux-amd64 update
```

Tried with version 2020.10.2
```
wget https://github.com/cloudflare/cloudflared/releases/download/2020.10.2/cloudflared-linux-amd64
chmod +x ./cloudflared-linux-amd64
./cloudflared-linux-amd64 update --force
```

**Comment by Nick-Payne** [comment]
I just got this exact same error message on a Raspberry Pi when running

`sudo cloudflared update`

Running cloudflared -v shows the version as 2020.10.0.

**Comment by KommX** [comment]
See #253.

**Comment by chungthuang** [comment]
We have increased timeout to 60 seconds for versions after 2020.10.2, prior to that it is 5 seconds. Please try to update cloudflared using your package manager if you are on versions 2020.10.2 or older.

**Comment by BojanZelic** [comment]
Thanks @chungthuang  that seems to work
