### ISSUE TITLE
2020.11.3 ends without error

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#258]
even with loglevel debug, the last line in the log file is:
[2020-11-12T10:22:08.8022149Z]: Starting metrics server on 127.0.0.1:12714/metrics
... and then the process ends. Same config works fine with 2020.10.2

**Comment by adamchalmers** [comment]
Hi, thanks for reporting this. Could you please post your OS and which arguments/config file `cloudflared` was invoked with?

**Comment by vidarak** [comment]
windows... x64
I only config file as argument as I want to have a clean installation procedure across all our servers, with only the config file to edit.
Config.yml
hostname: some.public.hostname
url: https://127.0.0.1
name: OUR-INTERNAL-SERVERNAME
logfile: c:\cloudflared\cloudflared.log
no-tls-verify: true

**Comment by FireMasterK** [comment]
I am facing this issue in Windows 10 too, the logs contain nothing useful.

```
C:\Users\kavin>cloudflared --url http://127.0.0.1:8080
INFO[2020-11-15T22:56:05+05:30] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
INFO[2020-11-15T22:56:05+05:30] Version 2020.11.5
INFO[2020-11-15T22:56:05+05:30] GOOS: windows, GOVersion: go1.15.3, GoArch: amd64
INFO[2020-11-15T22:56:05+05:30] Environment variables map[proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:http://127.0.0.1:8080]
INFO[2020-11-15T22:56:05+05:30] Starting metrics server on 127.0.0.1:33057/metrics
INFO[2020-11-15T22:56:05+05:30] cloudflared will not automatically update on Windows systems.
INFO[2020-11-15T22:56:05+05:30] Initial protocol h2mux
```

**Comment by FireMasterK** [comment]
I updated to `2020.11.5` and I no longer face this issue.

**Comment by TownLake** [comment]
Thanks for the report. Could you update to 2020.11.6 - this version includes a fix for Windows deployments.

@FireMasterK can you share your configuration file as well? Or are you just invoking it from the command.

**Comment by vidarak** [comment]
Updated to 2020.11.6. Finally a 2020.11-release that works...

**Comment by adamchalmers** [comment]
Glad to hear that was the problem. We're updating our integration tests to cover Windows whenever we upgrade, so hopefully that won't be a problem again.
