### ISSUE TITLE
Unable to run if macOS network device is already set to pull from local server

### ISSUE THREAD

**Issue by MindTooth** [cloudflare/cloudflared#26]
Hi,

Figured I would give `cloudflared` a go today.  And after installing the service then rebooting, nothing worked.

After some trial & error, I located the issue to be that I've set the network device to use 127.0.0.1 as the resolver.  And therefore it seems like the device/port is taken.

The error is as following:
```
~ $ sudo cloudflared
INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml 
INFO[0000] Build info: {GoOS:darwin GoVersion:go1.9.1 GoArch:amd64} 
INFO[0000] Version 2018.4.8                             
INFO[0000] Flags map[proxy-dns:true]                    
INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
INFO[0000] Adding DNS upstream                           url="https://1.0.0.1/dns-query"
INFO[0000] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/ 
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://localhost:53"
FATA[0000] Error opening metrics server listener         error="lookup localhost on 127.0.0.1:53: read udp 127.0.0.1:49289->127.0.0.1:53: read: connection refused"
```

<img width="780" alt="screen shot 2018-04-30 at 11 28 42" src="https://user-images.githubusercontent.com/33870508/39421520-bb5be928-4c69-11e8-9b51-bdb5fd08a61e.png">

Am I understanding it wrong that I can't use `cloudflared` as a alternative to stubby, dnscrypt-proxy, unbound, etc.?

Running the latest version of macOS (10.13.4).  And installed via `brew`.

**Comment by vavrusa** [comment]
It seems like you're missing `localhost` in /etc/hosts, so it can't resolve it on startup. It typically looks like this:

```
$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
127.0.0.2       localhost.site
```

You can also force an address (instead of the name `localhost`) in the configuration (`/usr/local/etc/cloudflared/config.yaml`) like this:

```
proxy-dns-address: 127.0.0.1
```

**Comment by MindTooth** [comment]
Super nice 👍  

Seems I've cleaned house way to much when reverting some ad blocking via the `hosts` file..
