### ISSUE TITLE
Different behavior between access token and service access id/secret for access tcp

### ISSUE THREAD

**Issue by etiennetremel** [cloudflare/cloudflared#260]
I'm using the `cloudflared access tcp` command, the tunnel work correctly when I login using `cloudflared login` but not when I specify a service token.

From the logs, the only difference I see is that cloudflared is using a `Cf-Access-Token` vs `Cf-Access-Client-Id` and `Cf-Access-Client-Id` when specifying the service token.

I'm running a tunnel which forward traffic to a service running on port 9000 as below:
```
$ cloudflared tunnel- --hostname=target.example.com
  --url=tcp://service:9000
  --origincert=/etc/cloudflared/certs/cert.pem
```

The following steps work as expected:
```
$ cloudflared login
$ cloudflared access tcp --hostname=target.example.com --url=0.0.0.0:9210 --log-level=debug

// ...

$ curl 0.0.0.0:9210
DEBUG[2020-11-16T17:24:46Z] Access Websocket request: GET / HTTP/1.1
Host: target.example.com
Cf-Access-Token: <access-token>

DEBUG[2020-11-16T17:24:47Z] Websocket response: "HTTP/1.1 101 Switching Protocols...
```

The following steps doesn't work:
```
$ cloudflared access tcp --hostname=target.example.com --url=0.0.0.0:9210 --log-level=debug \
  --service-token-id=<cloudflare access client id> \
  --service-token-secret=<cloudflare access client secret>

// ...

$ curl 0.0.0.0:9210
DEBUG[2020-11-16T17:24:23Z] Websocket request: GET / HTTP/1.1
Host: target.example.com
Cf-Access-Client-Id: <cloudflare access client id>
Cf-Access-Client-Secret: <cloudflare access client secret>

ERROR[2020-11-16T17:24:23Z] failed to connect to https://target.example.com with error: websocket: bad handshake
```

Additional information:
```
$ cloudflared version
cloudflared version 2020.11.6 (built 2020-11-15-0231 UTC)
```

Any idea what could be wrong?

**Comment by TownLake** [comment]
Could you confirm how you have your Access policy configured with the service token rule? We've [published an example](https://developers.cloudflare.com/cloudflare-one/tutorials/ssh-service-token) of how to configure this model, let us know if that helps clarify.

**Comment by TownLake** [comment]
Closing after 3 weeks; please let us know if you get a chance to look at the tutorial and if that solves it or if you have additional questions and we can reopen.
