### ISSUE TITLE
TryCloudflare isn't working

### ISSUE THREAD

**Issue by gunar** [cloudflare/cloudflared#261]
Executing `cloudflared tunnel` is supposed to print a URL on my screen but it seem stuck at "Starting metrics server":

```
$ cloudflared tunnel
INFO[2020-11-17T18:31:21Z] Version 2020.11.7
INFO[2020-11-17T18:31:21Z] GOOS: linux, GOVersion: go1.15.3, GoArch: amd64
INFO[2020-11-17T18:31:21Z] Environment variables map[logfile:/var/log/cloudflared.log proxy-dns:true proxy-dns-address:127.0.0.1 proxy-dns-port:5300 proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query]
INFO[2020-11-17T18:31:21Z] Adding DNS upstream - url: https://1.1.1.1/dns-query
INFO[2020-11-17T18:31:21Z] Adding DNS upstream - url: https://1.0.0.1/dns-query
INFO[2020-11-17T18:31:21Z] Starting DNS over HTTPS proxy server on: dns://127.0.0.1:5300
INFO[2020-11-17T18:31:21Z] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
INFO[2020-11-17T18:31:21Z] Starting metrics server on 127.0.0.1:40095/metrics
```

PS: I got here by following [these instructions](https://developers.cloudflare.com/argo-tunnel/learning/trycloudflare).

**Comment by nmldiegues** [comment]
Hello @gunar . Thank you for reporting this.

I believe that you have hit a recent change, which should be logging as an error. E.g.: 
```
$ cloudflared tunnel
INFO[2020-11-17T19:43:42Z] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
INFO[2020-11-17T19:43:42Z] Version 2020.11.7
INFO[2020-11-17T19:43:42Z] GOOS: linux, GOVersion: go1.15.3, GoArch: amd64
INFO[2020-11-17T19:43:42Z] Environment variables map[proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query]
INFO[2020-11-17T19:43:42Z] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
You must either set ingress rules in your config file, or use --url, or use --unix-socket
```

To fix that, you have to pass the `--url` flag to identify the local origin that you want to serve over the tunnel (whereas before we were assuming localhost:8080). You can also pass `--hello-world` to get a dummy landing page to test it out. Check these out in https://developers.cloudflare.com/argo-tunnel/configuration/arguments or via `cloudflared tunnel --help`

Let us know if this is not the case and we can look further.

**Comment by gunar** [comment]
Hi @nmldiegues, thanks for looking into this. I've tried `--url` to no avail—same output. The hello-world page worked—intermittently though. Could this have something to do with my use of OpenVPN? Although I've tried these with the VPN off and with the VPN on and neither of them worked.

**Comment by nmldiegues** [comment]
It should work regardless of the VPN as long as you have outbound connectivity to the Internet on port 7844 (see https://developers.cloudflare.com/argo-tunnel/faq#what-are-the-ports-and-ips-used-by-cloudflared)

If that's not the problem, then maybe try adding `--transport-loglevel debug --loglevel debug` to the end of your command to see if anything else useful shows up.

**Comment by gunar** [comment]
Nothing useful—no difference at all actually. Only hello-world works so far—both with and without the VPN.

Here's what my current `config.yml` (automatically generated) looks like:

```yml
---
logfile: /var/log/cloudflared.log
proxy-dns: true
proxy-dns-address: 127.0.0.1
proxy-dns-port: 5300
proxy-dns-upstream:
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query
```

**Comment by nmldiegues** [comment]
Pardon my ignorance: how exactly did that get "automatically generated"?

What if you remove that file and retry?

**Comment by gunar** [comment]
Yes that works!

It got automatically generated because I've installed `cloudflared` using the [AUR packge](https://aur.archlinux.org/packages/cloudflared/). I've left a [comment](https://aur.archlinux.org/packages/cloudflared/#comment-776137) there too in case others have the same problem.

My problem is solved. Thank you @nmldiegues.
