### ISSUE TITLE
HTTP2 protocol with SSE support doesn't seem to work for tunneling Concourse

### ISSUE THREAD

**Issue by analytically** [cloudflare/cloudflared#262]
When adding `protocol: http2` to the config file (supporting SSE) the tunnel to Concourse still fails to load build logs, so something must be off for SSE support.

**Comment by chungthuang** [comment]
Hi @analytically, the protocol is only available for named tunnels after release 2020.11.4. Checkout https://blog.cloudflare.com/argo-tunnels-that-live-forever/ for named tunnels are and https://developers.cloudflare.com/argo-tunnel/create-tunnel for how to set up a named tunnel.

**Comment by analytically** [comment]
Got it to work `Initial protocol http2` but SSE still doesn't seem to be fully supported. I'm trying to tunnel Concourse (https://concourse-ci.org/) which uses SSE for the build logs but it doesn't come through.

**Comment by chungthuang** [comment]
I haven't used Concourse before. Do you know what response headers it returns? We expect SSE to include `content-type: text/event-stream` https://github.com/cloudflare/cloudflared/blob/master/origin/proxy.go#L230.

**Comment by analytically** [comment]
Yeah it's `text/event-stream` but it's suffixed with `; charset=utf-8"`

**Comment by analytically** [comment]
https://github.com/concourse/concourse/blob/2e467ac405b1f19c76f56b5e184b5b79e6af6418/atc/api/buildserver/eventhandler.go#L32

**Comment by chungthuang** [comment]
Thanks for pointing this out, we will fix it in the upcoming release.

**Comment by analytically** [comment]
Any idea when this would be? I can submit a simple PR if you'd like.

**Comment by chungthuang** [comment]
I have one in review by the team. It should be released by the end of the day.

**Comment by chungthuang** [comment]
Thank you for your patience. Digging further into the issue, we found our edge logic also needs to be updated, so I expect it to be ready tomorrow.

**Comment by analytically** [comment]
Using 2020.11.9 SSE still doesn't seem to be working as it should. Chrome now shows

`Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR` and it seems the events are not streamed.

**Comment by analytically** [comment]
Seems like the response event stream is missing headers.

**Comment by analytically** [comment]
#199

**Comment by chungthuang** [comment]
Perhaps you tried before our edge logic rollout was completed. Can you give it another try?

**Comment by analytically** [comment]
I have just tried (restart of cloudflared), unfortunately same behaviour as before. Also see #199

**Comment by analytically** [comment]
The events are there but seem buffered.

**Comment by abelinkinbio** [comment]
We recently released a new feature that allows users to connect any service that relies on TCP-based protocols to Cloudflare's network. This should help alleviate some of the issues mentioned above to start.

Check it out: https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel
