### ISSUE TITLE
Use same download location for ARM64 build

### ISSUE THREAD

**Issue by analytically** [cloudflare/cloudflared#265]
Currently Equinox doesn't serve the ARM64 build so we're unable to template the download location:

```
https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-$${attr.cpu.arch}.tgz
```

The file is available here: https://github.com/cloudflare/cloudflared/releases/download/2020.8.2/cloudflared-linux-arm64

**Comment by chungthuang** [comment]
We have moved download to https://developers.cloudflare.com/argo-tunnel/getting-started/installation. The URL is `https://github.com/cloudflare/cloudflared/releases/download/{version}/cloudflared-linux-arm64`

**Comment by analytically** [comment]
@chungthuang would be handier if we had a Equinox location (url without version) that also offered a ARM64 release...

**Comment by nmldiegues** [comment]
@analytically You should be able to do it with github: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases

E.g.: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64 resolve to the latest arm64 release
