### ISSUE TITLE
Poor performance using argo tunnel

### ISSUE THREAD

**Issue by FireMasterK** [cloudflare/cloudflared#266]
Hi there,

I have a server which I use to stream/download large files with multiple threads, when I use argo tunnel for this, I get significantly lower speeds compared to an A record after 10-30 seconds.

With argo tunnel: 900-1000KB/s
Without: 12-16 MB/s

This is how I run argo tunnel:
```
cloudflared tunnel --hostname pipedargo.kavin.rocks --url http://127.0.0.1
```

Any suggestions on why this happens?

**Comment by chungthuang** [comment]
@FireMasterK you can try out our new transport implementation in latest release. Note that it only supports named tunnel, the setup guide is at https://developers.cloudflare.com/argo-tunnel/create-tunnel. Once you create the tunnel and route, you can run it with the new transport using `cloudflared tunnel run -p http2 <tunnel ID>`

**Comment by FireMasterK** [comment]
I can't seem to create the DNS record with the command.
```
cloudflared tunnel route dns piped-1 pipedargo.kavin.rocks
Failed to add route: code: 1000, reason: Internal server error
```

**Comment by chungthuang** [comment]
Have you tried adding from dashboard https://developers.cloudflare.com/argo-tunnel/routing-to-tunnel/dns#route-traffic-from-the-cloudflare-dashboard?

**Comment by FireMasterK** [comment]
The transport seems to improve it, but just marginally. It's now at 1.2 MB/s after 10-20 seconds.

**Comment by chungthuang** [comment]
Are you only seeing performance issue after 10-20 second? What is the transfer rate in the first 10s?

**Comment by FireMasterK** [comment]
About normal, about 16 MB/s

**Comment by chungthuang** [comment]
It will help a lot if you have an example server we can use to reproduce.

**Comment by morpig** [comment]
Experiencing the same issue. For me it's more on latency.

I'm running two dedicated servers (same isp/asn), peered with the same CF colo.

I ran ```time curl "http://xxx"```, one server only requires ~200-300ms, while the other one goes up to 900-1200ms.

My cloudflared client:
```./cloudflared access tcp --hostname xxx --url localhost:18081```

**Comment by chungthuang** [comment]
What protocol is your server using? I assume it's not HTTP because you are using `cloudflared access tcp`.

**Comment by FireMasterK** [comment]
Here's something you can test with:

No Argo: 
```
https://pipedproxy.kavin.rocks/videoplayback?expire=1606166556&ei=vNO7X_SGDcvFhwa9moyADw&ip=209.141.46.38&id=6aacfe284f9ba4a4&itag=315&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=aP&mm=31%2C26&mn=sn-n4v7knlk%2Csn-a5msen7z&ms=au%2Conr&mv=m&mvi=2&pl=23&initcwndbps=106250&vprv=1&mime=video%2Fwebm&ns=05RqcxLacH2t9yzjqkKJF6UF&gir=yes&clen=1648069666&dur=634.566&lmt=1544611995945231&mt=1606144842&fvip=2&keepalive=yes&c=WEB&txp=5532432&n=e6KKmz430y_OdIk&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI-Q2iR1eMSvOtOJXIcG_ASnFLXyiRRAb5ioccaJB2pzAiBiYZHuJkl1XJAg1rHXTzZstYgAMl516IKT00XNts8v6w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKpbtOrkz4UEdzPqfMfpOO6ZbUe24j7XxI2zn9sxfqDTAiB65g1C3TLFBbAAHC20gPIGGgNlupSR8OWbDHu_sx9MxQ%3D%3D&host=r2---sn-n4v7knlk.googlevideo.com
```
With Argo:
```
https://pipedproxyargo.kavin.rocks/videoplayback?expire=1606166556&ei=vNO7X_SGDcvFhwa9moyADw&ip=209.141.46.38&id=6aacfe284f9ba4a4&itag=315&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=aP&mm=31%2C26&mn=sn-n4v7knlk%2Csn-a5msen7z&ms=au%2Conr&mv=m&mvi=2&pl=23&initcwndbps=106250&vprv=1&mime=video%2Fwebm&ns=05RqcxLacH2t9yzjqkKJF6UF&gir=yes&clen=1648069666&dur=634.566&lmt=1544611995945231&mt=1606144842&fvip=2&keepalive=yes&c=WEB&txp=5532432&n=e6KKmz430y_OdIk&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAI-Q2iR1eMSvOtOJXIcG_ASnFLXyiRRAb5ioccaJB2pzAiBiYZHuJkl1XJAg1rHXTzZstYgAMl516IKT00XNts8v6w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKpbtOrkz4UEdzPqfMfpOO6ZbUe24j7XxI2zn9sxfqDTAiB65g1C3TLFBbAAHC20gPIGGgNlupSR8OWbDHu_sx9MxQ%3D%3D&host=r2---sn-n4v7knlk.googlevideo.com
```

**Comment by abelinkinbio** [comment]
If the issue still persists (or resurfaces in the future), I'd recommend filing a ticket with Cloudflare Support. From there, we can ask you to share more details on your config with logs to debug.

**Comment by hessercan** [comment]
I have this same issue. I have vms setup in multiple locations and have the tunnels running on each of them. I use Cloudflare WARP to connect to those sites. The file transfer speed between me and them is like 350kb/s max. Am I missing something? I'm using one.dash.cloudflare.com for the entire setup.
