### ISSUE TITLE
Loglevel

### ISSUE THREAD

**Issue by fobi81** [cloudflare/cloudflared#268]
Hi,

After the last update (2020.11.11) we receive logs as...

[36mINFO[0m[2020-11-26T12:20:58Z] CF-RAY: 5f839108c838fc75-ZAG Status: 200 OK served by ingress 0

Are some log level defaults are changed?

We don't have any "loglevel" configured in configuration. We using defaults.

Regards,
Robert.

**Comment by chungthuang** [comment]
Hi @fobi81 we added extra logs in recently releases to improve observability. If they are too noisy, you can use `log-level` flag to change verbosity. The supported levels are `debug`, `info`, `error` and `fatal`.

**Comment by fobi81** [comment]
Hi @chungthuang,

Thank's for the info. We will configure logging. 
We did update on our stage environment with low traffic and this log level is quite noisy. This can be a problem in production, especially if you using cloud services. Disk IOPS are quite "expensive" in the cloud.
The only concern is to people that already use _cloudflared_ need to be aware of this change.

Cheers!

**Comment by analytically** [comment]
Agreed, 200 OK should not be logged at info level IMHO

**Comment by chungthuang** [comment]
Thank you all for the feedback, sorry we didn't take disk usage into account. We are going to log responses at debug level in the next release.

**Comment by nmldiegues** [comment]
I confirm that this issue was fixed and will be available in the next release.

**Comment by morpig** [comment]
Any ETA on the next release? Quite disturbing with the req logs. 😅

**Comment by adamchalmers** [comment]
2020.12.0 should be out today!

**Comment by morpig** [comment]
looks like it occurs again in > 2020.12.0.. can you please check?

i'm running 2020.12.4 with loglevel info:

```
6:54PM INF CF-RAY: 6121hac67d07c395-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac94c48cc24-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121he0b0a76356d-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdb73ba435c1-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdd9f97d3597-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hcbd28e51710-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hcbf3969d9d4-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac9684cc336-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdba1d441910-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdd9ef093550-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121he06299e3550-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hcbe8c2c18ac-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac9ffbe19cd-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdb73f74e4b3-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdb8291a357f-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac80c561a46-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac68c9517b3-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdba4c8735a4-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121he06382e357f-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdef8f8aa95e-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hd35ae1101f6-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hdbc8aa73556-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac97cd6e483-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hacbeb3417ab-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hac67cbb01d9-SIN Status: 101 Switching Protocols served by ingress 0
6:54PM INF CF-RAY: 6121hd0ebbb23562-SIN Status: 101 Switching Protocols served by ingress 0
```

**Comment by nmldiegues** [comment]
> looks like it occurs again in > 2020.12.0.. can you please check?
> 
> i'm running 2020.12.4 with loglevel info:
> 
> ```
> 6:54PM INF CF-RAY: 6121hac67d07c395-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac94c48cc24-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121he0b0a76356d-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdb73ba435c1-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdd9f97d3597-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hcbd28e51710-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hcbf3969d9d4-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac9684cc336-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdba1d441910-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdd9ef093550-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121he06299e3550-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hcbe8c2c18ac-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac9ffbe19cd-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdb73f74e4b3-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdb8291a357f-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac80c561a46-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac68c9517b3-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdba4c8735a4-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121he06382e357f-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdef8f8aa95e-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hd35ae1101f6-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hdbc8aa73556-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac97cd6e483-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hacbeb3417ab-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hac67cbb01d9-SIN Status: 101 Switching Protocols served by ingress 0
> 6:54PM INF CF-RAY: 6121hd0ebbb23562-SIN Status: 101 Switching Protocols served by ingress 0
> ```

We'll fix that

**Comment by analytically** [comment]
Still seeing too much logging at INFO level using `2021.1.4`:

```
 INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2:38PM INF Version 2021.1.4
2:38PM INF GOOS: linux, GOVersion: go1.15.6, GoArch: amd64
2:38PM INF Environment variables map[hostname:airflow.galois.tools metrics:10.190.147.158:23178 no-autoupdate:true origincert:/etc/cloudflared/cert.pem proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:10.190.147.158:28520]
2:38PM INF Initial protocol h2mux
2:38PM INF Starting metrics server on 10.190.147.158:23178/metrics
2:38PM INF Connection established connIndex=0 location=SEA
2:38PM INF Each HA connection's tunnel IDs: map[0:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug]
2:38PM INF Route propagating, it may take up to 1 minute for your new route to become functional
2:38PM INF Connection established connIndex=1 location=LAX
2:38PM INF Connection established connIndex=2 location=SEA
2:38PM INF Each HA connection's tunnel IDs: map[0:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 1:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug]
2:38PM INF Route propagating, it may take up to 1 minute for your new route to become functional
2:38PM INF Each HA connection's tunnel IDs: map[0:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 1:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 2:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug]
2:38PM INF Route propagating, it may take up to 1 minute for your new route to become functional
2:38PM INF Connection established connIndex=3 location=LAX
2:38PM INF Each HA connection's tunnel IDs: map[0:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 1:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 2:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug 3:a6tpksux068gk49x2bllzi4rcgtrka78cni6ksrqy41g1eazzvug]
2:38PM INF Route propagating, it may take up to 1 minute for your new route to become functional
2:38PM INF mux - metrics: Stopping mux metrics updater
2:38PM INF CF-RAY: 61289494f87ef58d-SEA Status: 302 FOUND served by ingress 0
2:38PM INF CF-RAY: 612894963a15f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 6128949bd8d7f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 6128949bd8d8f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 612894a59d6cf58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 6128949bd8d6f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 612894a8c8e2f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 612894a8c8e0f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 612894a8d8edf58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8c8eaf58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8d8f0f58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8d8f2f58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8c8ebf58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8d8ecf58d-SEA Status: 304 NOT MODIFIED served by ingress 0
2:38PM INF CF-RAY: 612894a8c8e7f58d-SEA Status: 200 OK served by ingress 0
2:38PM INF CF-RAY: 612894a8d903f58d-SEA Status: 200 OK served by ingress 0
```

**Comment by nmldiegues** [comment]
Correct @analytically , we confirm that was a regression and it is already fixed for the upcoming release
