### ISSUE TITLE
Argo tunnel with Sharepoint Caches my login publicly

### ISSUE THREAD

**Issue by rif5la** [cloudflare/cloudflared#275]
I setup argo tunnel for my sharepoint site. The sharepoint site requires user login. When I login from my computer, I notice that when I tested the site from another remote computer, it shows my user info publicly.

Is argo only meant for static sites?

**Comment by stevenanthonyrevo** [comment]
I can assume if a website is being tunneled through Cloudflare's service to the internet it can expose public information. 
I would recommend being fully aware of the services you expose to the internet via Cloudflare's service.

**Comment by TownLake** [comment]
Is the site using NTLM?

**Comment by vidarak** [comment]
Do you mean the login form contains your username pre-filled in the other computer even if you didn't visit the site before on that one? Are you using Google Chrome with signed-in and sync'ed profile by any chance?
