### ISSUE TITLE
 Couldn't start tunnel: Error getting origin cert: Client didn't specify origincert path when running from terminal

### ISSUE THREAD

**Issue by thphongv108** [cloudflare/cloudflared#279]
https://developers.cloudflare.com/access/protocols-and-connections/ssh/putty-clients
**cloudflared.exe access ssh --hostname "the hostname of the SSH server" --url localhost:"unused port"**

`cloudflared.exe --hostname electro-locator-speeds-accommodate.trycloudflare.com --url ssh://localhost:5050`

INFO[2020-12-15T18:52:07+07:00] Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
INFO[2020-12-15T18:52:07+07:00] Version 2020.12.0
INFO[2020-12-15T18:52:07+07:00] GOOS: windows, GOVersion: go1.15.6, GoArch: amd64
INFO[2020-12-15T18:52:07+07:00] Environment variables map[hostname:electro-locator-speeds-accommodate.trycloudflare.com proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:ssh://localhost:5050]
INFO[2020-12-15T18:52:07+07:00] cloudflared will not automatically update on Windows systems.
INFO[2020-12-15T18:52:07+07:00] Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp]
ERROR[2020-12-15T18:52:07+07:00] You need to specify the origin certificate path with --origincert option, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/arguments/ for more information.
ERROR[2020-12-15T18:52:07+07:00] Couldn't start tunnel: Error getting origin cert: Client didn't specify origincert path when running from terminal
Error getting origin cert: Client didn't specify origincert path when running from terminal

**Thanks Team**

**Comment by nmldiegues** [comment]
Hello @thphongv108 ,

Did you perform `cloudflared tunnel login` as per the Setup instructions? https://developers.cloudflare.com/argo-tunnel/getting-started/setup

You may also be interested in reading this Tutorial for an end to end view of securing an SSH server with Tunnel and Access: https://developers.cloudflare.com/cloudflare-one/tutorials/zero-trust-security/gitlab
(more tutorials at https://developers.cloudflare.com/argo-tunnel/learning/tutorials)

**Comment by thphongv108** [comment]
> Xin chào @ thphongv108 ,
> 
> Bạn có thực hiện `cloudflared tunnel login`theo hướng dẫn Cài đặt không? https://developers.cloudflare.com/argo-tunnel/getting-started/setup
> 
> Bạn cũng có thể quan tâm đến việc đọc Hướng dẫn này để biết cách bảo mật máy chủ SSH bằng Tunnel và Access: https://developers.cloudflare.com/cloudflare-one/tutorials/zero-trust-security/gitlab
> (thêm hướng dẫn tại https://developers.cloudflare.com/argo-tunnel/learning/tutorials )

Hi @nmldiegues
When I use the OpenSSH client to connect then everything is fine. I want to use Putty and see the instructions here "https://developers.cloudflare.com/access/ssh/putty" I followed the instructions but got the error as above

**Comment by nmldiegues** [comment]
@thphongv108 the error you show in the first comment takes place when you start an Argo Tunnel via cloudflared.
Hence, it's not clear to me how changing the SSH client has anything to do with that.

Can you track all the steps you've done, one by one, so I can try to understand them?

**Comment by thphongv108** [comment]
I've done it successfully, thank @nmldiegues

**Comment by Pythonweasel** [comment]
I don't know if anyone is still having this issue but, I found a work around. 

My error message was: ERR Cannot determine default origin certificate path. No file cert.pem in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable originCertPath=                               error parsing tunnel ID: Error locating origin cert: client didn't specify origincert path 

I specified the cert.pem in my config.yml but the error did not clear. 

I had to cd to  "/usr/local/etc/cloudflared" and copy the cert.pem to this directory. I am running wsl on a windows machine. Hope this helps.
