### ISSUE TITLE
Monitoring Uptime: per tunnel before disconnection with restart or closed PID

### ISSUE THREAD

**Issue by stevenanthonyrevo** [cloudflare/cloudflared#283]
Looking for a monitoring solution to set alerts up per tunnel.

For example, a tunnel may go down due to a disconnection from the internet and the tunnel may not auto restart itself, unless manually triggered again from the terminal. 

```
WARN[326478] Tunnel disconnected due to error              error="No IP address to claim"
```
Does Argo Tunnel provide a way to review healthy connections or each connection accessing the edge network?
Possible logging the uptime per tunnel? 

Any suggestions are welcome, looking to avoid downtime of tunneling unless specifically closing a tunnel port or process ID.

**Comment by chungthuang** [comment]
Hi @stevenanthonyrevo, in version `2020.12.0`  we added a new endpoint `/ready` to the metrics server.

**Comment by sphr2k** [comment]
@chungthuang I created a script that checks the endpoint every 15 seconds ans restarts the tunnel if it's disconnected, but that can't be the actual solution, can it?

**Comment by vidarak** [comment]
The fact that connections do not automatically re-connect or get rerouted to alternative POPs is an obvious design flaw or bug. Please raise the priority of this.

**Comment by TownLake** [comment]
Hi @vidarak - `cloudflared` does attempt to reconnect automatically (and to new data centers if it's unable to connect to a previously established data center).

@stevenanthonyrevo saw the thumbs up - let us know if the `/ready` endpoint helps or if you have feedback on it.

**Comment by vidarak** [comment]
> Hi @vidarak - `cloudflared` does attempt to reconnect automatically (and to new data centers if it's unable to connect to a previously established data center).
 This doesn't work. I have a support ticket open for it which is forwarded to engineering department which is slow-walking it.

**Comment by stevenanthonyrevo** [comment]
Noticed a one of my tunnels had some errors.... 

@chungthuang I had checked in the Cloudflare Dashboard and seen the original DNS records (AAA) actually went missing. Not sure, if this is normal behavior or was this fixed in the update? 

Thanks!

**Comment by nmldiegues** [comment]
Please update to `2021.1.1` and let us know if it helps.

**Comment by stevenanthonyrevo** [comment]
Thanks, @nmldiegues!  Great work 👍 on the increased visibility into the logs and metrics within version`2021.1.4`.  

Any way to include the health of the DNS connection,  similar to apache logs but showing the connection to the Cloudflare's DNS record each tunnel creates?  

Something like this would be super helpful

```
[Wed Oct 11 14:32:52 2020] [error][AAAA] [proxied] [connection missing]  domain.com
[Wed Oct 11 14:35:00 2020] [warn] [AAAA] [proxied] [connection awaiting] domain.com
[Wed Oct 11 14:37:00 2020] [info] [AAAA] [only-dns][connection healthy]  domain.com
[Wed Oct 11 14:37:00 2020] [info] [AAAA] [proxied] [connection healthy]  domain.com
``` 
_Date, Notice, Record Name, Record Type, Health, Domain Name_

**Comment by abelinkinbio** [comment]
Glad this was helpful. We're looking to add UI support within the Teams Dashboard in Q3 as well which may look like this. Thanks for the feedback.
