### ISSUE TITLE
use paths instead of sub domain

### ISSUE THREAD

**Issue by hackmonker** [cloudflare/cloudflared#286]
okay this might be a long shot, but just wanted to clarify it before giving up. I was able to set up an argo tunnel, route and then access it from app.domain.com. so everything works fine.

my question is, is it possible to use path instead of subdomains. so like use domain.com/app instead of cname entries in cloudflare? thanks

**Comment by nmldiegues** [comment]
Hello @hackmonker 

To answer directly your question: you cannot route a tunnel to a specific path of a domain. 

However, you can have a single tunnel serving various origin services with the ingress rules controllable via the host path: https://developers.cloudflare.com/argo-tunnel/configuration/ingress

Does that help?

**Comment by hackmonker** [comment]
Thanks for clarifying that. I did saw the ingress rules for something like app1.domain.com, app2.domain.com.
Just wanted to know if it was possible for paths like a reverse proxy. but thanks anyway will be using the ingress path method. cheers and happy new year. :D

**Comment by adamchalmers** [comment]
Yes, my suggestion is to run the tunnel on hostname `domain.com` and use ingress rules like
```yaml
ingress:
  - hostname: domain.com
    path: /app*
    service: localhost:8080
  - service: http_status:404
```
