### ISSUE TITLE
Auto update disabled by default on linux when installed as a service

### ISSUE THREAD

**Issue by ziyaointl** [cloudflare/cloudflared#287]
Relevant file: https://github.com/cloudflare/cloudflared/blob/69fd502db3c0f16002c3beb5fc123220debafb3d/cmd/cloudflared/linux_service.go#L64

This seems to be the case for more than 3 years: https://github.com/cloudflare/cloudflared/blame/f0cfad8efa6a8b72090390d75db2b4247991ae8d/cmd/cloudflared/linux_service.go#L55

Is there a stability concern for enabling auto update for long-running services?

**Comment by TownLake** [comment]
We want customers to control their update schedule, which is why this was structured as an opt-in. 

On the stability side, if a team has not deployed Argo Tunnel with a load balancer, then an update will cause downtime. Making this the default behavior helps new users avoid those types of issues.

**Comment by ziyaointl** [comment]
@TownLake This makes a lot of sense. Thank you!
