### ISSUE TITLE
CNAME delete command

### ISSUE THREAD

**Issue by anuraagrijal3138** [cloudflare/cloudflared#289]
I am trying to create cloudflare tunnel on the fly as kubernetes pod.
I have the following as the startup script for my pod:
```
    #!/bin/sh
    tunnel_name=$(openssl rand -base64 12 | sed "s/[^a-zA-Z0-9]//g")
    cloudflared tunnel create $tunnel_name
    tunnel_uuid=$(ls /etc/cloudflared | grep ".json" | sed -e 's/\.json$//')
    cat > /etc/cloudflared/config.yml << EOF
    tunnel: $tunnel_uuid
    credentials-file: /etc/cloudflared/$tunnel_uuid.json
    ingress:
      - hostname: kiali.abc.work
        service: http://kiali.istio-system:20001
      - hostname: argocd.abc.work
        service: http://argocd-server.argocd:80
      - hostname: tracing.abc.work
        service: http://tracing.istio-system:80
      - service: http_status:404
    EOF
    cloudflared tunnel route dns $tunnel_uuid kiali.abc.work
    cloudflared tunnel route dns $tunnel_uuid argocd.abc.work
    cloudflared tunnel route dns $tunnel_uuid tracing.abc.work
    cloudflared tunnel run
```

I wanted to add a prestop hook script that deletes the tunnel and also deletes the CNAME record so that after restart new tunnel is created and I can use the same cloudflared config file. But I did not find command to delete the CNAME that is created with following command:
```
cloudflared tunnel route dns $tunnel_uuid kiali.abc.work
cloudflared tunnel route dns $tunnel_uuid argocd.abc.work
cloudflared tunnel route dns $tunnel_uuid tracing.abc.work
```
Thank you in advance.

**Comment by TownLake** [comment]
Hi @anuraagrijal3138 - just so we understand what you're trying to accomplish, is there a reason you want to delete the CNAME record?

**Comment by anuraagrijal3138** [comment]
Hello @TownLake, I am trying to run cloudflared as pod in kubernetes cluster. In case cloudflared pod restarts, above startup script runs again but the following command fails because these names kiali.abc.work, argocd.abc.work and tracing.abc.work are already associated with the previously created tunnel:
```
cloudflared tunnel route dns $tunnel_uuid kiali.abc.work
cloudflared tunnel route dns $tunnel_uuid argocd.abc.work
cloudflared tunnel route dns $tunnel_uuid tracing.abc.work
```
I can manually delete CNAME when the cloudflared pod restarts but I wanted to make the process dynamic and automated. 
cloudflared tunnel delete {name} only deletes the tunnel but it does not delete the CNAMEs associated with the tunnels.

Hope this clarified the issue. Let me know if there are any other questions.

**Comment by TownLake** [comment]
Thanks for clarifying.

Is there a reason you want to create a new, unique, tunnel at startup? You could remove the `route` step from the startup script by creating the Tunnel once, ahead of time, and using the same credentials file and Tunnel ID. That way you can configure your DNS records once, to point to that consistent Tunnel ID, and separate it from the `run` steps.

I know this is a bit clunky; we're working on ways to make it easier to scale with k8s more broadly in the near term.

**Comment by anuraagrijal3138** [comment]
Thanks for the reply. Right now we are using the method you have described in the comment. It works great but we wanted to remove the process of manually creating the tunnel. 
I will keep an eye out for updates.
