### ISSUE TITLE
tunnel list output sorting

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#300]
Please add parameter to sort the output of tunnel list by any of the column names. The default should be to sort by name.

**Comment by adamchalmers** [comment]
Sounds useful. If anyone wants to implement this, you'd just need to sort the tunnels after they're queried, [here](https://github.com/cloudflare/cloudflared/blob/master/cmd/cloudflared/tunnel/subcommands.go#L198-L201).

**Comment by adamchalmers** [comment]
Feature is now on master, it'll be available in 2021.2.1
