### ISSUE TITLE
Allow for reloading/changing configuration without dropping all tunnels?

### ISSUE THREAD

**Issue by yaleman** [cloudflare/cloudflared#301]
If it's already a feature, I can't find the documentation - is there a way to reload/change the running configuration without dropping all the tunnels? We're using this in an increasingly-large deployment and want to be able to make changes without having to drop every single user's connection for ~minutes.

**Comment by yaleman** [comment]
This seems to refer to the fact that it's watching the configuration file, but I can't find any references to it in documentation, config or functionality? https://github.com/cloudflare/cloudflared/commit/41c358147c001c0e23b92f6508d49e792e3a7623

**Comment by adamchalmers** [comment]
G'day James, this is definitely on our roadmap. We're still planning exactly how this would work. Can I ask, which parts of your config file do you tend to change most often?

**Comment by yaleman** [comment]
That'd totally be the ingress rules - we're using it in bastion mode and rapidly expanding our usage of it, which is slowed down by having to coordinate with everyone around killing their sessions 😄

**Comment by adamchalmers** [comment]
I totally understand. We're going to be working on that soon, it's one of the next items on our roadmap, but I'm not sure when it'll be done.

**Comment by yaleman** [comment]
Thanks for the response, I'd like to leave this issue open until the feature request is done, so that it gives the community somewhere to see it's still in the pipeline, if that's OK?

Also, is it possible for someone to explain the code added in AUTH-2587? I'm happy to open another issue if that's required.

**Comment by adamchalmers** [comment]
Absolutely, let's leave this open so others can chime in. We have an
internal ticket about this too, but it'd be good to hear as much from users
as we can. The code from AUTH-2587 was part of a project that was sadly
shelved a while back.

**Comment by danopia** [comment]
I'm also looking for config reloading. The ingress rule list would by far be my most obvious candidate for what would be updated at runtime.

I think it's also reasonable if a 'first pass' on config reloading depended on receiving a specific signal such as `SIGUSR1` instead of watching for file changes; but file watching would be the most ideal overall.

I'm investigating a usecase of generating the config file dynamically using a Kubernetes cluster state. In this case cloudflared could serve the traditional ingress-controller role of routing HTTP traffic to the correct Kubernetes services. Unfortunately, and especially with Websocket traffic involved, restarting each cloudflared when a DNS name is introduced or cleaned up is pretty intrusive.

**Comment by andrewheberle** [comment]
> Absolutely, let's leave this open so others can chime in. We have an internal ticket about this too, but it'd be good to hear as much from users as we can.

This is me chiming in 😄 

As noted in #373 our main use case is also K8s, however it would be great to have this possible.

With multiple instances it is possible to update the config and start a new `cloudflared` instance of the same tunnel and then stop the old one however this is not simple to implement without manual intervention.

Having a main `controller` process that starts a new `cloudflared` instances on config change and signals the old instance to stop could work ok and avoid complex changes to the existing code.

**Comment by suhasagasthya** [comment]
Hey, was curious on this feature and we are in need of this as well, where we are constantly adding new ingress rules for customer traffic and the tunnel dropping connections each time is a pain. How are we going with this? Any new updates would really help.

**Comment by nmldiegues** [comment]
Hello,

The way we recommend is to rely on multiple cloudflared instances per tunnel: https://blog.cloudflare.com/highly-available-and-highly-scalable-cloudflare-tunnels/ (or other links such as https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/deploy-cloudflared-replicas  and https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s)

You can ramp up a new instance with a new config and then ramp down the old instance, effectively allowing to switch config (or even update cloudflared version) without losing requests.

This does not help with long lived connections, however. That's something we would need to tackle intra-cloudflared.

**Comment by morremeyer** [comment]
Can this be re-opened please? We do use multiple cloudflared instances in our Kubernetes clusters, but we do deploy the configuration separatly from the cloudflared pods. This allows for easier use in our platform, but currently requires regular manual restarts of the `Deployment`.

**Comment by maxpain** [comment]
Please reopen this

**Comment by arunesh90** [comment]
I hope this gets re-considered. It's pretty absurd to assume that everyone should just run multiple cloudflared instances of the same tunnel to be able to gracefully rollout new config changes.

It would be great if this feature request could be reconsidered or that at least this feature request could be re-opened for futher discussion, as it's clear that people need such a feature. @jcsf @lmpn

**Comment by robsoncombr** [comment]
+1
