### ISSUE TITLE
SRV Resolution of dynamic ports served by Consul DNS Discovery.

### ISSUE THREAD

**Issue by LKNSI** [cloudflare/cloudflared#305]
Feel free to close this issue if already documented, however I was unable to find mentions of it in past open/closed issues.

Task: Currently trying to reduce network complexity by removing HAProxy from the edge nodes (reducing the need for a HAProxy server to do SRV resolution from Argo.)

Problem: SRV resolution within cloudflared is working as intended i.e. (_<node>-ca._tcp.service.consu  -> 10.x.x.x) resolves to a Private Address on the VPC. However we're at a loss on how to instruct cloudflared to use the port numbers contained within the SRV records.  Currently cloudflared will use port 80 when it is not described within the config file, leading to the a failure to connect (no surprise).

Would this be something you might find useful to either comment on or implement if not already?

Pseudo Suggestion (HAProxy Inspired): 
```
url: _endpoint-ca._tcp.service.consul SRV
```

**Comment by LKNSI** [comment]
I see

```golang
func resolveSRVToTCP(srv *net.SRV) ([]*net.TCPAddr, error) {
	ips, err := netLookupIP(srv.Target)
	if err != nil {
		return nil, errors.Wrapf(err, "Couldn't resolve SRV record %v", srv)
	}
	if len(ips) == 0 {
		return nil, fmt.Errorf("SRV record %v had no IPs", srv)
	}
	addrs := make([]*net.TCPAddr, len(ips))
	for i, ip := range ips {
		addrs[i] = &net.TCPAddr{IP: ip, Port: int(srv.Port)}
	}
	return addrs, nil
}
```

in [discovery.go](https://github.com/cloudflare/cloudflared/blob/7420439ed2a9b13cef7ae7548a093ec3af468e80/edgediscovery/allregions/discovery.go#L74) here, and I can loosely assume this is supported - am I right in saying that?

**Comment by LKNSI** [comment]
Just to ensure this isn't wasting developers time - does this feature already exist?

**Comment by sodabrew** [comment]
That method is used exclusively for cloudflared to find the origin severs. It is not used to find the local servers inside your network.

https://github.com/cloudflare/cloudflared/blob/a34604cfc7b1feaf3c87d8c2cd5bf752ac1ebf4d/edgediscovery/allregions/discovery.go#L14-L25

**Comment by fraserdarwent** [comment]
This would be a useful feature to see
