### ISSUE TITLE
tunnel list should optionally list cloudflared version number and protocol

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#307]
tunnel list should optionally list cloudflared version number and protocol
It would be useful to keep track of this information across dozens of running instances

**Comment by adamchalmers** [comment]
Are you asking for it to list the version/protocol of 

1. The cloudflared you executed the "tunnel list" command on
2. The cloudflared running each tunnel in the list?

**Comment by vidarak** [comment]
Option 2. Need a way to find servers running outdated versions or check if config need to be updated to specify http2 protocol.

**Comment by vidarak** [comment]
It is also a bit strange that new named tunnels do not show up on dash.cloudflare.com's Traffik>Argo Tunnel list. After switching to named tunnels this list is now empty for me.

**Comment by adamchalmers** [comment]
Yeah, we're building a new UI soon. I built that Traffic UI in my first few weeks at Cloudflare, but the new one will be part of the Teams dash (https://dash.teams.cloudflare.com). 

I like the idea of building a more connection-focused {{tunnel list}} UI with more detailed information about connections. I'll look into that.

**Comment by adamchalmers** [comment]
OK, we've drawn up a plan for this (internal ref: TUN-3993). It's going to look something like this. What do you think?

```
$ cloudflared tunnel list
 
ID                                   NAME       CREATED              CLOUDFLAREDS RUNNING
d42f8847-d518-4fa7-af85-811b31952eff my-tunnel  2021-01-08T16:11:06Z 2           
 
$ cloudflared tunnel list --connections my-tunnel             
 
CLOUDFLARED CLIENT ID                 LOCAL IP        RUN AT                OS/ARCHITECTURE  CLOUDFLARED VERSION  CONNECTIONS
ad4b6cbc-5cae-45cc-b6d1-297f68fdbdc6  111.123.101.1   2021-01-08T16:11:06Z  Windows 10       2021.2.5             2xDFW, 2xSEA
ed05f81d-a970-4e07-a43e-95408c48ceef  111.123.101.2   2021-01-08T16:11:07Z  Windows 10       2021.2.4             2xDFW, 2xDOG
```

**Comment by vidarak** [comment]
Looks nice. Just missing protocol column and maybe a column with statistics about how many reconnects the connection/tunnel has had in the past week or so to track unreliable connections?

**Comment by adamchalmers** [comment]
Reconnects go through a different flow, I'd say it's unlikely we add that to the UI until later. Maybe when we build the actual web dashboard. 

By protocol, you mean h2mux/http2, the protocol used to communicate with the edge? Unlikely we would add that as most users don't need to know about it. We will eventually release a version with only http2 and no h2mux.

**Comment by abelinkinbio** [comment]
Hi there - new Tunnel PM here 👋 

Exciting update on this one 🚀

You can find the new Tunnel UI by visiting the Cloudflare for Teams [dashboard](https://dash.teams.cloudflare.com/access/tunnels).
