### ISSUE TITLE
2021.2.1 version is logged as "DEV" to log file

### ISSUE THREAD

**Issue by vidarak** [cloudflare/cloudflared#308]
Log file entry:
{"level":"info","time":"2021-02-06T23:48:48Z","message":"Version DEV"}

**Comment by adamchalmers** [comment]
Thanks for the report. This will be fixed in the next release (ticket ID is TUN-3878)

**Comment by adamchalmers** [comment]
Fixed in 2021.2.2, thanks for reporting.
