### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by morpig** [cloudflare/cloudflared#309]
Hi,

Last couple of days I've been experiencing random disconnects from my cloudflared clients (running access tcp). I'm running two cloudflared clients in different servers (1 in aws, 1 bare metal) in different countries. Both connects to different CF colos, and disconnects at the same time.

No error is thrown from server side, all normal. I'm running 2020.12.0 for server side, but this also occurs in 2021.2.1

server side:
```
INFO[2021-02-07T16:32:02Z] Starting tunnel xxx
INFO[2021-02-07T16:32:02Z] Version 2020.12.0
INFO[2021-02-07T16:32:02Z] GOOS: linux, GOVersion: go1.15.6, GoArch: amd64
INFO[2021-02-07T16:32:02Z] Environment variables map[proxy-dns-upstream:https://1.1.1.1/dns-query, https://1.0.0.1/dns-query url:tcp://localhost:8081]
INFO[2021-02-07T16:32:02Z] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
INFO[2021-02-07T16:32:02Z] Initial protocol h2mux
INFO[2021-02-07T16:32:02Z] Starting metrics server on 127.0.0.1:46235/metrics
INFO[2021-02-07T16:32:02Z] Connection 0 registered with CDG using ID xxxx
INFO[2021-02-07T16:32:03Z] Connection 1 registered with CDG using ID xxxx
INFO[2021-02-07T16:32:04Z] Connection 2 registered with AMS using ID xxxx
INFO[2021-02-07T16:32:05Z] Connection 3 registered with AMS using ID xxxx
```

client side (running 2021.2.1):
```
{"level":"error","error":"websocket: bad handshake","originURL":"https://xxx","time":"2021-02-07T17:42:04Z","message":"failed to connect to origin"}
{"level":"error","error":"websocket: bad handshake","originURL":"https://xxx","time":"2021-02-07T17:42:04Z","message":"failed to connect to origin"}
{"level":"error","error":"websocket: bad handshake","originURL":"https://xxx","time":"2021-02-07T17:42:04Z","message":"failed to connect to origin"}
{"level":"error","error":"websocket: bad handshake","originURL":"https://xxx","time":"2021-02-07T17:42:04Z","message":"failed to connect to origin"}
{"level":"error","error":"websocket: bad handshake","originURL":"https://xxx","time":"2021-02-07T17:42:04Z","message":"failed to connect to origin"}
```

I double-checked the connection from client side to cf's colo, no packet loss or route changes. same thing for the server side too.

any solutions? thanks!

**Comment by vidarak** [comment]
You should not use 2020.12.0 as it has (re-)connection issues.

**Comment by morpig** [comment]
> You should not use 2020.12.0 as it has (re-)connection issues.

Hi, yes i noticed about that issue, and have upgraded to 2021.2.1. Unfortunately, it still occurs to me. I don't think it's a (re-)connection issue, as the cloudflared tunnel doesn't show any errors or disconnects from the CF POP.

Errors usually thrown when there are connection issues:
```
2021-02-09T02:19:10Z ERR Serve tunnel error error="read tcp xxx:33560->198.41.192.13:7844: read: connection reset by peer" connIndex=2
2021-02-09T02:19:10Z INF Retrying connection in 5s seconds error="read tcp xxx:33560->198.41.192.13:7844: read: connection reset by peer" connIndex=2
2021-02-09T02:19:11Z ERR Connection terminated error="read tcp xxx:33560->198.41.192.13:7844: read: connection reset by peer" connIndex=2
```

In this case there are no errors/disconnects, traffic just automatically disappear randomly, and will reconnect in 2-5 seconds.

**Comment by morpig** [comment]
closing this issue — looks like there's an connection issue between the cloudflared tunnel and my tcp application, which leads to random drops.
