### ISSUE TITLE
"About" link is outdated on GitHub

### ISSUE THREAD

**Issue by joel0** [cloudflare/cloudflared#310]
Visit https://github.com/cloudflare/cloudflared and look at the right side of the page in the "About" section.  The link `https://developers.cloudflare.com/argo-tunnel/` goes to the Argo Tunnel docs with a warning header that they will be deleted soon.

**Comment by TownLake** [comment]
Thanks for the flag; fixing here:
https://github.com/cloudflare/cloudflared/pull/311
