### ISSUE TITLE
CentOS 7 systemd cloudflared.service which config.yml

### ISSUE THREAD

**Issue by centminmod** [cloudflare/cloudflared#313]
I installed cloudflared service on CentOS 7 and it created /etc/systemd/system/cloudflared.service

```
[Unit]
Description=Argo Tunnel
After=network.target

[Service]
TimeoutStartSec=0
Type=notify
ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml --no-autoupdate tunnel run
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
The ExecStart uses config file at `--config /etc/cloudflared/config.yml`

But why does service status read the `/root/.cloudflared/config.yml` ?

The `systemctl status cloudflared` reads

```
INF Settings: map[autoupdate-freq:24h0m0s config:/root/.cloudflared/config.yml
```

**Comment by TownLake** [comment]
Can you share the command that you ran to install the service?

`sudo cloudflared --config cloudflared-config.yaml service install`

should install it using the non-standard config file location, and then it does look like you ran the enable command to generate that unit file.

`sudo systemctl enable cloudflared`

Could you try:

`sudo systemctl reload cloudflared.service`

to pick up the latest configuration and see if that works?

**Comment by centminmod** [comment]
Sorry for late reply, I installed cloudflared and service using my guide at https://blog.centminmod.com/2021/02/09/2250/how-to-setup-cloudflare-argo-tunnel-on-centos-7/

```bash
cloudflared service install
service cloudflared start
chkconfig cloudflared on
```

but looks like the systemd service does read expected config file now `/etc/cloudflared/config.yml`

```
INF Settings: map[autoupdate-freq:24h0m0s config:/etc/cloudflared/config.yml 
```

so looks like not an issue with latest cloudflared service install
