### ISSUE TITLE
Cloudflared version DEV on cloudflared -v

### ISSUE THREAD

**Issue by Toregev** [cloudflare/cloudflared#314]
For the last couple of releases if I go to command line and check what version of cloudflared is currently installed using "cloudflared -v" I get the response "cloudflared version DEV (built unknown)" where as previously it would give the current version number along with the date and time of publish. I believe this is something that started with the release of version 2021.2.0 and is still there in the current version.

**Comment by nmldiegues** [comment]
Hello @Toregev ,

Thank you for reporting this.
It should have already been fixed in the latest release:
```
./cloudflared --version
cloudflared version 2021.2.2 (built 2021-02-10-1808 UTC)
```
