### ISSUE TITLE
Allow for proxy configuration with websockets in arbitrary TCP connections

### ISSUE THREAD

**Issue by jmonson** [cloudflare/cloudflared#317]
We are trying to run `cloudflared access tcp ...` behind a squid proxy. However, the dialer doesn't support proxy. Meaning, we can't set `https_proxy` env. For example:

`env https_proxy=http://myproxy:12345 ./cloudflared access tcp ...`

Fails as the `https_proxy` isn't respected.

**Comment by cThrice** [comment]
LGTM :)

We have validated this fix.  Additionally this function was already added to different parts of cloudflared ( such as the tunnel dns and ingress )

https://github.com/cloudflare/cloudflared/search?q=ProxyFromEnvironment&type=

**Comment by TownLake** [comment]
This has been merged and released in 2021.2.3 - thanks for the feedback and the PR!

**Comment by romeroyonatan** [comment]
Hello,
This fix is not working with the latest version (2021.2.5).

It was working until 2021.2.4

**Comment by nmldiegues** [comment]
Thanks for reporting this @romeroyonatan , we'll get it fixed

**Comment by nmldiegues** [comment]
This was fixed and will be available again in the next release.

**Comment by romeroyonatan** [comment]
Thank you very much

**Comment by nmldiegues** [comment]
This was released as part of 2021.3.1

**Comment by mcartmel** [comment]
Trying to get this to work in Windows and the http_proxy environment variable doesn't seem to be used. Should it work for Windows as well?

I'm just using:
`set http_proxy=http://proxy_ip:port`
