### ISSUE TITLE
Allow connections to backends without SSL verification

### ISSUE THREAD

**Issue by daviesalex** [cloudflare/cloudflared#32]
While far from ideal, it is sometimes useful to tunnel to internal devices with certificates that you do not control. A specific option to skip SSL verification would permit bypassing errors like this:

`ERRO[0054] HTTP request error                            connectionID=2 error="x509: certificate has expired or is not yet valid"`

**Comment by rishabh-bector** [comment]
Can you specify the url that cloudflared should connect to as http rather than https?

`cloudflared --hostname www.example.com http://localhost:8080`

In this case, cloudflared will talk to your origin using http. Otherwise, it will be using https with tls/ssl.

**Comment by daviesalex** [comment]
Unfortunately there exist a class of (proprietary) systems/appliances that run HTTPS only, but use rubbish crypto that is difficult to change.  That is the use case at least for us.

**Comment by rishabh-bector** [comment]
@daviesalex I just updated our ArgoTunnel docs with the `--origin-ca-pool` flag: 

https://developers.cloudflare.com/argo-tunnel/reference/arguments/#origin-ca-pool

This way, you should be able to give cloudflared your own certificate and it will be trusted even if the cert is not signed by us.

**Comment by daviesalex** [comment]
Brilliant, thank you!
