### ISSUE TITLE
TUN-3924: Removed db-connect command

### ISSUE THREAD

**Issue by jdanyow** [cloudflare/cloudflared#321]
https://github.com/cloudflare/cloudflared/commit/a8ae6de213f88b22047f0ca6275751eb8bc00a85 removes the db-connect command. Any chance it can stick around for a bit longer?

>We aren’t adding new features or fixing any bugs with db-connect, but we plan on keeping it in cloudflared until we launch “proper” support for database connections from Workers.
https://community.cloudflare.com/t/future-of-db-connect-sql-with-workers/196851

**Comment by TownLake** [comment]
Hey Jeremy - thanks for the feedback. Could you help us understand how you're using it?

We're planning to release a significant update to Argo Tunnel this week where a single, more capable model will subsume some of the non-HTTP use cases. The db-connect beta feature added complexity and issues that stopped us from releasing it to GA; we expect those problems to be resolved with this new architecture.

If you can walk us through how you're using it today we can take a look and see if that theory holds with your use case.

cc @Electroid as well.

**Comment by jdanyow** [comment]
I’m using db-connect to query an azure sql db from a cloudflare worker.

**Comment by TownLake** [comment]
Ah, makes sense. That’s not the target use case of what is being launched this week.

The next release of `cloudflared` will introduce a breaking change for that use case, but we failed to communicate the db-connect deprecation widely enough when we added the notice into the CLI last year and we did not coordinate on our side. That’s our mistake.

We’re going to take care of the following:

Versions that predate this upcoming release will continue to be available on GitHub with the db-connect functionality. Those will not be removed and can continue to be used to support db-connect.
We’ll update the db-connect repo with notes about version compatibility with `cloudflared`. The db-connect repo will also stay available.
We’re exploring moving it into its own repository to provide a webservice to perform DB operations which could be exposed with Argo Tunnel until better TCP support is introduced in Workers.

The Workers team is still focused on a better solution for SQL connectivity long-term.

Happy to answer any questions about sticking to the most recent version. I apologize for the lack of communication about db-connect and its status in `cloudflared` over the last year. That lack of communication is my fault and I’ll make sure we improve that on our side.

**Comment by jdanyow** [comment]
No worries, great news that I'll be able to stick to a past version of cloudflared or migrate to the standalone service. Really my fault for using the db-connect alpha, just seemed like that's where things were heading. It's awesome to hear better TCP support is coming to workers. I don't suppose there are any details you can share with respect to the estimated timeline?

**Comment by TownLake** [comment]
Glad to hear it, thanks for the response. Tagging @Electroid and @greg-mckeon here who can comment on timeline or reach out about feedback. Will close the issue for now with the original question answered.
