### ISSUE TITLE
TLS handshake with edge error: x509: certificate has expired

### ISSUE THREAD

**Issue by stevenanthonyrevo** [cloudflare/cloudflared#322]
Would be able to explain this error? @adamchalmers 

I received the error after spinning up another tunnel using the same login session however different domain. 

Does `x509: certificate has expired` mean I need to reload my PEM file. 

Thanks, cheers!

**Comment by adamchalmers** [comment]
The cert.pem file is limited to a single zone. Try running "cloudflared login" again and choosing the different zone. 

To use multiple certificates, give them different names e.g. foo.com.cert.pem and bar.org.cert.pem and then use the --origin-cert flag to specify the appropriate cert.

**Comment by nmldiegues** [comment]
@stevenanthonyrevo  this is currently being investigated as noted in https://www.cloudflarestatus.com/

**Comment by stevenanthonyrevo** [comment]
Thanks for the quick reply! @adamchalmers 

I tried reinstalling cert and renaming with --origin-cert flag but the error was still there. 

I'll wait for further resolution on the Cloudflare side. Thanks, @nmldiegues for letting me know about the service interruption.

**Comment by nmldiegues** [comment]
Good morning @stevenanthonyrevo 

The incident was updated: https://www.cloudflarestatus.com/incidents/jvydcx604vv9
The situation was fixed a few hours ago.

However, clients with version 2019.11.2 or older must update --- I don't think that's your situation, but I prefer it to be here for others to know about it.
We highly recommend pulling the latest 2021.2.2.

Also a friendly reminder about the lack of support for versions older than 2020.5.1 as per https://github.com/cloudflare/cloudflared/blob/master/README.md#deprecated-versions
