### ISSUE TITLE
Add a way to delete routing rules from the CLI (or via API)

### ISSUE THREAD

**Issue by victorhooi** [cloudflare/cloudflared#328]
I can use cloudflared to create new routing rules:

```
cloudflared tunnel route dns <UUID or NAME> www.app.com
```

However, there doesn't seem to be any way to actually delete a given routing rule from the CLI once its created.

Would it be possible to add this ability? Or is there any API endpoint we can hit to script this currently?

**Comment by adamchalmers** [comment]
You can use the existing [Delete a DNS Record](https://api.cloudflare.com/#dns-records-for-a-zone-delete-dns-record) endpoint using the cloudflare HTTP API, or you can delete the DNS records in the dashboard, but for now cloudflared doesn't support deleting your DNS records from the command line.

**Comment by ThickDrinkLots** [comment]
Hi!
I am also interested in the CLI-way to delete routing rules. I found that in 2021.1.0 release notes stands:

> - 2020-12-29 TUN-3689: Delete routes via cloudflared CLI

(via https://raw.githubusercontent.com/cloudflare/cloudflared/master/RELEASE_NOTES)

Unfortunately I can't find any documented way how to do it.
I'll be thankful for tips.

**Comment by abelinkinbio** [comment]
It looks like this issue has been handled by the community. I'll close this ticket out, but feel free to reach back out with any other questions.
