### ISSUE TITLE
Auto update service is not enabled by default

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflared#33]
Hi! After installing cloudflared as a service two systemd files related to the auto update function are created, "cloudflared-update.service" and "cloudflared-update.timer". The intended behavior here is for the user to enable them manually, if the auto update function is desired, or it should be on by default?

**Comment by pguizeline** [comment]
Hi! I can confirm this behavior, I've installed cloudflared on Debian 9 using the x64 .deb provided and created the following:

cloudflared.service
`[Unit]
Description=cloudflared DNS over HTTPS proxy
After=syslog.target network-online.target

[Service]
Type=simple
User=cloudflared
EnvironmentFile=/etc/cloudflared/config.yml
ExecStart=/usr/local/bin/cloudflared
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target` 

config.yml
`proxy-dns: true
proxy-dns-upstream:
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
proxy-dns-port: 5053`

The binary is not auto updating every 24h, I have to manually run `cloudflared update` to actually update it.

What I did as a sloppy workaround is that I've created a cronjob to run the command every month. Maybe I'm missing something? Thanks for any help!

**Comment by analytically** [comment]
@rishabh-bector it's not enabled by default, without any config I see `no-autoupdate=true` in the log.

**Comment by daltoniam** [comment]
To clarify about the auto updater, it is set to run by default when installed as a service that isn't on Windows. It also is disabled when running interactively from a shell or was installed by a package manager. I'll go ahead and close this for now and if there is a specific feature request please open an issue or PR. Thanks!

**Comment by hkeide** [comment]
@daltoniam Does installing from a .deb file using dpkg count as using a package manager?

**Comment by daltoniam** [comment]
@hkeide It does. If installed from a package repo the auto updater will be disabled by default. The exception to this is packages installed from https://developers.cloudflare.com/argo-tunnel/downloads do have the auto updater enabled by default.
