### ISSUE TITLE
2021.3.1 New behavior 

### ISSUE THREAD

**Issue by schack** [cloudflare/cloudflared#337]
I CLI, I noticed the presence of a .cloudflared/config.yml takes precedence over any command-line arguments.
Is that intended behavior? 
In my case:
cloudflared tunnel list stopped working (displayed none of my tunnels)

**Comment by abelinkinbio** [comment]
Hi there - new Tunnel PM here 👋

Thank you for reporting this issue. Would you be able to provide us with the command sequence and output you receive?

**Comment by schack** [comment]
I think it was fixed many versions ago. I reported it back in March.
