### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by v0l** [cloudflare/cloudflared#34]
Hi, I am running cloudflared on my Synology DS1817+ so that i can access my CCTV at home (im behind CGNAT), the live playback of video is passed over websocket along with other config. 

Is there a plan to support websockets?

**Comment by skhaz** [comment]
+1

**Comment by dknecht** [comment]
It’s coming soon

**Comment by sssilver** [comment]
Websocket support has been out for a while!

Closing the issue.
