### ISSUE TITLE
cloudflared 2021.3.2 (and 2021.3.1) breaks short-lived cert config

### ISSUE THREAD

**Issue by ideologysec** [cloudflare/cloudflared#340]
```bash
$ cloudflared --version
$ cloudflared access ssh-config --short-lived-cert --hostname node1-ssh.example.com
Add to your /Users/user/.ssh/config:

Host node1-ssh.example.com
  ProxyCommand bash -c '/usr/local/bin/cloudflared access ssh-gen --hostname %h; ssh -tt %r@cfpipe-node1-ssh.example.com >&2 <&1'

Host cfpipe-node1-ssh.example.com
  HostName node1-ssh.example.com
  ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
  IdentityFile ~/.cloudflared/node1-ssh.example.com-cf_key
  CertificateFile ~/.cloudflared/node1-ssh.example.com-cf_key-cert.pub

$ ls -la /Users/user/.cloudflared
-rw-------   1 user  staff   227 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key
-rw-------   1 user  staff   797 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key-cert.pub
-rw-------   1 user  staff   161 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key.pub
-rw-------   1 user  staff   874 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-token
-rw-------   1 user  staff  1529 Mar 24 16:22 example.cloudflareaccess.com-org-token

$ ssh node1-ssh.example.com
no such identity: /Users/user/.cloudflared/node1-ssh.example.com-cf_key: No such file or directory
user@node1-ssh.example.com: Permission denied (publickey).
kex_exchange_identification: Connection closed by remote host
```

Downloaded cloudflared-2021.2.5, and when connecting it generated the keys properly, with no random UUID strings in the filenames.

Unless I'm missing something, this makes it very hard to construct ssh config blocks with wildcards, since the uuid is unique per host and endpoint.

**Comment by mahdiamer** [comment]
> ```shell
> $ cloudflared --version
> $ cloudflared access ssh-config --short-lived-cert --hostname node1-ssh.example.com
> Add to your /Users/user/.ssh/config:
> 
> Host node1-ssh.example.com
>   ProxyCommand bash -c '/usr/local/bin/cloudflared access ssh-gen --hostname %h; ssh -tt %r@cfpipe-node1-ssh.example.com >&2 <&1'
> 
> Host cfpipe-node1-ssh.example.com
>   HostName node1-ssh.example.com
>   ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
>   IdentityFile ~/.cloudflared/node1-ssh.example.com-cf_key
>   CertificateFile ~/.cloudflared/node1-ssh.example.com-cf_key-cert.pub
> 
> $ ls -la /Users/user/.cloudflared
> -rw-------   1 user  staff   227 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key
> -rw-------   1 user  staff   797 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key-cert.pub
> -rw-------   1 user  staff   161 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-cf_key.pub
> -rw-------   1 user  staff   874 Mar 24 16:22 node1-ssh.example.com-bb3a5a62d00dd0976b744d3aa9df6c5ed404c388a54008ffa527dce11ab7ef4e-token
> -rw-------   1 user  staff  1529 Mar 24 16:22 example.cloudflareaccess.com-org-token
> 
> $ ssh node1-ssh.example.com
> no such identity: /Users/user/.cloudflared/node1-ssh.example.com-cf_key: No such file or directory
> user@node1-ssh.example.com: Permission denied (publickey).
> kex_exchange_identification: Connection closed by remote host
> ```
> 
> Downloaded cloudflared-2021.2.5, and when connecting it generated the keys properly, with no random UUID strings in the filenames.
> 
> Unless I'm missing something, this makes it very hard to construct ssh config blocks with wildcards, since the uuid is unique per host and endpoint.

**Comment by Michael9127** [comment]
Thanks for the bug report, ill start looking at this.

**Comment by Michael9127** [comment]
A fix has been merged and released in version 2021.3.3.

**Comment by ideologysec** [comment]
Looks great, but, there's no Darwin/macOS releases for 3.3 or 3.4. Did something break in the build chain? (can't confirm it's fixed for all my users since most of them are on macOS); we're still bound to 2.5 until a new macOS binary actually gets built.

**Comment by nmldiegues** [comment]
> Looks great, but, there's no Darwin/macOS releases for 3.3 or 3.4. Did something break in the build chain? (can't confirm it's fixed for all my users since most of them are on macOS); we're still bound to 2.5 until a new macOS binary actually gets built.

I've commented on https://github.com/cloudflare/cloudflared/issues/342
We're going to get the mac release fixed soon.

**Comment by nmldiegues** [comment]
Release 2021.3.5 fixed the macOS binaries that were missing.
