### ISSUE TITLE
no Darwin releases for 2021.3.3 or 2021.3.4

### ISSUE THREAD

**Issue by ideologysec** [cloudflare/cloudflared#342]
Like the title says - no binaries appear to have been built for 3.3 or 3.4. Is this intentional, does it take longer to build for darwin due to the new codesigning in the binary, or?

**Comment by nmldiegues** [comment]
Hello,

There was an internal problem with the build causing mac binaries to not go out. We're on top of it.
Thanks for reporting

**Comment by ideologysec** [comment]
Awesome, thanks. 🙏

**Comment by nmldiegues** [comment]
Release 2021.3.5 fixed the macOS binaries that were missing.
