### ISSUE TITLE
Is WARP coming anytime soon?

### ISSUE THREAD

**Issue by lfv89** [cloudflare/cloudflared#343]
I'm on a Linux machine using `cloudflared` as my agent to Cloudflare Gateway.

My understanding is that WARP will eventually come co `cloudflared`, is only a matter of "when", correct?

**Comment by ipostelnik** [comment]
See https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel that describes how to connect private networks to allow WARP clients to access them directly.

**Comment by lfv89** [comment]
If I understood correctly this guide doesn't show how to setup WARP on Linux.

**Comment by ipostelnik** [comment]
I can't speak about when teams client may be available on Linux. What is the use case where you need it?

**Comment by keatontaylor** [comment]
May or may not be related to the original post, but I'd be curious if the end goal for cloudflared is to make the tunnel between the cloudflare edge and the cloudflared process effectively be powered by warp/wiregaurd vs. the current implantation. 

Then again a wireguard tunnel solely for proxying traffic might be a little overkill if the http/2 gRPC based proxy is more compatible with the cloudflare edge stack already. You probably can't say one way or another but I am certainly curious to see what the future holds. :)

**Comment by TownLake** [comment]
WARP is available on Linux [today](https://developers.cloudflare.com/warp-client/setting-up/linux), but it lacks the functionality to enroll in Gateway or participate in the private routing features with Cloudflare Tunnel. We'll be adding that functionality later this summer / early this fall.
