### ISSUE TITLE
Unable to establish connection. error="already connected to this server, trying another address" 

### ISSUE THREAD

**Issue by dorianmariefr** [cloudflare/cloudflared#344]
Tried on latest version and built from master:

```
./cloudflared tunnel --loglevel=debug run --url localhost:3000 dev
```

```
2021-03-28T00:40:08Z ERR Unable to establish connection. error="already connected to this server, trying another address" connIndex=3
2021-03-28T00:40:08Z ERR Connection terminated error="already connected to this server, trying another address" connIndex=3
```

full logs: https://gist.github.com/dorianmariefr/db02394e42bb2aeddbef8fcda5d60609

**Comment by dorianmariefr** [comment]
Also seems like it's creating multiple API keys, I had like 6 and removed them and now 3

**Comment by nmldiegues** [comment]
Hello @dorianmariefr ,

From the logs you can see that other 3 connections were established correctly:
> 2021-03-28T00:41:50Z INF Connection ae7ff38f-9faa-4cf9-9df1-c31a1b329f36 registered connIndex=0 location=AMS
> 2021-03-28T00:41:50Z INF Connection 50be3a3d-0923-430b-9105-f0cbeb187307 registered connIndex=1 location=CDG
> 2021-03-28T00:41:51Z INF Connection d5a6e383-63f6-4419-8697-5b286f6bb88d registered connIndex=2 location=AMS
2021-03-28T00:41:51Z DBG rpcconnect: rx error: context canceled

So that alone means that your origin should be reachable via Argo Tunnel. Are you experiencing any problem as a user? Or just concerned about that last log with the error?

That last error is not a big deal: the connection should retry and eventually succeed connecting to another server. We reject that the same cloudflared can connect twice or more to the same server because that defeats the purpose of multiple connections (which is resilience/high availability).


> Also seems like it's creating multiple API keys, I had like 6 and removed them and now 3

What do you mean with API keys? How are you observing this?

**Comment by dorianmariefr** [comment]
Thanks for your reply.

It was not working (when I had the dev.socializus.app route) and now to test it again I try to create a DNS entry:

```
~/s/c/cloudflared> cloudflared tunnel route dns dev dev.socializus.app
Failed to add route: code: 1000, reason: Internal server error
```

> What do you mean with API keys? How are you observing this?

https://dash.cloudflare.com/profile/api-tokens it had a lot of tokens, I deleted them and now back to 3 (all Argos related)

**Comment by dorianmariefr** [comment]
Nervemind, the internal server error was because I already had a DNS record

And it's working fine

**Comment by dorianmariefr** [comment]
Now my log is just errors. It works but I don't think I should have that many errors

<img width="721" alt="Screenshot 2021-03-29 at 01 17 44" src="https://user-images.githubusercontent.com/58794487/112771528-9b190100-902c-11eb-924d-3749aaa88db9.png">

**Comment by 1219099256** [comment]
> Now my log is just errors. It works but I don't think I should have that many errors
> 
> <img alt="Screenshot 2021-03-29 at 01 17 44" width="721" src="https://user-images.githubusercontent.com/58794487/112771528-9b190100-902c-11eb-924d-3749aaa88db9.png">

I’m using warp and this happens

**Comment by nmldiegues** [comment]
That is expected:  WARP establishes a long lived connection to Cloudflare edge, and all your traffic goes through it.

That's at odds with Tunnel, that tries to establish 2 different connections to 2 different Cloudflare regions. In each of those, they are now going over the same WARP connection, which defeats the purpose of multiple Tunnel connections (which is high availability).

It is not common/expected that a machine running Tunnel (usually to serve origins) is also running WARP (usually to protect users egressing to the Internet).

**Comment by 1219099256** [comment]
> That is expected:  WARP establishes a long lived connection to Cloudflare edge, and all your traffic goes through it.
> 
> That's at odds with Tunnel, that tries to establish 2 different connections to 2 different Cloudflare regions. In each of those, they are now going over the same WARP connection, which defeats the purpose of multiple Tunnel connections (which is high availability).
> 
> It is not common/expected that a machine running Tunnel (usually to serve origins) is also running WARP (usually to protect users egressing to the Internet).

I got it, thanks for your reply

**Comment by rany2** [comment]
> That's at odds with Tunnel, that tries to establish 2 different connections to 2 different Cloudflare regions. In each of those, they are now going over the same WARP connection, which defeats the purpose of multiple Tunnel connections (which is high availability).

Is it possible to get cloudflared to use only one connect then? I tried searching for the config option but wasn't able to

**Comment by rany2** [comment]
I had the time to read the code and I think you'd do it by doing `cloudflared tunnel --ha-connections 1 run` to set it to connect to one server. This seems correct to me
