### ISSUE TITLE
Is there any one-liner argo tunnel CLI being introduced to replace the "legacy mode" `cloudflared tunnel` command?

### ISSUE THREAD

**Issue by pirate** [cloudflare/cloudflared#349]
We're starting to see some messages in our logs saying our one-liner cloudflared tunnels are being deprecated.
```logs
2021-04-05T18:45:36Z INF You are running a Tunnel in legacy mode which will be deprecated. Please use the documentation below to switch to pre-created Tunnels for improved stability and management.
```

This is worrying, as we believe one of the main selling points of argo (and the reason we switched to it in the first place) is that it allows for declarative one-liner docker-compose setups for ingress, with no state or config to manage.

Take this `docker-compose.yml` file for example:

```yaml
version: '3'

services:
    someapp:
        image: python:3.9-alpine
        command: python3 -m http.server --directory /usr/src/app --bind 0.0.0.0 8000
        volumes:
            - ./site:/usr/src/app:ro
    
    argo:
        image: cloudflare/cloudflared
        command: tunnel --no-autoupdate --retries 8 --hostname someapp.example.com --url http://someapp:8000
        volumes:
            - ./argo_cert.pem:/etc/cloudflared/cert.pem:ro
```

This is a beautiful, minimalist way to handle ingress with cloudflared in docker, and all it requires is that the user has an argo cert from https://www.cloudflare.com/a/warp present at `./argo_cert.pem`. No config files to manage, no caches to keep track of, no external commands to run to set anything up, and the entire app is completely stateless. If you destroy and recreate the containers or move the project to a new machine there is nothing to worry about, everything is described by the docker-compose file alone.

We've been using and recommending this setup to people for years, and it's been successfully serving millions of hits in production across dozens of projects. We'd hate to have to start managing config files or having to run multiple commands to set up argo state, at that point we may as well switch back to using nginx or caddy for ingress.

So our question is this: moving forward, is there any one-liner method to start an argo ingress tunnel without having to pre-create the tunnel or manage config files?

**Comment by adamchalmers** [comment]
Hi, yes, one-liner mode (we call it ad-hoc mode internally) still works with the new named tunnel system. The only thing you'll need to change is you'll supply a `--name` argument. You can run your named tunnels in one line, like this:

```bash
$ cloudflared tunnel --name pirate --url http://localhost:888 --hostname pirate.adamchalmers.com
```

**Comment by nmldiegues** [comment]
Besides what @adamchalmers  has pointed out, I'd like to point out that the key weaknesses for legacy tunnels (that are not `tunnel create`-ed _a priori_) are explained in https://blog.cloudflare.com/argo-tunnels-that-live-forever/

**Comment by pirate** [comment]
Great, that's a relief, thanks for the super quick reply. Are there plans for it to be documented on https://developers.cloudflare.com/docs? (side-note, I can't find the argo docs anywhere from that page, shouldn't there be a section called argo? or at least a search box)

is there any reason not to have `--name` default to the hostname if it's not passed? Otherwise it seems in the common case 99% of the time we'll be setting `--name someapp.example.com`, which feels a bit redundant next to `--hostname someapp.example.com`.

**Comment by adamchalmers** [comment]
Docs are now located at https://developers.cloudflare.com/cloudflare-one/connections/connect-apps unfortunately the current docs assume people are using Argo Tunnel as part of their Cloudflare for Teams setup, rather than a "beautiful, minimal way to handle ingress". We're also planning to rename Argo Tunnels to "Cloudflare Tunnels" so there's a bit of housekeeping to be done there.

We might make --name default to hostname in the future, but that would migrate all users from classic tunnels to named tunnels. We've still got a few tasks to finish before we're ready to migrate all users over. But it's being considered at some point in the future, once we make sure that every workflow with classic tunnels is easy with named tunnels.

**Comment by pirate** [comment]
Got it, thanks.

![image](https://user-images.githubusercontent.com/511499/113628667-387ac300-9633-11eb-8f8d-a7b765050887.png)

*Right now it only shows the step 1, step 2, step 3 system where they're created/run separately, so I assume documenting the ad-hoc mode with `--name` will be added later on then.)

**Comment by nmldiegues** [comment]
For the record, the warning about deprecation is already pointing out to the shortcut of using `--name NAME`:

```
You are running a Tunnel in legacy mode which will be deprecated. Please use the documentation below to switch to pre-created Tunnels for improved stability and management.
 - To expose applications to the internet create a permanent tunnel as described in https://developers.cloudflare.com/cloudflare-one/connections/connect-apps.
 - If you are running an ad-hoc tunnel from the terminal, add --name NAME flag to `cloudflared tunnel` command.
See https://developers.cloudflare.com/cloudflare-one/tutorials/migrate-lb-tunnel for an example of migrating an existing tunnel.
```

**Comment by pirate** [comment]
Aha, I didn't realize what "ad-hoc" meant to at the time, I just clicked the link and saw the instructions for the 3-step process. Makes sense now.

**Comment by abeluck** [comment]
We're having trouble creating "ad-hoc" tunnels from dev-workstations.

It seems the combination of `--name` with `--hostname` is not supported?

```
2021-05-03T16:10:47Z WRN The property `hostname` in your configuration is ignored because you configured a Named Tunnel in the property `tunnel`. Make sure to provision the routing (e.g. via `cloudflared tunnel route`) or else your origin will not be reachable. You should remove the `hostname` property to avoid this warning.
```

Also, we're seeing that our tunnels are not routable (as described in the warning!)

* Are non-named tunnels / ephemeral tunnels not supported at all anymore?
* What's the proper way to create + route a tunnel in a one-liner?

We use these tunnels for testing and development on dev-workstations. It allows them to use full oauth workflows that require a publicly reachable redirect url.

**Comment by nmldiegues** [comment]
I've just checked: that warning is a false positive in your case. We'll get the warning fixed. But the bottom line is that it should be working.

I just tried:
```
cloudflared tunnel --hostname subdomain.mydomain.com --name mytesttunnel --hello-world
```

And I got:
 - a new tunnel (named mytesttunnel) with a UUID
 - a DNS record provisioning a CNAME subdomain.mydomain.com -> UUID.cfargotunnel.com

With the tunnel being reachable.

**Comment by pirate** [comment]
Ok copying from the other discussion on #336:

Just for future reference / people finding this via google, it seems the correct new one-liner command is this:

```bash
  argo:
    image: cloudflare/cloudflared:2021.11.0
    command: tunnel --no-autoupdate -f --hostname subdomain.example.com --name whatever --url http://localhost:8080
    user: root
    volumes:
      - ./data/certs/cert.pem:/etc/cloudflared/cert.pem:r
    restart: on-failure
 ```
 
 Notes:
 - `:latest` tag is broken, you must specify a version (see #422). **(maybe this will be fixed soon?)**
     ```logs
     Pulling argo     ... error
     ERROR: for argo  manifest for cloudflare/cloudflared:latest not found: manifest unknown: manifest unknown
     ERROR: manifest for cloudflare/cloudflared:latest not found: manifest unknown: manifest unknown
     ```
 - `user: root` must be added or `/etc/cloudflared` mounted as a volume, otherwise the process within docker doesn't have permission to write to the folder (for al tunnels: legacy, ad-hoc, and named in the newer versions) **is there any way to do it without this? this really breaks a lot of docker security**
     ```logs
     argo_1      | failed to create tunnel: Your tunnel 'statping.zervice.io' was created with ID 22215e33-ba04-4a70-8685-<redacted>. However, cloudflared couldn't write tunnel credentials to /etc/cloudflared/22215e33-ba04-4a70-8685-<redacted>.json.
    argo_1      | The file-writing error is: open /etc/cloudflared/22215e33-ba04-4a70-8685-<redacted>.json: permission denied
    argo_1      | The tunnel was deleted, because the tunnel can't be run without the credentials file
    ```
 - `-f` must be added to avoid conflicting with old tunnel DNS records, but you still have to go to https://dash.cloudflare.com -> DNS settings and delete any old records manually, because `-f` doesn't actually work to overwrite existing records, it still fails if you have a conflicting existing record. **is there any stronger version of `-f` that doesn't have this problem?**
     `ERR Register tunnel error from server side error="Your Cloudflare account already have DNS records, [type: CNAME, content: 4103cd42-c30c-41a0-8ad1-<redacted>.cfargotunnel.com], for the subdomain subdomain.example.com you are attempting to create. Please delete the records in the Cloudflare dashboard before starting Argo Tunnel" connIndex=0`
- the `cert.pem` file must be refreshed if migrating from an old 2020 version, even if the expiration isn't met. the new `cloudflared` versions require newer certs

**Comment by pirate** [comment]
imo the new named tunnel design massively complicated cloudflared by making it stateful daemon with multiple config and credentials files to manage. Ya'll should at least consider documenting the stateless mode better (`--hostname <> --url <> --name <>`) here: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide

Updated instructions for anyone landing here via google:

This setup allows initializing a tunnel in a Docker one-liner with no `config.yml`/`<credentials>.json` needed, no separate `cloudflared tunnel login`/`create` steps, no pre-made tunnel UUIDs needed, and no tunnel connector tokens needed. It creates a new named tunnel automatically with a DNS record (and overwrites any existing conflicting DNS records).

1. download a cert from https://dash.cloudflare.com/argotunnel for `yourdomain.com` to `./etc/cloudflared/cert.pem`
2. setup the following block in `docker-compose.yml`:
```yml
...
services:
    app:
        ...
        listen:
            - 80

    argo:
        image: cloudflare/cloudflared
        command:  tunnel --no-autoupdate --overwrite-dns --retries 15 --protocol http2 --url http://app:80 --hostname test.yourdomain.com --name test.yourdomain.com
        volumes:
            - ./etc/cloudflared:/etc/cloudflared
        restart: on-failure
```
3. run `docker-compose up` to verify that the tunnel connects and visit https://test.yourdomain.com to verify that it's visible (you may have to refresh a few times as it initializes)

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/arguments/
