### ISSUE TITLE
[Question] How to achieve zero-downtime with load balancing?

### ISSUE THREAD

**Issue by crackalak** [cloudflare/cloudflared#353]
I have 2 pods running cloudflared (statefulset) connected to separate tunnels, these have been added to a cloudflare pool (equal weights) and then to a load balancer with a health monitor, which is routed through to the `/ready` endpoint of the cloudflared metrics server.

When I run a restart of the stateful set and continually refresh the site in the browser, some of the requests come back as HTTP 503 until the restart is completed and the cloudflared instances have finished registering.
I would have expected that as the tunnel connection unregisters, the load balancer would fail over to the other pod.

As the minimum monitor interval is 60 seconds for my subscription, is this as good as it gets or am I missing something?

**Comment by nmldiegues** [comment]
Hello @crackalak ,

You may be interested in following this tutorial https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel (that uses this example https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s) to accomplish this.

**Comment by crackalak** [comment]
@nmldiegues didn't think you could run multiple tunnels with the same credentials, but this has been fixed now 😃 thanks!

https://blog.cloudflare.com/highly-available-and-highly-scalable-cloudflare-tunnels/
