### ISSUE TITLE
Where's the documentation for cloudflared daemon?

### ISSUE THREAD

**Issue by CRYPTO-4N0M4LY** [cloudflare/cloudflared#355]
Hi,

Where can I find the documentation for usage of **cloudflared**, such as the available commands, what they do and so on?
Thanks!

**Comment by TownLake** [comment]
You can find all of the documentation [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps), including commands and configuration options.

**Comment by CRYPTO-4N0M4LY** [comment]
Um, unfortunately, there's no single page that lists the flags and params for the daemon, anywhere that I can find.
There are just examples on random pages that mention a feature/flag of the daemon.

**Comment by TownLake** [comment]
Should have linked to the more specific part of that section; under Configure a tunnel, we [list out the set of configuration options](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/config) that can be used with the configuration file and [this page](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress) lists out the rules for configuring ingress traffic. The configuration file arguments can be used as command line flags, but we recommend using them in the configuration file instead.
