### ISSUE TITLE
could not determine kind of name for C.BrotliDecoderSetCustomDictionary

### ISSUE THREAD

**Issue by reqlez** [cloudflare/cloudflared#361]
Hi.

Do any of you have any comments for this issue here?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254293

So, comparing this:
https://github.com/cloudflare/brotli-go/blob/master/reader.go

and THIS:
https://github.com/google/brotli/blob/master/go/cbrotli/reader.go

it is clear that this C.BrotliDecoderSetCustomDictionary function does not exist anymore in the newer version.

And i'm getting build errors:

github.com/cloudflare/brotli-go
vendor/github.com/cloudflare/brotli-go/reader.go:79:2: could not determine kind of name for C.BrotliDecoderSetCustomDictionary

**Comment by reqlez** [comment]
installed latest go version, same thing.

Is this related to LLVM  / Freebsd13?

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1692176611=/tmp/go-build -gno-record-gcc-switches"

**Comment by reqlez** [comment]
Hello.

Any ideas about this?

**Comment by szclsya** [comment]
Same issue here. Failed to build from port tree on FreeBSD 13-RELEASE.

**Comment by reqlez** [comment]
Honestly, nobody even looked at this for over a month, I don't think anybody gives a shit about FreeBSD lol  I submitted bug reports here and at freebsd site, e-mailed... not sure if anybody cares or too busy.

**Comment by reqlez** [comment]
Almost a year later... still does not build... same "C.BrotliDecoderSetCustomDictionary" issue.

**Comment by reqlez** [comment]
Tested on FreeBSD 13.1 with golang 1.18.2 on amd64, still same error :(

**Comment by reqlez** [comment]
Well, after fighting with this for a whole year... it seems this only will build inside a jail, kind of sad, since I did not modify my environment at all from default...

poudriere testport -j 131Ramd64 -i net/cloudflared

![image](https://user-images.githubusercontent.com/6512602/169720950-121da0de-1e25-4270-9cf8-7725118b15a0.png)

Closing ticket.
