### ISSUE TITLE
Non-existent release 2021.5.2 in cloudflared Homebrew formula results in brew "RuntimeError: Empty archive"

### ISSUE THREAD

**Issue by adamfeldman** [cloudflare/cloudflared#368]
```bash
==> Upgrading cloudflare/cloudflare/cloudflared 2021.4.0 -> 2021.5.2
==> Downloading https://packages.argotunnel.com/dl/cloudflared-2021.5.2-darwin-amd64.tgz
Error: An exception occurred within a child process:
  RuntimeError: Empty archive
```

`2021.5.2` does not show in the [list of releases](https://github.com/cloudflare/cloudflared/releases), while `2021.5.1` is the latest [in release notes](https://github.com/cloudflare/cloudflared/commit/9ff65c1e90d7e12d59cae58cb47d14fc2bb83c12).

Perhaps this is the offending commit: https://github.com/cloudflare/homebrew-cloudflare/commit/8dd22575976a07f0aba1600f33a57b3ac96587ec

Someone else also had this issue: https://github.com/cloudflare/homebrew-cloudflare/issues/27

**Comment by adamfeldman** [comment]
Due to the way `brew upgrade` seems to work, this breaks `brew upgrade` which stops running due to the `RuntimeError` from attempting to install `cloudflared`. A workaround is to run `brew upgrade PACKAGENAME PACKAGENAME` for anything else I need to upgrade (listed by `brew update`)

**Comment by kapitainsky** [comment]
Sorry your workaround is not clear. Could you please clarify how to run it?

 I have the same problem with 2021.5.3

```
admin:~$ brew upgrade
==> Upgrading 1 outdated package:
cloudflare/cloudflare/cloudflared 2021.5.1 -> 2021.5.3
==> Upgrading cloudflare/cloudflare/cloudflared 2021.5.1 -> 2021.5.3
==> Downloading https://packages.argotunnel.com/dl/cloudflared-2021.5.3-darwin-amd64.tgz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  RuntimeError: Empty archive
```

`brew update `is up to date and only failing upgrade is cloudflared

**Comment by adamfeldman** [comment]
@kapitainsky sorry I was unclear. The workaround doesn't resolve the issue with `cloudflared`, but allowed me to update my other Homebrew packages.

**Comment by kapitainsky** [comment]
> @kapitainsky sorry I was unclear. The workaround doesn't resolve the issue with `cloudflared`, but allowed me to update my other Homebrew packages.

Thx! clear now.

**Comment by adamfeldman** [comment]
Looks like this just affects the Mac build – all the other platforms show as >1mb in their tarball.

https://github.com/cloudflare/cloudflared/releases/tag/2021.5.4

**Comment by adamfeldman** [comment]
That would make it a problem not in the Homebrew formula, but for any Mac clients.

**Comment by kapitainsky** [comment]
ok - I guess some automated build and somebody trusting it too much and we have to wait until build error is fixed.

**Comment by gnawhleinad** [comment]
Still an issue for 2021.5.5,

> ```
> ==> Upgrading 1 outdated package:
> cloudflare/cloudflare/cloudflared 2021.4.0 -> 2021.5.5
> ==> Upgrading cloudflare/cloudflare/cloudflared 2021.4.0 -> 2021.5.5 
> ==> Downloading https://packages.argotunnel.com/dl/cloudflared-2021.5.5-darwin-amd64.tgz
> ######################################################################## 100.0%
> Error: An exception occurred within a child process:
>   RuntimeError: Empty archive
> ```

**Comment by gnawhleinad** [comment]
2021.5.6 upgraded succesfully!

Thanks!

**Comment by adamchalmers** [comment]
Hi all, sorry for the churn. We had some problems with our build pipeline, and as I'm sure you can tell from the flurry of commits, it took a little trial and error to fix. 2021.5.6 is now out on Homebrew and should fix the problem.

**Comment by adamfeldman** [comment]
Thank you @adamchalmers!
