### ISSUE TITLE
Using the hidden resolver with proxy-dns yeilds errors

### ISSUE THREAD

**Issue by AdrianKoshka** [cloudflare/cloudflared#37]
If you follow the instructions from https://blog.cloudflare.com/welcome-hidden-resolver/ everything seems to work, but `socat` and `cloduflared` both produce a bunch of errors.

## Steps to reproduce:

Host: Fedora 28
Tor: `Tor version 0.3.2.10 (git-31cc63deb69db819).`
socat:
```
alc@am1m-s2h ~ % socat -V
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Feb  9 2018 23:25:47
   running on Linux version #1 SMP Tue Jul 3 14:06:39 UTC 2018, release 4.17.4-200.fc28.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
```
cloudflared: `cloudflared version 2018.7.2 (built 2018-07-13-1701 UTC)`

1. have tor running
2. make sure you have `127.0.0.1 dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion` in your `/etc/hosts`
3. Enter into a terminal:

```
socat TCP4-LISTEN:443,reuseaddr,fork SOCKS4A:127.0.0.1:dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion:443,socksport=9150
```

4. Enter into another terminal:

```shell
$ cloudflared proxy-dns --upstream "https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query"
```

5. At another terminal, do:

```shell
$ dig @127.0.0.1 www.google.com
```

You'll get back an empty result from `dig`:

```shell
alc@am1m-s2h ~ % dig @localhost www.google.com

; <<>> DiG 9.11.3-RedHat-9.11.3-12.fc28 <<>> @localhost www.google.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 37990
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9e84201c1387408a (echoed)
;; QUESTION SECTION:
;www.google.com.			IN	A

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Jul 13 20:41:28 EDT 2018
;; MSG SIZE  rcvd: 55
```

`dig` seems to be able to try to make a request, but the result is just empty.

### `socat` error:

```
2018/07/13 20:42:37 socat[30223] E connect(5, AF=2 127.0.0.1:9150, 16): Connection refused
```

### `cloudflared` error:

```
error="failed to perform an HTTPS request: Post https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query: EOF"
```

**Comment by AdrianKoshka** [comment]
Tried swapping the port from `9150` to `9050` (the port tor uses...) and while `socat` no-longer produces an error, `cloudflared` now spits out:

```
ERRO[0009] failed to connect to an HTTPS backend "https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query"  error="failed to perform an HTTPS request: Post https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

and the `dig` result is still empty.

**Comment by mahrud** [comment]
Hmm, I just followed the steps you described and it worked :/ Can you try opening `https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/favicon.png` in Tor browser? (or setup socks if you don't have Tor browser)

**Comment by AdrianKoshka** [comment]
I had opened it in the tor browser, and it did indeed work!

**Comment by mahrud** [comment]
Can you try this, please:
```
curl -s --socks5-hostname 127.0.0.1:9150 "https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion/dns-query?name=google.com&type=A" -H 'accept: application/dns-json' 
```

**Comment by AdrianKoshka** [comment]
Interestingly enough, the version of fedora doesn't have support for `socks5`, only `socks4` and `socks4a`.

**Comment by mahrud** [comment]
Sorry, that's what I meant. 9150 is Tor browser's port. Okay so the service
is working, the problem must be either socat or cloudfared. Oh, you don't
have another process listening on 443 or 53, do you?

**Comment by AdrianKoshka** [comment]
I don't think I have anything listening on `443`, I could check, as for `53`, I know for sure I don't.

**Comment by AdrianKoshka** [comment]
Yep, nothing on `443`.

**Comment by AdrianKoshka** [comment]
I must have been doing something wrong...because now I got it working :)

**Comment by mahrud** [comment]
Possibly, or maybe it took a bit longer than usual to establish a circuit. Either way, glad it's working!
