### ISSUE TITLE
[Question] Is manually specifying edge locations for connections possible?

### ISSUE THREAD

**Issue by hazarkarabay** [cloudflare/cloudflared#370]
`cloudflared tunnel` automatically selects 4 edge locations for making its connections as I see. In my testing, it always pick 2 different datacenter locations and open two connections each of them. 
Assuming Argo Tunnel can use every edge location shown in https://www.cloudflarestatus.com/ , it seems to be making bad decisions. For example, there is a CF edge location exactly in my city but it prefers using some location in Latin America - 10000+km and ~120ms away from me. 

Is there any way to give "hints" about which location should it prefer when making its connections to `cloudflared`?

**Comment by nmldiegues** [comment]
Hello @hazarkarabay ,

No, it is not possible to choose specific edge locations. Our edge advertises anycast IPs to which cloudflared connects (see https://www.cloudflare.com/en-gb/learning/cdn/glossary/anycast-network/ for more information).

Out of curiosity, can you share with us (or our support) which location are you in, and which locations it connects to?
Has this been happening for a while, or just recently?

**Comment by hazarkarabay** [comment]
Thank you for the answer. When I tried on one of our servers it used the closest CF edges so it actually works as excepted.
It still makes the weird decisions in my lab but it not an issue since it proved to work fine if used in production.
