### ISSUE TITLE
Any plans to bring back the Cloudflared Ingress Controller for K8s?

### ISSUE THREAD

**Issue by andrewheberle** [cloudflare/cloudflared#373]
Now that `cloudflared` supports named tunnels with multiple instances along with its own ingress rules, is there anything on the roadmap to bring back the K8s Ingress Controller?

We currently point `cloudflared` at our existing Ingress Controller (HAProxy in our case but it could just as easily be NGINX or Traefik) but it would be great to avoid the extra step and apart from allowing config changes on the fly as per #301, it seems like almost everything is there to allow a full featured Ingress Controller implementation for K8s.

**Comment by Vad1mo** [comment]
Totally, I would like to see cloudflared implementing the ingress api or even as a more powerful and versatile solution embedding cloudflared into nginx-ingress. The second option would allow the user to use all the NGINX-ingress docs, resource and public wisdom and benifits from tunnels.

**Comment by TownLake** [comment]
We do not plan to bring back the Ingress Controller or resume support for it. More info [here](https://github.com/cloudflare/cloudflare-ingress-controller/issues/172#issuecomment-541230988).

**Comment by mabels** [comment]
Hi,

i build by my own a cloudflared-controller which uses the k8s ingress manifest and is controlled by annotations.
It's in a very early state but i will try to improve it in the next weeks. 
To bring it to a full working controller i need your help.
Please try it and give some feedback it would be wonderful.

https://github.com/mabels/cloudflared-controller

Thx

meno
