### ISSUE TITLE
cloudflared generates credentials JSON file content as bytes array

### ISSUE THREAD

**Issue by nirmalraghavan** [cloudflare/cloudflared#378]
cloudflared version 2020.6.4 (built 2020-06-16-1958 UTC)

After successfully executing the command, `cloudflared tunnel create tunnel-name` cloudflared generating credentials JSON file with contents as array of numbers. This JSON file is invalid and not recognised the by the cloudflared service itself and throwing JSON format error.

Converting this byte array to string produced the actual JSON content.

**Comment by adamchalmers** [comment]
Hi! You should upgrade to the latest cloudflared. I've never seen that happen before.

**Comment by nirmalraghavan** [comment]
Yes, it was fixed by updating to the latest (2021.5.9) version.
