### ISSUE TITLE
Perfectly good llist + record format now polluted with human readable messages

### ISSUE THREAD

**Issue by jonseymour** [cloudflare/cloudflared#383]
This change:

https://github.com/cloudflare/cloudflared/commit/89d0e45d628ef8c11d6e811beb6dfb05adec5690#diff-1901beb64dbc739ce67ab303c191a2a5206e71fd870905c22b3ce5621522b89fR302

means that the `tunnel list` subcommand now does not have a simple:

HEADER
RECORD
RECORD
....

format, but instead has:

HUMAN READABLE POLLUTION
HEADER
RECORD
RECORD
RECORD
....

I understand the need to be helpful to users but it would be kinder to people who are scripting this command if we didn't have to filter out the pollution injected for the benefit of human users.

One suggestion would be to write this information instead to stderr, which is never expected to contain structured output, or to provide a -q option which would allow script writers to indicate that they really, really, only want the structured output without any additional unstructured output of potentially unbounded complexity on a stream that up until this point has only contained structured output for these commands.

**Comment by nmldiegues** [comment]
Hello @jonseymour ,

You can use this to obtain structured output (in JSON, but YAML is also possible in the same way) and split the error/warning to another log (or just dev/null):
```
cloudflared tunnel list --output json 2> error 1> output
```

**Comment by jonseymour** [comment]
Ok, fair enough. I wasn't using the JSON output option previously, but if that is available I will use that.

FYI: Splitting the "You can obtain more detailed information for each tunnel with `cloudflared tunnel info <name/uuid>" output out of the semi-structured, column-based output isn't possible because it is written to stdout, not stderr, along with the semi-structured output.

I will close on this basis.
