### ISSUE TITLE
Selection of host when same tunnel is served by multiple hosts

### ISSUE THREAD

**Issue by adyanth** [cloudflare/cloudflared#392]
I have a HA setup where two VMs are connected via different ISPs. Both of them run cloudflared to connect to the same tunnel and serve the same content.

This works as expected when one goes down, the other one would still be up, but I have no control to select what is prioritized when both are up. I do *not* need loadbalancing, just a active passive behaviour. Right now, it seems to randomly select between the two hosts.

Any ideas on this?

**Comment by nmldiegues** [comment]
Hello @adyanth ,

Running 2 or more cloudflared for the same tunnel is purely meant for active high availability of your origin. As you said, they are picked randomly, and there's no plans to change that.

What you describe really seems like load balancing to me, where you'd create 1 tunnel for each of those origin, and place them on the Cloudflare Load Balancer in 2 separate pools, with 1 pool having more priority than the other, such that your 2nd origin will only be used if the 1st one is unavailable.

**Comment by adyanth** [comment]
Okay, so it is intended to work like that.

Multiple tunnels atleast for me do not make much sense since both of them talk to the same origin server, just through different ISPs.

Anyway, thanks for the explanation, understood that load balancing with priority can do what I want.

Thanks!
