### ISSUE TITLE
Include licensing information

### ISSUE THREAD

**Issue by svrana** [cloudflare/cloudflared#396]
Would be great to have a LICENSE file

I'd like to add this package to nixos so that this package can be trivially installed. However I'd need licensing information before I can do that. Thank you for considering!

**Comment by TownLake** [comment]
Hi @svrana - we publish licensing material [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/license) in our documentation; let us know if you have any additional questions.

**Comment by curbengh** [comment]
A copy of the license is also available on this repo (https://github.com/cloudflare/cloudflared/blob/master/LICENSE).

---

cloudflared is already available as a NixOS package ([cloudflared.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cloudflared/default.nix)). Note that cloudflared is distributed under a non-free license, so Nix repo cannot distribute the (compiled) binary on cache.nixos.org. So, before you install, you must have `nixpkgs.config.allowUnfree = true;` in your config, then your NixOS is able to download and compile the binary when you install cloudflared.nix.
