### ISSUE TITLE
Cloudflared is still checking for updates with --no-autoupdate

### ISSUE THREAD

**Issue by DamienDelporte** [cloudflare/cloudflared#406]
Hi folks,

For info i'm using "cloudflare/cloudflared:2021.6.0-amd64" docker image for my tests inside a kube.

Our NetworkPolicies only allow egress to ports/ips you have described here : https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips.

It seems that the "--no-autoupdate" flag is not disabling the check of new version at first start.
The configuration in the /etc/cloudflared/config.yml file is doing the same.

Command used is :
```
cloudflared tunnel --no-autoupdate run
```

```
2021-06-25T15:46:16Z ERR update check failed error="Get \"https://update.argotunnel.com?arch=amd64&clientVersion=&os=linux\": dial tcp 104.18.6.49:443: i/o timeout"
{"level":"error","error":"Get \"https://update.argotunnel.com?arch=amd64&clientVersion=&os=linux\": dial tcp 104.18.6.49:443: i/o timeout","time":"2021-06-25T15:46:16Z","message":"update check failed"}
```

Could you add a new flag to disable that behaviour like "--no-update-check" or disable the update check at startup with the already existing "--no-autoupdate" ?

Regards,
Damien

**Comment by nmldiegues** [comment]
Hello @DamienDelporte ,

It looks like that URL is stale, we only updated https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/#what-are-the-ports-and-ips-used-by-cloudflared
I'll make sure that is fixed.

Indeed we do not autoupdate, but we still check for possible updates and relevant messages to convey to the user.

Adding an extra flag is a possibility, but it's the first time we hear this feedback so we're not likely to jump trigger and do it right away, unless a PR contributing that is provided by the community.

**Comment by danishprakash** [comment]
> unless a PR contributing that is provided by the community.

I'd like to work on this. Would that be fine?

**Comment by nmldiegues** [comment]
> > unless a PR contributing that is provided by the community.
> 
> I'd like to work on this. Would that be fine?

All community contributions are welcome!

**Comment by karnauskas** [comment]
Just noticed same issue in the logs:
```
ERR update check failed error="Get \"https://update.argotunnel.com?arch=arm&clientVersion=2021.10.5&os=linux\": net/http: TLS handshake timeout"
```
While having `no-autoupdate:true` in config map.

**Comment by nmldiegues** [comment]
> Just noticed same issue in the logs:
> 
> ```
> ERR update check failed error="Get \"https://update.argotunnel.com?arch=arm&clientVersion=2021.10.5&os=linux\": net/http: TLS handshake timeout"
> ```
> 
> While having `no-autoupdate:true` in config map.

Correct. As I noted above:
```
Indeed we do not autoupdate, but we still check for possible updates and relevant messages to convey to the user.
```

So this means that we *never* auto update, if you have `no-autoupdate:true`.  But we still reach out to `update.argotunnel.com` (which we may use, e.g., to inform you that your version has a severe/critical bug and we highly recommend the update).

**Comment by casmith** [comment]
And if the software cannot reach the URL, it considers it a fatal operation and shuts down? Is that the correct behavior?

**Comment by zenati** [comment]
Is there any solution? If the cluster can't reach the update URL, the pod crashes. Is there a way to change this behaviour or simply stop checking? Thanks.

**Comment by zenati** [comment]
@nmldiegues thank you

**Comment by DATAPOWERELECTRICAL** [comment]
hi there,
i have added cloudflared tunnel --autoupdate-freq 24h run and it still showing no autoupdate..
any ideas ?
