### ISSUE TITLE
Authenticated origin pull

### ISSUE THREAD

**Issue by curbengh** [cloudflare/cloudflared#407]
I recently setup cloudflared tunnel and modified my origin web server to bind to localhost. The setup works fine, even though I didn't disable Full Strict SSL and authenticated origin pull.
Those settings are not relevant to cloudflare tunnel?

**Comment by sodabrew** [comment]
Correct. Full Strict SSL and Authenticated Origin Pull are settings that apply to the Cloudflare Edge POPs connecting to your origin servers.

The cloudflared daemon connects from your server into nearby Cloudflare Edge POPs. It is inherently authenticated (cloudflared login) and uses strict SSL (cloudflared will refuse to connect to a server that fails SSL handshake).
