### ISSUE TITLE
Disable / Block DNS Rebinding?

### ISSUE THREAD

**Issue by war59312** [cloudflare/cloudflared#41]
Hi,

Sadly cloudflared is doing DNS rebinding. :(

How to block?

Example of cloudflared:

> nslookup a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network 192.168.10.122
> Server:  raspberrypi
> Address:  192.168.10.122
> 
> Non-authoritative answer:
> Name:    a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network
> Address:  192.168.1.27

Example of bind9 with DNS rebinding blocked:

> nslookup a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network
> Server:  localhost
> Address:  127.0.0.1
> 
> *** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network

Example of asus router with DNS rebinding blocked:

> nslookup a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network 192.168.10.1
> Server:  router.asus.com
> Address:  192.168.10.1
> 
> Non-authoritative answer:
> Name:    a.34.192.228.43.1time.192.168.1.27.forever.1343173a-5e69-4bc9-b767-2b82212c1221.rebind.network
> Address:  34.192.228.43

As you can see above, I've been able to stop DNS rebinding on most of my network. Everything but in cloudflared. :(

cloudflared is returning the fake local ip address of 192.168.1.27. :(

Thanks,

Will

Edit: net192.rebindtest.com is another good test.

**Comment by war59312** [comment]
This is still an issue.

Really just need to blacklist out of the box:

  

> 10.*
>   172.16.*
>   172.17.*
>   172.18.*
>   172.19.*
>   172.20.*
>   172.21.*
>   172.22.*
>   172.23.*
>   172.24.*
>   172.25.*
>   172.26.*
>   172.27.*
>   172.28.*
>   172.29.*
>   172.30.*
>   172.31.*
>   192.168.*

**Comment by IAM-db** [comment]
It needs to be whitelisted.

**Comment by IAM-db** [comment]
William David Smith?
