### ISSUE TITLE
Errors running tunnel on Docker

### ISSUE THREAD

**Issue by morpig** [cloudflare/cloudflared#411]
Hi,

I'm currently trying to run cloudflared tunnel from docker (cloudflare/cloudflared:2021.6.0-amd64) and several errors appeared on logs. Any ideas why? This caused my tcp connections to be dropped (running tcp service)

```
2021-07-07T15:05:27Z ERR failed to write ping message error="short write"
2021-07-07T15:06:21Z ERR failed to write ping message error="short write"
2021-07-07T15:08:09Z ERR failed to write ping message error="short write"
2021-07-07T15:09:57Z ERR failed to write ping message error="short write"
Recover from http2 response writer panic, error (0xe34040,0x1117350)
```

Docker args:
```
docker run -v ~/.cloudflared/cert.pem:/etc/cloudflared/cert.pem -v ~/.cloudflared/uuid.json:/etc/cloudflared/uuid.json cloudflare/cloudflared:2021.6.0-amd64 tunnel --logfile tunneltcp.txt  run --url tcp://172.17.0.1:8081 tcp
```

Any ideas why?

**Comment by nmldiegues** [comment]
Hello @morpig 

Is this reproducible? If so, can you provide us with a scenario we can run on our side?

If not, how often is this happening?

**Comment by morpig** [comment]
Hard to reproduce for me too, as it's occurring randomly. 

Based on that error, is that occurring from CF edge <-> cloudflared or cloudflared <-> tcp service?

**Comment by nmldiegues** [comment]
That's cloudflared -> tcp service

**Comment by morpig** [comment]
Yup you're right, seems to be an issue within the docker networking stuffs, fixed it by directly bridging to my main NIC (added --net=host).

Thanks for your help! 😅
