### ISSUE TITLE
Cloudflared doesn't attempt to reconnect after machine is asleep and disconnected from the network for some time

### ISSUE THREAD

**Issue by anh0516** [cloudflare/cloudflared#412]
After my machine is asleep for some time and not connected to the network, `cloudflared` doesn't reconnect to WARP, presumably due to some sort of timeout. However, cloudflared still attempts to route traffic through WARP, even though the connection was dropped, meaning that I can't access the Internet until I restart the service. There doesn't seem to be any options to make it automatically reestablish a connection upon reconnecting to the network. I've looked at both the command line options for `warp-cli` and `cloudflared` and don't see any way to do this. Is auto-reconnection implemented? I'd like to use WARP on my laptop without issues. A temporary workaround might be to create a service that waits a few seconds for reconnection to the network upon waking up and then restarts the service.

**Comment by nmldiegues** [comment]
Hello @anh0516 ,

I am confused about you mentioning cloudflared and WARP here. They are different tools, which I would expect to be executing in different machines. Can you elaborate on your setup? And can you show logs of what is failing with cloudflared?

**Comment by anh0516** [comment]
@nmldiegues I assumed that the two were somehow connected. I don't see a GitHub page for WARP so I opened an issue here. I guess not. 

I'm using Manjaro testing with kernel 5.13.0-2 and an Intel WiFi card. I found the log. 
[warp-log.log](https://github.com/cloudflare/cloudflared/files/6780176/warp-log.log)
It's definitely complaining before my machine reconnects to the network.

Where would I open an issue / submit a bug report for WARP?

**Comment by nmldiegues** [comment]
So what you are saying is that you are *not* running cloudflared at all.  You are just running the WARP client (this one https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/download-warp ) ?

Then the right way would be through Cloudflare Support.

Based on my experience, WARP client reconnects when I resume my laptop. However, I use a Macbook, so maybe the behaviour depends on the OS? I wouldn't know the details of that.

**Comment by anh0516** [comment]
@nmldiegues I just installed it because I wasn't sure which to install and the official packages are not available for Arch/Manjaro so I had to install from the AUR without directions on what packages to install. I'll see if I can find any info in the docs over there.
