### ISSUE TITLE
How to use cloudflared tunnel from android?

### ISSUE THREAD

**Issue by 1337C0D3RS** [cloudflare/cloudflared#414]
i badly need this, if someone know how to do this please let me know.

**Comment by 1337C0D3RS** [comment]
after a couple of research and try and error method, i finally figured out, how to run cloudflared tunnel on my android phone to expose my local server to internet (if any one need the same comment below and then i'll update this with detailed steps)

**Comment by asystentka-jolka** [comment]
I'm just trying to do the same :) 

what I did:
```
apt install golang debianutils git
cd ~
git clone https://github.com/cloudflare/cloudflared.git --depth=1
cd cloudflared
sed -i 's/linux/android/g' Makefile
make cloudflared
```

all is fine, but when I try to execute I have:

```
~/cloudflared $ ./cloudflared --version
bash: ./cloudflared: No such file or directory
```

@1337C0D3RS how you did this?

BTW
I did this on termux

**Comment by 1337C0D3RS** [comment]
i first installed ubuntu without gui in termux, and then i used arm64 cloudflared binary and voila it worked.

PS: i used this app called andronix to install ubuntu in termux. [click here to download from playstore](https://play.google.com/store/apps/details?id=studio.com.techriz.andronix&hl=en_IN&gl=US)

**Comment by 1337C0D3RS** [comment]
let me know, if need any help.

**Comment by asystentka-jolka** [comment]
@1337C0D3RS  thx :)
I already figured out where the problem was, I had to add this:
```
export GOARCH=arm
make cloudflared
```

**Comment by sudarshan-reddy** [comment]
Very cool to see you've figured this out. I'm closing this issue in lieu of that. Perhaps you should do a gist/blogpost on this. Feels useful. 😄
