### ISSUE TITLE
Can't create ssh tunnel to remote server

### ISSUE THREAD

**Issue by AutomatoRobotics** [cloudflare/cloudflared#419]
Hello,

I'm running into a very frustrating problem. On my remote server I installed the latest cloudflared, authorized it and it loads with the following config.yml:
```
tunnel: 2fbc7467-4aac-4ec6-bdd9-***
credentials-file: /etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json
ingress:
    - hostname: removed.automatorobotics.com
      service: ssh://localhost:22
    - service: http_status:404
```

All the documents show that I need to add a CNAME for the tunnel, but now it's automatically updated with a AAAA record so I can't create a cname with the same "removed" subdomain.

The output doesn't indicate any failures, but an Argo tunnel is not created (as seen from the Traffic-ArgoTunnel list). 
Here's the output:
```
2021-07-21T12:20:08Z INF Starting tunnel tunnelID=2fbc7467-4aac-4ec6-bdd9-***
2021-07-21T12:20:08Z INF Version 2021.7.0
2021-07-21T12:20:08Z INF GOOS: linux, GOVersion: devel +11087322f8 Fri Nov 13 03:04:52 2020 +0100, GoArch: amd64
2021-07-21T12:20:08Z INF Settings: map[cred-file:/etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json credentials-file:/etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json]
2021-07-21T12:20:08Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
2021-07-21T12:20:08Z INF Generated Connector ID: 260a90a1-065f-438f-b136-47e602af747d
2021-07-21T12:20:08Z INF Initial protocol http2
2021-07-21T12:20:08Z INF Starting metrics server on 127.0.0.1:35245/metrics
2021-07-21T12:20:09Z INF Connection 23164074-95f5-45d2-b5ee-88674a64794c registered connIndex=0 location=AMS
2021-07-21T12:20:10Z INF Connection 18725454-1500-40b1-9021-82fa2b728940 registered connIndex=1 location=LHR
2021-07-21T12:20:11Z INF Connection b9ba2fd9-ffc0-40ce-b2c2-66666b5b64cf registered connIndex=2 location=AMS
2021-07-21T12:20:12Z INF Connection fdafee0e-a64b-45ea-8e4e-71acdab4624a registered connIndex=3 location=LHR

```
It's very frustrating that there isn't any indication that this is actually a failed connection :-(

When I run the following manually, it works without any issues:
`cloudflared tunnel --url ssh://localhost:22 --hostname removed.automatorobotics.com `

and the Argo tunnel is created and works great.

However, I do want to use a named tunnel as I want it to run by the cloudflared service. Any ideas?

**Comment by nmldiegues** [comment]
I believe you have identified the problem; but you are not yet aware of it.

When you just run:
```
??
```
You are running in a deprecated mode. That is why you get this in the logs:
```
You are running a Tunnel in legacy mode which will be deprecated.
```

This deprecated mode sets up a AAAA record on your zone DNS.


When you run with `cloudflared tunnel run`, instead, you are using Named Tunnels, which use CNAME record. You can place the CNAME manually, or use the command line (more info at https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns).

But in any case, you must first remove the AAAA (that you created when you ran in the deprecated mode) so that you can set up the CNAME.


If you do that, named tunnels will work.

**Comment by AutomatoRobotics** [comment]
Thanks for the fast response!
It would be useful to have a clear workaround for this in the docs, as there are many tutorials out there that will lead to the same situation as I was in and it's unclear if it's safe to remove the AAAA records. Or perhaps when running a new tunnel and such a record exists the cli can indicate the problem and propose removing it?

Going forward, I removed the records, added the cname using the cli interface and saw that it's indeed created in the DNS records correctly (forwarding to the right agrotunnel domain).
However I still can't access the tunnel and it's not listed under the Argo tunnels list in the traffic tab. How can I debug this further?

Many thanks

**Comment by nmldiegues** [comment]
> not listed under the Argo tunnels list in the traffic tab

Only legacy tunnels (the ones not named) show up there.
The new (recommended) named ones will show up in a new UI in the future. Watch out for updates in that front.

As for not being able to access, are there any logs you get on either side? (client side, and tunnel server side)

**Comment by AutomatoRobotics** [comment]
OK, thanks for the followup.
Here's the cloudflared tunnel log:
```
{"level":"info","tunnelID":"2fbc7467-4aac-4ec6-bdd9-***","time":"2021-07-22T07:02:53Z","message":"Starting tunnel"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"Version 2021.7.0"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"GOOS: linux, GOVersion: devel +11087322f8 Fri Nov 13 03:04:52 2020 +0100, GoArch: amd64"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"Settings: map[cred-file:/etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json credentials-file:/etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json logfile:/tmp/argolog.txt]"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"Generated Connector ID: 3dea4c6f-4ccd-4d91-9ec1-80d2b06ca9bc"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"Initial protocol http2"}
{"level":"info","time":"2021-07-22T07:02:53Z","message":"Starting metrics server on 127.0.0.1:41029/metrics"}
{"level":"info","connIndex":0,"location":"AMS","time":"2021-07-22T07:02:54Z","message":"Connection d63de145-19d1-4f9e-9bf9-8cc340c4f1c7 registered"}
{"level":"info","connIndex":1,"location":"LHR","time":"2021-07-22T07:02:55Z","message":"Connection fb6eda9d-0c2b-4eda-bc4f-830b3b304f5e registered"}
{"level":"info","connIndex":2,"location":"AMS","time":"2021-07-22T07:02:56Z","message":"Connection 0af38687-752f-4b21-9f08-6021aa47b85f registered"}
{"level":"info","connIndex":3,"location":"LHR","time":"2021-07-22T07:02:57Z","message":"Connection 505098a7-efbc-48ad-b9a3-34a85f94a5a9 registered"}

```

When trying to connect with ssh on the other end to the asset (after configuring .ssh/config according to the docs) I get:
```
2021-07-22T07:40:01Z ERR failed to connect to origin error="dial tcp: lookup subdomain.automatorobotics.com: no such host" originURL=https://subdomain.automatorobotics.com
dial tcp: lookup subdomain.automatorobotics.com: no such host
kex_exchange_identification: Connection closed by remote host

```

The CNAME of "subdomain" is configured in the DNS tab of CF. it's pointing to:
2fbc7467-4aac-4ec6-bdd9-***.cfargotunnel.com

Thanks again, this is quite frustrating but when it worked with the legacy tunnels it was really magical :-)
We also enabled SSH web access/rendering in the application configuration, so we also see that it can't be accessed because the subdomain isn't resolving to anything despite appearing in the list.

**Comment by nmldiegues** [comment]
My recommendation is to start simple and build from there.

Does this work?
```
tunnel: 2fbc7467-4aac-4ec6-bdd9-***
credentials-file: /etc/cloudflared/2fbc7467-4aac-4ec6-bdd9-***.json
hello-world: true
```
I.e., if you access your domain, you should now get a hello world page served by cloudflared.

From there, maybe then switch it to serve a local origin. E.g., start some simple http server (e.g. with python) on your cloudflared machine, and add an ingress rule to it with a custom subdomain. Does it also work? Then continue moving from there.

**Comment by AutomatoRobotics** [comment]
I changed the tunnel config.yml and saw in the log that it indeed launched the helloworld server.
When I accessed the subdomain on the browser I was presented with the OTP challenge (didn't resolve the name before, so that's progress). After successfully authenticating, I got this message from CF in the browser:
```
Unable to connect to origin. Please confirm that the tunnel is set up correctly and the origin is healthy.
```

**Comment by nmldiegues** [comment]
I cannot see any errors on our end for *.automatorobotics.com in the last hour.
I see the tunnel is up and running fine too.

From this end it all looks good.

Maybe you can remove the Access protection temporarily to strip down this even further to a working example.

**Comment by AutomatoRobotics** [comment]
Can you please direct me how to do it? I can't find this setting in settings of the tunnel in the CF Teams dashboard.

**Comment by nmldiegues** [comment]
So you must have done something like https://developers.cloudflare.com/cloudflare-one/tutorials/ssh#create-a-zero-trust-policy , correct?

I'm suggesting to remove that first part "Create a Zero Trust policy" to see if it works or not.

**Comment by AutomatoRobotics** [comment]
You're correct. I removed my application from the access policy (now it's empty) and I can see the Hello World when browsing to the subdomain. How to proceed from here?
Again thanks, such rapid support is really appreciated!

**Comment by nmldiegues** [comment]
Maybe you can now try again the SSH ingress rule (it'll not be Access protected, but I suppose you still require some SSH key or password, so it's ok temporarily). If that works, then you know everything is good except for Access.

As to why Access is causing problems, you'll have to ask Cloudflare Support by opening a ticket in your account, since I am not able to look into that.

**Comment by AutomatoRobotics** [comment]
Problem solved - it appears that defining the Applications for zero trust policy AFTER setting the CNAME + tunnel for the first time resolves this. Many thanks for your support!

**Comment by nmldiegues** [comment]
Happy to hear that it's working.
