### ISSUE TITLE
Using argo with a React web application

### ISSUE THREAD

**Issue by ekimia** [cloudflare/cloudflared#42]
trying to figure out how this would work with a web application using React and figured someone has encountered this. Any ideas? Would love to contribute an example of this sort of setup.

**Comment by sssilver** [comment]
Hi!

You can power both the static web application assets, and whatever backend it speaks to through Argo Tunnel. The idea is to serve the content on your server only to `cloudflared`, and have it proxy the actual requests through Cloudflare.

The Quickstart docs may be the best way to get started -- https://developers.cloudflare.com/argo-tunnel/quickstart/
