### ISSUE TITLE
Use Origin Server Certificate Instead Of Cloudflare!

### ISSUE THREAD

**Issue by IzumiSena** [cloudflare/cloudflared#421]
Use Origin Server Certificate Instead Of Cloudflare! 
At this moment Cloudflare Acting As a Man-In-The-Middle
Cause every time i access my site via Cloudflare Argo Tunnel!
My Domain Shows Cloudflare SSL Cert On Browser! And In The Origin I am Using Let's Encrypt SSL Cert!

So its like First Everything Goes Via Cloudflare SSL then They Decrypt All Those Data With There Key! Then Again Encrypt By My Origin Let's Encrypt Cert Then All Those Data Get Stored In My Origin Server! 

Why Not Just Use Origin Server Cert On Domain? I Don't Want To Use Cloudflare Generated SSL Which Act as a MITM!

If There Is Already a Solution Then let me Know!

**Comment by sodabrew** [comment]
You can forward a TCP socket. The connection would be double-encrypted between Cloudflare and the cloudflared instance, and would be end-to-end encrypted using your certificate between the client and your server process.

**Comment by IzumiSena** [comment]
> You can forward a TCP socket. The connection would be double-encrypted between Cloudflare and the cloudflared instance, and would be end-to-end encrypted using your certificate between the client and your server process.
> 
> But for the common case HTTPS to a CDN service, terminating SSL at the edge is a feature. It makes your site faster and allows you to process requests at the edge POP.

Any instruction or guide link?

**Comment by sodabrew** [comment]
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress#supported-protocols
