### ISSUE TITLE
Docker tag latest isn't latest version

### ISSUE THREAD

**Issue by karuboniru** [cloudflare/cloudflared#422]
I am trying to integrate cloudflared's docker image into my CoreOS's instance, I want the newest version of cloudflared is always pulled, but when you do a pull of `latest` tag:
```
[core@fcos ~]$ podman run --rm docker.io/cloudflare/cloudflared:latest -v
cloudflared version 2020.7.0 (built 2020-07-01-1654 UTC)
```
Seems that you always have to sepcify the version like `docker.io/cloudflare/cloudflared:2021.7.0`. And always update the version string accordingly.
***
The root cause of this problem (I think) is that you did not tag latest version with `latest` tag, if doing so, pulling latest docker image will be convenient.

**Comment by patricegautier** [comment]
yes please!  That latest tag is really necessary for containerr/watchtower to be able to pull updates

**Comment by jauderho** [comment]
@sudarshan-reddy That seems odd that it is not possible to overwrite the latest tag as it seems to work for me across multiple images built.

FWIW, I do have a working setup that I would happy to contribute if that helps.

- Dockerfile - https://github.com/jauderho/dockerfiles/blob/main/cloudflared/Dockerfile
- Github Action - https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/cloudflared.yml
- Docker Hub - https://hub.docker.com/r/jauderho/cloudflared/tags?page=1&ordering=last_updated
- GHCR - https://github.com/jauderho/dockerfiles/pkgs/container/cloudflared

As a bonus, the image is half the size of the official image.

To update, there's a small external script that monitors for a new cloudflared release, updates BUILD_VERSION and builds new images upon detection of a new release tag.

**Comment by sudarshan-reddy** [comment]
@jauderho this is a great idea. I'd prefer not having an external script and handle that via a gh action as well. Do you want to make a Pull request for this?

**Comment by jauderho** [comment]
> @jauderho this is a great idea. I'd prefer not having an external script and handle that via a gh action as well. Do you want to make a Pull request for this?

I will if I find some time. I only just figured out how to use a GH action to update build tags. This will require some changes on your end (need special purpose PAT with workflow perms) but here's the meat: 

- https://github.com/jauderho/dockerfiles/blob/main/.github/workflows/update.yml
- https://github.com/jauderho/dockerfiles/blob/main/scripts/updateDockerImages.sh

The script could probably use some beefing up for error checking but it works.

**Comment by GingerAdonis** [comment]
I was surprised to see there's no `latest` tag already. Manually updating my compose file seems unnecessary. Are there any plans to also push to `latest`?

**Comment by master-hax** [comment]
still seeing this issue. image `cloudflare/cloudflared` did not work, `cloudflare/cloudflared:2022.1.2` did.

**Comment by pewter77** [comment]
Same problem as master-hax. Latest isn't latest, 2022.1.2 works fine if specified manually but makes updating or deploying a bit of a pain.

**Comment by nmldiegues** [comment]
This is definitely on our radar, but there is still a technical impediment preventing this improvement. We'll eventually sort it out.

**Comment by alexjeen** [comment]
Adding to the pile, adding latest here would allow us to automatically update the cloudflared services every monday.
