### ISSUE TITLE
arm64 bin download link 404 / arm build does not match system.

### ISSUE THREAD

**Issue by raspuk** [cloudflare/cloudflared#428]
Hi all,

The arm64 bin download (https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64) is currently 404'ing.

Also the arm64 .deb download (https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm.deb) is showing the following error on install:

dpkg: error processing archive cloudflared-linux-arm.deb (--install):
 package architecture (arm) does not match system (arm64)
Errors were encountered while processing:
 cloudflared-linux-arm.deb

As i'm guessing its not the arm64 build.

Both links are found on the main support site here:

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#linux

Any resolution would be greatly appreciated.

Hardware: Rpi 4 8Gb, Raspbian 64bit.

**Comment by kiracus** [comment]
it seems @sudarshan-reddy removed it from this commit https://github.com/cloudflare/cloudflared/commit/cd4af5696d0db81caae903b33e4bbddfb5aff9ff 

@sudarshan-reddy , is it removed by accident? could we revert the change? thanks

**Comment by sudarshan-reddy** [comment]
Oops. Doesn't need a revert though. I'll simply add it to list of builds here: https://github.com/cloudflare/cloudflared/blob/master/build-packages.sh#L18.

**Comment by sudarshan-reddy** [comment]
You should be able to download an arm64 build from here: https://github.com/cloudflare/cloudflared/releases. 

We are also in the process of updating the links on the install page.
