### ISSUE TITLE
Can't update from 2021.7.4

### ISSUE THREAD

**Issue by KommX** [cloudflare/cloudflared#429]
I run `cloudflared` on Raspbian 10. I have been notified about the releases of 2021.8.0 and 2021.8.1, but I can't update to these versions via the usual `sudo cloudflared update`:

```
pi@raspberrypi:~ $ sudo cloudflared -v
cloudflared version 2021.7.4 (built 2021-07-28-1036 UTC)
pi@raspberrypi:~ $ sudo cloudflared update
2021-08-04T20:32:49Z INF cloudflared is up to date version=
```

**Comment by pheiduck** [comment]
Can confirm, happen because they dropped the armv6 package which is used for armhf architecture (32-bit Raspberry Pi).
If you have followed the documentation from Pi-hole.

**Comment by sudarshan-reddy** [comment]
Thanks for the report guys. Can you point me to how you installed cloudflared please?

**Comment by sudarshan-reddy** [comment]
Just reproduced it on my rpi. I'm on it.

**Comment by sudarshan-reddy** [comment]
This issue should now be fixed. Appreciate you guys being on top of this. Let me know if you can update now.

**Comment by KommX** [comment]
Yes, now, this works again.
Thank you!
