### ISSUE TITLE
Unable to create a tunnel in cloudflared

### ISSUE THREAD

**Issue by aijkl** [cloudflare/cloudflared#430]
I'm using DeepL, so the text is difficult to understand, but no offense is intended, thank you.

I have multiple servers running, so I have multiple cloudflared instances running.

In cloudfalred1.service, dev.hoge.org
ww.hoge.org in cloudflared2.service
poster.hoge.org in cloudflared3.service
Part of this, poster.hoge.org, is no longer working.
I have not changed any configuration files.
The output is "ERR Register tunnel error from server side error="Reached maximum retry 5: rpc: connection closed" connIndex=0". You can use AzureVM to create a new server.
This prevents name resolution for poster.hoge.org.
The configuration file for poster.hoge.org is as follows

hostname: http://poster.hoge.org
url: http://localhost:5009
credentials-file: /etc/cloudflared/d3efd20a-3c0f-4740-a6e0-1a26d0344427.json

If I change the above configuration file "poster" to "test", it works, and the subdomain "poster" is no longer available.

In normal operation, when I create a tunnel with argo-tunnel, it is added to Cloudflare's DNS configuration screen as "AAA", but "poster" is not added, "test" is added, but it is gone because I deleted "poster" when I tried to fix it myself, but it was added without any problem before.

This problem started when I rebooted the server.
I tried to run it on a new server using AzureVM, but it failed.

Can you please help me?
It could be a serious problem from the fact that the problem occurred even after trying with a new AzureVM. Thank you for your help.

<img width="269" alt="スクリーンショット 2021-08-05 164247" src="https://user-images.githubusercontent.com/51302983/128312518-cf9c2a8b-4369-408f-b670-8a3e3e1fc23d.png">

![23af5584942831e187cceaacef42d359f7ba2d53](https://user-images.githubusercontent.com/51302983/128310878-a3297dd6-46da-42cb-ac2e-35fc7a967df7.png)

**Comment by nmldiegues** [comment]
Hello @aijkl ,

The information provided above is a quite confusing. 
I've checked that:
 - there's no orange-clouded poster.hoge.org
 - there's no orange-clouded test.hoge.org
 - there's no DNS pointing at d3efd20a-3c0f-4740-a6e0-1a26d0344427

Maybe you can follow some tutorial (such as https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab#cloudflare-tunnel) to try to create a working configuration? Seems like various things are not making sense in the setup you described above.

**Comment by aijkl** [comment]
The word "hoge" was used to mean "hide", sorry for the confusion.
It is actually poster.orange-mikan.org and private.orange-mikan.org.
poster.orange-mikan.org is a non-working domain.
![image](https://user-images.githubusercontent.com/51302983/128333295-74e09250-159c-4499-823e-ba73405680f8.png)

**Comment by nmldiegues** [comment]
I see that "private.orange-mikan.org" is pointing to a AAAA record with `fd10:aec2:5dae::`. That's the legacy tunnels that are no longer recommended.

I cannot find anything with "poster.orange-mikan.org ".

It seems like you are missing something like:
`cloudflared tunnel route dns d3efd20a-3c0f-4740-a6e0-1a26d0344427
 poster.orange-mikan.org`  that will create a CNAME of poster.orange-mikan.org pointing to d3efd20a-3c0f-4740-a6e0-1a26d0344427.cfargotunnel.com and thus route that domain to your named tunnel (with ID d3efd20a-3c0f-4740-a6e0-1a26d0344427).

**Comment by aijkl** [comment]
@nmldiegues 
I don't know the difference between CNAME and AAA, so I don't know what the solution is.
I have the following output

error="Your Cloudflare account already have DNS records, [type: CNAME, content: d3efd20a-3c0f-4740-a6e0-1a26d0344427.cfargotunnel.com], for the subdomain poster.orange-mikan.org you are attempting to create. Please delete the records in the Cloudflare dashboard before starting Argo Tunnel"
```
#config.yml
#https://developers.cloudflare.com/argo-tunnel/reference/config
hostname: http://poster.orange-mikan.org
url: http://localhost:5009
credentials-file: /etc/cloudflared/d3efd20a-3c0f-4740-a6e0-1a26d0344427.json
```

**Comment by nmldiegues** [comment]
Ok so the DNS route seems correct.

All you need to do is to run that tunnel `d3efd20a-3c0f-4740-a6e0-1a26d0344427` (named `poster`).
That tunnel is inactive since 2020-12-18 10:44:14 UTC

**Comment by aijkl** [comment]
![image](https://user-images.githubusercontent.com/51302983/128337692-75802ec2-1f71-42d2-bf1c-946a2c5d5091.png)

It was working until yesterday.
I am not sure why it shows as inactive since Dec.

What is a named tunnel?
. /cloudflared tunnel --config /etc/cloudflared/config2.yml run poster
↑. /cloudflared tunnel --config /etc/cloudflared/config2.yml run poster

2021-08-05T10:52:38Z INF Initial protocol h2mux
2021-08-05T10:52:38Z INF Starting metrics server on 127.0.0.1:44501/metrics
2021-08-05T10:52:39Z ERR Register tunnel error from server side error="Unauthorized: Record for tunnel not found" connIndex=0
2021-08-05T10:52:40Z INF Retrying connection in 1s seconds error="Unauthorized: Record for tunnel not found" connIndex=02021-08-05T10:52:42Z ERR Register tunnel error from server side error="Unauthorized: Record for tunnel not found" connIndex=0
2021-08-05T10:52:42Z INF Retrying connection in 2s seconds error="Unauthorized: Record for tunnel not found" connIndex=0^C2021-08-05T10:52:42Z INF Initiating graceful shutdown due to signal interrupt ...

I have output like this.

**Comment by nmldiegues** [comment]
The problem is that you have deleted tunnel `d3efd20a-3c0f-4740-a6e0-1a26d0344427` at `2021-08-05 00:25:04 UTC`.

You will have to create a new tunnel and update the DNS CNAME record to point to the new UUID generated as per https://developers.cloudflare.com/cloudflare-one/tutorials/gitlab#cloudflare-tunnel

**Comment by aijkl** [comment]
Thank you.
I'll give it a try.

**Comment by aijkl** [comment]
It worked, thank you very much.
Thank you very much for your help.
