### ISSUE TITLE
Windows 10 - Nothing happen on install

### ISSUE THREAD

**Issue by SuperSonicSites** [cloudflare/cloudflared#431]
Hi, I'm trying to install the latest release yet nothing happen in the terminal. It stays blank.

**Comment by sudarshan-reddy** [comment]
Can you show us some screenshots and/or system logs please? This is to see how you are going about making your installs.

**Comment by jgentes** [comment]
Hi @SuperSonicSites - I ran into this too. The executable is actually the `cloudflared` .exe you want to run. Try `cloudflared-windows-amd64 help` and you should get some output.

**Comment by sudarshan-reddy** [comment]
I've submitted a revision to the official documents to correct instructions: https://github.com/cloudflare/cloudflare-docs/pull/1977. 

Thanks so much for the report @SuperSonicSites
