### ISSUE TITLE
Tunnel server stopped - Unregistered tunnel connection

### ISSUE THREAD

**Issue by phamngocsonls** [cloudflare/cloudflared#437]
My tunnel have log look like:

{"level":"info","time":"2021-08-16T22:01:03Z","message":"Initiating graceful shutdown due to signal terminated ..."}
{"level":"info","connIndex":3,"time":"2021-08-16T22:01:03Z","message":"Unregistered tunnel connection"}
{"level":"info","connIndex":1,"time":"2021-08-16T22:01:03Z","message":"Unregistered tunnel connection"}
{"level":"info","connIndex":2,"time":"2021-08-16T22:01:03Z","message":"Unregistered tunnel connection"}
{"level":"info","connIndex":0,"time":"2021-08-16T22:01:04Z","message":"Unregistered tunnel connection"}
{"level":"info","time":"2021-08-16T22:01:04Z","message":"Tunnel server stopped"}
{"level":"info","time":"2021-08-16T22:01:04Z","message":"Metrics server stopped"}

What happend with cloudflared tunnel. After 15 min, cloudflared tunnel have been restarted

**Comment by sudarshan-reddy** [comment]
Hey @phamngocsonls from the logs it looks like it received a request to shutdown.

**Comment by phamngocsonls** [comment]
> Hey @phamngocsonls from the logs it looks like it received a request to shutdown.
> 
> ‘’’
> Initiating graceful shutdown due to signal terminated
> ‘’’

Connection drop during "Tunnel server stopped" and before registered new connection?

**Comment by sudarshan-reddy** [comment]
cloudflared receive a sigterm. This is an indication to shutdown. Connections are unregistered before a shutdown. 

This is expected behaviour.

**Comment by cslovell** [comment]
In my case I had set up the tunnel with the intention of cloudflared to work and serve connections, and the sigterm is unexpected and it's hard to see what's causing it. At this point it's not working as expected but the logs indicate no error.
