### ISSUE TITLE
Run multi cloudflared instance vs one

### ISSUE THREAD

**Issue by phamngocsonls** [cloudflare/cloudflared#440]
- Hi, What happened if i run multi cloudflared instance on 1 VM. 
Can it increase performance vs run single instance.
-Is there any documents about cloudflared performance (max ccu, rps, bps?)

**Comment by sudarshan-reddy** [comment]
Why would you do want to run multiple cloudflareds on the same machine?


Have you read https://blog.cloudflare.com/highly-available-and-highly-scalable-cloudflare-tunnels/ ? It talks about general use cases of multiple cloudflareds.

**Comment by phamngocsonls** [comment]
@sudarshan-reddy 
I want to increase multiple of max connection cloudflared instance can handle in one VM.
Some time cloudflared instance status go terminated, other instance can help for HA case in limit of VM instance

**Comment by sudarshan-reddy** [comment]
@phamngocsonls more connections do not give increase in performance. They exist as a fallback mechanism if one of our edges you’re connecting to fails.

to ensure fallback on your side, you can run multiple cloudflareds but on different vms as in that blog I referenced above. 


let me know if this clears up your doubts.
