### ISSUE TITLE
Installing cloudflared on raspberry pi 4 using open media vault

### ISSUE THREAD

**Issue by Kate222** [cloudflare/cloudflared#441]
I use raspberry pi 4 for open media vault. What should I install  Cloudflared?

**Comment by sudarshan-reddy** [comment]
Hey @Kate222 , I haven’t used a pi 4 but the arm build works on my pi3. Can you try https://github.com/cloudflare/cloudflared/releases/download/2021.8.2/cloudflared-linux-arm ?

**Comment by Kate222** [comment]
> 
> 
> Hey @Kate222 , I haven’t used a pi 4 but the arm build works on my pi3. Can you try https://github.com/cloudflare/cloudflared/releases/download/2021.8.2/cloudflared-linux-arm ?

Thank you.
