### ISSUE TITLE
brew 404 error when upgrading

### ISSUE THREAD

**Issue by adaptive** [cloudflare/cloudflared#45]
brew 404 error when upgrading
`==> Upgrading 1 outdated package, with result:
cloudflare/cloudflare/cloudflared 2018.7.3 -> 2018.8.0
==> Upgrading cloudflare/cloudflare/cloudflared
==> Downloading https://developers.cloudflare.com/argo-tunnel/dl/cloudflared-2018.8.0-darwin-amd64.tgz`

`curl: (22) The requested URL returned error: 404
Error: Failed to download resource "cloudflared"
Download failed: https://developers.cloudflare.com/argo-tunnel/dl/cloudflared-2018.8.0-darwin-amd64.tgz`

**Comment by gedw99** [comment]
me too !


==> Upgrading 2 outdated packages, with result:
glib 2.58.0 -> 2.58.0_1, cloudflare/cloudflare/cloudflared 2018.7.3 -> 2018.8.0
==> Upgrading glib 
==> Downloading https://homebrew.bintray.com/bottles/glib-2.58.0_1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/cf/cf62335e49678260e16ea6a6af2ddc971d538f535b2e8e83bf5ad4d14b53036a?__gda__=exp=1536248952~hmac=728310c380019505b23960c02055dd77059d1
######################################################################## 100.0%
==> Pouring glib-2.58.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.58.0_1: 435 files, 18.4MB
==> Upgrading cloudflare/cloudflare/cloudflared 
==> Downloading https://developers.cloudflare.com/argo-tunnel/dl/cloudflared-2018.8.0-darwin-amd64.tgz

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "cloudflared"
Download failed: https://developers.cloudflare.com/argo-tunnel/dl/cloudflared-2018.8.0-darwin-amd64.tgz

**Comment by adaptive** [comment]
fixed, thanks
