### ISSUE TITLE
turn cloudflared into an open source project?

### ISSUE THREAD

**Issue by pabs3** [cloudflare/cloudflared#464]
I noticed that the [cloudflared license](https://github.com/cloudflare/cloudflared/blob/master/LICENSE) is a proprietary one that does not allow modifications etc. At my workplace we have a policy that no software that includes telemetry is allowed and no proprietary software is allowed. One of our customers wants us to use cloudflared for accessing their servers over SSH. We would like to continue supporting that customer but cannot continue to do so with their new cloudflared requirement.

Could you release cloudflared under an [open source licence](https://opensource.org/osd) and turn turn cloudflared into an open source project?

I think this would benefit Cloudflare as other folks could help with the (many) open issues and pull requests.

I note the project is already operating similar to an open source project in that the source code is public, the code is on GitHub, and you are accepting pull requests, but the submitters of those pull requests are violating your copyright license, which opens them up to legal action by Cloudflare, which is a bit concerning. Releasing the code under an open source license would put those concerns to rest.

**Comment by fragtastic** [comment]
I hope the included license is an oversight, as it is contradictory to the effectively opensource nature of the project.

The most concerning lines essentially boil down to "`You are expressly prohibited from modifying, adapting, translating, preparing derivative works ... the Software ...`"

https://github.com/cloudflare/cloudflared/blob/e2b18364f49a7e075f02b0a87c585c58a1b6904a/LICENSE#L37-L41

**Comment by pabs3** [comment]
Me too, the license was very surprising to read. I agree those are the
most concerning lines in the license, but I think that the project
should use an existing standard easily understood open source license
rather than a custom one, to reduce license proliferation and to give
developers confidence of their open source rights for the project.

PS: I've tried to escalate this to the cloudflare open source team, but
the mail was rejected. I also asked some of the committers to
cloudflared to escalate the issue to the cloudflare open source team.
If you know of any other ways to escalate this, I would be happy to
have assistance bringing it to the attention of Cloudflare. I'm not on
Twitter, if you are then probably a tweet might help.

https://github.com/cloudflare/.github/issues/13

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by nmldiegues** [comment]
Thanks for flagging this. This may very well be a historical artifact that should be fixed. This has reached our radar as soon as you opened the issue, and we are checking the due process on how to go about it.

We’ll keep updating as soon as there are news.

**Comment by pabs3** [comment]
I see, thanks for the info and the update.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by alchzh** [comment]
Is there an update on this? I am a happy cloudflare tunnels user on my personal servers but license is an issue for different use.

**Comment by nmldiegues** [comment]
> Is there an update on this? I am a happy cloudflare tunnels user on my personal servers but license is an issue for different use.

Yes, I think there'll be updates soon.

@abelinkinbio  can confirm.

**Comment by alchzh** [comment]
> @alchzh curious what issues you're hitting in personal use cases as well.

Personal use case is fine -- was planning on doing some docker stuff w/ jupyterhub and cloudflared for access tunnels since restrictions on university network and then publishing that publicly (or at least with people at my school). On second thought the license is probably not an issue here since I wouldn't be modifying the source of cloudflared? Of course having the project be really open source is still something I want to see.

**Comment by abelinkinbio** [comment]
@alchzh Makes sense. In the interim, thanks for the added context, and we'll continue to provide updates as we have them.

**Comment by pabs3** [comment]
@abe thanks for considering the request. I'd like to suggest using a
standard open source license rather than modifying the existing license
to make it open source. Personally I prefer the GPL for the new license
but the Apache2, BSD or MIT licenses would also work.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@nmldiegues @abelinkinbio has there been any update on this? Also what would the new license be? Personally I prefer the GPL for the new license but the Apache2, BSD or MIT licenses would also work.

**Comment by jspraul** [comment]
Bump after 5 months.

https://news.ycombinator.com/item?id=30283987#30284770

**Comment by abelinkinbio** [comment]
Thanks for bumping this thread. This is still on our radar and we should have a more meaningful update shortly.

**Comment by abelinkinbio** [comment]
Thank you again to all who provided feedback on the limitations under our previous license. As you can see in our [developer documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/license), we have updated the license for this project. This should be reflected in Github this week as well. 

Excited to see what this unlocks 🔓

**Comment by pabs3** [comment]
@abe thanks a lot for switching to the Apache 2 license!

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I have filed a new issue about the remaining GitHub changes:

   https://github.com/cloudflare/cloudflared/issues/573

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
