### ISSUE TITLE
Checksum for cloudflared-linux-amd64.deb wasn't uploaded for the 2021.9.0 release.

### ISSUE THREAD

**Issue by jon360** [cloudflare/cloudflared#468]
The 2021.9.0 release shows the following hash:
cloudflared-linux-amd64: 27270c4ee59e0261ea68a5007f82c99670c1ff18ed8722344efab6570af9f977

But the actual sha256sum of the download is:
e79d8d6476536cf21850cbf43c0fc3e964756e107fc7ffae33aea77613d3138a  cloudflared-linux-amd64.deb

**Comment by sudarshan-reddy** [comment]
The `cloudflared-linux-amd64` hash is for the `cloudflared-linux-amd64` binary here: https://github.com/cloudflare/cloudflared/releases/download/2021.9.0/cloudflared-linux-amd64

**Comment by sudarshan-reddy** [comment]
It just looks like the checksum for `deb` is not uploaded.
