### ISSUE TITLE
Loglevel 'debug' shows too much information, and 'info' too little

### ISSUE THREAD

**Issue by simeyla** [cloudflare/cloudflared#47]
The `debug` level for loglevel is extremely detailed for incoming requests. The next level `info` shows no incoming requests at all.

Often I want to just see all the URLS coming in, but not the headers and full 'cloudflare diagnostics'.

Would be great to get a log level that just showed incoming URLS and not all the request/response headers
This could be useful for both production and development workflows. I'm primarily using it for development and it's very helpful to see what's being requested.

**Comment by zackbloom** [comment]
Great point, thanks @simeyla. I believe request logs were removed from the info output as on machines which get a lot of traffic they themselves could be noisy. It sounds like we need a new level between what info shows now, and the current debug level logging.

Another option would be to do this the way web servers do it, separate 'access' logs from 'error' logs.

**Comment by abelinkinbio** [comment]
Our updated log levels can be found at https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments#loglevel

We currently support the following log level values to specify the verbosity of logging. The default `info` level will produce limited output and we would recommend using `warn` in production. Available levels are: `trace`, `debug`, `info`, `warn`, `error`, `fatal`, `panic`.
