### ISSUE TITLE
Official Docker Container doesn't report version to dash.teams.cloudlflare.com Access Tunnels

### ISSUE THREAD

**Issue by neruve** [cloudflare/cloudflared#476]
When you use the official docker image, it doesn't seem to be reporting the version to cloudflare. I had the same problem with 2021.8.2 and now on 2021.9.1 it does the same thing (the tunnel works fine though)

![image](https://user-images.githubusercontent.com/20587695/135077628-2e24e376-1ed7-4b6e-8e7c-68525a3a6b6f.png)

**Comment by nmldiegues** [comment]
Hello @neruve 

Thanks for reporting this problem. We have fixed it in https://github.com/cloudflare/cloudflared/commit/d54c8cc74544927dab45823681185615b4489363 so the next Docker images generated will have the version reported correctly.

**Comment by neruve** [comment]
Awesome. Thank you guys! It's not a huge deal. More of an OCD of things not working lol

**Comment by neruve** [comment]
Can confirm this was indeed fixed in 2021.9.2

Thanks again!
