### ISSUE TITLE
You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/service/ for more information.

### ISSUE THREAD

**Issue by Timtaran** [cloudflare/cloudflared#481]
Hello, I have `You need to specify the origin certificate path by specifying the origincert option in the configuration file, or set TUNNEL_ORIGIN_CERT environment variable. See https://developers.cloudflare.com/argo-tunnel/reference/service/ for more information.` error, but if i set ` --origincert "/home/nonroot/.cloudflared/cert.pem"`(i tryed ` --origincert "/home/nonroot/.cloudflared/"` too) i will got an a error
```
ERROR[2021-10-02T10:19:22Z] Cannot find a valid certificate for your origin at the path:

    /home/nonroot/.cloudflared

If the path above is wrong, specify the path with the -origincert option.
If you don't have a certificate signed by Cloudflare, run the command:

        cloudflared login

Error locating origin cert: Cannot find a valid certificate at the path /home/nonroot/.cloudflared
```

![изображение](https://user-images.githubusercontent.com/60805088/135712266-827feca2-091d-48c5-97d3-896aef4104bf.png)

**Comment by sudarshan-reddy** [comment]
Can you show us the full `cloudflared` command you ran? I suspect you supplied the flag in the wrong position.

**Comment by BrodyStone21** [comment]
@sudarshan-reddy not OP but I'm having the same issue. Looks like quite a few people are experiencing this. It seems like it's a permissions issue and the `cert.pem` file is never actually being created. Below is the command I ran (in Docker). I'm using the latest version which is 2021.11.0-amd64. 

`docker run -it --rm -v ~/.config/cloudflared:/etc/cloudflared/ cloudflare/cloudflared:2021.11.0-amd64 tunnel create ubuntu`

**Comment by skol101** [comment]
Same issue here with microk8s cluster. I followed instructions from here https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel

**Comment by littldr** [comment]
@skol101 I got the same error just some minutes ago. Ensure that you use the lastest version of `cloudfrontd`. (the linked manifest in the docs point to a quite old version). Additionally I made the mistake to pick a different name for the `credentials.json` while creating the k8s secret. So double check the names you picked for the files. It seems like that `cloudfrontd` does something strange if the `credentials-file` in the `config.yaml` point to a non-existing file. 🤷 
After fixing this, everything worked for me. :)

**Comment by derkoe** [comment]
Just ran in to this issue. Ther error occurs when using the image from the docs `cloudflare/cloudflared:2021.4.0`.

It goes away when switching to the current version (`cloudflare/cloudflared:2022.3.1`)

**Comment by nmldiegues** [comment]
Where did you find `cloudflare/cloudflared:2021.4.0` in the docs @derkoe ?

**Comment by derkoe** [comment]
It was here https://developers.cloudflare.com/cloudflare-one/tutorials/many-cfd-one-tunnel/#deploy-cloudflared - but it seems @levidurfee has updated the file yesterday https://github.com/cloudflare/argo-tunnel-examples/commit/cd94169d69c9573171d15c0ce0168f726abada7c

**Comment by nmldiegues** [comment]
I see. We have a long standing issue where our Docker image has no latest tag. We still have that on the radar to be fixed, but it depends on non-technical issues that we cannot solve autonomously.

In the meantime we recommend always using the latest cloudflared version available regardless of what (potentially stale) docs say.

**Comment by derkoe** [comment]
You could also use [Renovate](https://docs.renovatebot.com/) to update the image tag in the deployment automatically.

**Comment by BrodyStone21** [comment]
> I see. We have a long standing issue where our Docker image has no latest tag. We still have that on the radar to be fixed, but it depends on non-technical issues that we cannot solve autonomously.
> 
> In the meantime we recommend always using the latest cloudflared version available regardless of what (potentially stale) docs say.

Yes, please do work on this! I just realized that my image was several months out of date today.

**Comment by derkoe** [comment]
it seems that the current version `2022.8.4` has the same issue again
