### ISSUE TITLE
Argo Tunnel Mysql

### ISSUE THREAD

**Issue by ben29** [cloudflare/cloudflared#482]
m trying to do Argo Tunnel to mysql server:

cloudflared tunnel --url tcp://localhost:3306 --hostname sql.domain.com

and try to connect

mysql -h sql.domain.com -uroot -p13 -P 80
mysql -h sql.domain.com -uroot -p13 -P 443
mysql -h sql.domain.com -uroot -p13 -P 3306

nothing works.

getting:
ERROR 2013 (HY000): Lost connection to MySQL server at ‘reading initial communication packet’, system error: 2

**Comment by nmldiegues** [comment]
I believe this is being addressed in https://community.cloudflare.com/t/argo-tunnel-mysql/311650

The TLDR is that Tunnel works via Cloudflare's HTTP stack for L7 (e.g. HTTP or websocket). But for L4, you need something on the client side (either `cloudflared access tcp` or WARP and private routing configured to the Tunnel origin).
