### ISSUE TITLE
Free SSH tunnel error: "failed to parse quick Tunnel ID: invalid UUID length: 0"

### ISSUE THREAD

**Issue by ztgasdf** [cloudflare/cloudflared#487]
Command run: `cloudflared tunnel --url ssh://localhost:22 --logfile ./cloudflared.log --metrics localhost:45678`

Version used: cloudflared version 2021.10.2 (built 2021-10-14-1509 UTC)

```
2021-10-15T03:14:07Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2021-10-15T03:14:07Z INF Requesting new quick Tunnel on trycloudflare.com...
failed to parse quick Tunnel ID: invalid UUID length: 0
```

**Comment by nmldiegues** [comment]
Thanks for the report. We are investigating the issue (which is confirmed).

Note that these types of tunnels (where you haven't created a Cloudflare account) are meant for ephemeral usage and have less guarantees of uptime.
If you are relying on them, we highly encourage you to create a Cloudflare account and pre-create your Named Tunnels as per  https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide

**Comment by LostRuins** [comment]
Hi, 

`failed to parse quick Tunnel ID: invalid UUID length: 0`

I am getting the same issue with anonymous tunnels again. Could it be related to yesterday's outage?

**Comment by arenasys** [comment]
https://www.cloudflarestatus.com/
Cloudflare is having troubles. You can try the Kaggle notebook instead if you want.

**Comment by KrisCoulson** [comment]
@LostRuins you're not the only one on this issue tonight. Must be something up.

**Comment by shadowchiki** [comment]
hi, i am getting the same error than @LostRuins

**Comment by LostRuins** [comment]
Cloudflarestatus.com does show that "tunnels" is up but trying to create one with cloudflared fails.

Hoping it will be resolved soon.

**Comment by saifalfalah** [comment]
I'm getting the same issue with Tunnels. 🙋‍♂️

**Comment by divya206** [comment]
Are you guys facing this same issue? failed to parse quick Tunnel ID: invalid UUID length: 0

**Comment by incubiq** [comment]
I have the same error... existing tunnels (before outage) are running OK, but unable to create a new one

**Comment by teddybear082** [comment]
same

**Comment by sudarshan-reddy** [comment]
Hello. We are aware of this issue and working on it. However, as a work around, you should still be able to create a standard Named Tunnel which is attached to a Zone. I will post an update on this thread once we fix this.

**Comment by jahilldev** [comment]
This is an ongoing issue (for the past ~12hrs now):
https://www.cloudflarestatus.com/incidents/hm7491k53ppg

**Comment by techyminati** [comment]
`failed to parse quick Tunnel ID: invalid UUID length: 0`

similar issue here as well

**Comment by xalteropsx** [comment]
same issue lol

**Comment by sudarshan-reddy** [comment]
This should be fixed now.

**Comment by xalteropsx** [comment]
Yup fixed now ☺️

**Comment by LostRuins** [comment]
Still happens occasionally.
