### ISSUE TITLE
Windows Installer not not working

### ISSUE THREAD

**Issue by AmodeusR** [cloudflare/cloudflared#493]
I downloaded Cloudfared windows installer, both 32 and 64 bits, but none of them worked, it just open a blank terminal and that's it. Am I doing something wrong, or...?

**Comment by TonnyWildeman** [comment]
Sorry to respond here. Perhaps a new feature request or similar would be better.

I made the same mistake in assuming the .exe is also an installer. I think the internet standard name for these types of executables is Portable. So, a rename for the Type in the table on the downloads page would clear things up.

FYI: if you zip the .exe. The size shrinks to around 17mb. Probably the .exe is delivered zipped at the protocol layer. But that requires processing power, everytime. So maybe, it would be better to deliver the portable executable in a zip. And turn of zip on the protocol layer for zipped files.

**Comment by Jarrettgohh** [comment]
In Windows, I didn't go through the steps as mentioned in the link sent by @sudarshan-reddy. I simply downloaded the `.exe` file provided, changed the name of the `.exe` file to `cloudflared.exe` (or whatever relevant for yourself), changed directory to the downloads folder, and created a tunnel using: `.\cloudflared.exe tunnel`

**Comment by DavidBendahan** [comment]
For me I needed to be in the `C:\Program Files (x86)\cloudflared` directory in order to install:

![image](https://user-images.githubusercontent.com/16686247/216499558-8c5a6a36-0cc7-42bb-aa1f-8b57ef896689.png)

**Comment by TonnyWildeman** [comment]
``<off-topic/>``
@DavidBendahan What are you using for your pwsh terminal coloring, etc.?
``</off-topic/>``

**Comment by DavidBendahan** [comment]
Hi @TonnyWildeman , I'm using `oh-my-posh`, adding here the [Installation tutorial link](https://zimmergren.net/making-windows-terminal-look-awesome-with-oh-my-posh/) 👍
