### ISSUE TITLE
Overwrite flag while pushing a CNAME record through cloudflared has no effect

### ISSUE THREAD

**Issue by Richigeht** [cloudflare/cloudflared#499]
Hi,
I tried to replace and update a bunch of DNS entries from one cloudlfared to another instance with the cloudflared cli like proposed in the help dialog, however I only get an error presented:

```cloudflared tunnel route dns --overwrite-dns betatester rclone02```
Failed to add route: code: 1003, reason: An A, AAAA or CNAME record already exists with that host.

Also if using the -f (I tried to also use it after the hostname and dns name) it also doesn‘t do what I would expect from the help:
```
DESCRIPTION:
   Creates a DNS CNAME record hostname that points to the tunnel.

OPTIONS:
   --overwrite-dns, -f  Overwrites existing DNS records with this hostname (default: false) [$TUNNEL_FORCE_PROVISIONING_DNS]
````

Unless I misunderstood it, I think this is a bug. I am running cloudlfared version:
***cloudflared version 2021.10.3 (built 2021-10-15-0916 UTC)***

if you need further information or can correct me, if I did something wrong, please let me know :)

**Comment by nmldiegues** [comment]
I think you may be hitting a limitation of that functionality:  you are providing the subdomain to route to, but not the fully qualified domain.

I.e., you are doing:
```
cloudflared tunnel route dns --overwrite-dns yourtunnel subdomain
```

And if you instead do:
```
cloudflared tunnel route dns --overwrite-dns yourtunnel subdomain.yourdomain.com
```

It will work.
This is because the "overwrite logic" we have in place is not able to work with just the subdomain (and infer the domain).

**Comment by Richigeht** [comment]
Oh great! The error message was not really pushing me into catching this - especially since you normally don't need the full domain name/you couldn't combine two different domains within one single tunnel. 

I can confirm using the full domain name it works.

**Comment by LinHouYu** [comment]
I followed your tutorial but still reported an error display 
REST request failed: Get "https://api.cloudflare.com/client/v4/accounts/6c0e03b7fb6f1e818595a701d17d8810/cfd_tunnel?is_deleted=false&name=minecraftjava": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
