### ISSUE TITLE
Websocket header host bug

### ISSUE THREAD

**Issue by elderapo** [cloudflare/cloudflared#50]
`Host` header is set to value from option `--url` in `cloudflared` for `ws` requests. I believie it's a bug since it's setting `Host ` header to `--hostname` for `http/https` requests.

Showcase: https://github.com/elderapo/cloudflare-ws-bug

**Comment by sssilver** [comment]
Thanks for reporting this. We’re working on a fix and will release in the next few days.

**Comment by sssilver** [comment]
We have released a new version of `cloudflared` (2018.10.4), which fixes this bug. Please reopen if the issue is still there.
