### ISSUE TITLE
Error using Cloudflare generated Origin CA Certificates with Cloudflared

### ISSUE THREAD

**Issue by haneef95** [cloudflare/cloudflared#505]
Hi,

I'm using the [Cloudflare Origin CA Certificate](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca) on the origin server.

However, cloudflared is throwing this error: 
`The service may be down or it may not be responding to traffic from cloudflared: x509: certificate is valid for *.domain.com, a.domain.com, not my-container" cfRay=rasefasefasef ingressRule=1 originService=https://my-container:8443`

Is there anyway around this?
# Potential options
For now:
1. Get Cloudlfare to generate a certificate for `my-container`, but, cloudflare requires FQDN. Not an option (unless that is changed of course)❌
2. Use `noTLSVerify` on the config.yaml. But, I don't want to do that in this specific scenario, as I would like certificate verification. ⁉
3. Certificate pinning? Is it possible to point cloudflared to trust a certificate without checking the hostnames? By pointing to a copy of the `.pem` file generated by cloudflare or a hash of that? ❔
4. Get `cloudflared` to match the certificate SAN/DNS Name against the requested url in the user's browser (defined as `hostname` in the config.yaml)? As opposed to verifying against the `service` url in the `config.yaml`.
5. Anything else?

Thanks in advance

**Comment by haneef95** [comment]
Oops! false alarm, sorry!

It turns out, there's already a parameter for that, which works between option 3 and 4 above.

`originServerName`

According to the [docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#originservername) (who reads them anyway 😜)
> Hostname that cloudflared should expect from your origin server certificate.

Essentially overriding the normal certificate verification process.

**Comment by haneef95** [comment]
Oops! false alarm, sorry!

It turns out, there's already a parameter for that, which works between option 3 and 4 above.

`originServerName`

According to the [docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress#originservername) (if I only read it more thoroughly earlier 😜)
> Hostname that cloudflared should expect from your origin server certificate.

Essentially overriding the normal certificate verification process.

**Comment by haneef95** [comment]
> 3\. Certificate pinning? Is it possible to point cloudflared to trust a certificate without checking the hostnames? By pointing to a copy of the `.pem` file generated by cloudflare or a hash of that? ❔

Side note: Would still be good to have this option for self-signed certificates though! 😊

**Comment by jmvaswani** [comment]
So did you put "my-container" (for example) as the origin Hostname?
