### ISSUE TITLE
POST/PUT/PATCH requests with no body causing 502 errors

### ISSUE THREAD

**Issue by e3dio** [cloudflare/cloudflared#509]
I spent several hours trying to figure out why I was getting 502 errors, finally narrowed it down to the fact that the tunnel is re-writing the Content-Length header for POST/PUT/PATCH requests and removing the "0" for zero body, that needs to be there

**Comment by e3dio** [comment]
Hmm I still don't know what is going on, something with sending an empty body POST/PUT/PATCH request is causing issue with next request that goes through tunnel, I will paste my previous text:

When a POST or PUT or PATCH request is made through the tunnel without a Body the immediate next request through the tunnel (does not matter what source, different computer/ip etc) errors 502 with console msg: “Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: EOF”. Then the request after that works. If you send another POST/PUT/PATCH without body the next request again will 502. Without the tunnel it works fine.

I set up a test endpoint to try here: https://test.cloudflare1.app

Any POST/PUT/PATCH request without Body will cause the next request to 502 error. If you wait 10 seconds after the POST/PUT/PATCH request it will work fine without error. There must be some bug with Cloudflare Tunnel

This is using a uWebSockets http server, if you use a Node.js server there is no issue. But the uWebSockets should be using standard request/response behavior, and without the tunnel there is no issue

**Comment by e3dio** [comment]
See here https://github.com/cloudflare/cloudflared/blob/master/vendor/golang.org/x/net/http2/transport.go#L1874-L1878

the comments look like it is supposed to send Content-Length: "0" header for POST/PUT/PATCH requests, but it doesn't and something breaks the next request

**Comment by e3dio** [comment]
Ok looks like this code was just recently updated and is not in the latest cloudflared release yet, I guess need to wait for next release and try again, might be fixed

**Comment by nmldiegues** [comment]
Hello @e3dio ,

We have modified something related to content-length header recently so that's likely the culprit.
We'll investigate this new issue.

**Comment by nmldiegues** [comment]
I confirm that we are unable to reproduce this with other webservers. I've double checked and we have some tests that should be catching this, but they are running fine.

So this may be specific to uWebSockets. I'll give it a shot.

**Comment by nmldiegues** [comment]
Can you share the source for your test app?  That may be easier to reproduce the problem.

**Comment by nmldiegues** [comment]
In the meantime, I've confirmed that you can upgrade the transport protocol (used between cloudflared <-> Cloudflare edge) to QUIC and it will work around this problem (see https://blog.cloudflare.com/getting-cloudflare-tunnels-to-connect-to-the-cloudflare-network-with-quic/)

All it takes is for you to specify the property: `protocol: quic` in your config YAML, or `--protocol quic` in your tunnel CLI arguments.

**Comment by nmldiegues** [comment]
So far I haven't been able to narrow this down to a regression.  I have the feeling that this problem has existed for a while and is unrelated to the changes done for Issue #500 

> I spent several hours trying to figure out why I was getting 502 errors

Can you confirm if this was ever working for you before with Tunnel?

In the meantime, note my comment above: you can upgrade to QUIC protocol and workaround this bug.

**Comment by hst-m** [comment]
Yep `--protocol quic` fixed the 502 issue, I see the content-length header is now sent as "0" though not sure if that is relevant. The uWebSocket library uses HTTP/1.1 but the author is adding QUIC now, maybe relevant. Below is example server with uWebSockets.js:

```javascript
// package.json
{ "dependencies": { "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.4.0" } }

// run with node.js
require('uWebSockets.js').App()
.any('/*',res=>res.end('success'))
.listen(8080,s=>{})
```
I will continue using `--protocol quic`, thanks for looking at this, I was trying to deploy existing apps to cloudflared tunnel which I like using, nice product

**Comment by e3dio** [comment]
Yep `--protocol quic` fixed the 502 issue, I see the content-length header is now sent as "0" though not sure if that is relevant. The uWebSocket library uses HTTP/1.1 but the author is adding QUIC now, maybe relevant. Below is example server with uWebSockets.js:

```javascript
// package.json
{ "dependencies": { "uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.4.0" } }

// run with node.js
require('uWebSockets.js').App()
.any('/*',res=>res.end('success'))
.listen(8080,s=>{})
```
I will continue using `--protocol quic`, thanks for looking at this, I was trying to deploy existing apps to cloudflared tunnel which I like using, nice product

**Comment by nmldiegues** [comment]
Glad to hear that it's working.

> The uWebSocket library uses HTTP/1.1 but the author is adding QUIC now, maybe relevant

Note that the `protocol` setting defines the transport used in Cloudflare Edge <-> cloudflared communication;  it does not change the transport for cloudflared <-> origin (that may not even be HTTP at all, since we support a myriad of things there).

We're unlikely to chase this bug in the other transports since this is the first time we hear about this and we're moving away from the older transports. For now tunnels still default to `protocol: http2`, but is likely to change soon. 
If anyone else stumbles upon this, the recommendation is to change the `protocol: quic` setting.
