### ISSUE TITLE
After DDoS cloudflared cannot recover

### ISSUE THREAD

**Issue by Meister1977** [cloudflare/cloudflared#511]
Hi,

My site received yesterday a DDoS attack, 2.6k http rps. Cloudflare mitigated automatically. But after this, the cloudflared service (windows, latest cloudflared) still uses a lot of memory, and there are a lot of connection issues. I had to restart the service to work it properly again. Seems to me, without the cloudflared the mitigation was success, but with the cloudflared the connection problems remain after the attack.

Could you please check why it cannot recover after the attack?

**Comment by Meister1977** [comment]
Is there any way to help you to figure out the details of the potential memory leak?

**Comment by abelinkinbio** [comment]
We're happy to hear the attack was mitigated. This is interesting. Would you be able to open a ticket with Cloudflare Support? We'll be able to provide better assistance in that channel and can request account and tunnel-specific information which may be relevant while troubleshooting.

**Comment by abelinkinbio** [comment]
Closing this issue and moving discussion into #701
