### ISSUE TITLE
CloudFlare WARP is unable to Forward DNS queries to a Private DNS Resolver

### ISSUE THREAD

**Issue by RyanPrice-King** [cloudflare/cloudflared#515]
When connecting WARP client, I am able to connect to the whole private network, but am unable to resolve DNS queries to the internal DNS resolver.

Currently the only way to resolve queries is to create DNS override policies, which is not appropriate for my use case. 

It would be good to specify a DNS forwarding IP over WARP network Tunnel and possibly to define which zones get forwarded.

**Comment by nmldiegues** [comment]
There'll be good news on this front soon.

@abelinkinbio  can chime in on the details

**Comment by abelinkinbio** [comment]
@RyanPrice-King stay tuned for more on this "soon" ✍️

**Comment by RyanPrice-King** [comment]
I notice you can now specify DNS forwarding for the DNS Fallback options, is this the first part completed for this?  Am very eager to see WARP DNS forwarding :)

**Comment by abelinkinbio** [comment]
Nice catch! Your intuition is correct 🤓

 We published a [blog post](https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/
) yesterday that has a waitlist to stay up to date on this feature, but I'll be posting here as well. And to your point, creating a local fallback record and pointing that to your internal DNS resolver will be the first step once UDP support goes live.

**Comment by RyanPrice-King** [comment]
Sorry to waken this issue again, but do you have any update to the progress on this or any ETA by any chance please?

**Comment by abelinkinbio** [comment]
Thanks for bumping this thread. This feature is in production and you can get started by following this guide in our [developer documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/private-hostnames-ips). 

Let us know if you have any feedback on documentation or otherwise.

**Comment by ndom91** [comment]
Have set it up recently and works like a charm! Thanks for letting me deprecate my legacy VPN :sweat_smile: :tada:

**Comment by RyanPrice-King** [comment]
I think I have misinterpreted something here.  I can not get what I wanted to work.  I needed DNS forwarding to DNS resolver at the WARP tunnel end, not client end.  

Client connects WARP -> DNS query over WARP.  
The DNS Fallback stops requests even going down the WARP tunnel.  So is not a solution for me.

Is this still something that wont work?

**Comment by pcm1ke** [comment]
I can’t get this to function despite having every set properly. I have a fallback domain of diffident.net set to use my local dns server (192.168.2.6, actually a pihole setup using another cloudflared instance to do DoH on 5053). My tunnel is on a separate LXC at 192.168.2.7, which also uses 192.168.2.6 for lookups. Everything on my pan is using 192.168.2.6 perfectly fine including the LXC at .7. However, when I’m away from home and use warp to connect back to my lan (192.168.2.0/24, which is added properly as a private network and literally nothing is being excluded, so everything is going over warp) everything works EXCEPT resolution of my lan hostnames (*diffident.net). I can reach everything via their respective IPs, just no resolution of the one domain I personally added to the fallback network. Can anyone please help me solve this problem? Cloudflare tunnel is one of my only options as it actually works with T-Mobile where as other wireguard solutions fail completely on T-Mobile. Thank you!

**Comment by RyanPrice-King** [comment]
Firstly, sorry quic should be lowercase.  Another thing to check is that
you have enabled UDP to pass through the tunnel under firewall proxy
settings.  Also have you tried enabling dns logging in the client to see
what is happening with your queries better.

**Comment by RyanPrice-King** [comment]
In the cloudflare logs can you confirm the tunnel is configured to run with
the QUIC protocol
