### ISSUE TITLE
CloudFlare Teams for WARP will not let me remove default entries from the Local Domain Fallback

### ISSUE THREAD

**Issue by RyanPrice-King** [cloudflare/cloudflared#516]
When trying to remove the "lan" zone from the Local Domain Fallback option, it does not remove it, but instead duplicates it and give success message.

I have also tried this with the API, which shows my custom DNS fallback with the fallback list GET request, but in the Web UI this is not represented and also does not apply to the WARP client.

There appears to be no way to remove "lan" from the local domain fallback so I can pass *.lan hostnames down the WARP tunnel.

**Comment by nmldiegues** [comment]
I don't think there's much we can do about that since that's not specific to cloudflared, but rather a whole other product/software from Cloudflare.

@abelinkinbio  how can we best help here?

**Comment by abelinkinbio** [comment]
@RyanPrice-King thanks for flagging this. I've raised a bug ticket and we will have a fix out in our next release tomorrow morning.

**Comment by RyanPrice-King** [comment]
Nice.  That would be great.  Thank you @abelinkinbio  👍

**Comment by RyanPrice-King** [comment]
This appears to be working for me now.  Thank you again :)
