### ISSUE TITLE
Hosting wildcard through tunnel

### ISSUE THREAD

**Issue by yaleman** [cloudflare/cloudflared#521]
Is this configuration possible? I can't seem to find a working configuration - adding a wildcard CNAME to the tunnel address doesn't allow proxying like a specific subdomain does.

**Comment by kevbook** [comment]
I've tried below and it works.

```yml
ingress:
  - hostname: "*.example.com"
```

**Comment by yaleman** [comment]
But are you specifying individual hostnames in the actual DNS zone? When I configure a wildcard to point at the tunnel hostname, I only get loopback IPv6 responses when attempting to connect... specifying individual hostnames works fine.

**Comment by aofei** [comment]
> Non-enterprise customers can create but not proxy wildcard records.
>
> -- https://support.cloudflare.com/hc/en-us/articles/360017421192-Cloudflare-DNS-FAQ#h_2C7rPZioPs5FIMJgvWiPST

Apparently you have to upgrade your zone to Enterprise plan to get what you want.

**Comment by yaleman** [comment]
Ah, that'll do it, thanks.

**Comment by EricRabil** [comment]
I was able to create a proxied wildcard record on a free website, but cannot replicate it on a `.dev` domain.

**Comment by jontybrook** [comment]
> > Non-enterprise customers can create but not proxy wildcard records.
> > -- https://support.cloudflare.com/hc/en-us/articles/360017421192-Cloudflare-DNS-FAQ#h_2C7rPZioPs5FIMJgvWiPST
> 
> Apparently you have to upgrade your zone to Enterprise plan to get what you want.

Just as an FYI for anyone else coming across this. **_Cloudflare now supports proxying wildcard ‘*’ record for DNS management in all customer plans. This used to only be offered to Enterprise plans._**

Excellent! 👍🏼 

Source: [](https://developers.cloudflare.com/support/dns/troubleshooting/cloudflare-dns-faq/)
