### ISSUE TITLE
Docker version not providing sufficient UDP buffers

### ISSUE THREAD

**Issue by schack** [cloudflare/cloudflared#522]
The Docker version of Cloudflared you provide here: https://hub.docker.com/r/cloudflare/cloudflared
is unable to allocate sufficient UDP buffers when running in QUIC mode.

It logs this message on startup:

failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

**Comment by chungthuang** [comment]
Hi @schack, cloudflared tried to increase the UDP buffer size, but it failed to. When running as a docker container, you need to change the buffer size from the docker host. Have you tried the suggestion in https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size?

**Comment by schack** [comment]
Hi @chungthuang, I'm running in Kubernetes, you would not happen to have a working configuration/example for that, would you?

**Comment by chungthuang** [comment]
I haven't tried it, but maybe you can use [sysctls](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/) to change UDP buffer size.

**Comment by nmldiegues** [comment]
Note that this is not malign. cloudflared still continues to work and proxy. There may be some impact on the performance of proxied traffic, but we haven't got measurements to quantify, as that would depend on the different buffer sizes.

Anyway, it is up to the environment owner to configure the said buffers as Chung Ting suggested above.

**Comment by Hongbo-Miao** [comment]
I got same "failed to sufficiently increase receive buffer size" error. I posted the solution at https://stackoverflow.com/questions/75779066/got-failed-to-sufficiently-increase-receive-buffer-size-error-for-cloudflared/75779067#75779067

Hopefully it saves some time for people who meet same problem in future! 😃
