### ISSUE TITLE
Question about Cloudflare cccess for multiple internal resources

### ISSUE THREAD

**Issue by kevbook** [cloudflare/cloudflared#524]
Oftentimes, an engineer would need access to multiple internal resources. For example multiple databases. This use-case seems like a typical one to replace a traditional VPN solution. 

```bash
$ cloudflared access tcp --hostname db1.domain.com --url 127.0.0.1:1234
$ cloudflared access tcp --hostname db2domain.com --url 127.0.0.1:2345
$ cloudflared access tcp --hostname alb1.domain.com --url 127.0.0.1:3456
```

Is this the only way to solve this?

**Comment by whalehub** [comment]
> Is this the only way to solve this?

@kevbook No, you can also use [Cloudflare WARP](https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel) to access those resources if you create routes for them using `cloudflared`.

**Comment by kevbook** [comment]
> @kevbook No, you can also use [Cloudflare WARP](https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel) to access those resources if you create routes for them using `cloudflared`.

Thanks, that makes sense. It would be kind of a replacement for our VPN with subnet level access. I was hoping we can do better. I also found https://github.com/mmiranda/cfdtunnel, which seems like a wrapper by creating multiple `cloudflared access`

**Comment by nmldiegues** [comment]
Agree with @whalehub 

If you want to access various private origins at the network level then you are better off with WARP -> Tunnel. See https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel for an end to end example
