### ISSUE TITLE
WebSocket connections don't work in 2021.11.0

### ISSUE THREAD

**Issue by iamacarpet** [cloudflare/cloudflared#526]
First of all, thanks for the great product, I've been enjoying testing Cloudflare for Teams.

Had a slight hickup with getting WebSockets to work though...

I'm using Access & Tunnel, with a `cloudflared` config that looks like this:

```
tunnel: <uuid>
credentials-file: /root/.cloudflared/<uuid>.json
ingress:
  - hostname: app.mydomain.com
    path: /ws
    service: ws://localhost:5000
  - hostname: app.mydomain.com
    path: /live/*
    service: ws://localhost:5000
  - hostname: app.mydomain.com
    service: http://localhost:5000
  - service: http_status:404
```

Most of the app works great, but the bits requiring the websockets didn't:

Debug tools in Chrome shows a response of `101 Switching Protocols` as expected, but then no traffic/frames, then it drops after a few seconds.

Wireshark locally between `cloudflared` and the app service shows the `Upgrade` header is missing.

Rolling back to 2021.4.0 fixes the problem and it works beautifully, so something must have changed.

I picked that version as there were other tickets talking about websockets working on it.

Any idea what it is?

**Comment by nmldiegues** [comment]
Hello @iamacarpet ,

There must be something non-trivial about your setup and/or origin that is causing that, as we have different test suites making sure websocket works through tunnel.

Can you help us reproduce that? What are you serving behind your Tunnel, is it something we can run ourselves?
Is your site exposed to the Internet (guess not since you mention Access).

**Comment by iamacarpet** [comment]
Hello @nmldiegues ,

Appreciate your reply.

I’d have thought the same if it wasn’t for my colleague trying the same thing as me & getting the exact same error.

We are both trying to expose local installs of [Frigate](https://github.com/blakeblackshear/frigate) with access controlled entry (as it’s private CCTV) and it is using websockets for the live view & event notifications.

My colleague also exposed OctoPrint for his 3D printer via the same ‘cloudflared’ instance using ingress rules & had the same result (websocket broken unless we downgrade to 2021.4.0).

During office hours we are enterprise customers at our employer (and so very kindly got a great demo of Cloudflare for Teams from our account manangers), so following on from that, we are both trialling the functionality on personal, **free tier accounts**, which is the only information I think might be relevant?

We both followed the documentation to create an application in Access & configure the tunnel, so nothing really out of the ordinary, so I’m hoping it’s fairly simple to replicate.

I noticed a lot of your mock testing in this repo keeps traffic local to the daemon (kind of the point of mock traffic I suppose), but could this require testing against the edge for some kind of interplay at that level?

**Comment by nmldiegues** [comment]
> I noticed a lot of your mock testing in this repo keeps traffic local to the daemon (kind of the point of mock traffic I suppose), but could this require testing against the edge for some kind of interplay at that level?

Those would be the unit tests. But we have acceptance tests that are essentially real client applications, running against our real edge, with everything "for real". Not to mention the myriad of internal usages we have relying on Tunnels at Cloudflare.

I just tested manually a simple example:
```
import argparse
import asyncio
import logging
import websockets


async def echo(websocket: websockets.WebSocketServerProtocol, _path: str):
    await websocket.send("hello, client!")
    data = await websocket.recv()
    logging.debug(f"WS Echo server received: {data}")
    await websocket.send(data)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='http test server')
    parser.add_argument("--host", type=str, help="host to listen on", default="localhost")
    parser.add_argument("-p", "--port", type=int, help="port to listen on", default=8083)
    args = parser.parse_args()

    start_server = websockets.serve(echo, args.host, args.port)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()
```

Ran that as my websocket origin.

Then ran a Tunnel pointing to it with this config:
```
ingress:
  - hostname: "*.trycloudflare.com"
    service: ws://localhost:8083
  - service: http_status:404
```

And ran the Tunnel:
```
cloudflared tunnel --protocol h2mux/http2/quic --config ~/Downloads/config.yaml
```

(tried all 3 protocols, all 3 worked)

Tested the origin with the client:
```
python -m websockets ws://tropical-spokesman-involvement-lanka.trycloudflare.com
```

(the URL was obviously a random one I got by using account-less "trycloudflare" Tunnels to get this going quickly)

and it worked fine.


This is the minimal reproducing example I can provide of a working websocket over Tunnel.
What'd be great is the equivalent minimal reproducing example of one that does not work :)

**Comment by iamacarpet** [comment]
Thanks for the info @nmldiegues ,

The amount of internal testing certainly makes things more interesting to reproduce, and your small sample was super helpful, thank you! :).

Trying out your sample works on both the trycloudflare.com domain and my own tunnel/domain...

Great, so it's not as bad as we thought, most websockets do work! :).

I managed to re-create the issue with this:

```python
from wsgiref.simple_server import make_server
from ws4py.websocket import EchoWebSocket
from ws4py.server.wsgirefserver import WSGIServer, WebSocketWSGIRequestHandler
from ws4py.server.wsgiutils import WebSocketWSGIApplication

server = make_server('', 8083, server_class=WSGIServer,
                     handler_class=WebSocketWSGIRequestHandler,
                     app=WebSocketWSGIApplication(handler_cls=EchoWebSocket))
server.initialize_websockets_manager()
server.serve_forever()
```

I went with ws4py as that appears to be what Frigate is using, however I also tried a sample with Tornado (which is what OctoPrint is using) and couldn't re-create the problem there, although the full application does experience the same thing.... I think it's probably my lack of experience with Python, apologies.

I'm testing with `websocat` on the CLI and taking a look at the resulting traffic in Wireshark, shown below:
![Screenshot 2021-12-09 10 00 45 AM](https://user-images.githubusercontent.com/1333857/145375471-bbf5b1ca-6607-4905-a368-9d66c96e8e57.png)
(left is your working example, right is my broken one)

What immediately stands out is the `Content-Length: 0` in the broken one (and the upgrade headers are all correct).

If I start proxying via nginx, `cloudflared -> nginx -> python`, and use `more_clear_headers Content-Length`, it fixes things!

![Screenshot 2021-12-09 10 04 29 AM](https://user-images.githubusercontent.com/1333857/145375946-18b4cb79-bf52-40cd-9a02-fca5703cdd93.png)

Wireshark capture of the header being removed & it working as expected.

I then tried the same with the full Frigate application and again, it fixed the problem.

Now, you could argue the websocket implementation shouldn't be sending that header and you'd probably be correct, but it's obviously something that affects a fair few Python apps and it does work on release `2021.4.0`, so it isn't the edge that doesn't like it, it's something with `cloudflared` itself?

**Comment by nmldiegues** [comment]
Awesome investigation @iamacarpet 

I think that'll be enough for us to pick up from there and chase this down.

**Comment by nmldiegues** [comment]
Can you try your problematic setup with Tunnel running with `--protocol quic`?

**Comment by iamacarpet** [comment]
Good call @nmldiegues , I totally forgot to test the protocol.

`--protocol quic` also fixes things, as it looks like mine is defaulting to `http2`

**Comment by nmldiegues** [comment]
Cool, that matches my experiments based on all the great investigation you've done above.

Our feedback is then to use that new protocol (some context about it in https://blog.cloudflare.com/getting-cloudflare-tunnels-to-connect-to-the-cloudflare-network-with-quic/) because that's "the future" and we'll not be chasing down (what seems to be corner case) bugs in previous transport protocols whenever possible if they are addressed in the most recent protocol.

We'll eventually be transitioning all Tunnels to `quic` seamlessly (just like we did from `h2mux` to `http2, but for now it's still opt-in.

**Comment by iamacarpet** [comment]
Brill, thanks @nmldiegues 

Just need to figure out how to add the protocol option to the systemd service, as I believe you can't specify it in the config file.. Is that right?

**Comment by nmldiegues** [comment]
As with almost every property, you can specify it either in the config yaml (root property `protocol: quic`) or in the command arguments itself (`cloudflared tunnel --protocol quic ...`)

**Comment by iamacarpet** [comment]
> As with almost every property, you can specify it either in the config yaml 

Amazing, that's the bit I couldn't find in the documentation, thanks so much!
