### ISSUE TITLE
Missing ARM64 SHA265 Checksum

### ISSUE THREAD

**Issue by jacobwoffenden** [cloudflare/cloudflared#529]
Hey,

The SHA265 Checksum for ARM64 is missing from https://github.com/cloudflare/cloudflared/releases/tag/2021.12.0

I have it as `5f9c9980c1d6daea1abe78b43befb754011e9d2fdb31dc280547f0eb8d6da34b`

**Comment by nmldiegues** [comment]
https://github.com/cloudflare/cloudflared/releases/tag/2021.12.1 fixed that issue
