### ISSUE TITLE
Failed to install Cloudflared exec format error

### ISSUE THREAD

**Issue by MBtest13** [cloudflare/cloudflared#533]
OS: ubuntu 20.04.3 x86_64 

Steps failed :
# For Debian/Ubuntu
wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
sudo apt-get install ./cloudflared-linux-amd64.deb
cloudflared -v

apt-get install == already the newest version
cloudflared -v == cannot execute bianary flie: exec format error

i tried updating the dpkg amd64 but no luck. 

The odd thing is it worked for about 10 min two days ago. Then I noticed while tcp capture my failover DNS was getting more traffic and this port was not resolving the DNS-querys. I attempted a reinstall after removing all directories and this is what I get now. 

Also, all dependencies are up to date. 

Thank you.

**Comment by nmldiegues** [comment]
I have not been able to reproduce this.  I have tried to install that package in a ubuntu VM 64bit and it worked fine.

**Comment by MBtest13** [comment]
ok thanks, i think i might just scrub this vm image and start over....

**Comment by dpdug4n** [comment]
Ran into a similar issue on PopOS after following the install instructions from PiHole. Copying the binary to the expected path resolved the issue.
`sudo cp /usr/bin/cloudflared /usr/local/bin/cloudflared
`
