### ISSUE TITLE
Pass stdin to curl

### ISSUE THREAD

**Issue by uhthomas** [cloudflare/cloudflared#535]
stdin is not passed to curl and so curl commands which rely on stdin (e.g uploading a file, submitting data) will not work:

```sh
echo 'Hello, world!' | cloudflared access curl https://httpbin.example/post -X POST -d @-
```

The workaround as described in [the documentation](https://developers.cloudflare.com/cloudflare-one/tutorials/cli#using-the-token-as-an-environment-variable) is to manually add the header to curl.

```sh
echo 'Hello, world!' | curl -H "cf-access-token: $(cloudflared access token -app=httpbin.example)" https://httpbin.example/post -X POST -d @-
```

I imagine the fix would be to pass stdin to [`exec.Cmd`](https://pkg.go.dev/os/exec#Cmd) in the [run](https://github.com/cloudflare/cloudflared/blob/d4733efb25d79f95634997a395db0e32bc3247ed/cmd/cloudflared/access/cmd.go#L296) function.

What are your thoughts? Do you feel this could be useful?

#### version

```sh
❯ cloudflared -v
cloudflared version 2021.12.1 (built 2021-12-16-0823 UTC)
```

**Comment by tonickkozlov** [comment]
@uhthomas This should be fixed in e63ec3450381851689ae726202b6325fb2e3924d
