### ISSUE TITLE
[Feature Request] Display FIPS in startup/version

### ISSUE THREAD

**Issue by jeff-armis** [cloudflare/cloudflared#542]
When launching cloudflared using FIPS, can this be displayed on startup (or --version)? 

Example:
`2022-01-03T10:56:39Z INF Version 2021.12.3` ==> `2022-01-03T10:56:39Z INF Version 2021.12.3-FIPS`

Just looking for a simple way to prove we're using the FIPs enabled `cloudflared`.

**Comment by nmldiegues** [comment]
Something analogous to this will be available once https://github.com/cloudflare/cloudflared/commit/a39d95d5f7bc273ceca682a96252672191f6c743 is released (which will be in the next release).

This is shown in 3 ways:
 - the version output with cloudflared version and alike commands
 - the build_info prometheus metric
 - a logging message when tunnel is run
