### ISSUE TITLE
Cloudflare WARP Client does not work on Windows on ARM

### ISSUE THREAD

**Issue by jamesyip** [cloudflare/cloudflared#546]
I have a surface pro x. After installing the Cloudflare WARP client, the client cannot activate the WARP or DOH. No issue on x64 version of the Windows. This issue only exists in ARM version of Windows.

**Comment by abelinkinbio** [comment]
@jamesyip Thanks for flagging! As a heads up, this is the issue forum for `cloudflared`, but I have passed this feedback along to the relevant team who can take a better look at this. 

Do you have a support ticket open yet?

**Comment by jamesyip** [comment]
Nope. But then we should change this issue to create cloudflared for Windows on ARM native build.

**Comment by jamesyip** [comment]
Unfortunately we do not have account manager.

**Comment by hajekj** [comment]
I am definitely interested in both cloudflared and WARP for Windows arm64 as well. Even though WARP works for me on ARM64 via the emulation, it still isn't smooth experience.

**Comment by ShotgunPR** [comment]
Hi, I have some Windows Surface using ARM CPUs (for example: Snapdragon(R) X 10-core X1P64100 @ 3.40 GHz). 

Does windows cloudflare client support these fully?

**Comment by kkrum** [comment]
Yes it does.
