### ISSUE TITLE
UDP tunnel support? 

### ISSUE THREAD

**Issue by Albonycal** [cloudflare/cloudflared#548]
I'd be nice to be able to tunnel UDP based services

**Comment by TownLake** [comment]
this is supported today:
https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/

**Comment by Albonycal** [comment]
My bad :sweat_smile: I did read that blog post, but didn't noticed the "wait list" 
Thanks
