### ISSUE TITLE
Super Bot Fight Mode blocks RDP access 

### ISSUE THREAD

**Issue by mastercoms** [cloudflare/cloudflared#556]
Hi, I was having trouble connecting to a tunnel for RDP access and tried all suggested tips. After some luck, I found that this access was blocked in the firewall logs as:

Bot Fight Mode for Definite Bots
manage definite bots

Managed Challenge

So, I set Super Bot Fight Mode: Definitely automated to Allow and it works now.

Is this a documentation issue (should note allowing definite bots is required) or a CloudFlare rules issue (this traffic should not be detected as a bot)? I would prefer keeping the protection for bots, but I suppose I can also split out our domains between our teams and public URLs.

**Comment by abelinkinbio** [comment]
Thanks for flagging this one. This sounds like a rules issue, but we'll take a look and confirm. Also, are you using `cloudflared access` or `warp` on the client side? Do you have a screenshot you'd be able to share of redacted logs as well?

**Comment by mastercoms** [comment]
Thank you! It was `cloudflared access rdp`. Do you want the client logs or firewall logs?

**Comment by jhult** [comment]
We are seeing things like git/[Gitea](https://github.com/go-gitea/gitea) be blocked:

```
git/2.30.1 (Apple Git-130) (Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 21.2.0; darwin x64) vscode/1.63.2 (Visual Studio Code)
```

Query string: `?service=git-upload-pack`
Service: `Bot fight mode`
Action taken: `JS Challenge`

**Comment by jhult** [comment]
Looks like Jenkins build jobs are also being blocked:

Query string: `?delay=0sec`
Service: `Bot fight mode`
Action taken: `JS Challenge`
