### ISSUE TITLE
Version 2022.1.3 shows as version "DEV" in logs

### ISSUE THREAD

**Issue by henworth** [cloudflare/cloudflared#558]
Though the binary install on MacOS shows the correct version, when deployed as a docker container the version is logged as `DEV`:

```2022-01-31T20:45:19Z INF Version DEV```

This is also reflected in the tunnel list in the Cloudflare portal.

**Comment by abelinkinbio** [comment]
Thanks for flagging this one. This is a known issue we're looking into on our end. What does the Zero Trust dashboard show under Access > Tunnels for the Version?

**Comment by henworth** [comment]
I looked into this more, what I've found is that this is due to my custom image that was building from source. I've adjusted this image to use the official one as the base and the portal no longer shows `DEV`. I'm guessing even though I was grabbing source from a tagged release that there's no version information being compiled in?

**Comment by nmldiegues** [comment]
You can grab the sources and commit a released tag:

```
 ▶ make cloudflared
GOOS=darwin GOARCH=amd64 go build -v -mod=vendor  -ldflags='-X "main.Version=2022.3.1" -X "main.BuildTime=2022-03-08-1443 UTC" ' github.com/cloudflare/cloudflared/cmd/cloudflared

▶ ./cloudflared version
cloudflared version 2022.3.1 (built 2022-03-08-1443 UTC)
```

and still get the expected version
