### ISSUE TITLE
Cloudflared dns over https does not support e-sni

### ISSUE THREAD

**Issue by f4nff** [cloudflare/cloudflared#56]
`cloudflared proxy-dns --port 53 --upstream https://cloudflare-dns.com/dns-query`

My catching content is as follows：
![image](https://user-images.githubusercontent.com/19538878/47592998-4f1f8900-d9a8-11e8-8174-9b866e986eb2.png)

**Comment by lib-xdown** [comment]
It’s been a long time, still not realized,
