### ISSUE TITLE
websocket: cloudflared panic

### ISSUE THREAD

**Issue by wloot** [cloudflare/cloudflared#562]
Logs:
```
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdda9a0]
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: goroutine 659 [running]:
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: github.com/cloudflare/cloudflared/origin.(*bidirectionalStream).Read(0xc000594620, {0xc00020e000, 0xc000866750, 0xc0005946f8})
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /cfsetup_build/origin/proxy.go:264 +0x20
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: io.copyBuffer({0x7fa05c287098, 0xc000866750}, {0x7fa05c2870e0, 0xc0007be9c0}, {0x0, 0x0, 0x0})
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /usr/local/go/src/io/io.go:423 +0x1b2
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: io.Copy(...)
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /usr/local/go/src/io/io.go:382
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: github.com/cloudflare/cloudflared/websocket.copyData({0x7fa05c287098, 0xc000866750}, {0x7fa05c2870e0, 0xc0007be9c0}, {0xd4d35f, 0xc000292460})
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /cfsetup_build/websocket/websocket.go:98 +0x35
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: github.com/cloudflare/cloudflared/websocket.Stream.func2()
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /cfsetup_build/websocket/websocket.go:44 +0xa5
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]: created by github.com/cloudflare/cloudflared/websocket.Stream
Feb 06 13:28:33 v2202110158121165328 cloudflared[124423]:         /cfsetup_build/websocket/websocket.go:43 +0x19e
Feb 06 13:28:33 v2202110158121165328 systemd[1]: cloudflared.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 06 13:28:33 v2202110158121165328 systemd[1]: cloudflared.service: Failed with result 'exit-code'.
```

Protocol: 
`quic`

**Comment by nmldiegues** [comment]
Hey @wloot ,

Can you confirm the cloudflared version used?

**Comment by wloot** [comment]
> Hey @wloot ,
> 
> Can you confirm the cloudflared version used?

Sure, it is 2022.2.0.

**Comment by nmldiegues** [comment]
Can you share any insights about the application being proxied that caused this?

We can try to understand and fix the problem, but I'd like to have a representative workload that would trigger this, and so far all our existing tests, load tests, and a few other apps that I've stressed tested, never caused a similar issue.

**Comment by nmldiegues** [comment]
We have done some work/fixes for QUIC protocol transport in both cloudflared and our edge.
Would you mind letting us know how this goes with latest cloudflared version `2022.2.2`?

**Comment by wloot** [comment]
> We have done some work/fixes for QUIC protocol transport in both cloudflared and our edge. Would you mind letting us know how this goes with latest cloudflared version `2022.2.2`?

I still have the panic at the latest cloudflared version `2022.2.2`(btw my usage is to proxy [emby](https://emby.media/) application), and here is log:
```
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdd6cc0]
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: goroutine 328 [running]:
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: github.com/cloudflare/cloudflared/proxy.(*bidirectionalStream).Read(0x1, {0xc000806000, 0xc00030b4d0, 0xc0002f2240})
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /cfsetup_build/proxy/proxy.go:269 +0x20
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: io.copyBuffer({0x7f44843cb670, 0xc00030b4d0}, {0x7f44843cb6f8, 0xc000a36660}, {0x0, 0x0, 0x0})
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /usr/local/go/src/io/io.go:423 +0x1b2
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: io.Copy(...)
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /usr/local/go/src/io/io.go:382
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: github.com/cloudflare/cloudflared/websocket.copyData({0x7f44843cb670, 0xc00030b4d0}, {0x7f44843cb6f8, 0xc000a36660}, {0x100000000000004, 0x0})
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /cfsetup_build/websocket/websocket.go:135 +0x35
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: github.com/cloudflare/cloudflared/websocket.unidirectionalStream({0x7f44843cb670, 0xc00030b4d0}, {0x7f44843cb6f8, 0xc000a36660}, {0x109be75, 0xe}, 0xc000706be0, 0xc00060e1e0)
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /cfsetup_build/websocket/websocket.go:85 +0xd8
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]: created by github.com/cloudflare/cloudflared/websocket.Stream
Feb 25 00:49:49 v2202110158121165328 cloudflared[592969]:         /cfsetup_build/websocket/websocket.go:61 +0x28f
Feb 25 00:49:49 v2202110158121165328 systemd[1]: cloudflared.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 25 00:49:49 v2202110158121165328 systemd[1]: cloudflared.service: Failed with result 'exit-code'.
```

**Comment by nmldiegues** [comment]
How long does it normally take you to reproduce this problem?
What do you do in emby to reproduce it?

I've set it up and have been streaming a video over a Tunnel with QUIC transport protocol for 15min and so far so good.

**Comment by wloot** [comment]
That depends. I share my site with a few friends, so I don't know which exactly action is causing this problem. And if it is able to help you, i use NGINX as a man-in-the-middle between emby and cloudflared. Here are some configuration snippets of nginx:
```
  location = /embywebsocket {
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header Host $host;
    proxy_pass http://emby;
    proxy_http_version 1.1;
    proxy_set_header Upgrade websocket;
    proxy_set_header Connection Upgrade;
  }
```

**Comment by nmldiegues** [comment]
What do you gain with having nginx in the middle?

**Comment by wloot** [comment]
> What do you gain with having nginx in the middle?

I try to modify some responses of emby, actually do not touching websockets. I will test with websocket path bypassed nginx:
```
protocol: quic

ingress:
  - path: /embywebsocket
    service: http://<emby docker ip>:8096
  - path: /socket
    service: http://<emby docker ip>:8096
  - service: unix:/var/run/emby.sock
```

**Comment by nmldiegues** [comment]
It seems you are running emby in docker?  Can you share that setup? (dockerfile, etc...) so that I can reproduce as closely as possible

**Comment by wloot** [comment]
Well, i am using `linuxserver/emby:latest` image, you can find it at dockerhub https://hub.docker.com/r/linuxserver/emby

**Comment by nmldiegues** [comment]
Where does `unix:/var/run/emby.sock` come from in that containerized setup?

**Comment by nmldiegues** [comment]
I'm asking that because I simply do:

```
protocol: quic

ingress:
  - service: http://<emby docker ip>:8096
```

and the whole app seems to work fine over the Tunnel, so I'm trying to figure out if you have anything else that is relevant here to reproducing the issue

I've now set up 10 browsers playing videos in a loop over my Tunnel for the past hour, and it's still not reproducing the problem.

**Comment by wloot** [comment]
The domain socket is listened by nginx. And i doubt that video playback is the action causing the problem, as websocket is seem to not active during the time. I will do some test and try to figure it out.

**Comment by nmldiegues** [comment]
It looks like websocket is used for some user actions (e.g., mark a video as played, or mark it as favourite).

**Comment by wloot** [comment]
I think i know what is going on.

**Comment by nmldiegues** [comment]
Thanks for digging further into this @wloot 

It is becoming more and more apparent that this is reproducible only very specific circumstances. 

Your comments make it sound like it reproduces easily, but no luck for me yet.
Do you think you can provide the full nginx config (on the origin/server side)?
I've taken the snippets above, and I'm now doing `user -> cloudflare edge -> cloudflared -> nginx -> emby` and still unable to reproduce the problem after some time clicking actions to trigger websocket usage (e.g. like videos, mark as seen, etc...) across a few devices/browsers.

Also, why did you add a nginx on the eyeball/user side in your last comment? It's just proxying, with no changes. Why would that influence anything?

**Comment by wloot** [comment]
Hi, client-side nginx is designed to terminate the ws tunnel (the `upgrade` header) to upstream, this is to simulate a broken client. I believe these configurations can help you reproduce the problem

user side(front cloudflare edge) nginx config:
```
server {
    listen 80;
    server_name <another domain>;

    location / {
      proxy_set_header Host <my emby domain>;
      proxy_pass http://<my emby domain>;
    }
}
```

cloudflared config:
```
protocol: quic

ingress:
  - service: unix:/var/run/emby.sock
```

nginx behind cloudflared config:
```
server {
  listen unix:/var/run/emby.sock;
  server_name <my emby domain>;

  location / {
    proxy_pass http://<emby docker ip>:8096;
  }

  location = /embywebsocket {
    proxy_pass http://<emby docker ip>:8096;
    proxy_http_version 1.1;
    proxy_set_header Upgrade websocket;
    proxy_set_header Connection Upgrade;
  }
  location = /emby/embywebsocket {
    proxy_pass http://<emby docker ip>:8096;
    proxy_http_version 1.1;
    proxy_set_header Upgrade websocket;
    proxy_set_header Connection Upgrade;
  }
}

```

**Comment by nmldiegues** [comment]
I've used exactly the set up you described on your last post, and I still cannot reproduce any problem.

Do you think you can provide a minimal reproducing example that I can literally copy paste and reproduce the issue?

**Comment by wloot** [comment]
It's so weird as I get the panic every time....

**Comment by nmldiegues** [comment]
Unless there's a minimal reproducing example I can use, I'm afraid my hands are stuck here.

Feel free to re-open should that change.
