### ISSUE TITLE
[Feature request] Railgun™ into Cloudflared

### ISSUE THREAD

**Issue by Meister1977** [cloudflare/cloudflared#564]
Do Cloudflare has a plan to add Railgun™ into the client app?
I think, it would be a huge boost to the speed of the dynamic web sites.
https://www.cloudflare.com/website-optimization/railgun/

**Comment by abelinkinbio** [comment]
Many of the initial benefits of Railgun have been incorporated into our network as we've expanded over time. We do not have any current plans to directly integrate Cloudflare Tunnel + Railgun.
