### ISSUE TITLE
DNS forwarding by static IP to DNS server over WARP tunnel

### ISSUE THREAD

**Issue by RyanPrice-King** [cloudflare/cloudflared#568]
#515 
I think I have misinterpreted something here. I can not get what I wanted to work. I needed DNS forwarding to DNS resolver at the WARP tunnel end, not client end.

Client connects WARP -> Client forwards DNS query over WARP tunnel to DNS server.
The DNS Fallback stops requests even going down the WARP tunnel. So is not a solution for me.

Is this still something that wont work?

**Comment by nmldiegues** [comment]
```
Client connects WARP -> Client forwards DNS query over WARP tunnel to DNS server.
```

This is exactly what became possible in the link provided in #515 

Let's say you define mydomain.private as a DNS Fallback with IP 10.1.0.13
Then you add a IP Route of 10.1.0.13/32 (or any superset of that) that points to a Cloudflare Tunnel with warp-routing enabled and reachability to 10.1.0.13.
When WARP/Teams enabled clients in your account do DNS resolution for mydomain.private, that will send a UDP resolution to your private DNS Resolver at 10.1.0.13 through: WARP client -> Cloudflare -> cloudflared tunnel -> 10.1.0.13

**Comment by RyanPrice-King** [comment]
oh whoops, yeah it does work.  I think i had not restarted the WARP client to apply the change.  Sorry about that :).

On a different note though, as UDP is not working, is there any way to be able to get pings to function over WARP also?

**Comment by nmldiegues** [comment]
Ping through WARP to the Internet works.
But ping through WARP to a Tunnel private origin is not yet supported.

Ping works with ICMP, which is not dependent on TCP nor UDP. 
So having UDP now enables things such as DNS resolution (and other protocols that sit on top of UDP), but does not mean anything to ping.

I'll close this issue since it's key concern is addressed.

**Comment by RyanPrice-King** [comment]
ok thankyou and sorry to bother you with this.  Do you have any idea when ICMP might work?
