### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by yoderme** [cloudflare/cloudflared#569]
It would be really nice if there were a helm chart to deploy the cloudflared in kubernetes.

I created one based on the example in a yaml file at https://github.com/cloudflare/argo-tunnel-examples/tree/master/named-tunnel-k8s

Is this something the maintainers of this repo would be interested in?

**Comment by nmldiegues** [comment]
Sounds like a good idea. Thanks for the initiative.

**Comment by nmldiegues** [comment]
Handled by https://github.com/cloudflare/argo-tunnel-examples/issues/16#event-6069481048
