### ISSUE TITLE
update repository for new Apache 2.0 license

### ISSUE THREAD

**Issue by pabs3** [cloudflare/cloudflared#573]
Thanks for making cloudflared an open source project in #464.

@abe There is more to do than just updating the website, so I've opened this issue for fixing the remaining issues.

You need to update the `LICENSE` file in this repository to [the official plain text copy of the Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt).

You need to update the references to the license name in these two files:

 * replace `Cloudflare Service Agreement` with `Apache License Version 2.0` in the `Makefile`
 * replace `Cloudflare License` with `Apache License Version 2.0` in `cmd/cloudflared/main.go`

Presumably the Cloudflare Access service has a different license to the cloudfared project, so there should be some link to the Cloudflare Access service agreement from the README or elsewhere.

**Comment by nmldiegues** [comment]
Thanks for looking into this @pabs3 

Abe will provide feedback next week on these issues.

**Comment by abelinkinbio** [comment]
@nmldiegues thanks for the nudge on this one. 

@pabs3 We've reviewed these changes with our team and should have these updates out shortly.

**Comment by pabs3** [comment]
@abelinkinbio excellent, please do make sure that you mention the
Cloudflare Access service agreement too. I also recommend mentioning
the Cloudflare Access privacy policy if there is one of those too.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by septatrix** [comment]
Is there anything left after c54e8cd8e62e2b551bcedff0c25a80f4ec0f38fa?

**Comment by abelinkinbio** [comment]
As Cloudflare Access and Cloudflare Tunnel are distinct products we shouldn't need to call it out here. I'll close this issue out and flag it internally. We'll get the readme updated in the meantime!

Oh, and thank you @pabs3!

**Comment by pabs3** [comment]
@abelinkinbio I was confusing the two services, woops! Substitute
Cloudflare Access in my messages for Cloudflare Tunnel and they will
probably make more sense.

Since cloudflared isn't useful in any way without accessing the
Cloudflare Tunnel service, the terms of service for Cloudflare Tunnel
should be linked from the README, otherwise people will be affected by
an agreement that they have not read.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
