### ISSUE TITLE
Cloudflared pkg for Debian 11 Bullseye?

### ISSUE THREAD

**Issue by neilpanchal** [cloudflare/cloudflared#576]
### Debian 11 support
Not sure if this is the place to report or ask, but wanted to inquire when do expect `cloudflared` pkg to be available for Debian 11 (Bullseye)?

### Install instructions on https://pkg.cloudflare.com/
But, it shows that there is no support for Debian 11 (bullseye) on the main page:

<img width="888" alt="Screen Shot 2022-02-18 at 9 10 14 AM" src="https://user-images.githubusercontent.com/8161031/154729954-c0c34398-a72e-47da-8e7d-0b87246af262.png">

Since Bullseye release has been out since Sept 2021, perhaps this is an actual issue with Debian 11 support?

There is a thread on Reddit as well: https://old.reddit.com/r/CloudFlare/comments/pnpfru/cloudflared_debian_11/

Support ticket on Cloudflare seems to be closed without a comment or explanation: https://community.cloudflare.com/t/cloudflare-package-repo-debian-bullseye-support/340417

Ofcourse there are ways to install `cloudflared` on Debian 11, but apt repository seems to be the easiest to keep the client up-to-date.

**Comment by nmldiegues** [comment]
We'll likely have an update soon on this. @abelinkinbio  can help with more details

**Comment by fancsali** [comment]
I am having the same issue, apt is report this:

```
Reading package lists... Done                                                                                                                                                                                                                                    
E: The repository 'https://pkg.cloudflare.com bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I can't remember the debian repo layout by heart, so I haven't checked manually, but I can only assume the whole dists/bullseye directory is either missing or not complete yet.

Please do look into this.

**Comment by metjm** [comment]
running into the same issue

**Comment by neilpanchal** [comment]
@nmldiegues @abelinkinbio Any update on this? I presume this is a matter of publishing to the repository. Cloudflared runs and maintains our services and it is crucial to have it automatically update through the `apt` package manager.

**Comment by abelinkinbio** [comment]
@neilpanchal unfortunately we haven't been able to pick this work up quite yet. That said, we are still planning to get to this shortly and will provide updates on this thread. Thanks for your patience.

**Comment by eximius313** [comment]
Although `cloudflared` is available for the `ARM64` architecture, it's - unfortunately - not present in the `Cloudflare Package Repository`. 
Do you have plans to add it along with `Debian 11 (bullseye)` support?

**Comment by drpoutine** [comment]
> Although `cloudflared` is available for the `ARM64` architecture, it's - unfortunately - not present in the `Cloudflare Package Repository`. Do you have plans to add it along with `Debian 11 (bullseye)` support?

+1 to this. The builds are always here but its not on debian 11 for arm/armhf and arm64 on the debian repo, nor is there a bullseye repo. can it be added soon™ please so it can also keep itself up to date via apt in those systems?


i feel like this issue has been pushed down the road for some time now 🤔

**Comment by nmldiegues** [comment]
As @abelinkinbio  said, this is really happening soon™
Stay tuned.

**Comment by neilpanchal** [comment]
@sudarshan-reddy Not familiar with the underlying root cause and what it takes to distribute apps on Debian registries, but, I hope it gets fixed in a way that doesn't need manual intervention everytime a new Debian release comes along. Thanks so much for taking on this.

**Comment by sudarshan-reddy** [comment]
It would likely be a one time setup that you'd generally do when adding a new apt repository @neilpanchal . We have an internal beta testing repo and will soon have this out for you guys.

**Comment by Compr0mzd** [comment]
+1

**Comment by docbrinkmann** [comment]
+1

**Comment by sudarshan-reddy** [comment]
Here's a beta link to try this. Add sudo wherever necessary. 

``` 
mkdir -p --mode=0755 /usr/share/keyrings
curl https://pkg-beta.try.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg-beta.try.cloudflare.com/cloudflared bullseye main' >  /etc/apt/sources.list.d/cloudflared.list
apt-get update
 
apt-get install cloudflared
```

**Comment by neilpanchal** [comment]
> Here's a beta link to try this. Add sudo wherever necessary.
> 
> ```
> mkdir -p --mode=0755 /usr/share/keyrings
> curl https://pkg-beta.try.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
> echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg-beta.try.cloudflare.com/cloudflared bullseye main' >  /etc/apt/sources.list.d/cloudflared.list
> apt-get update
>  
> apt-get install cloudflared
> ```

Just tried it:

```bash
■ ~ / ➞  sudo apt install cloudflared
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  cloudflared
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 14.9 MB of archives.
After this operation, 32.0 MB of additional disk space will be used.
Get:1 https://pkg-beta.try.cloudflare.com/cloudflared bullseye/main amd64 cloudflared amd64 7e8922b8 [14.9 MB]
Fetched 14.9 MB in 3s (4920 kB/s)
Selecting previously unselected package cloudflared.
(Reading database ... 33352 files and directories currently installed.)
Preparing to unpack .../cloudflared_7e8922b8_amd64.deb ...
Unpacking cloudflared (7e8922b8) ...
Setting up cloudflared (7e8922b8) ...
Processing triggers for man-db (2.9.4-2) ...
■ ~ / ➞  cloudflared -v
cloudflared version 7e8922b8 (built 2022-06-22-1619 UTC)
```

Very nice!

Says the version is `7e8922b8`. I presume this would be ok for production use? I checked the commit hash in the releases and couldn't find it.

**Comment by eximius313** [comment]
Installation is successful, but the purging (`dpkg --purge cloudflared`) does not clean the service
```
$ ls /etc/systemd/system/cloudflared*
cloudflared.service 
cloudflared-update.service  
cloudflared-update.timer
```

nor config files:
```
$ ls /etc/cloudflared/
config.yml
```

So after reinstall (`apt-get install --reinstall cloudflared`) when one tries to install new service, they get:
```
cloudflared service is already installed at /etc/systemd/system/cloudflared.service; if you are running a cloudflared tunnel, you can point it to multiple origins, avoiding the need to run more than one cloudflared service in the same machine; otherwise if you are really sure, you can do `cloudflared service uninstall` to clean up the existing service and then try again this command
```

**Comment by sudarshan-reddy** [comment]
Did you try ‘cloudflared service uninstall’ ?

**Comment by eximius313** [comment]
Sure, but I think , but I think that `post-removal script` should handle that.

Moreover - I was getting weird errors while trying to `systemctl disable cloudflared`:
```
Unit /etc/systemd/system/cloudflared.service is masked, ignoring.
```

**Comment by sudarshan-reddy** [comment]
You're correct. Do you wanna open a separate issue to track that?

**Comment by eximius313** [comment]
Sure. Here it is: https://github.com/cloudflare/cloudflared/issues/686

**Comment by drpoutine** [comment]
> Here's a beta link to try this. Add sudo wherever necessary.
> 
> ```
> mkdir -p --mode=0755 /usr/share/keyrings
> curl https://pkg-beta.try.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
> echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg-beta.try.cloudflare.com/cloudflared bullseye main' >  /etc/apt/sources.list.d/cloudflared.list
> apt-get update
>  
> apt-get install cloudflared
> ```

Does this include the ARMHF and ARM64 builds as well?

**Comment by truls1502** [comment]
I was wondering how is going with this issue, or do we have any official roadmap or checklist for when this OS should be supported? What is the blocker at the moment, and is there somewhere we, contributors, can help with moving on the case? Is it #686 or a different one? 🤓

**Comment by sudarshan-reddy** [comment]
The beta packaging endpoint should support the combinations that gh binaries exist for  today. We’re trying to get this moved to the official endpoint sometime this week or the next. 

Is there something specific you need?

**Comment by sudarshan-reddy** [comment]
And of course! You can always help make this process better. Feel free to have a look at that issue! I can help you along the way if you need context or guidance.  :)

**Comment by truls1502** [comment]
I just wanted to get this OS Debian Bullseye supported since several of our machines are using Bullseye instead of Buster. I have been following this issue for a couple of weeks. 😊 So, I don't want only to watch the issue but step in and help if there is a possibility. 

However, concerning my previous comment, do you have some guidance on what is needed to get an OS version officially supported, like an official checklist or any documentation that might be completed before creating an officially supported package? 

If yes, I would be happy to know what is the remaining tasks if you could enlighten me. 

If not, let me know what is missing to do now. So, I can see if I can contribute something from my side to help this case. 🤓

**Comment by drpoutine** [comment]
> Here's a beta link to try this. Add sudo wherever necessary.
> 
> ```
> mkdir -p --mode=0755 /usr/share/keyrings
> curl https://pkg-beta.try.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
> echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg-beta.try.cloudflare.com/cloudflared bullseye main' >  /etc/apt/sources.list.d/cloudflared.list
> apt-get update
>  
> apt-get install cloudflared
> ```

Confirmed working `Linux DietPi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux` using info above. Installed `cloudflared version 2022.7.1 (built 2022-07-06-1248 UTC)` via apt.


**For previous manual installations of `cloudflared`, use `dpkg --purge cloudflared`.** 

added the repo by `sudo su -` since thats how i have it setup. but once the repo is added any user systemwide should beable to use it.

**Comment by sudarshan-reddy** [comment]
This should go live sometime today or tomorrow. Let's track it here: https://github.com/cloudflare/cloudflared/issues/719.
