### ISSUE TITLE
Running cloudflared with no arguments gives a "bad file descriptor" error

### ISSUE THREAD

**Issue by jpeach** [cloudflare/cloudflared#578]
**Describe the bug**

```
% cloudflared
bad file descriptor
```

**To Reproduce**

See above

**Expected behavior**

Probably with no arguments, I would expect `cloudflared` to emit a usage error. If the no-argument version does something different that requires a file descriptor somewhere, I'd expect that to be mentioned in the help output.

**Environment and versions**
 - OS: macos
 - Architecture: M1
 - Version: cloudflared version 2022.2.0 (built 2022-02-04-1103 UTC)

**Logs and errors**

N/A

**Additional context**

N/A

**Comment by n8felton** [comment]
+1

Came to add that `~/Library/Logs/com.cloudflare.cloudflared.err.log` is flooded with `bad file descriptor` after doing `cloudflared service install`

**Comment by DevinCarr** [comment]
This is no longer the case on macOS arm64 builds, it should accurately report: `unable to find config file` if none is available in the current directory. Please feel free to reopen this PR if you are still running into the issue with the latest cloudflared

**Comment by dcohenb** [comment]
Still happening version 2023.8.2
macOS Ventura 13.5.2 (M2 Pro)

```
$ cloudflared
bad file descriptor

$ cloudflared version
cloudflared version 2023.8.2 (built 2023-08-31-1503 UTC)
```

**Comment by ammmir** [comment]
still happening on cloudflared version 2025.2.1 (built 2025-02-26T16:44:32Z)
