### ISSUE TITLE
i386 deb package doesn't work

### ISSUE THREAD

**Issue by yuzuriha-shu** [cloudflare/cloudflared#579]
The package does not work on a debian distrib.

**To Reproduce**

1. Downloaded **cloudflared-linux-386.deb** from the GitHub release page.
2. I tried to install the package with `sudo dpkg -i cloudflared-linux-386.deb`
3. Printed the following error _"package architecture (386) does not match system architecture (i386)"_.

**Environment and versions**

 - OS: Debian GNU/Linux 10 (buster)
 - Architecture: x86 (i386)

**Logs and errors**

sudo dpkg -i cloudflared-linux-386.deb
dpkg: error processing cloudflared-linux-386.deb file (--install):
 package architecture (386) does not match system architecture (i386).
Errors were encountered while processing:
 cloudflared-linux-386.deb

**Comment by antivodonik** [comment]
There is a workaround by doing
`sudo dpkg --add-architecture 386`
and then installing it with dpkg
