### ISSUE TITLE
Can't connect via SSH, `banner line contains invalid characters`

### ISSUE THREAD

**Issue by nihaals** [cloudflare/cloudflared#581]
**Describe the bug**
When I SSH to my host I get:
```
$ ssh ssh.example.com
kex_exchange_identification: banner line contains invalid characters
banner exchange: Connection to UNKNOWN port 65535: invalid format
```

**To Reproduce**
1. SSH to a host
2. Notice error
3. Go to the web SSH page (`https://ssh.example.com` in a browser) and login
4. Notice it works

`~/.ssh/config`
```
UseKeychain yes

Host ssh.example.com
    ProxyCommand /opt/homebrew/bin/cloudflared access ssh --hostname %h
```

**Expected behavior**
SSH works.

**Environment and versions**
Client:
- OS: macOS 12.2.1
- Architecture: Apple Silicon
- Version: `cloudflared version 2022.2.2 (built 2022-02-23-0847 UTC)`

Server:
- OS: Arch Linux
- Architecture: x86_64
- Version: `cloudflared version 2022.1.2 (built 2022-01-13-1311 UTC)`

**Comment by nmldiegues** [comment]
Is my understanding correct that you have an Access Application requiring authentication for users accessing your hostname?
If so, can you (briefly) remove that and try this to see if it works without Access?

**Comment by nihaals** [comment]
Yes, I currently have a Cloudflare Tunnel going to `ssh.example.com`, with an Access Application in front of `ssh.example.com`.

I changed the hostname of the Access Application (so it would go directly to the Tunnel) and I got the same error.

**Comment by nmldiegues** [comment]
Your using the same cloudflared (for access and tunnel) in that same environment/machine?

**Comment by nihaals** [comment]
I'm SSHing from a different machine, the server's on Linux and the client's on macOS.

**Comment by nmldiegues** [comment]
Is this the first time you have set up a Tunnel for SSH?  Or was this working before?

Have you tried with the in-browser rendered client? https://developers.cloudflare.com/cloudflare-one/tutorials/ssh-browser

**Comment by nmldiegues** [comment]
> I'm SSHing from a different machine, the server's on Linux and the client's on macOS.

And what's the cloudflared version and architecture in each case?

**Comment by nihaals** [comment]
Server: `cloudflared version 2022.1.2 (built 2022-01-13-1311 UTC)` amd64 Linux
Client: `cloudflared version 2022.2.2 (built 2022-02-23-0847 UTC)` arm64 macOS

**Comment by nihaals** [comment]
> Is this the first time you have set up a Tunnel for SSH? Or was this working before?

This was working a few days ago with no changes (that I can think of) on the server.

> Have you tried with the in-browser rendered client?

This works fine.

**Comment by nihaals** [comment]
Somehow removing and re-adding the Access Application seems to have fixed it (with the same config, I only changed the hostname off and back). Does this need further investigation still?

**Comment by nihaals** [comment]
Also, additional context, I had the issue for at least 24 hours, so it seems changing the Access Application did make the difference.

**Comment by nmldiegues** [comment]
Yeah, based on the problem presented in the first comment of the issue, I had a hunch this was due to Access (and not the cloudflared daemon itself).

If the problem reappears, the right way to go would be to open up a support ticket with Cloudflare.
