### ISSUE TITLE
Unknown field when attempting to build for mips

### ISSUE THREAD

**Issue by Sammy1Am** [cloudflare/cloudflared#582]
When attempting to build cloudflared for the mips architecture using this Docker command:

`docker run --rm -v "C:\Users\Me\cloudflared":/usr/src/myapp -w /usr/src/myapp -e GOOS=linux -e GOARCH=mips golang bash -c "go get -v github.com/cloudflare/cloudflared/cmd/cloudflared; GOOS=linux GOARCH=mips go build -v -x github.com/cloudflare/cloudflared/cmd/cloudflared"`

I'm getting the following error:
`github.com/cloudflare/cloudflared/origin/go/pkg/mod/github.com/cloudflare/cloudflared@v0.0.0-20220128151037-e09dcf6d6097/origin/tunnel.go:532:3: unknown field 'MaxDatagramFrameSize' in struct literal of type "github.com/lucas-clemente/quic-go".Config`

As far as I can tell `MaxDatagramFrameSize` actually *does not* exist in the quic-go library being referenced, so the error makes sense in that regard.  But since the regular builds / releases seem to still be working fine, I'm hoping someone might have some thoughts about what's going on.

**Comment by nmldiegues** [comment]
I've tried it out simply with:
```
GOOS=linux GOARCH=mips go build -v -mod=vendor github.com/cloudflare/cloudflared/cmd/cloudflared
```

Which worked out fine on latest master branch.  Can you confirm this?

**Comment by Sammy1Am** [comment]
Update:
The command provided by @nmldiegues worked great after cloning the git repo (the key seemed to be the `-mod=vendor` bit.  I'm not sure how people were able to do it using `go get`, but that seems to conflict with `-mod=vendor` somehow so it wasn't working.

Appreciate the help!
