### ISSUE TITLE
Cannot install .deb package on RaspberryPi 2B (armv7/armhf)

### ISSUE THREAD

**Issue by fancsali** [cloudflare/cloudflared#583]
**Describe the bug**
Trying to install the official `.deb` package downloaded from github, the installation fails due to architecture mismatch.

**To Reproduce**
1. Download packge
2. Try to install: `dpkg -i cloudflared-linux-arm.deb`
3. The package manager complains about the architecture not matching. (`arm` vs `armhf`)

**Expected behavior**
The package should install.

**Environment and versions**
 - OS: Raspberry Pi OS 11.2 (bullseye) -- official image
 - Architecture: armv7l (armhf)
 - Version: 2022.2.2 (latest as of creating the ticket)

**Logs and errors**
```
# dpkg -i cloudflared-linux-arm.deb
dpkg: error processing archive cloudflared-linux-arm.deb (--install):
 package architecture (arm) does not match system (armhf)
Errors were encountered while processing:
 cloudflared-linux-arm.deb
```

**Additional context**
I might be wrong here, but the package claims to be for the `arm` architecture; however, looking at the Debian docs (https://www.debian.org/releases/stretch/armhf/ch02s01.html.en#idm268) the three valid architecture symbolic names are: `armel` and `armhf`, `arm64`. Or am I missing something?

**Comment by matgad** [comment]
Hi @fancsali. I had the same issue and I solved with:
`dpkg --add-architecture arm`
forcing the system to install `arm` packages.

Not the most elegant solution, but it may be a temporary workaround. Anyway, I agree that the correct architecture should be changed to `armhf` for the next releases.

**Comment by LeoWinterDE** [comment]
Relates to #359

**Comment by sudarshan-reddy** [comment]
This should now be fixed. Can you check https://github.com/cloudflare/cloudflared/issues/359#issuecomment-1160499777 ?

**Comment by fancsali** [comment]
Just as a follow-up thought: will this make into the official repository (https://pkg.cloudflare.com/#debian-title)? I can't even see `buster` there, to be honest...

**Comment by sudarshan-reddy** [comment]
it will and is already being tracked at: https://github.com/cloudflare/cloudflared/issues/576
