### ISSUE TITLE
real client_ip inside `X-Forwarded-For` in case of using warp routing to connect private networks

### ISSUE THREAD

**Issue by cageyv** [cloudflare/cloudflared#598]
**Describe the feature you'd like**
Send real client_ip inside `X-Forwarded-For` in case of using warp routing to connect private networks
this will allow the systems behind cloudflared to display this information in the logs for a better understanding of where the request came from, as well as use all other logic based on real client_ip

**Describe alternatives you've considered**

**Additional context**
- something similar was discussed earlier here: #492 
- my case is request tracing. without this information, it turns out that all requests came from cloudflared daemon :)

**Comment by k235vg** [comment]
To buy referal the system ask me i must getbpay cide but i cant get howi do? Pleas help me

**Comment by k235vg** [comment]
To buy referal the system ask me i must get pay  code but i cant get how i do? Pleas help me

**Comment by cageyv** [comment]
This issue is still actuals.

**Comment by cageyv** [comment]
Looks like that this is not an issue anymore or require additional time to verify. Anyway I'm going to close that issue.
