### ISSUE TITLE
Ability to bind on more than one interface or ip possible?

### ISSUE THREAD

**Issue by lfxc** [cloudflare/cloudflared#6]
I saw in the example  binding to localhost.  I'm trying to figure out how to bind to multiple interfaces as dnsmasq can do, i.e., eth0, tun0, etc.., or to listen on all ip's.  thx!

**Comment by vavrusa** [comment]
Hey, right now it can't listen to more than one interface. You can however listen on all addresses:

```
$ cloudflared proxy-dns --address 0.0.0.0 --upstream https://1.1.1.1/dns-query
INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml
INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://0.0.0.0:53"
INFO[0000] Starting metrics server                       addr="127.0.0.1:55230"
```

If you use it as a service, you can add `proxy-dns-address: 0.0.0.0` to the config file,
see https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/

**Comment by lfxc** [comment]
thanks!

Can it listen on and ipv6 address?

**Comment by vavrusa** [comment]
Yes: `cloudflared proxy-dns --address ::`

**Comment by lfxc** [comment]
Sorry, I should have asked if it can listen on both ipv4 and ipv6 at the same time

**Comment by vavrusa** [comment]
Yes, it supports dual-stack, so if you bind to `::` it will also bind to all IPv4 addresses.
