### ISSUE TITLE
ARMv8 builds

### ISSUE THREAD

**Issue by mnaser** [cloudflare/cloudflared#60]
While ARMv6 is popular, aarch64 (armv8) is pretty neat and used in a lot of modern hardware, it'd be nice for CloudFlare to publish builds for that.

We can provide some infrastructure if necessary.

**Comment by moderation** [comment]
I installing / building cloudflared on aarch64 (Rock64 and RockPro 64) without issue. `go get -u github.com/cloudflare/cloudflared/cmd/cloudflared`

**Comment by mnaser** [comment]
@moderation 

Interesting -- We're trying to see how we can get this integrated to our Ansible playbooks, so RPMs are pretty easy to add there vs maintaining our own locally built $foo

**Comment by sssilver** [comment]
@moderation did you build it with CGO?

**Comment by moderation** [comment]
I don't recall having to set any configuration. I just build using `go get -u github.com/cloudflare/cloudflared/cmd/cloudflared` and run as a systemd service.

**Comment by fuelflo** [comment]
+1 for the port to aarch64

**Comment by MadSpindel** [comment]
Any updates on this?

**Comment by cadroguett** [comment]
any news on this?

**Comment by jjssoftware** [comment]
I tried and failed to build this for armbian aarch64 on a nanopi neo2. My attempts were with go v1.12.6 (the latest at the time of writing) and with `go get -u github.com/cloudflare/cloudflared/cmd/cloudflared`

After some time, my build attempts unfortunately fail with an out of memory error.

An official aarch64/armv8 version pre-built here would be really really nice and very much appreciated: https://developers.cloudflare.com/argo-tunnel/downloads/

**Comment by Zer0CoolX** [comment]
Any word on this?

I would love to see official download links for this.

I cannot even find directions for how I could potentially compile aarch64 for myself, if anyone has directions I would be interested.

Thanks

**Comment by moderation** [comment]
@Zer0CoolX I'm building on a Pine64 Rock64 and RockPro64 aarch64 boards with no issues with a simple `go get -u github.com/cloudflare/cloudflared/cmd/cloudflared`. Both of these boards have 4GB of RAM so I'm not hitting the memory issues others are having. Having said that I'm running the same command without issue on a Raspberry Pi too (but that is not aarch64).

**Comment by jjssoftware** [comment]
There's a really helpful comment here from @bcatubig: https://github.com/cloudflare/cloudflared/issues/115#issuecomment-521092436

After trying and failing to get this to build targetting aarch64 due to resource constraints with my nanopi neo2 as the build device, I followed this approach and have got this to successfully build using a full fat amd64 linux distro that targets aarch64 with `go build`

Thank you @bcatubig, very much appreciated.

**Comment by danacr** [comment]
@jjssoftware @Zer0CoolX here you go: https://github.com/danacr/drone-cloudflared

let me know if you want me to actually support this

**Comment by jjssoftware** [comment]
Nice work @danacr. This issue is resolved for me now personally since I was able to build for arm64 as described in my previous comment. Your [drone-cloudflared repo](https://github.com/danacr/drone-cloudflared) might still be useful for other people though.

**Comment by samuelaguilera** [comment]
@danacr Thank you a lot man! I don't know if you're going to get a community for your builds, but since months trying to make CloudFlare DNS-Over-HTTPS working on my pihole (over an Orange Pi Win board), thanks to your build it's finally working.

**Comment by QC-FreAk** [comment]
Chiming in, you saved my bacon, building the same thing for my home network.

**Comment by danacr** [comment]
@samuelaguilera @jjssoftware @QC-FreAk I just had the time to fully automate the repository. Now it creates the appropriate releases. Feel free to update your versions when needed.

**Comment by samuelaguilera** [comment]
Great news! Thanks @danacr

**Comment by yieme** [comment]
@ cloudflare when is this going to be available at https://developers.cloudflare.com/argo-tunnel/downloads/ ???

**Comment by sodabrew** [comment]
edc6969 was merged in time for the 2020.8.0 release, please see https://github.com/cloudflare/cloudflared/releases for recent releases with an arm64 build.

**Comment by TownLake** [comment]
Closing this request with the latest releases; please open a new ticket if you run into issues with the new builds. Thanks for the feedback.
