### ISSUE TITLE
Add repo for CentOS 8, CentOS Stream and Fedora

### ISSUE THREAD

**Issue by septatrix** [cloudflare/cloudflared#601]
**Describe the feature you'd like**
A repo should be added for the newer CentOS versions and Fedora. The currently supported CentOS releases all reached EOL.

**Describe alternatives you've considered**
Always fetch the latest release from github manually

**Comment by sudarshan-reddy** [comment]
This is now done: https://pkg.cloudflare.com/#centos-8 says 8 but the same will work for 9 too.

**Comment by septatrix** [comment]
I just tested it on Fedora 35 Server Edition and it seem to work without problems there too
