### ISSUE TITLE
Allow choice of DoH or DoT

### ISSUE THREAD

**Issue by seamooose** [cloudflare/cloudflared#61]
I have cloudflared deployed within a relatively locked down network where external connections are limited. 

Internal servers and clients are provided with the cloudflared servers for public DNS resolution, and from there DoH hits cloudflare for secure requests. However this has created minor problems in some client environments where traffic profiling is performed. The profiling is basic but effective. It is primarily based on protocol/port and acts as a means to determine what services are consuming bandwidth on any given day. As a result, there is no way to distinguish between DNS and HTTPS traffic.

With this in mind, it would be great if we could have additional options added to cloudflared to support DoT (instead of just DoH). This would make it easier to lock down outbound connections (ie to port 853) and also profile traffic accordingly.

Thanks.

**Comment by cnmade** [comment]
I have similar problem, How to configure cloudflared by using DOT(DNS over TLS) instead DOH (DNS over HTTPS)
because we have problem on HTTPS default port.
