### ISSUE TITLE
Option to Display Team Name Instead of Zero Trust when logged into Warp with a Cloudflare Zero Trust Account

### ISSUE THREAD

**Issue by baustinceltic** [cloudflare/cloudflared#616]
**Describe the feature you'd like**
It would be nice if it was possible to have the team name (or other custom text) displayed instead of "Zero Trust" when logging into Warp with a Cloudflare Zero Trust account. 

**Additional context**
When rolling this out to end users we've found that some users are unaware that they're either not logged into their account or if they are that the Gateway protected resources are available based on the "Zero Trust" message.  We believe it would be a better indication to users that they can now access company protect resources if the Team/Company name was displayed there instead.

![Replace with Team Name](https://user-images.githubusercontent.com/35930209/162236953-cd700d19-141d-44e0-8da6-d0a23455c6b9.png)

Rep

**Comment by nmldiegues** [comment]
@kkrum  will take in this feedback for the Zero Trust client team

I'll close the issue as that is not specific to cloudflared open source project
It's probably best to share this type of feedback in https://community.cloudflare.com/ when the Cloudflare product is not mapping to an open source project
