### ISSUE TITLE
Windows Installer Doesn't Install

### ISSUE THREAD

**Issue by sosensible** [cloudflare/cloudflared#619]
**Describe the bug**
First, windows did not want to keep the file, had to OK it twice.

Second, the cloudflared-windows-amd64.exe file when executed opens a terminal window and sits there doing nothing. I also tried to approach it from administrator access, this includes opening Windows Terminal with Administrator access and executing it from the command prompt in PowerShell.

**To Reproduce**
See above

**Expected behavior**
Immediately when launched from the file browser a terminal window is opened doing nothing. When opening from the terminal the line returns and it just sits there.

**Environment and versions**
Edition	Windows 11 Pro
Version	21H2
Installed on	‎12/‎30/‎2021
OS build	22000.556
Processor	Intel(R) Celeron(R) N5095 @ 2.00GHz 
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by sudarshan-reddy** [comment]
‘cloudflared-windows-amd64.exe’ isn’t an installer but the full executable. Have you tried using it on a power shell or command line?

**Comment by sosensible** [comment]
Awesome, working. Still need to find the installer, yes. Spending too much time in Linux, should have spotted that.

**Comment by sosensible** [comment]
Awesome, working. Still need to find the installer, yes. Spending too much time in Linux, should have spotted that.
