### ISSUE TITLE
Publish official docker image

### ISSUE THREAD

**Issue by tanner-bruce** [cloudflare/cloudflared#62]
Hey guys, it would be nice if an official docker image was published for cloudflared. I wrote a rudimentary Dockerfile that I will submit a PR for.

**Comment by hazcod** [comment]
Better option (scratch image): https://github.com/hazcod/argo/blob/master/Dockerfile

**Comment by crazy-max** [comment]
I have created a [multi-platform Docker image](https://github.com/crazy-max/docker-cloudflared) if you are interested.

```
$ docker run --rm mplatform/mquery crazymax/cloudflared:latest
Image: crazymax/cloudflared:latest
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x
```

**Comment by evaldasou** [comment]
@tanner-bruce  why You closed this? It seems there is still not official docker image for cloudflared.
I see people wrote multiple examples on how to do this and there was like 3 issues created about this.

Is it so hard for a company like cloudflare to push docker image to their official repository? Does it take a year or two for such simple thing to do? :)

**Comment by P4sca1** [comment]
There is a Dockerfile in this repo, which builds cloudflared.
Why are images not published to https://hub.docker.com/u/cloudflare?

**Comment by TownLake** [comment]
Quick update: we now have a supported and published image:
https://hub.docker.com/r/cloudflare/cloudflared
available on DockerHub

**Comment by crazy-max** [comment]
@TownLake Are you interested about a PR to handle [multi-platform Docker image](https://github.com/crazy-max/docker-cloudflared#multi-platform-image)?

**Comment by neutrongenious** [comment]
no instructions included, my container is going into CrashLoopBackOff

**Comment by Michael9127** [comment]
@neutrongenious What do the logs show?
