### ISSUE TITLE
Increase 100 connections per tunnel limit?

### ISSUE THREAD

**Issue by voarsh2** [cloudflare/cloudflared#620]
**Describe the feature you'd like**
Can the 100 connections per tunnel limit be increased?
Or is the only option to create multiple separate tunnels leading to the same service.

Automatic setup (docker) doesn't allow allows the same domain to have multiple tunnels as it already exists..... so it has to be setup manually...)
![image](https://user-images.githubusercontent.com/60437695/162553461-d37ba41b-a8aa-4fc4-aea5-060b0ffbf8dc.png)

**Context**
I haven't confirmed, but doesn't this limit actively limit and slow down the time it takes to get a connection to cloudflared if you have 100 concurrent users/connections?

If the limit can't be increased, and automatic setup with docker where you can manage the tunnel thru the GUI doesn't allow more than one tunnel for the domain, is there a better way to go about this?

**Comment by sudarshan-reddy** [comment]
The number of connections in a tunnel only exists for redundancy among our edge and do not balance traffic between them or increase bandwidth. Can you tell us why you are reaching this limit and want so many connection?

**Comment by nmldiegues** [comment]
There is no 100 concurrent users/connections limit. 
You can have unlimited users accessing your origin protected by Tunnel

The only limits we have are documented in https://developers.cloudflare.com/cloudflare-one/technical-limitations/#cloudflare-tunnel-limitations
