### ISSUE TITLE
Failed to create quic connection

### ISSUE THREAD

**Issue by bshor** [cloudflare/cloudflared#624]
**Describe the bug**
I created a Cloudflare tunnel entirely through the Zero Trust dashboard to my remote server. It worked completely fine for a few days, but today, it's down. It's telling me it is constantly failing to create a new quic connection, and "failed to dial to edge: timeout: no recent network activity" in the systemctl log. See below for the exact wording.

What could be going on?

**Environment and versions**
 - OS: Linux (Garuda, Arch Derivative), Kernel 5.17.1
 - Architecture: AMD 3700x (64bit)
 - Version: 2022.04

**Logs and errors**
```
λ sudo systemctl status cloudflared
● cloudflared.service - cloudflared
     Loaded: loaded (/etc/systemd/system/cloudflared.service; enabled; vendor preset: disabled)
     Active: activating (start) since Mon 2022-04-11 14:59:51 CDT; 1min 2s ago
   Main PID: 1421352 (cloudflared)
      Tasks: 18 (limit: 154307)
     Memory: 21.3M
        CPU: 75ms
     CGroup: /system.slice/cloudflared.service

Apr 11 15:00:02 trgk cloudflared[1421352]: 2022-04-11T20:00:02Z INF Retrying connection in up to 4s seconds connIndex=0
Apr 11 15:00:11 trgk cloudflared[1421352]: 2022-04-11T20:00:11Z ERR Failed to create new quic connection error="failed >
Apr 11 15:00:11 trgk cloudflared[1421352]: 2022-04-11T20:00:11Z ERR Serve tunnel error error="failed to dial to edge: t>
Apr 11 15:00:11 trgk cloudflared[1421352]: 2022-04-11T20:00:11Z INF Retrying connection in up to 8s seconds connIndex=0
Apr 11 15:00:22 trgk cloudflared[1421352]: 2022-04-11T20:00:22Z ERR Failed to create new quic connection error="failed >
Apr 11 15:00:22 trgk cloudflared[1421352]: 2022-04-11T20:00:22Z ERR Serve tunnel error error="failed to dial to edge: t>
Apr 11 15:00:22 trgk cloudflared[1421352]: 2022-04-11T20:00:22Z INF Retrying connection in up to 16s seconds connIndex=0
Apr 11 15:00:33 trgk cloudflared[1421352]: 2022-04-11T20:00:33Z ERR Failed to create new quic connection error="failed >
Apr 11 15:00:33 trgk cloudflared[1421352]: 2022-04-11T20:00:33Z ERR Serve tunnel error error="failed to dial to edge: t>
Apr 11 15:00:33 trgk cloudflared[1421352]: 2022-04-11T20:00:33Z INF Retrying connection in up to 32s seconds connIndex=0
```

**Additional context**

**Comment by darth-pika-hu** [comment]
#617 same as mine.

**Comment by nmldiegues** [comment]
See https://github.com/cloudflare/cloudflared/issues/617#issuecomment-1095654592

**Comment by darth-pika-hu** [comment]
@bshor The only solution is forcing http2 protocol instead of quic at this moment.

**Comment by bshor** [comment]
Thanks! How do I do that?

**Comment by darth-pika-hu** [comment]
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/#protocol 

use http2.

**Comment by nmldiegues** [comment]
Release 20221.4.1 should help with this.

**Comment by bshor** [comment]
It worked. I had to delete the tunnel and uninstall the cloudflared service. Once I recreated the tunnel, it all worked with 2022.4.1.
