### ISSUE TITLE
Tunnel: support HTTP/2 to origin servers

### ISSUE THREAD

**Issue by agcom** [cloudflare/cloudflared#625]
**Describe the bug**
Cloudflared disabled support for HTTP/2 connection to origin servers; cause it sets the `TLSClientConfig` to a non-nil value on `http.Transport` when instantiating one; particularly in here :point_down: https://github.com/cloudflare/cloudflared/blob/8a07a900fde36efe48fd27ad5f974273015e8270/ingress/origin_service.go#L279-L287

> See Go `http` documentation on `TLSClientConfig`: https://github.com/golang/go/blob/go1.17.9/src/net/http/transport.go#L165-L169:
> ```go
>     // TLSClientConfig specifies the TLS configuration to use with
>     // tls.Client.
>     // If nil, the default configuration is used.
>     // If non-nil, HTTP/2 support may not be enabled by default.
>     TLSClientConfig *tls.Config
> ```

This can be easily fixed by setting [`ForceAttemptHTTP2`](https://github.com/golang/go/blob/go1.17.9/src/net/http/transport.go#L278-L283) to true on on the `http.Transport`; pretty assured that it wouldn't break anything, right?
> [`http.DefaultTransport`](https://github.com/golang/go/blob/go1.17.9/src/net/http/transport.go#L43-L54) also does this, which is used in `http.DefaultClient`.

**To Reproduce**
1. Create and run a simple HTTP server that supports HTTP/1.1 and HTTP/2 protocols (possibly with a mock TLS certificate); log the used HTTP protocol on each request.
2. Run cloudflared and create a tunnel to the HTTP server (possibly with `--no-tls-verify` option).
3. Issue a request to the server.
4. See `HTTP/1.1` log out (cloudflared never attempts HTTP/2 nor protocol upgrade from HTTP/1.1).

**Expected behavior**
HTTP/2 should be preferred to HTTP/1.1 when available (in this context, when connecting to origin servers).

**Environment and versions**
 - OS: Ubuntu 20.04.4 LTS
 - Architecture: x86_64
 - Version: 8a07a900fde36efe48fd27ad5f974273015e8270 (latest commit on master at the time).

**Additional context**
- I did the suggested fix, and it worked as expected (preferred HTTP/2 when available, otherwise sticked to HTTP/1.1); can make a PR if my judgement is relevant.
- Supporting HTTP/2 clear-text (`h2c`) connection to origin servers is a bit more complicated, but can be a feature request.
- I assumed that this is not the intended behavior, therefore issued a bug, not a feature request.

**Comment by nmldiegues** [comment]
Hello @agcom 

I don't think this was done on purpose. Do you recall @sudarshan-reddy ?

You may open the PR if you wish to and we'll take it in appropriately.

**Comment by sudarshan-reddy** [comment]
Agreed. This doesn't seem intentional. Happy to accept a PR for this @agcom .

**Comment by agcom** [comment]
Closed by #656; a follow-up pull request can be enabling `h2c` connections to origin services (Go HTTP/2 client requires TLS by default).
