### ISSUE TITLE
Package cloudflared.rpm is not signed

### ISSUE THREAD

**Issue by NotCoolKiwi** [cloudflare/cloudflared#626]
**Describe the bug**

When I run `curl -L --output cloudflared.rpm https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm && sudo yum localinstall -y cloudflared.rpm` I get `Package cloudflared.rpm is not signed`

**To Reproduce**

1. Run `curl -L --output cloudflared.rpm https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm && sudo yum localinstall -y cloudflared.rpm` (I am using RHEL 8)
2. See error

**Expected behavior**
`cloudflared.rpm` installs successfully

**Environment and versions**
 - OS: RHEL 8
 - Architecture: AMD64 (x64_86)
 - Version: 2022.4.1 (latest)

**Comment by NotCoolKiwi** [comment]
For now, i'm going to install 2022.4.0, because I can't take any chances with security on production. Please get this fixed soon!

**Comment by nmldiegues** [comment]
I don't think the packages published on github were ever signed. So going back to older versions won't help you.

The ones available in https://pkg.cloudflare.com/ are signed
However, that repo is stale in terms of OS flavors. We'll likely work on providing a better alternative in the next few months.

**Comment by NotCoolKiwi** [comment]
Ah, thank you for clarifying! Would you like me to close this issue or leave it open for the alternative you've been working on?

**Comment by nmldiegues** [comment]
I think we can close this since everything is working as expected/intended.
