### ISSUE TITLE
Issue with - Simple ssh access via tcp 

### ISSUE THREAD

**Issue by MOOGAA** [cloudflare/cloudflared#631]
**Describe the bug**
The Bug Is that the tcp tunnel access isn't working properly as i desired in any way/shape/form

**To Reproduce**
1. Configure

___both side___

> ssh running on port `10022/tcp` authentication with just password

2. Runing

```
OS: Ubuntu 22.04 LTS x86_64
Host: Google Compute Engine
Kernel: 4.19.0-20-cloud-amd64
Shell: bash 5.1.16
```

3. See error

**Expected behavior**

`Note : i do know that there is a dedicated option for ssh but I'd still like to use tcp bcz that just works with tcp and i did used it with ngrok and that worked just fine`

my goal is to get tcp ___like ssh & other programs depending on tcp connection___ access to ___gcp shell___ environment

I was expecting that i can directly access ssh through port 10022/tcp

& 

Make http(s)/ws(s)/<database> through any other */tcp port forwarding

`but its not working as my pov as it should`

`But` i just tryed ssh and from results im disappointed some what now im confused how do i proxy a database or ssh

More over id also like 2 know how cloudflared interact with the server-headless-ssh

**Logs and errors**
` unfortunately currently don't hav logs of ssh but ill add that as asap when i do it again *-currently working on another project-* `

**Comment by MOOGAA** [comment]
I like to host testing projects on gcp shell bcz i can access terminal and hot fix it asap before i do pr so in a way im saving my corporate resources

**Comment by sudarshan-reddy** [comment]
Have you tried https://developers.cloudflare.com/cloudflare-one/tutorials/ssh/?

**Comment by sudarshan-reddy** [comment]
Hey Mooga! Thanks for giving tunnel a try. This is a common enough usecase that we have a tutorial for it. Do you wanna check it out and let me know if that lets you use ssh? 

Have you tried https://developers.cloudflare.com/cloudflare-one/tutorials/ssh/

**Comment by MOOGAA** [comment]
> Hey Mooga! Thanks for giving tunnel a try. This is a common enough usecase that we have a tutorial for it. Do you wanna check it out and let me know if that lets you use ssh?
> 
> Have you tried https://developers.cloudflare.com/cloudflare-one/tutorials/ssh/

`Yes m8 i Know & i have tryed it`

the specifically made option for soul perpose of ssh , which i have mentioned before thanks for enlightenment , but im wanna just know 

> that if as documentation is mentioning a tcp tunnel and i hav personally use ngrok to tunnel a tcp connection 

- to be specific the port 22/tcp 
- for ssh perposes
- which did worked and it is working
- which i supose is a normal condition
- than why on 🌎 if i use cloudflared to tunnel tcp which according to documentation should work as a Arbitrary TCP there is no mention of anything which may/may not prevent any kind of issues regarding web socket binding

**Comment by sudarshan-reddy** [comment]
ssh and tcp are the same alias underneath if you use access and hence why that documentation applies.  

This is why that documentation I linked is important.  You cannot use a non cloudflared access based ssh since this is an L7 proxy that gets wrapped by websockets.

Of course, you can use the plain client like you want but with our warp-client connected so tcp packets can be proxied.

check https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel/
