### ISSUE TITLE
Automated reverse proxy with docker

### ISSUE THREAD

**Issue by pakokrew** [cloudflare/cloudflared#634]
**Describe the feature you'd like**
When used within docker, I would love to see something similar as [nginx-proxy/nginx-proxy](https://github.com/nginx-proxy/nginx-proxy), where reverse proxy configuration is automatically generated when containers are started and stopped. 

Say, whenever a container spawns with a `VIRTUAL_HOST` environment variable and an exposed port, automatically add an ingress rule in the config.yaml and make cloudflared reloads it.

**Describe alternatives you've considered**
Currently, we have to manually manage the config.yaml with the different virtual hosts we want to proxy to our different containers. 

**Additional context**
[docker-gen](https://github.com/nginx-proxy/docker-gen) may be a solid good start.

**Comment by joliveirinha** [comment]
Hi @pakokrew ,

You could use cloudflared with a wildcard ingress rule to your ingress controller (eg. nginx-proxy, traefik, ...)  for your docker environment. 
Something like this:

```
ingress:
  - hostname: *.domain.tld
    service: http://ingress-proxy:80
  - service: http_status:404
  ```
  
  This is also similar to what we propose for kubernetes envs (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/kubernetes/#deploy-in-front-of-an-ingress-controller)

**Comment by pakokrew** [comment]
> You could use cloudflared with a wildcard ingress rule to your ingress controller (eg. nginx-proxy, traefik, ...) for your docker environment. Something like this:

Interesting one. I was thinking of a case where we could get rid of the ingress controler (nginx-proxy) and just use the cloudflare tunnel for that usage, but maybe it makes more sense to continue using our fav reverse proxy which has more functionality and which is already configured for our uses. 
Thanks !
