### ISSUE TITLE
Build packages for Ubuntu Jammy Jellyfish (22.04)

### ISSUE THREAD

**Issue by F21** [cloudflare/cloudflared#640]
**Describe the feature you'd like**
I would like to see Ubuntu Jammy Jellyfish (22.04) added as a supported version in Cloudflare's package repositories (https://pkg.cloudflare.com/)

**Describe alternatives you've considered**
N/A

**Additional context**
It would be nice to have a repo for jammy as it is a LTS release, since I prefer to install cloudflared using my package manager and have the package manager handle updates for cloudflared.

**Comment by sudarshan-reddy** [comment]
@F21 , we’re working on adding this and you should see it soon!

**Comment by gillesdupont9** [comment]
Hi,
Any ETA yet?

**Comment by maxpain** [comment]
Any updates?

**Comment by F21** [comment]
@maxpain Per #663, it's in internal beta and could be available in a few weeks (@sudarshan-reddy couldn't promise a date).

**Comment by binaryfire** [comment]
Looking forward to this. We manage our deployments and updates via Ansible and rely on apt for package management. Using .deb files directly isn't ideal.

**Comment by sudarshan-reddy** [comment]
You can try out our beta pkg downloader if you want. 

```
mkdir -p --mode=0755 /usr/share/keyrings
curl https://pkg-beta.try.cloudflare.com/cloudflare-main.gpg -o /usr/share/keyrings/cloudflare-main.gpg
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg-beta.try.cloudflare.com/cloudflared jammy main' >  /etc/apt/sources.list.d/cloudflared.list
apt-get update
 
apt-get install cloudflared
```

Let us know if you run into any problems. 

This will also be available in `pkg.cloudflare.com` soon.

**Comment by stephenogg** [comment]
Maybe change this webpage https://pkg.cloudflareclient.com/install so that it doesn't say that Jammy is a supported release until it actually is. Or indicate that it's coming soon - to avoid frustration.

**Comment by abelinkinbio** [comment]
@stephenogg as a note, https://pkg.cloudflareclient.com/install is for the Warp Desktop Client and not `cloudflared` specifically. If all goes well with the testing of the new beta pkg downloader - we hope to consolidate these two repos to avoid confusion in the future. 

Thank you for the feedback. We're looking forward to bringing this to General Availability.

**Comment by nickweavers** [comment]
https://pkg.cloudflareclient.com/install also lists Bionic (Ubuntu 18.04) as supported but I cannot find the cloudflared package after adding the repo:
$ apt-cache search cloudflared

Will this be addressed here too?
Thanks.

**Comment by sudarshan-reddy** [comment]
To re-iterate what @abelinkinbio said, 

>  as a note, https://pkg.cloudflareclient.com/install is for the Warp Desktop Client and not cloudflared specifically. If all goes well with the testing of the new beta pkg downloader - we hope to consolidate these two repos to avoid confusion in the future.

Follow https://github.com/cloudflare/cloudflared/issues/640#issuecomment-1164391371 for cloudflared installs (Note: This is a beta for now)

**Comment by xxxpsyduck** [comment]
Error why setting beta cloudflared on 22.04 jammy:
```sh
Setting up cloudflared (2022.7.1) ...
ln: failed to create symbolic link '/usr/local/bin/cloudflared': No such file or directory
dpkg: error processing package cloudflared (--configure):
 installed cloudflared package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 cloudflared
E: Sub-process /usr/bin/dpkg returned an error code (1)```

**Comment by xxxpsyduck** [comment]
> That's being tracked here: #686. Did you already have a cloudflared installed as a service?

No I don't

**Comment by sudarshan-reddy** [comment]
https://pkg.cloudflare.com/#ubuntu-jammy should work now.

**Comment by 911realdeb** [comment]
i get this error 

N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://pkg.cloudflare.com/cloudflared jammy InRelease' doesn't support architecture 'i386'

**Comment by phntom** [comment]
i get this error when trying to install
```
Setting up cloudflared (2022.11.1) ...
ln: failed to create symbolic link '/usr/local/bin/cloudflared': No such file or directory
dpkg: error processing package cloudflared (--configure):
 installed cloudflared package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 cloudflared
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by phntom** [comment]
just an fyi, can get it to work if I run `sudo mkdir /usr/local/bin`

**Comment by war59312** [comment]
To fix:

`Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://pkg.cloudflare.com/cloudflared jammy InRelease' doesn't support architecture 'i386'`

Run:

`sudo nano /etc/apt/sources.list.d/cloudflared.list`

Change to:

`deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main`
