### ISSUE TITLE
Tunnel does not work with a docker container

### ISSUE THREAD

**Issue by gitshiteru** [cloudflare/cloudflared#642]
Hello,

Running a web app with a docker container on the origin server, as this:
`561eed33e15d        web_budget:v6       "/usr/bin/supervisor…"   3 hours ago         Up 3 hours          0.0.0.0:443->443/tcp, 0.0.0.0:9000->8080/tcp   web-app`

With respect to a tunnel, I have encountered the following error:

> toshio@es01:~/.cloudflared$ cloudflared tunnel run 
> 2022-05-10T23:59:08Z INF Starting tunnel tunnelID=9e0da78a-baaa-4ae2-a503-cb1d15f1d83f
> 2022-05-10T23:59:08Z INF Version 2022.5.0
> 2022-05-10T23:59:08Z INF GOOS: linux, GOVersion: go1.17.5, GoArch: amd64
> 2022-05-10T23:59:08Z INF Settings: map[cred-file:/home/toshio/.cloudflared/9e0da78a-baaa-4ae2-a503-cb1d15f1d83f.json credentials-file:/home/toshio/.cloudflared/9e0da78a-baaa-4ae2-a503-cb1d15f1d83f.json]
> 2022-05-10T23:59:08Z INF cloudflared will not automatically update if installed by a package manager.
> 2022-05-10T23:59:08Z INF Generated Connector ID: 9edf2957-8bb4-4221-b828-172434466448
> 2022-05-10T23:59:08Z INF Initial protocol quic
> 2022-05-10T23:59:08Z INF Starting metrics server on 127.0.0.1:42627/metrics
> 2022/05/10 23:59:08 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> 2022-05-10T23:59:09Z INF Connection 3ad5db84-c30a-4879-af44-cfd6365a6096 registered connIndex=0 location=SIN
> 2022-05-10T23:59:09Z INF Connection e18e9e9a-2d25-4b5c-afd1-0c458d4786e8 registered connIndex=1 location=HKG
> 2022-05-10T23:59:10Z INF Connection 0d6b4232-7f75-4084-b6ce-2bc5c3cf3aaa registered connIndex=2 location=SIN
> 2022-05-10T23:59:11Z INF Connection 54202d2d-728e-49c8-880e-31e0b34fa506 registered connIndex=3 location=HKG
> 2022-05-11T00:00:30Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: read tcp 127.0.0.1:42072->127.0.0.1:443: read: connection reset by peer" cfRay=7096a27f2a743457-NRT ingressRule=1 originService=https://localhost:443
> 2022-05-11T00:00:30Z ERR Failed to handle QUIC stream error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: read tcp 127.0.0.1:42072->127.0.0.1:443: read: connection reset by peer" connIndex=3

Aslo, the configuration is this:

> toshio@es01:~/.cloudflared$ cat config.yml 
> 
> tunnel: 9e0da78a-baaa-4ae2-a503-cb1d15f1d83f
> credentials-file: /home/toshio/.cloudflared/9e0da78a-baaa-4ae2-a503-cb1d15f1d83f.json
> originRequest:  # Top-level configuration
>   originServerName: es01.datagem.cloud
>   noTLSVerify: true
> 
> ingress:
>   - hostname: azure.datagem.cloud
>     service: https://localhost:443

What would be wrong configuration?
Any thought, please.
---Toshio from Tokyo

**Comment by nmldiegues** [comment]
The error is self-explanatory in:
```
Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: read tcp 127.0.0.1:42072->127.0.0.1:443: read
```

cloudflared (127.0.0.1:42072) tries to open a TCP connection to your ingress service origin (127.0.0.1:443) and is unable to

I suggest you hop on the container and test connectivity to your origin, e.g.:
```
curl -i -k https://localhost:443
```
