### ISSUE TITLE
missing download cloudflared-2018.7.2-linux-arm.tar.gz for arm32

### ISSUE THREAD

**Issue by mybuntu-git2** [cloudflare/cloudflared#643]
**Describe the bug**
the version of Cloudflared for arm32 has never worked after 2018.7.2 and workarounds have stalled
currently there is no available build of that release.

please recover that release and keep it available, it is the only way we can use Cloudflared on raspberry pi zero arm32. we use that build to integrate pihole with doh.

reference:
https://github.com/pi-hole/docs/issues/710

**Comment by sudarshan-reddy** [comment]
Hey @mybuntu-git2, have you looked at https://github.com/cloudflare/cloudflared/issues/359#issuecomment-962831824 ?

**Comment by sudarshan-reddy** [comment]
Can you confirm this works btw?
