### ISSUE TITLE
Starting DNS over HTTPS proxy server error

### ISSUE THREAD

**Issue by bencleric** [cloudflare/cloudflared#653]
**Describe the bug**

**To Reproduce**
1. Configure '...'
2. Run '....'
3. See error

**Expected behavior**

**Environment and versions**
 - OS: [e.g. MacOS]
 - Architecture: [e.g. AMD, ARM]
 - Version: [e.g. 2022.02.0]

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by sudarshan-reddy** [comment]
Hey @bencleric ! I’d request you to please open the issue with proper descriptions as indicated in the template. As this stands, we’re able to glean nothing from the title.
