### ISSUE TITLE
HTTP ERROR 404 when running  cloudflared as service

### ISSUE THREAD

**Issue by oddife** [cloudflare/cloudflared#662]
Ubuntu 22.04 LTS (GNU/Linux 5.15.0-27-generic x86_64)

when I run Cloudflared as a service I get,   This yourwebsite.com page can’t be found, No webpage was found for the web address: https://yourwebsite.com HTTP ERROR 404
but if I uninstall the cloudflared service and run 'cloudflared tunnel run mytunnel' I'm able to access the page.

**Comment by sudarshan-reddy** [comment]
@oddife can you please reopen this issue in the recommended Jira format with more information for us to reproduce? That will help me understand your problem much faster.
