### ISSUE TITLE
Cloudflared in Ubuntu 22.04 Jammy Jellyfish Installation

### ISSUE THREAD

**Issue by rotycha** [cloudflare/cloudflared#663]
Hello, I know that at the moment there is no package to download cloudflared in Ubuntu 22.04.  I have tried installation with the source however I kept getting errors saying this OS was not supported.  Is there really no way to install cloudflared in 22.04?  If not is there any date for when the package might be released?

**Comment by sudarshan-reddy** [comment]
We have an issue tracking this at https://github.com/cloudflare/cloudflared/issues/640

the new packaging system is in an internal beta and should be out soon (I cannot give you a date but it shouldn’t be longer than a couple of weeks).

We do appreciate your patience in waiting this long.

**Comment by rotycha** [comment]
> We have an issue tracking this at #640
> 
> the new packaging system is in an internal beta and should be out soon (I cannot give you a date but it shouldn’t be longer than a couple of weeks).
> 
> We do appreciate your patience in waiting this long.

I just want to double check then there is no other way to install it other than waiting?

**Comment by rotycha** [comment]
> You can download the binary or deb from our releases page. So just to be clear, a workaround exists.

Is there any chance you could describe how to go about that?  My end goal is to set up persistent tunnels.  I have already done this before but I have never had to install cloudflare with just the files.  Thank you for everything so far.
