### ISSUE TITLE
IPv6 Support for Cloudflare Edge Connections

### ISSUE THREAD

**Issue by DevinCarr** [cloudflare/cloudflared#664]
# How to try it out

We recently released IPv6 support for outgoing connections to Cloudflare's edge in the master branch ([dd540af](https://github.com/cloudflare/cloudflared/commit/dd540af695448ea1bfef28762060fb98455d455d)) and starting today you can try it out too!

**NOTE: You will need to build from master branch to use this feature flag**

There are three modes available for connecting to the Cloudflare edge:

- `--edge-ip-version auto`: Rely on host operating system to determine which IP version to select. The first IP version returned from the DNS resolution of the region lookup will be used as the primary set. In dual IPv6 and IPv4 network setups, `cloudflared` will separate the IP versions into two address sets that will be used to fallback in connectivity failure scenarios.
- `--edge-ip-version 6`: Resolve only IPv6 addresses
- `--edge-ip-version 4`: Resolve only IPv4 addresses (current default)

## For command-line usage

Here is an easy way to change your cloudflared run command to get started:
```
cloudflared tunnel --edge-ip-version auto run <tunnel>
```

## For UI managed tunnels

For those who use the UI-managed configuration in the Zero Trust dashboard, you will have to update your service file directly (For example, on Linux: `/etc/systemd/system/cloudflared.service`):

1. Update your cloudflared path to the new binary

1. Update your ExecStart to match something similar to:
    ```
    ExecStart=/path/to/built/cloudflared tunnel --edge-ip-version auto run --token <token>
    ```

# How to report problems

Please feel free to report problems you experience with enabling IPv6 on this thread. Check the following steps to help us work with you to diagnose issues:

1. **Make sure run with debug logging enabled**
    - via `cloudflared tunnel --loglevel debug`

1. **Report environment and versions**
    - OS: [e.g. MacOS]
    - Architecture: [e.g. AMD, ARM]
    - Commit: via `git rev-parse HEAD`

1. **Edge connection check**
    - Run `curl https://www.cloudflare.com/cdn-cgi/trace` to check which IP version is attempted (please do not share the full results, just check and report the IP version: IPv4 or IPv6)

1. **Check if connected**
    - Run `cloudflared tunnel info <TUNNEL-ID/TUNNEL-NAME>` to check which IP version is reported by "ORIGIN IP"

**Comment by rootbeerdan** [comment]
POGGERS

![ipv6-tunnel-img](https://global.danielmarks.dev/sx/2022/upload_0CkI22M0hHdrmq1V.png)

I am seeing some random errors referencing the 2606:4700:a8::8 endpoint, but the tunnel is up and I see traffic flowing!

`2022-06-09T21:53:15Z WRN Failed to serve quic connection error="timeout: no recent network activity" connIndex=2 ip=2606:4700:a8::8`

**Comment by Tugzrida** [comment]
Works well for me!

Not sure if it's expected that `edge-ip-version: auto` connects only over IPv6 on dual-stack hosts. From the description in the first post, I assumed it would connect over both 6 and 4 simultaneously for fallback.

**Comment by DevinCarr** [comment]
> Works well for me!
> 
> Not sure if it's expected that `edge-ip-version: auto` connects only over IPv6 on dual-stack hosts. From the description in the first post, I assumed it would connect over both 6 and 4 simultaneously for fallback.

Apologies for the confusion! `edge-ip-version: auto` will not leverage 6 and 4 for simultaneous "high availability" during initial connections by design. Only in the case of some detected connectivity failures will cloudflared attempt to fallback to IPv4 addresses. This means that you will typically only ever run into hybrid IPv6 and IPv4 connections if you experience some connectivity failures to trigger the fallback.

**Comment by rootbeerdan** [comment]
My suggestion here would be to allow UI managed tunnels to enable/disable IPv6, similar to this:

![create-tunnel-img](https://global.danielmarks.dev/sx/2022/upload_ksjdfn2uifain2kaj2.png)

We potentially have a use case where we would prefer IPv4 in a mobility situation, and being able to specify it would be helpful.

**Comment by IRGC** [comment]
does not seem to work now, falling back to v4 automatically. 
anybody else have this problem?

**Comment by sudarshan-reddy** [comment]
Are you checking out master? We temporarily reverted the change.

You can still check out the specific commit listed in this issue and build from there to get it to work.

**Comment by IRGC** [comment]
I tried both master and release build, v6 no longer works and falling back to v4 after multiple attempts.

**Comment by sudarshan-reddy** [comment]
That’s expected because we reverted the change on master.  Can you checkout this commit and build for now: 978e01f77eedf4f098f71423b42e639d12355015

**Comment by IRGC** [comment]
working again. and it shows as outdated version in zero trust dashboard > tunnels

**Comment by sudarshan-reddy** [comment]
That should be fine as a temporary measure. We should have a release sometime soon and you can get on that eventually.

**Comment by IRGC** [comment]
ok thanks for the quickest support.

**Comment by DevinCarr** [comment]
IPv6 support is back in master branch: dd540af695448ea1bfef28762060fb98455d455d

**Comment by DevinCarr** [comment]
Additionally, I have pushed a custom docker build here to try out while you are waiting for the release: https://hub.docker.com/r/devincarr/cloudflared/tags

`docker pull devincarr/cloudflared:ipv6`

**Comment by DevinCarr** [comment]
IPv6 support is in the latest release: [2022.7.0](https://github.com/cloudflare/cloudflared/releases/tag/2022.7.0)! Please give it a shot if you have the chance!

**Comment by Tugzrida** [comment]
Added `edge-ip-version: auto` to my config.yml and it's come up fine. Will report if there's any longer term issues 👍🏻

**Comment by streaps** [comment]
Added `edge-ip-version: 6` toc onfig.yml and it returns an error `expected string found int for edge-ip-version`.

`edge-ip-version: "6"` works though, but it would be nice, if cloudflared could accept a plain 4 or 6 without putting it into quotation marks.

**Comment by streaps** [comment]
The int error is still there.

**Comment by DevinCarr** [comment]
The comment Nuno made wasn't in respect to your concern to the error returned: `expected string found int for edge-ip-version`. He was just mentioning that there was a regression in version 2022.7.0 and to update to latest.

For your problem, the issue is that we accept three options for the `--edge-ip-version` flag: 'auto', '4', or '6'. Since there are different types I made the flag accept only string versions to simplify this case. That's why you are getting that error.

**Comment by streaps** [comment]
Yeah, YAML sucks and usability too. You only simplified the code and made it more error prone to users. It's confusing and the error message is too terse and technical. The wording of the error is also weird. It's also inconsistent with the command line parameters and logging (`edge-ip-version:6`). Why not use "ipv4" and "ipv6" as options, if you insist on string?

It's not that it's the most important thing. IPv6 tunnels seem to work fine, that's great. I just don't like bad usability and unnecessary friction for the user. Not every user of cloudflared is a programmer.

**Comment by DevinCarr** [comment]
I could look to add 'ipv4' and 'ipv6' as additional options to help with usability, but I don't want to break people who already have it setup with '4' or '6' in their config, so people would still run into the issue if they attempt to use '4' or '6' as numbers instead of strings.
