### ISSUE TITLE
💡 Less verbose output

### ISSUE THREAD

**Issue by apolinario** [cloudflare/cloudflared#677]
**Describe the feature you'd like**
I would like an output that is just this bit. Everything else is superfluous for my application
![image](https://user-images.githubusercontent.com/788417/175381609-3fd0cea8-7497-40fe-bcf3-a723b76c2bd6.png)

**Describe alternatives you've considered**
I can make it not output anything at all but then how do I know the URL?

**Comment by sssilver** [comment]
If the goal is simply to output the URL and nothing else, then `grep` of stderr is your friend:

`$ cloudflared tunnel 2> >(grep -oh "https://\(.*\)trycloudflare.com")`

Otherwise, you can specify a metrics endpoint, curl it via HTTP, and then play around with `grep` looking for `cloudflared_tunnel_user_hostnames_counts`:

```
$ cloudflared tunnel --metrics localhost:5678
...

$ curl https://localhost:5678 | grep cloudflared_tunnel_user_hostnames_counts

# HELP cloudflared_tunnel_user_hostnames_counts Which user hostnames cloudflared is serving
# TYPE cloudflared_tunnel_user_hostnames_counts counter
cloudflared_tunnel_user_hostnames_counts{userHostname="https://processes-shortly-encouraged-themes.trycloudflare.com"} 1
```

Hope this helps!

**Comment by apolinario** [comment]
Got it, that solves my problem, although the feature request for potentially having a way for users to set how verbose they want their outputs could still make sense maybe?

**Comment by sssilver** [comment]
Features like these are the reason the UNIX philosophy emerged -- building composable tools, each of which does one thing well, and in conjunction they become more powerful than the sum of the parts. The alternative is feature bloat and software that is significantly harder to maintain.
