### ISSUE TITLE
💡No ARM/ARM64 Docker Image for Cloudflared

### ISSUE THREAD

**Issue by iAmSaugata** [cloudflare/cloudflared#678]
**Describe the feature you'd like**
A clear and concise description of the feature. What problem does it solve for you?
Currently we don't have any ARM/ARM64 image available for cloudflared, hence it will be bit difficult for normal user to run cloudflared tunnel on ARM system, such as Raspberry Pi.

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?
For advance or moderated users, it is easy to create ARM build using Dockerfile, and I have already tested it with host network mode and it is working fine with following Docker-Compose file.

```version: "3"
services:
  cloudflared:
    image: cloudflared-arm:latest
    container_name: cloudflared-tunnel
    hostname: cloudflared
    restart: unless-stopped
    network_mode: "host"
    command: "tunnel --no-autoupdate run --token Your-Token"
    cap_add:
      - NET_ADMIN
```

**Additional context**
When I build image it is 47.1 MB but the one available in Docker Hub is 22.65 MB, why so?

**Comment by sudarshan-reddy** [comment]
This is being tracked in https://github.com/cloudflare/cloudflared/issues/628
