### ISSUE TITLE
🐛Can we add two Argo tunnel (two different zero trust account) in one cloudflared services ie. In /etc/cloudflared/config.yaml?

### ISSUE THREAD

**Issue by PATILpavan123** [cloudflare/cloudflared#683]
Can we add two Argo tunnel (two different zero trust account) in one cloudflared services ie. In /etc/cloudflared/config.yaml

**Comment by PATILpavan123** [comment]
Can we add two Argo tunnel (two different zero trust account) in one cloudflared services ie. In /etc/cloudflared/config.yaml

**Comment by nmldiegues** [comment]
A `cloudflared tunnel` can only run 1 Tunnel.

If you want to execute different Tunnels (regardless of being the same account or not), you need to do that via different `cloudflared tunnel` processes.

This is by design and won't be changed.
