### ISSUE TITLE
Unable to pass the credentials json to the cloudflared docker container🐛

### ISSUE THREAD

**Issue by modernNeo** [cloudflare/cloudflared#685]
**Describe the bug**

The `tunnel` command seems unable to access the `credentials-file` in the docker container, no matter where I put  it.

**To Reproduce**
`Cloudflared.dockerfile`
```
FROM cloudflare/cloudflared:2022.6.3-amd64

COPY cloudflare_configs/credentials.json /etc/cloudflared/credentials.json

COPY cloudflare_configs/config.yaml /etc/cloudflared/config.yml

CMD ["tunnel", "--no-autoupdate", "run"]
```
relevant part of `docker-compose.yml`
```
  cloudflared:
    container_name: cloudflared
    build:
      context: .
      dockerfile: Dockerfiles/Cloudflared.dockerfile
    networks:
      - proxy
```

relevant part of `config.yml`
```
tunnel: <UUID>
credentials-file: /etc/cloudflared/credentials.json
```

and then ran `docker-compose -f docker-compose.yml up --force-recreate -d`

And I get the following errors with each different location I try to copy the `credentials.json` to

`couldn't read tunnel credentials from /etc/cloudflared/credentials.json: open /etc/cloudflared/credentials.json: permission denied`

`couldn't read tunnel credentials from /etc/.cloudflared/credentials.json: open /etc/.cloudflared/credentials.json: permission denied`

`Tunnel credentials file '/root/.cloudflared/credentials.json' doesn't exist or is not a file`

`Tunnel credentials file '/root/cloudflared/credentials.json' doesn't exist or is not a file`

`couldn't read tunnel credentials from /credentials.json: open /credentials.json: permission denied`

**Expected behavior**
The `tunnel` service being able to access the `credentials.json` file

So...where am I supposed to be put the credentials in the docker container for the `tunnel` command to be able to read it?

**Comment by modernNeo** [comment]
Figured out the issue. the `credentials.json` file works if it is in the `/etc/cloudflared/` directory and `other` permissions has `read`.

The necessary permission should really be outlined somewhere in the https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#set-up-a-tunnel-locally-cli-setup documentation

**Comment by nmldiegues** [comment]
With the advent of https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/ you can now create a Tunnel via the UI (in dash.teams.cloudflare.com) and get an alternative way to run the container with files at all. That's recommended for most users.

Obviously if you still want to use the CLI (or API), you are free to do so, in which case your issue and feedback is valuable.

**Comment by modernNeo** [comment]
> With the advent of https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/ you can now create a Tunnel via the UI (in dash.teams.cloudflare.com) and get an alternative way to run the container with files at all. That's recommended for most users.

Guess that works for more users. but folks like myself appreciate being able to jut clone a repo and run one command to launch everything rather than have to navigate a GUI :)
