### ISSUE TITLE
🐛 QUIC protocol is being used by default

### ISSUE THREAD

**Issue by romeroyonatan** [cloudflare/cloudflared#688]
**Describe the bug**
Our tunnels are failing because cannot establish a QUIC connection.
The service configuration was installed by `cloudflared service install`
I can not manage the firewall rules to allow outgoing UDP connections

**To Reproduce**
1. Run `cloudflared service install`
1. Run `systemctl start cloudflared`
1. Run `systemctl status cloudflared`
1. See error `failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.2xx.xxx`

**Expected behavior**
[The official documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/#protocol) says that http2 protocol is used by default
> **protocol**
>  default: auto
> Specifies the protocol used to establish a connection between cloudflared and the edge. Available values are auto, http2, h2mux, and quic. The auto value will automatically configure the http2 protocol.

**Environment and versions**
 - OS: Ubuntu 20.04
 - Architecture: amd64
 - Version: 2022.7.0

**Logs and errors**
```
Jul 06 09:21:57 cloudflared[3643084]: 2022-07-06T09:21:57Z INF GOOS: linux, GOVersion: go1.17.10, GoArch: amd64
Jul 06 09:21:57 cloudflared[3643084]: 2022-07-06T09:21:57Z INF Settings: map[config:/etc/cloudflared/config.yml cred-file:/etc/cloudflared/***********.json credentials-file:/etc/cloudflared/***********.json no-autoupdate:true]
Jul 06 09:21:57 cloudflared[3643084]: 2022-07-06T09:21:57Z INF Generated Connector ID: ****************
Jul 06 09:21:57 cloudflared[3643084]: 2022-07-06T09:21:57Z INF Initial protocol quic
Jul 06 09:21:57 cloudflared[3643084]: 2022-07-06T09:21:57Z INF Starting metrics server on 127.0.0.1:33489/metrics
Jul 06 09:21:57 cloudflared[3643084]: 2022/07/06 09:21:57 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Jul 06 09:22:02 cloudflared[3643084]: 2022-07-06T09:22:02Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.***.***
Jul 06 09:22:07 cloudflared[3643084]: 2022-07-06T09:22:07Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.***.***
Jul 06 09:22:12 cloudflared[3643084]: 2022-07-06T09:22:12Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.***.***
Jul 06 09:22:22 cloudflared[3643084]: 2022-07-06T09:22:22Z ERR Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.***.***
```

**Comment by romeroyonatan** [comment]
Workarround: Force http2 connections

1. Open the cloudflared.service
    ```sudo systemctl edit --full cloudflared.service```
1. Add the argument `--protocol http2`
    ```diff
    - ExecStart=/usr/local/bin/cloudflared --config /etc/cloudflared/config.yml tunnel run
    + ExecStart=/usr/local/bin/cloudflared --protocol http2 --config /etc/cloudflared/config.yml tunnel run
    ```

**Comment by nmldiegues** [comment]
We actually just found this regression and are working to make a 2022.7.1 release that will avoid this problem.
Apologies for the inconvenience.

The correct workaround is to allow outbound UDP traffic to port 7844 on Cloudflare IPs noted as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ports-and-ips/

Using HTTP2 protocol works too, but that protocol is being abandoned in face of QUIC, so we do not recommend that.

@abelinkinbio  will work to make https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/#protocol updated to mention QUIC

**Comment by romeroyonatan** [comment]
Thank you very much 🙂

**Comment by sudarshan-reddy** [comment]
For posterity, note that the documentation is now corrected to say we default to QUIC. Thanks for pointing this out.
