### ISSUE TITLE
🐛 cloudflared update fails on Windows MSI deployment

### ISSUE THREAD

**Issue by ShadowXVII** [cloudflare/cloudflared#695]
**Describe the bug**
`cloudflared update` does not work on Windows. Despite reporting a success, it doesn't actually succeed.

**To Reproduce**
1. Install an older version of Cloudflared MSI.
2. Check version 
```
PS C:\Users\User> cloudflared --version
cloudflared version 2022.5.1 (built 2022-05-11-1402 UTC)
```
3. Run update: 
```
PS C:\Users\User> cloudflared update 
2022-07-14T22:50:44Z INF cloudflared has been updated version=2022.7.1
cloudflared has been updated to version 2022.7.1
```
4. Check version 
```
PS C:\Users\User> cloudflared --version
cloudflared version 2022.5.1 (built 2022-05-11-1402 UTC)
```

**Expected behavior**
Cloudflared should update in-place. Note that this was an MSI installer, so in-place upgrades might interfere with the registered MSI product version in the Windows Installer.

Maybe `cloudflared update` should be disabled, OR point to the MSI installer online if it's the MSI deployed version.

**Environment and versions**
 - OS: Windows
 - Architecture: x64
 - Version: 2022.05.11+

**Comment by sudarshan-reddy** [comment]
Thanks for reporting this @ShadowXVII . This is now on to do list.

**Comment by sudarshan-reddy** [comment]
Let’s track it here: https://github.com/cloudflare/cloudflared/issues/667
