### ISSUE TITLE
Android error. Read: connection refused

### ISSUE THREAD

**Issue by Luqaska** [cloudflare/cloudflared#696]
Hello,
For the last couple of days I have been trying to run Cloudflared on a aarch64-based Android device using a arm64 binary, but the following keep showing up:

Command: `./cloudflared login`
Result:
```
A browser window should have opened at the following URL:

https://dash.cloudflare.com/argotunnel?callback=https%3A%2F%2Flogin.cloudflareaccess.org%2F<censored>%3D

If the browser failed to open, please visit the URL above directly in your browser.
Failed to write the certificate due to the following error:
Get "https://login.cloudflareaccess.org/<censored>": dial tcp: lookup login.cloudflareaccess.org on [::1]:53: read udp [::1]:39217->[::1]:53: read: connection refused

Your browser will download the certificate instead. You will have to manually
copy it to the following path:

/data/data/com.termux/files/home/.cloudflared/cert.pem
Get "https://login.cloudflareaccess.org/<censored>": dial tcp: lookup login.cloudflareaccess.org on [::1]:53: read udp [::1]:39217->[::1]:53: read: connection refused
```

I tried using various terminal emulators, but the same error keeps making itself present. Also tried searching it for my own without finding any major results.

Does somebody know how to solve this issue?

**Comment by Luqaska** [comment]
I think this suits more with the forums, so I'll move this there

**Comment by sudarshan-reddy** [comment]
You can try this now much simpler  method to set up and run a tunnel:  https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/#:~:text=Cloudflare%20Tunnel%20is%20the%20easiest,open%2Dsource%20connector%2C%20cloudflared%20.

**Comment by Luqaska** [comment]
I've found a solution! :D

I just ran on Termux: `$ pkg install cloudflared` and then repeated the experiment, and it worked!
