### ISSUE TITLE
#### ⚠️ GitGuardian has uncovered 4 secrets following the scan of your pull request.

### ISSUE THREAD

**Issue by Mikec90** [cloudflare/cloudflared#697]
#### ⚠️ GitGuardian has uncovered 4 secrets following the scan of your pull request.

Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.

<details>
<summary>🔎 Detected hardcoded secrets in your pull request</summary>
<br>

| GitGuardian id | Secret                    | Commit           | Filename        |                      |
| -------------- | ------------------------- | ---------------- | --------------- | -------------------- |
| [-](https://dashboard.gitguardian.com/incidents/secrets) | Generic High Entropy Secret | 7d3d958ba7e1005d201a7e62289737fd5d716394 | config.toml | [View secret](https://github.com/cloudflare/cloudflare-docs/commit/7d3d958ba7e1005d201a7e62289737fd5d716394#diff-618063036395fe9ee107f22b46c9eadeL24) |
| [-](https://dashboard.gitguardian.com/incidents/secrets) | Generic High Entropy Secret | 58b6333afd7670da52bd237bec6b2c0cb708ae5e | products/ddos-protection/docs-config.js | [View secret](https://github.com/cloudflare/cloudflare-docs/commit/58b6333afd7670da52bd237bec6b2c0cb708ae5e#diff-52df2752523dc2c79065721d6fcdd2edL19) |
| [-](https://dashboard.gitguardian.com/incidents/secrets) | Generic High Entropy Secret | f5ad72dcb5f9b6b4072be76c18ee663e52f30f72 | products/ddos-protection/docs-config.js | [View secret](https://github.com/cloudflare/cloudflare-docs/commit/f5ad72dcb5f9b6b4072be76c18ee663e52f30f72#diff-52df2752523dc2c79065721d6fcdd2edL19) |
| [3543783](https://dashboard.gitguardian.com/incidents/3543783?occurrence=39342584) | Generic High Entropy Secret | 51cbbada456648d933bd539e901cb20bb22d0adb | products/ruleset-engine/docs-config.js | [View secret](https://github.com/cloudflare/cloudflare-docs/commit/51cbbada456648d933bd539e901cb20bb22d0adb#diff-767c295d7d76c2142cd9930e4176d4144b6eff12146e0090eb3dc9a29f90958dR15) |

</details>

<details>
<summary>🛠 Guidelines to remediate hardcoded secrets</summary>
<br>

1. Understand the implications of revoking this secret by investigating where it is used in your code.
2. Replace and store your secrets safely. [Learn here](https://blog.gitguardian.com/secrets-api-management?utm_source=product&amp;utm_medium=GitHub_checks&amp;utm_campaign=check_run_comment) the best practices.
3. Revoke and [rotate these secrets](https://docs.gitguardian.com/secrets-detection/detectors/generics/generic_high_entropy_secret#revoke-the-secret?utm_source=product&amp;utm_medium=GitHub_checks&amp;utm_campaign=check_run_comment).
4. If possible, [rewrite git history](https://blog.gitguardian.com/rewriting-git-history-cheatsheet?utm_source=product&amp;utm_medium=GitHub_checks&amp;utm_campaign=check_run_comment). Rewriting git history is not a trivial act. You might completely break other contributing developers' workflow and you risk accidentally deleting legitimate data.

To avoid such incidents in the future consider

-   following these [best practices](https://blog.gitguardian.com/secrets-api-management/?utm_source=product&amp;utm_medium=GitHub_checks&amp;utm_campaign=check_run_comment) for managing and storing secrets including API keys and other credentials
-   install [secret detection on pre-commit](https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit?utm_source=product&amp;utm_medium=GitHub_checks&amp;utm_campaign=check_run_comment) to catch secret before it leaves your machine and ease remediation.

</details>

---

<sup>🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&amp;utm_source=github&amp;utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.<br/><br/>Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!</sup>

_Originally posted by @gitguardian[bot] in https://github.com/cloudflare/cloudflare-docs/issues/5177#issuecomment-1186316818_

**Comment by sudarshan-reddy** [comment]
This issue has nothing actionable or follow the template.
