### ISSUE TITLE
📝Cloudflared tunnel configuration flag --ui

### ISSUE THREAD

**Issue by elcajon** [cloudflare/cloudflared#699]
**Available Documentation**
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/arguments/

**Suggested Documentation**
How to use the `--ui` flag with cloudflared tunnel.

**Additional context**
From `cloudflared tunnel --help` I can see that there is an `--ui` option.

```
--ui                 Launch tunnel UI. Tunnel logs are scrollable via 'j', 'k', or arrow keys. (default: false)
```

I can't find any information on how to use the flag. Starting a quick-tunnel with --ui option doesn't seem to have any effect. Should there be any web server started to visualize the tunnel metrics?

**Comment by sudarshan-reddy** [comment]
This is mostly a legacy feature. You can use the Cloudflare Tunnel dashboard (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/#set-up-a-tunnel-remotely-dashboard-setup) to interact with your tunnel on the UI.
