### ISSUE TITLE
yaml config not respecting dns-proxy-port value

### ISSUE THREAD

**Issue by brettzink** [cloudflare/cloudflared#7]
I'm trying to configure dns proxying via YAML and it's not respecting the port value. This works fine if I pass in command line arguments for dns-proxy-address and dns-proxy-port but in YAML the port value is ignored. 

given this yaml config:

```
proxy-dns: true
proxy-dns-port: 5053
proxy-dns-address: 0.0.0.0
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query
```

I get this output: 

> INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml
> INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
> INFO[0000] Adding DNS upstream                           url="https://1.0.0.1/dns-query"
> INFO[0000] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
> INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://0.0.0.0:53"
> FATA[0000] Cannot start the DNS over HTTPS proxy server  error="failed to create a UDP listener: listen udp 0.0.0.0:53: bind: address already in use"

On the command line, no problems: 

`cloudflared proxy-dns --port 5053 --address 0.0.0.0 --upstream https://1.1.1.1/dns-query https://1.0.0.1/dns-query`

```
INFO[0000] Applied configuration from /usr/local/etc/cloudflared/config.yaml
INFO[0000] Adding DNS upstream                           url="https://1.1.1.1/dns-query"
INFO[0000] Starting DNS over HTTPS proxy server          addr="dns://0.0.0.0:5053"
INFO[0000] Starting metrics server                       addr="127.0.0.1:33759"
```

**Comment by Forst** [comment]
Can confirm, version 2018.4.3 (Debian package).

**Comment by VirtualWolf** [comment]
Any update on this?

I _was_ able to work around it by using `TUNNEL_DNS_PORT` instead of `--port` but that has, uh, spontaneously stopped working and I can't get it working again short of manually running `cloudflared` from a terminal.

**Comment by YipYup** [comment]
> I'll add a workaround for the next release (should come out later today).

Did you get that release out?

**Comment by vavrusa** [comment]
Yes, it reads the port from configuration properly.

**Comment by cmer** [comment]
I'm still having this issue as of April 2020.

**Comment by mygoare** [comment]
I got the version `cloudflared version 2020.3.2 (built 2020-03-31-1706 UTC)`
It can works properly now. thx.

**Comment by daltoniam** [comment]
I can confirm the config DNS settings are working with the yaml config as of the current release of `2020.7.3`. Since the original issue is resolved, please open a new issue and we can take a look at that directly. Thanks!
