### ISSUE TITLE
💡 Prefer IPv6 when connect to Cloudflare.

### ISSUE THREAD

**Issue by fernvenue** [cloudflare/cloudflared#700]
**Describe the feature you'd like**
Hi, I just found out that one of my servers has a poor connection to Cloudflare when using IPv4, but seems to be fine when using IPv6, so I'm wondering is there any way to prefer IPv6 when `cloudflared` connects to Cloudflare? Use a flag like `-6` or something.

**Describe alternatives you've considered**
Actually, I think this should be a default behavior.

**Additional context**
If we already have this feature, could you please tell me how to do that or where I can find the documentation? Because I really tried my best to find it.

**Comment by nmldiegues** [comment]
In cloudflared 2022.7.1 you have this:
```
   --edge-ip-version value                             Cloudflare Edge ip address version to connect with. {4, 6, auto} (default: "4") [$TUNNEL_EDGE_IP_VERSION]
```

which you can use to force IPv6, or let cloudflared pick whatever the system favours (with `auto`)

Somewhere in the future we will make the default be `auto`, but we want to be careful about that change.

**Comment by fernvenue** [comment]
@nmldiegues Thank you so much, `--edge-ip-version auto` works good on the server.

> Somewhere in the future we will make the default be auto, but we want to be careful about that change.

Yes, that's reasonable, and thanks again for your help.

**Comment by abelinkinbio** [comment]
@fernvenue we'll get this better documented as well 🙂
