### ISSUE TITLE
Help with using example packages 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [cloudflare/cloudflared#702]
Can anyone explain how to build the /hello dir? 

Thanks!

**Comment by sudarshan-reddy** [comment]
Hey @stevenanthonyrevo !

you don’t have to build it. It gets used if you choose to use a ‘hello-world’  service.


See https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/local-management/ingress/

for how to use it with your Tunnel.
