### ISSUE TITLE
💡Allow CORS control

### ISSUE THREAD

**Issue by maggie0002** [cloudflare/cloudflared#705]
**Describe the feature you'd like**
I had initially been using NGINX and had granted access to users to use my API from other domains. It seems since I have switched to CloudflareD there is no option to achieve the same. It would be helpful to have some more granular control.

**Comment by sudarshan-reddy** [comment]
Hey @maggie0002 , before we look into this, can you give us a more concrete example of what you are trying to achieve. You should already be able to transparently pass and receive CORS headers between your service proxied by cloudflared and clients.

**Comment by maggie0002** [comment]
I have a Directus docker container running on a server: https://github.com/directus/directus/blob/main/docker/Dockerfile

Cloudflared points directly to that container and connects to a domain: https://mydomain.com

I then have a website running locally: mywebsite.local

In the code of that website, it tries to access `https://mydomain.com/api` 

```
[Error] Preflight response is not successful. Status code: 405
[Error] Fetch API cannot load https://mydomain.com/api due to access control checks.
```

**Comment by sudarshan-reddy** [comment]
I'm afraid this has nothing to do with cloudflared since it just proxies the traffic you send.

Did your nginx configuration have a setup CORS headers like

```
Access-Control-Allow-Origin:  http://127.0.0.1:3000
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Content-Type, Authorization
```
?

**Comment by sudarshan-reddy** [comment]
Did your nginx configuration have a setup CORS headers like

```
Access-Control-Allow-Origin:  http://127.0.0.1:3000
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Content-Type, Authorization
```
?

**Comment by maggie0002** [comment]
> I'm afraid this has nothing to do with cloudflared since it just proxies the traffic you send.
> 
> Did your nginx configuration have a setup CORS headers like
> 
> ```
> Access-Control-Allow-Origin:  http://127.0.0.1:3000
> Access-Control-Allow-Methods: POST
> Access-Control-Allow-Headers: Content-Type, Authorization
> ```
> 
> ?

Similar yes, but allowing all connections with the `Access-Control-Allow-Origin`. There isn't an NGINX proxy involved now though, it's just a process started with NPX: https://github.com/directus/directus/blob/main/docker/Dockerfile

You think it is the process started with NPX then that needs the config?

**Comment by sudarshan-reddy** [comment]
Ideally, with CORS, the browser sends some headers and expects a response from the server (Your service behind cloudflared). My guess is your nginx might have been doing this for you (it must have been configured to). Now you need:

1. Another service behind cloudflared to do this for you (could be a minimal nginx). 
or

2. Your origin service to do this.

**Comment by maggie0002** [comment]
For me it was a simple adding of an env variable to Directus: https://docs.directus.io/self-hosted/config-options/#cors

You saved me a whole bunch of time, I really appreciate it.
