### ISSUE TITLE
Error "unable to find config file" for windows amd64 installation 🐛

### ISSUE THREAD

**Issue by mayconfsbrito** [cloudflare/cloudflared#716]
**Describe the bug**
I'm trying to install the cloudflare client (cloudflared-windows-amd64.exe) to use Zero Trust from my Windows 11 host. But the message below is displayed from cmd. When I try to run the msi file nothing happens and the cloudflare isn't installed as well.
```
unable to find config file

[process exited with code 1 (0x00000001)]
```

**To Reproduce**
1. Download the windows executable from [cloudflared-windows-amd64.exe](https://github.com/cloudflare/cloudflared/releases/download/2022.7.1/cloudflared-windows-amd64.exe).
2. Run the executable file.

**Expected behavior**
The installation should be running.

**Environment and versions**
 - OS: Windows 11
 - Architecture: AMD64
 - Version: 22000.795

**Logs and errors**
No logs
```
unable to find config file

[process exited with code 1 (0x00000001)]
```

**Comment by abelinkinbio** [comment]
@mayconfsbrito after downloading `cloudflared` on your machine, did you happen to rename the executable? If not, would you be able to try running PowerShell as an admin and then running `.\cloudflared-windows-amd64.exe tunnel login` and letting me know what you see? 

If that doesn't help, I may recommend opening a Cloudflare support ticket where we can request logs and take a deeper look.

**Comment by mayconfsbrito** [comment]
@abelinkinbio I didn't rename the executable. 
Sorry for delaying my answer, I formatted and reinstalled windows completely in my machine because I thought that this problem could be related with my environment.

When I tryied running `.\cloudflared-windows-amd64.exe tunnel login` a cloudflare login page was open.
This way may work for my case.

Thank you so much @abelinkinbio

**Comment by sudarshan-reddy** [comment]
Are you able to bring tunnel up @mayconfsbrito ?
