### ISSUE TITLE
Bypass Cloudflare when connected to internal network 💡

### ISSUE THREAD

**Issue by In-FinIT** [cloudflare/cloudflared#717]
**Describe the feature you'd like**
A way for the Cloudflare client to detect when connected to specific networks and disconnect from Cloudflare, much in the way it currently supports disabling Cloudflare when on WiFi networks.

**Describe alternatives you've considered**
Currently users need to disable Cloudflare when connected to the internal network.

**Additional context**
This has been discussed by Cloudflare reps here - https://community.cloudflare.com/t/warp-client-split-tunneling-exclusions-woes-local-and-remote-access/377267 - but I can't see any further updates on the feature.

**Comment by DevinCarr** [comment]
This is the GitHub repository for the cloudflared client which is separate from the warp client. Additionally there is no warp client repository since that client is not open sourced so I can't point you in the direction beyond where you already found discussion on the Cloudflare community forums.

**Comment by abelinkinbio** [comment]
@In-FinIT It's also worth noting this has been a popular feature request and we do have a team actively thinking through potential solutions. We're targeting picking up this work in Q4 (Oct-Dec). As Devin mentioned, the Cloudflare community (and Cloudflare Blog) will be the best place to find/request updates, but we'll also circle back to this thread as we make progress. Thanks for upvoting this feature!
