### ISSUE TITLE
Eero Routers in Bridge Mode Break Cloudflared

### ISSUE THREAD

**Issue by gatewayuav** [cloudflare/cloudflared#718]
Honestly pretty confused about this one, but I've replicated it a couple of times now. 

My Old Network: Modem > UDM Pro > POE 16 > Orbi Router/Satellite in Bridge mode (wifi only) 
New Attempted Setup: Modem > UDM Pro > POE 16 > Eero Router/Satellite in Bridge mode

UDM Pro has ports 443 and 7844 allowed outbound. For some reason, Cloudflared works perfectly fine with my old setup, no issues at all, zero downtime. However; when I plug in the Eero setup all hell breaks loose and it constantly drops the tunnel with the below errors: The device running Cloudflared does not go through wifi and is connected directly to the switch.

"WRN If this log occurs persistently, and cloudflared is unable to connect to Cloudflare Network with `quic` protocol"
"INF Switching to fallback protocol http2"
"ERR Connection terminated error="failed to accept QUIC stream"

Is it possible the Eero devices are trying to compete for these ports?

**Comment by abelinkinbio** [comment]
@gatewayuav would you mind sharing the model/SKU of your new eero router? I'd like to take a look at the spec sheet and see what the default firewall policies look like. I suspect that QUIC traffic may be blocked by default. We have seen a handful of cases like this in the past. It's generally been a little tricky to see where this policy lives, but some hardware appliances do still enforce these kind of policies from when QUIC was still an experimental protocol.

**Comment by gatewayuav** [comment]
@abelinkinbio - I'm using the Eero Pro 6 specifically, the 3 piece model from Best Buy. I think what's odd is that this is bridge mode so in theory there should not be any firewall action going on with the model? The Cloudflared docker image is running off a computer connected directly to the model so really the traffic doesn't need to go through it. Is it possible Eero is also using those same ports?

I definitely don't expect full resolution on this one and am not sure I will even keep the units to serve my wifi but figured it might be an interesting use case/issue at the very least!

**Comment by gatewayuav** [comment]
Closing this one....

The Cloudflared container just happened to sit on one of the IP addresses that Eero also took...so that was fun. 

Leaving this up but closing with comment in case anyone wants a chuckle :D
