### ISSUE TITLE
🐛 Homebrew Ubuntu permission denied

### ISSUE THREAD

**Issue by namen3645** [cloudflare/cloudflared#720]
Ubuntu 20.04 
After install cloudfalared from brew

cloudflared@moto:~$ brew doctor
Your system is ready to brew.

cloudflared@motodetal:~$ ls -l /home/linuxbrew/.linuxbrew/bin/cloudflared
lrwxrwxrwx 1 cloudflared cloudflared 46 Aug 10 16:45 /home/linuxbrew/.linuxbrew/bin/cloudflared -> ../Cellar/cloudflared/2022.7.1/bin/cloudflared

cloudflared@moto:~$ cloudflared
bash: /home/linuxbrew/.linuxbrew/bin/cloudflared: Permission denied

**Comment by sudarshan-reddy** [comment]
Did you try to give it permission? 

What happens when you `chmod a+x home/linuxbrew/.linuxbrew/bin/cloudflared`?
