### ISSUE TITLE
🐛 `arm64` Docker image is built for the `linux/amd64` platform

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflared#727]
**Describe the bug**

2022.8.1 now has `arm64` builds - but these appear to be built for the wrong platform.

![image](https://user-images.githubusercontent.com/94662631/184882700-f3c3dd50-8848-47df-b203-c37fb84b22e9.png)

When running these on `arm64`, such as Apple Silicon, Docker reports the following:

```
Status: Downloaded newer image for cloudflare/cloudflared:2022.8.1-arm64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Attempting to `docker run` with a `--platform linux/arm64` flag results in the following error.

```
docker: Error response from daemon: image with reference cloudflare/cloudflared:2022.8.1-arm64 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
```

**To Reproduce**
1. Pull the image. `docker pull cloudflare/cloudflared:2022.8.1-arm64`
2. Run the image on a ARM64 platform. `docker run --platform linux/arm64 cloudflare/cloudflared:2022.8.1-arm64`
3. See error.

**Expected behavior**

Image to be built for the `linux/arm64` platform.

**Environment and versions**
 - OS: MacOS
 - Architecture: ARM
 - Version: 2022.8.1

**Comment by KianNH** [comment]
My best guess is that whilst `cloudflared` the binary has been built for `arm64` by specifying the `GOARCH`, the Docker image itself has not been built for `linux/arm64`.

https://github.com/cloudflare/cloudflared/blob/e09c62a7961c73bdab1f2f71cdd6e8f5c56a0bc4/Dockerfile.arm64#L14

**Comment by sudarshan-reddy** [comment]
That is correct. We are aware of this problem and working on a fix.

**Comment by KianNH** [comment]
It seems like it is just built with `docker build` which I'd expect to build for the architecture it is running on, whereas `docker buildx` allows for cross-platform building.

https://github.com/cloudflare/cloudflared/blob/e09c62a7961c73bdab1f2f71cdd6e8f5c56a0bc4/Makefile#L132

https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx

**Comment by KianNH** [comment]
@sudarshan-reddy whilst not specifically related to `cloudflared`, I hope you might know who to mention this issue to.

The Zero Trust dashboard provides users with a copy/paste command to setup a Docker container for remotely managed tunnels, but this command is just using the version (i.e `:2022.8.1`) which isn't a tag anymore since it is now `:2022.8.1-amd64` or `:2022.8.1-arm64`.

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/94662631/184886418-fb2f45ac-df5d-4fa9-919d-10c84546635b.png">

**Comment by sudarshan-reddy** [comment]
That report belongs here as well @KianNH . Ideally, we want to continue have that tag. I broke that with the latest release but should be able to fix it soon.

**Comment by sudarshan-reddy** [comment]
https://github.com/cloudflare/cloudflared/commit/906eb2d8403353cf0e9c641ce9319e929a425fd0 will fix the first problem. We'll have another release out soon.

**Comment by KianNH** [comment]
That was quick! Nice work.

Pulled down that commit locally & the resulting image is working fine for me, thanks for the help.

**Comment by sudarshan-reddy** [comment]
Thanks so much for confirming!

**Comment by sudarshan-reddy** [comment]
w.r.t the UX problem you reported, we might decide to fix it on the UI. I'll carry the torch on that one and keep this issue open until we see it through.

**Comment by KianNH** [comment]
It'd be cool to have a multi-platform image - so it remains as the `2022.8.1` tag but has `linux/amd64` and `linux/arm64` images in the manifest.

Might need to nudge the build process a bit in regards to architectures for the image (i.e `distroless`) and what's passed to `GOOS`/`GOARCH` - I think I've seen some PRs open in regards to that though.

I assume it's all built & published on Cloudflare's infrastructure as opposed to using GHA?

**Comment by sudarshan-reddy** [comment]
> It'd be cool to have a multi-platform image - so it remains as the 2022.8.1 tag but has linux/amd64 and linux/arm64 images in the manifest.


This already will hold true for `latest`. The idea is only requiring one to be specific if they want to pin to a particular version.

**Comment by sudarshan-reddy** [comment]
> I assume it's all built & published on Cloudflare's infrastructure as opposed to using GHA?

Correct.  This is beneficial to us because we have pre-configured alerts and metrics on this for easier maintenance.

**Comment by eknudtson** [comment]
To be sure, is the `2022.8.2` image tag going to be published, or should we begin pinning to arch specific versions?

**Comment by sudarshan-reddy** [comment]
You should pin to the arch version if you want to continue using `version`. `latest` should work either way.

**Comment by sudarshan-reddy** [comment]
This is now resolved. We've scheduled the UI to also change this the tag to `latest` and should be out soon. Thanks so much for being on top of this. ❤️
