### ISSUE TITLE
🐛 Release notes contain reverted and duplicate commits

### ISSUE THREAD

**Issue by kittenswolf** [cloudflare/cloudflared#728]
Not sure if bug is the right type, but the release notes include reverted and duplicate commits.

[Example](https://github.com/cloudflare/cloudflared/commit/e09c62a7961c73bdab1f2f71cdd6e8f5c56a0bc4):
```
- 2022-08-11 TUN-6617: Dont fallback to http2 if QUIC conn was successful.
- 2022-08-11 TUN-6617: Dont fallback to http2 if QUIC conn was successful.
- 2022-08-11 Revert "TUN-6617: Dont fallback to http2 if QUIC conn was successful."
- 2022-08-11 TUN-6617: Dont fallback to http2 if QUIC conn was successful.
```

I understand that these release notes are probably automatically generated, but these 4 lines contain just 1 change. Can this be prevented for future releases?

**Comment by sudarshan-reddy** [comment]
This is mostly because these are commit messages and we went back and forth a bit while testing. Like you rightly pointed out, the Release notes is just automatically generated from commit messages so ideally you want to rely on the CHANGES.md file to track noteworthy changes.
