### ISSUE TITLE
How to use IPV6 adresses in config.yaml?

### ISSUE THREAD

**Issue by YoKoGFX** [cloudflare/cloudflared#73]
What would be the correct way to add the ipv6 addresses of the CloudflareDNS to the config.yaml?
My current config is the default:
```
proxy-dns: true
proxy-dns-upstream:
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
```

**Comment by moderation** [comment]
I don't think this is documented but this works for me as a command line option. Remove the 1 if you want to listen on the public interface.

`--proxy-dns-address="::1"`

via https://github.com/cloudflare/cloudflared/issues/6#issuecomment-379165518

**Comment by YoKoGFX** [comment]
@moderation merci! :)
