### ISSUE TITLE
Allow Metrics Endpoint to bind on all interfaces💡

### ISSUE THREAD

**Issue by aczajkowski** [cloudflare/cloudflared#732]
**Describe the feature you'd like**
Currently Cloudflared exposes flag to enable metrics endpoint
```
--metrics <address>:<some_port>
```
There is no way to configure it to bind on loopback interface as well as on external interface.
You can either configure `--metrics 127.0.0.1:8099` or `--metrics 0.0.0.0:8099` 
Which ends up binding only loopback interface or only external interface.
I would be useful if there would be possibility to either provide multiple `--metrics` flag or pass only port which will mean bind on all interfaces.

**Comment by sudarshan-reddy** [comment]
Happy to take a PR for this.

**Comment by DevinCarr** [comment]
Binding `--metrics 0.0.0.0:8099` is binding to localhost as well as all other local interfaces. Are you possibly doing some other setup, or attempting to bind the metrics service to many different interfaces but not all?

**Comment by aczajkowski** [comment]
I've just recreated whole environment locally and tested again with newer version 2022.8.2 and was not able to reproduce problem any more. Seems it's something else causing this problem in dev envs.

Thx. for guidance and confirmation. Once figured out I will update this issue.
