### ISSUE TITLE
💡 Update from Cloudflare instead of GitHub.

### ISSUE THREAD

**Issue by fernvenue** [cloudflare/cloudflared#736]
**Describe the feature you'd like**
Hi, some of my servers only have IPv6 connection, and `cloudflared` using `--edge-ip-version 6` on those servers for now. Here's the problem, I can't update `cloudflared` whether automatically by systemd or manually by `cloudflared update`, I have to download binary and upload it to the server by myself, because GitHub doesn't support IPv6 :(

**Describe alternatives you've considered**
Could you please make `cloudflared` update itself from Cloudflare instead of GitHub? Or just give an option or flag let user can choose.

**Additional context**
Of course, I can use the old version, but that's a terrible solution, right?

**Comment by sudarshan-reddy** [comment]
What operating system are you on?

**Comment by fernvenue** [comment]
> What operating system are you on?

Hi @sudarshan-reddy, I'm using debian 11 bullseye.

**Comment by sudarshan-reddy** [comment]
What happens when you update this via apt?

**Comment by fernvenue** [comment]
> What happens when you update this via apt?

Hi @sudarshan-reddy, sorry for replying so late. Actually, I installed it using binary with `cloudflared service install`, and here's the error message when I run `cloudflared udpate` on some IPv6 only servers:

```
~# cloudflared update
2022-08-23T06:41:01Z ERR update failed to apply error="Get \"https://github.com/cloudflare/cloudflared/releases/download/2022.8.2/cloudflared-linux-amd64\": dial tcp 20.205.243.166:443: connect: network is unreachable"
failed to update cloudflared: Get "https://github.com/cloudflare/cloudflared/releases/download/2022.8.2/cloudflared-linux-amd64": dial tcp 20.205.243.166:443: connect: network is unreachable
```

Just like that, the error message told me that GitHub's address is unreachable, and that's reasonable because the server doesn't have IPv4 connection, and GitHub doesn't have AAAA record, that's why I wanna update from Cloudflare instead of GitHub.

**Comment by sudarshan-reddy** [comment]
Mostly trying to see if we have a valid asset (and can give you a temporary workaround at the same time).

**Comment by fernvenue** [comment]
That seems so great, `cloudflared` now successfully updated to the latest version by package manager, and when I run `cloudflared update` this time I just got the message:

> cloudflared was installed by a package manager. Please update using the same method.

So the problem solved I think, thank you so much for your help!

I still have another question about updating, I found `cloudflared-update.timer` and `cloudflared-update.service` working on my servers even when I'm using `--no-autoupdate`, is it fair expectation? Could you please tell me what should I do about auto update in common way?

**Comment by sudarshan-reddy** [comment]
It is. That’s a known issue on our roadmap.  Will take a look.
