### ISSUE TITLE
🐛 Tags for "2022.8.1" and "2022.8.2" missing on dockerhub

### ISSUE THREAD

**Issue by joelmukuthu** [cloudflare/cloudflared#737]
**Describe the bug**

See https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&name=2022.8.1 and https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&name=2022.8.2 and compare with https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&name=2022.8.0. For the former two versions, only the AMD64 and ARM64 tags are published. 

Is that intentional?

**To Reproduce**

See above.

**Expected behavior**

That https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&name=2022.8.1 and https://hub.docker.com/r/cloudflare/cloudflared/tags?page=1&name=2022.8.2 would be published to dockerhub.

**Environment and versions**

NA

**Logs and errors**

NA

**Additional context**

NA

**Comment by sudarshan-reddy** [comment]
Hey @joelmukuthu . You can now either use the `latest` tag to pull the docker image or append your arch (amd64 and arm64 are currently supported) to download for a specific version.

See: https://github.com/cloudflare/cloudflared/issues/727#issuecomment-1216920222
