### ISSUE TITLE
🐛`No connection could be made because the target machine actively refused it.` returned when accessing subdomain

### ISSUE THREAD

**Issue by Its-Tachanks** [cloudflare/cloudflared#742]
Upon running `cloudflared tunnel --config C:\Users\user\.cloudflared\config.yml run tunnelname` my tunnel creation runs properly, but will, when accessing the associated subdomain, returns `ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it." cfRay=74206971dbb7dab5-MIA ingressRule=0 originService=http://localhost:8080`. I am currently attempting to host a game server with SCP secret laboratory, found on steam, locally and tunnel it with my subdomain, but when accessing the domain I get bad gateway 502. I am 100% that my tunnel works properly as I have tested it with a basic local host web server with the same method and it worked, but tunneling my localhost port that is used with my game server does not work as intended with the 502 error and when using it within the game direct connect, instead printing the errors found below. I have found that the game only works with a direct connection localhost of `localhost:8080` and not `http://localhost:8080` meaning, maybe, if i were to be able to set the service in my ingress config, to `localhost:8080` solely, without http or anything staring it, it might work, but instead says `localhost:8080 is an invalid address, please make sure it has a scheme and a hostname`. Since my game server only works with a localhost:8080, how might I tunnel the server? (The ports can change with the local server, nothing is set in stone)

**To Reproduce**
1. Create a tunnel with the config.yml found below
2. Run cloudflared tunnel --config C:\Users\user\.cloudflared\config.yml run tunnelname
3. See error

If it's an issue with Cloudflare Tunnel:
1. Tunnel ID : 9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b
2. cloudflared config: 
```
tunnel: 9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b
credentials-file: C:\Users\user\.cloudflared\9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b.json
protocol: quic
originRequest:
noTLSVerify: true
ingress:
  - hostname: mysubdomiainhere
    service: http://localhost:8080
  - service: http_status:404
```

**Expected behavior**
Upon tunneling my game server local host to my website subdomain, I should be able to direct connect to it within the game and utilize it as a connection to the game server

 - OS: Windows
 - Architecture: AMD
 - Version: 2022.8.2

**Logs and errors**
`ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it." cfRay=74206971dbb7dab5-MIA ingressRule=0 originService=http://localhost:8080`

`{"level":"error","time":"2022-08-28T22:21:26Z","message":"Falling back to a default logger due to logger setup failure: unable to create a new logfile: open C:\\Users\\user\\.cloudflared: is a directory"}
{"level":"info","tunnelID":"9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b","time":"2022-08-28T22:21:26Z","message":"Starting tunnel"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"Version 2022.8.2"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"GOOS: windows, GOVersion: go1.18.5, GoArch: amd64"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"Settings: map[config:C:\\Users\\user\\.cloudflared\\config.yml cred-file:C:\\Users\\user\\.cloudflared\\9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b.json credentials-file:C:\\Users\\user\\.cloudflared\\9f9464ac-3ba6-4ea2-b19b-e110f93c5c4b.json logfile:C:\\Users\\user\\.cloudflared p:quic protocol:quic]"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"cloudflared will not automatically update on Windows systems."}
{"level":"error","time":"2022-08-28T22:21:26Z","message":"Falling back to a default logger due to logger setup failure: unable to create a new logfile: open C:\\Users\\user\\.cloudflared: is a directory"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"Generated Connector ID: 6de991ac-7b5d-43f2-b36c-400392b0513b"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"Initial protocol quic"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"cloudflared does not support loading the system root certificate pool on Windows. Please use --origin-ca-pool <PATH> to specify the path to the certificate pool"}
{"level":"debug","domain":"_v2-origintunneld._tcp.argotunnel.com","time":"2022-08-28T22:21:26Z","message":"looking up edge SRV record"}
{"level":"info","time":"2022-08-28T22:21:26Z","message":"Starting metrics server on 127.0.0.1:59585/metrics"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::7]:7844 UDP:[2606:4700:a0::7]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::3]:7844 UDP:[2606:4700:a0::3]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::10]:7844 UDP:[2606:4700:a0::10]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::4]:7844 UDP:[2606:4700:a0::4]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::6]:7844 UDP:[2606:4700:a0::6]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::2]:7844 UDP:[2606:4700:a0::2]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::1]:7844 UDP:[2606:4700:a0::1]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::9]:7844 UDP:[2606:4700:a0::9]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::5]:7844 UDP:[2606:4700:a0::5]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a0::8]:7844 UDP:[2606:4700:a0::8]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.37:7844 UDP:198.41.192.37:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.7:7844 UDP:198.41.192.7:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.57:7844 UDP:198.41.192.57:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.27:7844 UDP:198.41.192.27:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.107:7844 UDP:198.41.192.107:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.167:7844 UDP:198.41.192.167:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.77:7844 UDP:198.41.192.77:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.47:7844 UDP:198.41.192.47:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.227:7844 UDP:198.41.192.227:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.192.67:7844 UDP:198.41.192.67:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::3]:7844 UDP:[2606:4700:a8::3]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::5]:7844 UDP:[2606:4700:a8::5]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::6]:7844 UDP:[2606:4700:a8::6]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::1]:7844 UDP:[2606:4700:a8::1]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::9]:7844 UDP:[2606:4700:a8::9]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::4]:7844 UDP:[2606:4700:a8::4]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::2]:7844 UDP:[2606:4700:a8::2]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::7]:7844 UDP:[2606:4700:a8::7]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::8]:7844 UDP:[2606:4700:a8::8]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:[2606:4700:a8::10]:7844 UDP:[2606:4700:a8::10]:7844 IPVersion:6}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.113:7844 UDP:198.41.200.113:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.13:7844 UDP:198.41.200.13:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.33:7844 UDP:198.41.200.33:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.193:7844 UDP:198.41.200.193:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.233:7844 UDP:198.41.200.233:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.73:7844 UDP:198.41.200.73:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.63:7844 UDP:198.41.200.63:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.43:7844 UDP:198.41.200.43:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.53:7844 UDP:198.41.200.53:7844 IPVersion:4}"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"Edge Address: {TCP:198.41.200.23:7844 UDP:198.41.200.23:7844 IPVersion:4}"}
{"level":"debug","connIndex":0,"ip":"198.41.200.63","time":"2022-08-28T22:21:26Z","message":"edgediscovery - GetAddr: Giving connection its new address"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))"}
{"level":"debug","time":"2022-08-28T22:21:26Z","message":"rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))"}
{"level":"info","connIndex":0,"location":"MIA","ip":"198.41.200.63","time":"2022-08-28T22:21:27Z","message":"Connection f29beb04-eeb4-4180-82ce-dd80c82f113a registered"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))"}
{"level":"debug","connIndex":1,"ip":"198.41.192.7","time":"2022-08-28T22:21:27Z","message":"edgediscovery - GetAddr: Giving connection its new address"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (call = (questionId = 1, target = (importedCap = 0), interfaceId = 17804583019846587543, methodId = 2, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))"}
{"level":"info","connIndex":1,"location":"ATL","ip":"198.41.192.7","time":"2022-08-28T22:21:27Z","message":"Connection 8f08ff70-d859-48d5-b9aa-6468c35be77c registered"}
{"level":"debug","time":"2022-08-28T22:21:27Z","message":"rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))"}
{"level":"debug","connIndex":2,"ip":"198.41.200.233","time":"2022-08-28T22:21:28Z","message":"edgediscovery - GetAddr: Giving connection its new address"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))"}
{"level":"info","connIndex":2,"location":"MIA","ip":"198.41.200.233","time":"2022-08-28T22:21:28Z","message":"Connection 1aeb8b8a-a3cc-4866-94a8-3ef826ad4eb1 registered"}
{"level":"debug","time":"2022-08-28T22:21:28Z","message":"rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))"}
{"level":"debug","connIndex":3,"ip":"198.41.192.77","time":"2022-08-28T22:21:29Z","message":"edgediscovery - GetAddr: Giving connection its new address"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: tx (bootstrap = (questionId = 0, deprecatedObjectId = <opaque pointer>))"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: tx (call = (questionId = 1, target = (promisedAnswer = (questionId = 0, transform = [])), interfaceId = 17804583019846587543, methodId = 0, allowThirdPartyTailCall = false, params = (content = <opaque pointer>, capTable = []), sendResultsTo = (caller = void)))"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: rx (return = (answerId = 0, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [(senderHosted = 0)])))"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: tx (finish = (questionId = 0, releaseResultCaps = false))"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: rx (return = (answerId = 1, releaseParamCaps = false, results = (content = <opaque pointer>, capTable = [])))"}
{"level":"info","connIndex":3,"location":"ATL","ip":"198.41.192.77","time":"2022-08-28T22:21:29Z","message":"Connection c508324d-9531-4bdd-ad8b-e4876284e288 registered"}
{"level":"debug","time":"2022-08-28T22:21:29Z","message":"rpcconnect: tx (finish = (questionId = 1, releaseResultCaps = false))"}`

The game hosted is here "https://store.steampowered.com/app/700330/SCP_Secret_Laboratory/"

**Comment by nmldiegues** [comment]
I suspect your game expects TCP connections that are not HTTP.  Can you confirm what protocol your game expects on the port where it listens for? (localhost:8080)

if TCP, then you have 2 options:
 - users must rely on cloudflared access tcp to proxy their eyeballs to your tunnel: example where origin is a RDP server that speaks TCP https://developers.cloudflare.com/cloudflare-one/tutorials/rdp/
 - or users must run WARP in your CF account to be able to access your internal IP: https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel/

**Comment by Its-Tachanks** [comment]
The game utilizes UDP connections as I have found, but can also use TCP/UDP together

**Comment by nmldiegues** [comment]
Then if it requires UDP, you definitely need https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel/
This provides a look&feel experience of a VPN, with Zero Trust foundations
It only makes sense to apply to a scenario where your users/gamers are part of your Cloudflare Account;  i.e., this use case does not apply to DNS (Public Hostnames).
