### ISSUE TITLE
💡Web Interface of log level debug to see http inspect

### ISSUE THREAD

**Issue by ayon-maji** [cloudflare/cloudflared#744]
![image (2)](https://user-images.githubusercontent.com/98821176/187416820-48f74055-a40b-42d1-b460-e7e4e204cb5d.png)
**Web Interface of log level debug to see http inspect to help developers at the time of debugging**

**Comment by sudarshan-reddy** [comment]
Hi. @ayon-maji , you will have to give us more context and information on what you want to achieve. Can you open a new issue in the recommended template please?
