### ISSUE TITLE
🐛 High availability from.. the same PoP..?

### ISSUE THREAD

**Issue by morpig** [cloudflare/cloudflared#747]
Cloudflare team,

I noticed that recently both the region1.argotunnel.com and region2.argotunnel.com are routed to the same colo/city, which is not expected with cloudflared's HA design.

In my case, it usually goes to FRA and AMS colo for HA.

Is this expected? Are you routing it to different DC facilities in the same city?

```
root@ams01-path:~# dig region1.argotunnel.com

; <<>> DiG 9.16.1-Ubuntu <<>> region1.argotunnel.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18927
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;region1.argotunnel.com.                IN      A

;; ANSWER SECTION:
region1.argotunnel.com. 6492    IN      A       198.41.192.7
region1.argotunnel.com. 6492    IN      A       198.41.192.47
region1.argotunnel.com. 6492    IN      A       198.41.192.227
region1.argotunnel.com. 6492    IN      A       198.41.192.167
region1.argotunnel.com. 6492    IN      A       198.41.192.107

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Sep 02 23:39:45 WIB 2022
;; MSG SIZE  rcvd: 131

```

```
root@ams01-path:~# dig region2.argotunnel.com

; <<>> DiG 9.16.1-Ubuntu <<>> region2.argotunnel.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55134
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;region2.argotunnel.com.                IN      A

;; ANSWER SECTION:
region2.argotunnel.com. 300     IN      A       198.41.200.13
region2.argotunnel.com. 300     IN      A       198.41.200.113
region2.argotunnel.com. 300     IN      A       198.41.200.233
region2.argotunnel.com. 300     IN      A       198.41.200.53
region2.argotunnel.com. 300     IN      A       198.41.200.193

;; Query time: 8 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Sep 02 23:39:57 WIB 2022
;; MSG SIZE  rcvd: 131
```

```
root@ams01-path:~# curl 198.41.192.1 -v
*   Trying 198.41.192.1:80...
* TCP_NODELAY set
* Connected to 198.41.192.1 (198.41.192.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 198.41.192.1
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Fri, 02 Sep 2022 16:41:39 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: close
< X-Frame-Options: SAMEORIGIN
< Referrer-Policy: same-origin
< Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< Server: cloudflare
< CF-RAY: 7447b1c54c91b74e-AMS
< 
* Closing connection 0
error code: 1003
```

```
root@ams01-path:~# curl 198.41.200.1 -v
*   Trying 198.41.200.1:80...
* TCP_NODELAY set
* Connected to 198.41.200.1 (198.41.200.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 198.41.200.1
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Fri, 02 Sep 2022 16:41:26 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: close
< X-Frame-Options: SAMEORIGIN
< Referrer-Policy: same-origin
< Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< Server: cloudflare
< CF-RAY: 7447b1724b87fa58-AMS
< 
* Closing connection 0
error code: 1003
```

**Comment by DevinCarr** [comment]
Please note that we have a more expanded list of IP ranges (including IPv6) at: `region1.v2.argotunnel.com` and `region2.v2.argotunnel.com` noted here: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/ports-and-ips/

Additionally, everyone of those IPs are anycast IPs and will route based on the closest Cloudflare PoP. It could be that your route from your current location is reaching the same PoP, in cloudflared on the other-hand, we make sure to check the connections during registration to make sure we reach a unique edge location for the high availability connections.
If you have an example of a cloudflared tunnel violating this expectation, please feel free to provide your tunnel id and we can check out some more details on our side to verify.

**Comment by nmldiegues** [comment]
> Is this expected? Are you routing it to different DC facilities in the same city?

Yes. Even if all 4 connections say the same acronym, it's actually different underlying "availability zones" (using AWS' terms).

However, we generally try to have all colos (as we call them) in the same PoP (point of presence, e.g. FRA) in the same anycast region (either region1 or region2).
There may have been some mistake, so as Devin said, if you can show us your Tunnel ID as well as the logs where you saw the violation happening, we can fix it.

**Comment by morpig** [comment]
```
2022-09-02T17:23:30Z INF Initial protocol http2
2022-09-02T17:23:30Z INF Starting metrics server on 100.90.94.86:41237/metrics
2022-09-02T17:23:30Z INF Connection dcf4b8e1-1c15-4ffa-8a29-d7c5128e99a2 registered connIndex=0 ip=198.41.200.13 location=AMS
2022-09-02T17:23:31Z INF Connection 29474ce9-8745-41dc-803a-f68d4c1ebd70 registered connIndex=1 ip=198.41.192.47 location=AMS
2022-09-02T17:23:32Z INF Connection a7d939e0-ba7c-457d-bf64-2f9c3ed3bce7 registered connIndex=2 ip=198.41.200.43 location=AMS
2022-09-02T17:23:33Z INF Connection 609e78a9-2661-4cf1-8aa5-8cf61b4f54d4 registered connIndex=3 ip=198.41.192.107 location=AMS
```

During the old days (for me) it's always 2 different POPs for HA, this looks new to me. No warnings/errors on my side, so it's all good?

**Comment by morpig** [comment]
One more thing, let's say you have a scheduled maintenance in AMS pop. Are you going to drop all 4 connections at once?

Looking at region1.argotunnel and region1.v2.argotunnel, it's all on the same /24 ip block.

Usually I would see drops in 2 of 4 HA connections (while being rerouted to nearest pop), while having the remaining 2 connections online.

**Comment by nmldiegues** [comment]
> One more thing, let's say you have a scheduled maintenance in AMS pop. Are you going to drop all 4 connections at once?

Most PoPs are now composed of multiple independent colos. That's the case for AMS. We wouldn't do maintenance on all of it at the same time (normally). But it can happen under rare circumstances (or physical disasters that affect the independent AMS colos).

You'll still observe the same availability in practice for now, but regardless, we did not intend to have different AMS colos in different Tunnel regions. We'll get to the bottom of it. Thanks for reporting.

**Comment by morpig** [comment]
Sounds clear to me. Looks like AMS is one of CF's super pop now 😎

Thanks for clearing things up!
