### ISSUE TITLE
🐛High CPU utilization with latest version  2022.9.0 on ARM64 - Raspberry Pi 4B

### ISSUE THREAD

**Issue by iAmSaugata** [cloudflare/cloudflared#752]
**Describe the bug**

**To Reproduce**
1. Cloudflare Zero Trust
2.  Latest ARM64 Container
3. High CPU utilization than previous version

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 58d7dfc2-9105-4414-90f3-7979f05e55d4
5. cloudflared config: Cloudflare Zero Trust

**Expected behavior**
Similar CPU utilization as previous version

**Environment and versions**
 - OS: Linux RaspberryPi 5.15.61-v8+ 
 - Architecture: ARM
 - Version: 2022.9.0

![image](https://user-images.githubusercontent.com/26755120/188930548-3f1b99f7-c623-42f3-9b6a-69083ec2c6de.png)

**Comment by nmldiegues** [comment]
What previous version were you running with?

**Comment by iAmSaugata** [comment]
> What previous version were you running with?

I was running previous docker image(2022.8.4), today approx. 40 min ago I saw it is update and I pulled the latest one.

**Comment by sudarshan-reddy** [comment]
@iAmSaugata are you still seeing high CPU utilisation? Just so we can try to reproduce it, could you tell us more about what sort of traffic you are seeing when this happens?

**Comment by iAmSaugata** [comment]
> @iAmSaugata are you still seeing high CPU utilisation? Just so we can try to reproduce it, could you tell us more about what sort of traffic you are seeing when this happens?

Nope, it is no longer using high CPU, back to normal, I have no idea what happened just after update.

![image](https://user-images.githubusercontent.com/26755120/190157582-d73662d8-76f1-4ee9-8588-27db3fa206a3.png)

**Comment by DevinCarr** [comment]
Feel free to open a new issue and link to this one if you experience higher CPU latency than expected. Additionally, the more details you can provide from cloudflared (next time), the more we can help out!
