### ISSUE TITLE
🐛 ssh-config is generated for Linux despite installing the Windows version

### ISSUE THREAD

**Issue by y2k04** [cloudflare/cloudflared#753]
**Describe the bug**
If you do `cloudflared access ssh-config --hostname [hostname] --short-lived-cert` on Windows, it will create an ssh config entry made for Linux.

**To Reproduce**
1. Run `cloudflared access ssh-config --hostname [hostname] --short-lived-cert` on Windows
2. It will generate a config for a Linux OS, not Windows.

**Expected behavior**
It is meant to create an ssh config for Windows.

**Environment and versions**
 - OS: Windows
 - Architecture: x64
 - Version: 22H2 (22622.586)

**Logs and errors**
![image](https://user-images.githubusercontent.com/29883287/189507274-d9626529-c34b-4fcc-a0b4-9dd3f3a77c5b.png)

**Additional context**
N/A

**Comment by y2k04** [comment]
It doesn't have to do with the default shell for Windows, it is just how cloudflared was ported to Windows. It is just a small oversight by the developers, nothing big. "Should be easy" to fix this issue. It's just as "simple" as checking the operating system, OR, hard coding it for the specific release, whether it is for Linux and MacOS or Windows.

**Comment by Bexanderthebex** [comment]
@y2k04 yeah what exact config is tripping the it of is what I am trying to find out.

**Comment by y2k04** [comment]
When it generates the config, it specifies the shell as bash, even though I ran it under Windows, not WSL or a VM or Docker.

**Comment by Bexanderthebex** [comment]
@y2k04 that is exactly what I was referring to earlier...

**Comment by y2k04** [comment]
Could you please rephrase the question?

**Comment by y2k04** [comment]
I think it would close the issue :3
