### ISSUE TITLE
💡 Add multi-arch container builds for standard release version tags

### ISSUE THREAD

**Issue by jamurtag** [cloudflare/cloudflared#754]
**Describe the feature you'd like**
Create a multi-arch amd64/arm64 Docker build for standard app version tags (i.e. 2022.9.0).

**Describe alternatives you've considered**
n/a

**Additional context**
When cloudflared added support for arm64 images, the well-known release version tag was changed to architecture appended images, i.e. 2022.9.0-amd64 & 2022.9.0-arm64. An example of where this causes issues can be seen in this (Cloudflare) [cloudflared Helm chart](https://github.com/cloudflare/argo-tunnel-examples/blob/master/helm/cloudflare-tunnel/Chart.yaml#L19) - using `appVersion` in the Chart.yaml which defaults to the image tag if none is supplied - which now breaks as there is no architecture-neutral tag.

**Comment by dbackeus** [comment]
We also have need for this as we're running both arm64 and amd64 based nodes and would like to avoid using `:latest` if possible (which is currently the only tag which support both architectures).

**Comment by firecow** [comment]
Our upgrade routine via renovate is quite broken right now. In fact we only noticed the 2022.9.0 upgrade by shear luck :smile:

**Comment by sudarshan-reddy** [comment]
`docker pull cloudflare/cloudflared:2022.10.2` should work now.

**Comment by firecow** [comment]
@sudarshan-reddy We are very happy about this, thank you very much...

**Comment by sudarshan-reddy** [comment]
And we are very appreciative for all your input that makes cloudflared a better tool every iteration.
