### ISSUE TITLE
Nextcloud is buggy with Cloudflare Tunnel but is fine with TryCloudflare🐛

### ISSUE THREAD

**Issue by lekia** [cloudflare/cloudflared#764]
**Describe the bug**
I published my dockered Nextcloud with Cloudflare Tunnel.

Nextcloud Docker is missing its icons in navigation bar. And there is no login panel when visiting the website on mobile. Most of the other functions behave well.

The reason I submit the issue here but not at Nextcloud's is when I publish the same website (on the same time, the same host, the same port, and the same protocol) with "cloudflared tunnel", everything works perfectly.

![Screenshot 2022-09-23 230626](https://user-images.githubusercontent.com/11898314/191995639-37badf49-63ef-48bb-b167-1104042ff7fe.png)
![Screenshot 2022-09-23 230723](https://user-images.githubusercontent.com/11898314/191995649-de2a7f5f-4c61-4553-98bc-1f27f0141321.png)

I tried on VM on Play-with-Docker with the same result so I don't think it has anything to do with the host.

**To Reproduce**
1. Deploy Nextcloud Docker with an example docker-compose file on "Base version - FPM" (or apache) in docker-compose section on Nextcloud official [Github](https://github.com/nextcloud/docker) page. Port 8080 is exposed.
2. Execute "Install and run a connector" command on Access Tunnels on Cloudflare. In "Public Hostname" section, Add a hostname pointing to http://localhost:8080.
3. Visit the added hostname, install Nextcloud, and enter the dashboard.

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 1bd8eefc-2ec1-4d18-adff-47ad9d102041
5. cloudflared config: (Hostname points to http://localhost:8080 on Zero Trust dashboard. No CLI involved.)

**Expected behavior**
Just what I have with anonymous tunnel on TryCloudflare.

**Environment and versions**
 - OS: Ubuntu 20.04
 - Architecture: x86-64 WSL2
 - Version: 2022.9.0

**Logs and errors**
No error when "-loglevel info".

**Additional context**

**Comment by sudarshan-reddy** [comment]
Hey @lekia , unfortunately it looks like we need more information. 

It seems like you see tunnel proxying traffic. Your UI examples dont really tell us what's wrong.

**Comment by lekia** [comment]
> 

Thanks for the response.
What information is required? All I could tell is the nextcloud site is malfunction when served by cloudflare tunnel configured in zero trust panel but is fully functional by trycloudflare with a simple "cloudflared tunnel" command. I wonder if there is anything different between these two approaches. If none, it might be an issue in dash.cloudflare.com but not the teams dashboard and has nothing to do with cloudflare tunnel.

**Comment by lekia** [comment]
It's confirmed that the issue is caused by Rocket Loader and disable which gets everything running smoothly.
