### ISSUE TITLE
🐛 Connection refused when using `h2mux`.

### ISSUE THREAD

**Issue by fernvenue** [cloudflare/cloudflared#768]
**Describe the bug**
Hi, when I change the protocol to `h2mux`, all my tunnels down, and `cloudflared` keep trying to connect to `127.0.0.1:8080`. To be clear, I have no tunnel configured on that port, and I have no idea why `cloudflared` try to connect to the port. I tried to clear all my tunnels on dashboard and set them up again, but still like this, and if I change the protocol back to `quic` or `http2`, all tunnels back online. Is there anything should I do more if I wanna use `h2mux` as protocol?

**To Reproduce**
1. Add `--protocol h2mux` flag;
2. Run `systemctl daemon-reload` and `systemctl restart cloudflared`;
3. See error.

If it's an issue with Cloudflare Tunnel:
Yeah...but that's just happened to all my tunnels.

**Expected behavior**
I hope `cloudflared` works good with `h2mux` protocol.

**Environment and versions**
 - OS: debian 11 bullseye
 - Architecture: amd64
 - Version: 2022.9.1

**Logs and errors**
```
ERR error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:8080: connect: connection refused" cfRay=xxx-LAX originService=http://localhost:8080
```

**Additional context**
Sometimes we do need `h2mux` when UDP connection is poor or something, and it is a choice better than `http2` I think...

**Comment by nmldiegues** [comment]
Hello.

The root cause of your problem is that h2mux does not work with Tunnels configured in the Zero Trust dashboard.

There is no reason for anyone to use h2mux at this point. It is deprecated, not maintained, and we are just waiting for some time before we delete it in the codebase.

If you stay away from it, it should work!

**Comment by fernvenue** [comment]
I see, and thanks for your reply.
