### ISSUE TITLE
💡Logs formatted as newline delimited JSON 

### ISSUE THREAD

**Issue by eknudtson** [cloudflare/cloudflared#778]
**Describe the feature you'd like**
In order to automatically parse cloudflared logs in services like Datadog, I'd like to be able to choose line delimited JSON as the cloudflared log output format.

This also allows piping cloudflared output into utilities like jq to filter logs.

Thanks!

**Comment by sudarshan-reddy** [comment]
I'd ask for you to give us a more detailed requirement in the template provided to better look into this. Thanks!
