### ISSUE TITLE
🐛 Can't update with `cloudflared update` with .deb install method 

### ISSUE THREAD

**Issue by olliepop777** [cloudflare/cloudflared#779]
**Describe the bug**
I installed via the command `wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb` and whenever I run `cloudflared update` it errors out and says "cloudflared was installed by a package manager". I thought if I downloaded the .deb and installed manually I should be able to use cloudflared-update.service to update or run the update command directly? That I shouldn't be using my package manager to install/update? But how come I get that error then? 

**To Reproduce**
1. Run either `sudo systemctl start cloudflared-update.service` or `cloudflared update`

**Expected behavior**
cloudflared should update

**Environment and versions**
 - OS: Debian Linux
 - Architecture: AMD
 - Version: 11 Bullseye

**Comment by sudarshan-reddy** [comment]
When you use `dpkg -i` you are using the package manager. You can confirm by running ls -la /usr/local/etc/cloudflared/ and looking for .installedFromPackageManager in the output.
