### ISSUE TITLE
🐛 Docker images not generated for the newest cloudflared release

### ISSUE THREAD

**Issue by sudarshan-reddy** [cloudflare/cloudflared#783]
**Describe the bug**
The newest cloudflared release does not have docker images. This is a known problem and should be fixed soon. It's a resultant of working on a fix to make sure the version tagged docker images dont need arm/amd suffixes. 

**Environment and versions**
 Docker

**Comment by alexdelprete** [comment]
Hi Sudarshan,

are there any plans to make the images available also on ghcr.io?

**Comment by sudarshan-reddy** [comment]
Hey @alexdelprete , 

Thats not really in our roadmap AFAIK.

**Comment by sudarshan-reddy** [comment]
This is now fixed.
