### ISSUE TITLE
Connections to Argo on 443 instead of 7844

### ISSUE THREAD

**Issue by seamooose** [cloudflare/cloudflared#79]
In a situation where you are temporarily exposing a web service from an insecure location (e.g. doing some dev work on a local docker instance while connected to a guest wifi & wanting to demonstrate to a colleague) it would be nice if we could alter the port from 7844 to something more standard like 443.

Sometimes outbound connections on 7844 may not always be possible. That being said, this may be opening a can of worms. There may be a technical reason why this isn't possible, but it would be nice to explore the idea.

**Comment by sssilver** [comment]
Hi @seamooose,

Thanks for the request!

There are some operational and engineering hurdles to making this happen, and at this time this feature isn't on the roadmap for us.
