### ISSUE TITLE
macOS service failing to start with insufficient permisions

### ISSUE THREAD

**Issue by matthewburnett** [cloudflare/cloudflared#8]
https://community.cloudflare.com/t/macos-dns-over-https-installation-error/15241

Even with using `sudo cloudflared service install`, it still fails to launch because of permissions.

**Comment by selfagency** [comment]
had the same issue

```
time="2018-04-09T12:40:52-04:00" level=info msg="Applied configuration from /usr/local/etc/cloudflared/config.yaml"
time="2018-04-09T12:40:52-04:00" level=info msg="Adding DNS upstream" url="https://1.1.1.1/dns-query"
time="2018-04-09T12:40:52-04:00" level=info msg="Adding DNS upstream" url="https://1.0.0.1/dns-query"
time="2018-04-09T12:40:52-04:00" level=info msg="Starting DNS over HTTPS proxy server" addr="dns://localhost:53"
time="2018-04-09T12:40:52-04:00" level=fatal msg="Cannot start the DNS over HTTPS proxy server" error="failed to create a UDP listener: listen udp 127.0.0.1:53: bind: permission denied"
```

ddiller's solution in the ticket referenced above about moving the agent to the launchdaemon's folder worked for me. i recommend cloudflare makes that change in their service installer directly.

**Comment by vavrusa** [comment]
@selfagency thanks for reporting! This is fixed in the upcoming version, it should roll out later today.
