### ISSUE TITLE
F-Stack Support

### ISSUE THREAD

**Issue by victorstewart** [cloudflare/cloudflared#80]
I know this is a bit of pipe-dream to ask for, but nonetheless!

Been considering ditching the Linux network stack and basing my Websocket server on [F-Stack](https://github.com/F-Stack/f-stack) for a while. Even implemented it to play with.

But now I'm also considering using Argo and Argo Tunnel, instead of exposing my servers to the public internet anymore (for all the benefits of doing so).

But for now, I'd have to pick... unless... :)

**Comment by sssilver** [comment]
This isn't on our roadmap at the moment, but PRs are welcome!

**Comment by victorstewart** [comment]
i'll definitely circle back with a PR in near future!

**Comment by TownLake** [comment]
Thanks again for the note and idea; like we mentioned, this is not on our roadmap but we'd be happy to review ideas and PRs on it. Closing for now as we're coming up on the two year anniversary of the ticket.
