### ISSUE TITLE
GPG Key not signed when installing on RHEL 8 workstation

### ISSUE THREAD

**Issue by Bartman250** [cloudflare/cloudflared#800]
**Describe the bug**
Hello, I'm trying to install cloudflare warp client on Redhat 8 Workstation.
I have an issue installing the package if I try rpm or dnf

**To Reproduce**

I downloaded the latest package for RHEL 8 / Centos which is:

```
cloudflare_warp_2022_9_591_1_x86_64_98cffd08f8
```

I tried installing with rpm like this:

```
rpm -ivh cloudflare_warp_2022_9_591_1_x86_64_98cffd08f8.rpm
```

I get the error

```
error unpacking of archive failed on file /bin/warp-cli;635fd851: cpio Digest mismatch
```

I tried install with dnf like this:

```
dnf install cloudflare_warp_2022_9_591_1_x86_64_98cffd08f8.rpm
```

I get the error:

```
package cloudflare_warp_2022_9_591_1_x86_64_98cffd08f8.rpm is not signed
Error: GPG Check failed
```

Environment and versions
 - OS: Red Hat Enterprise Linux 8.6 (Ootpa)
 - Kernal: Linux 4.18.0-372.26.1.el8_6.x86_64
 - Architecture: Intel x86-64

Hope you can help - thankyou :)

**Comment by joliveirinha** [comment]
Hi @Bartman250 

This is cloudflare warp client which is different from cloudlfared. It actually uses a different repo. (https://pkg.cloudflareclient.com/install)

If you still have this issue, I suggest you open a support ticket so that the right team addresses it.

**Comment by schultetwin1** [comment]
Hi @Bartman250,

If you are a free user of WARP please post this issue on our forums: https://community.cloudflare.com/
If you are a Zero Trust customer please go through Cloudflare Support to get this addressed.

For a quick answer:
I believe you maybe running into the issue that you are not install cloudflare-warp from our package repository. The packages available for download are not signed (https://pkg.cloudflareclient.com/uploads/cloudflare_warp_2022_9_591_1_x86_64_98cffd08f8.rpm). But, if you use yum/dnf to install the cloudflare-warp package (as described here: https://pkg.cloudflareclient.com/install) those packages are signed.
