### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by antiger557** [cloudflare/cloudflared#804]
**Describe the bug**
Installer hangs at black CMD window.  No services running or tasks in task manager. 

**To Reproduce**
1. Run Cloudflared-windows-amd64.exe downloaded from (https://developers.cloudflare.com:8443/cloudflare-one/connections/connect-apps/use_cases/smb/#3-connect-as-a-user)
2. Observe black screen of CMD.

**Expected behavior**
Anticipated installation of cloudflared for persistent access.

**Environment and versions**
 - OS: Win 10 21h2
 - Architecture: AMD

**Additional context**

**Comment by sudarshan-reddy** [comment]
Check out https://github.com/cloudflare/cloudflared/issues/776#issuecomment-1272586600

I’ll close this issue since we are tracking it there.
