### ISSUE TITLE
Windows build not generated for cloudflared Release 2022.11.0

### ISSUE THREAD

**Issue by incapdns** [cloudflare/cloudflared#816]
I don't know the correct channel to notify that the download link is broken:

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/

This link above redirects to https://github.com/cloudflare/cloudflared/releases/download/2022.11.0/cloudflared-windows-amd64.exe, which in turn is a link that does not exist, leaving only the user's option compile from source.

**Comment by sudarshan-reddy** [comment]
> leaving only the user's option compile from source.

You can temporarily download the exes from our release page. It appears that the newest release does not have the windows binaries. We are working on this.

**Comment by sudarshan-reddy** [comment]
This is fixed now.
