### ISSUE TITLE
No such host on raspberry pi

### ISSUE THREAD

**Issue by zjustan** [cloudflare/cloudflared#818]
i have cloudflared installed on my raspberry pi. but it fails to talk to the cloudflare servers.

for example when i execute 
`cloudflared tunnel list`

this is what i get in return
`
REST request failed: Get "https://api.cloudflare.com/client/v4/accounts/6ff6a9b213e57ecc7c3df2b61144b5a5/cfd_tunnel?is_deleted=false": dial tcp: lookup api.cloudflare.com on 192.168.2.254:53: no such host`

sometimes i do get an answer and then i see the tunnels i have created. but it constantly fails to connect.

**Comment by sudarshan-reddy** [comment]
This seems like your raspberry pi just having connectivity problems. Do you notice connectivity problems in general when reaching for things from your rpi?

**Comment by zjustan** [comment]
nope, it just seems to be in cloudflare, when i ping api.cloudflare.com it just works fine
