### ISSUE TITLE
Error in macOS with command 'sudo cloudflared update'

### ISSUE THREAD

**Issue by GianPaoloFontani** [cloudflare/cloudflared#829]
error="Error: getChecksum: failed to find checksum for name"
failed to update cloudflared: Error: getChecksum: failed to find checksum for name

**Comment by b0gdanw** [comment]
Last working release for macOS is cloudflared version 2022.10.3.
On 2022.11.0 and 2022.11.1, cloudflared-darwin-amd64.tgz has size 45 Bytes

**Comment by b0gdanw** [comment]
No problem in building cloudflared version 2022.11.1 from source on macOS 11.7.1 (20G918) with go1.19.3.darwin-amd64.

**Comment by sudarshan-reddy** [comment]
This should be fixed now in the latest release.
