### ISSUE TITLE
Ability to choose Origin Cert domain when setting up

### ISSUE THREAD

**Issue by patryk** [cloudflare/cloudflared#83]
When running `cloudflared login`, the app creates Origin Cert:
`*.example.com, example.com`, but I want to just be able to set up a tunnel on a very specific hostname, e.g. `just.my.hostname.example.com`

Currently, one needs to do it manually by following the docs: https://developers.cloudflare.com/argo-tunnel/reference/tiered-subdomains/

But it would be great to do it directly during setup, e.g.
`cloudflared login --cert just.my.hostname.example.com,*.other.name.example.com`

**Comment by sssilver** [comment]
This is definitely a nice to have feature. This change would involve more than just cloudflared. We may revisit the way we do auth in Argo Tunnel at some point in the future.

**Comment by patryk** [comment]
I believe we should keep this issue open, even if it cannot be actioned right now.

**Comment by judge2020** [comment]
I second this. Being able to specify the hostname would help with auditing and managing Argo tunnel certificates in the CF dashboard.
