### ISSUE TITLE
🐛 cloudflared-darwin-amd64.tgz of the version 2022.11.1 is empty

### ISSUE THREAD

**Issue by suzuki-shunsuke** [cloudflare/cloudflared#831]
https://github.com/cloudflare/cloudflared/releases/download/2022.11.1/cloudflared-darwin-amd64.tgz is empty.

```console
$ tar -tf cloudflared-darwin-amd64.tgz
```

https://github.com/cloudflare/cloudflared/releases/download/2022.11.0/cloudflared-darwin-amd64.tgz is empty too.

On the other hand, https://github.com/cloudflare/cloudflared/releases/download/2022.10.3/cloudflared-darwin-amd64.tgz isn't empty.

```console
$ tar -tf cloudflared-darwin-amd64.tgz
cloudflared
```

**Comment by sudarshan-reddy** [comment]
Should be fixed in the latest release.
