### ISSUE TITLE
🐛Failed to list tunnels: code: 10000, reason: Authentication error

### ISSUE THREAD

**Issue by trulyliu** [cloudflare/cloudflared#832]
**Describe the bug**
🐛Failed to list tunnels: code: 10000, reason: Authentication error

**To Reproduce**
1. Configure ''
2. Run 'cloudflared --origincert /etc/cloudflared/mydomain.com.pem tunnel list'
3. See error
Failed to list tunnels: code: 10000, reason: Authentication error

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 
5. cloudflared config: 

**Expected behavior**
Tunnels can be listed

**Environment and versions**
 - OS: [ubuntu linux 22.04]
 - Architecture: [AMD64]
 - Version: [2022.11.0]

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**
Cloudflared version 2022.10.03 works well.

**Comment by trulyliu** [comment]
The certificate was created last year. 
If I use ./cloudflared tunnel list with new created origin certificates,  the command works.

The old origin certificate works well with cloudflared version <= 2022.10.03

**Comment by chase-replicated** [comment]
@trulyliu What format are your origin certs in? I think I'm hitting this same issue, so I went to the affected zone > SSL/TLS > Generated a new cert, used the origin cert .pem file in the tunnels list command but now I'm getting `Error decoding origin cert: Missing token in the certificate` , so I think my cert is malformed in some way but I'm having trouble finding any documentation on what format it should be in.

**Comment by trulyliu** [comment]
@chase-replicated  
The old origin certificate works well with cloudflared version <= 2022.10.03.
So I don't think it is malformed.

**Comment by trulyliu** [comment]
@chase-replicated the origin cert was generated by command:
cloudflared tunnel login

**Comment by trulyliu** [comment]
@chase-replicated the origin cert was generated by command:
cloudflared tunnel login

**Comment by sudarshan-reddy** [comment]
This just seems like you are not using the right cert. Have you tried using our dashboard to do this instead: https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/?

**Comment by trulyliu** [comment]
My certificate was created by 'cloudflared tunnel login',  Has this method been deprecated?
And the certificate works well with cloudflared version <= 2022.10.03.
