### ISSUE TITLE
🐛Error decoding origin cert: Missing token in the certificate

### ISSUE THREAD

**Issue by chase-replicated** [cloudflare/cloudflared#834]
**Describe the bug**
When trying to run `cloudflared -origincert=cert.pem tunnel route dns -f $TUNNEL $host` we're getting `Error: failed to fetch Argo Tunnel: Authentication error (10000)` . I found this issue https://github.com/cloudflare/cloudflared/issues/832 and thought maybe generating a new cert would help, so I went to the affected zone > SSL/TLS > Generated a new cert, used the origin cert .pem file in the tunnels list command but now I'm getting `Error decoding origin cert: Missing token in the certificate` , so I think my cert is malformed in some way but I'm having trouble finding any documentation on what format it should be in.

**To Reproduce**
1. Run `cloudflared -origincert=cert.pem tunnel route dns -f $TUNNEL $host` using an origin cert generated from zone > SSL/TLS 
2. get output `Error decoding origin cert: Missing token in the certificate` 

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 6129bfbd-6e0c-4049-8e2e-6e0bb0afe546
5. cloudflared config:     
```
tunnel: kgrid-api-stg
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
- hostname: kgrid.staging.replicated.systems
  service: http://kgrid-api.krid-system.svc.cluster.local:3000

# This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
# - service: http_status:404
- service: http://kgrid-api.krid-system.svc.cluster.local:3000
```

**Expected behavior**
Tunnel command should be authenticated when provided a valid origin cert

**Environment and versions**
 - Github Actions 
 - cloudflared version: 2022.10.0-amd64

**Logs and errors**
`Error: failed to fetch Argo Tunnel: Authentication error (10000)`
`Error decoding origin cert: Missing token in the certificate`

**Additional context**

**Comment by chase-replicated** [comment]
Was able to get this working using `cloudflared tunnel login` to generate the origin cert. Wondering if there's a way to do that programmatically, and/or a way to generate that in a user-agnostic way so that if my account is removed, these tunnels will continue working?

**Comment by sudarshan-reddy** [comment]
You will always have to have a tunnel associated with an account. 

You could also now use tokens that get generated if you create tunnels via the dash and do something like 

```
cloudflared tunnel run --token <token from dash.teams.cloudflare.com>
```

**Comment by joelmukuthu** [comment]
I also just ran into this while upgrading from `v2022.10.3` to `v2022.11.1`.  

@sudarshan-reddy, how do you handle breaking changes in release/versioning scheme? Is it to be expected that breaking changes be included in the month release? And to @chase-replicated's question, how does one create a tunnel via the command line client? I couldn't find it in the docs.
