### ISSUE TITLE
Connect to ssh over cloudflare tunnel without cloudflare access

### ISSUE THREAD

**Issue by yukebrillianth** [cloudflare/cloudflared#835]
![image](https://user-images.githubusercontent.com/61053094/205428080-ca6e19c0-dd54-4b14-a6e1-aeaaf0310d6f.png)

How to connect to ssh over cloudflare tunnel without running `cloudflared access ssh --hostname node1.morph.my.id --url localhost:2034` because I will integrate it with moss.sh

**Comment by morpig** [comment]
use cloudflare spectrum (dedicated ip) or cloudflare warp with private networking.

**Comment by sudarshan-reddy** [comment]
Like @morpig  says, https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel is probably an option you can explore.
