### ISSUE TITLE
🐛 Tunnel cannot connect on IPv6 only machine when installed with "Install and run a connector" command from Zero Trust dashboard

### ISSUE THREAD

**Issue by Rick-McClatchie** [cloudflare/cloudflared#842]
**Describe the bug**
When trying to install cloudflared with the command and token given on the Zero Trust dashboard (When creating and managing the tunnel via the web interface), on a IPv6 only server, the service tries to connect to IPv4 addresses. From what I've tried so far, it's impossible to specify somehow (similar to the  --edge-ip-version flag in the tunnel command) to use IPv6, or ideally detects that it's a IPv6 only server.

**To Reproduce**
1. Go to Zero Trust Dashboard (https://one.dash.cloudflare.com/)
2. Navigate to "Access" --> "Tunnels". Click "Create Tunnel". Give some name. Click "Save Tunnel". In "Choose your environment" select Debian. Copy command displayed underneath "If you don’t have cloudflared installed on your machine:".
3. Go to IPv6 only Debian machine. Paste command.
4. Now the command will hang indefinitely after "2022-12-08T11:09:18Z INF Using Systemd" is displayed in CLI.
5. Cancel hanging command with STRG + C
6. Run "systemctl status cloudflared"
7. See Error "Dec 08 11:20:09 ****** cloudflared[4582]: 2022-12-08T11:20:09Z ERR Serve tunnel error error="DialContext error: dial tcp 198.41.200.63:7844: connect: network is unreachable" connIndex=0 ip=198.41.2"

**Expected behavior**
cloudflared automatically detects the server does not have IPv4 connectivity and connects via IPv6. Similar to the "cloudflared tunnel  --edge-ip-version" command.

**Environment and versions**
 - OS: Tested with Debian 11 and Ubuntu 22.04
 - Architecture: x86_64
 - Version: 2022.11.1

**Logs and errors**
root@***redacted-hostname***:~# curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
> 
> sudo dpkg -i cloudflared.deb && 
> 
> sudo cloudflared service install ***redacted-connector-token***
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16.2M  100 16.2M    0     0  24.0M      0 --:--:-- --:--:-- --:--:-- 24.0M
Selecting previously unselected package cloudflared.
(Reading database ... 30573 files and directories currently installed.)
Preparing to unpack cloudflared.deb ...
Unpacking cloudflared (2022.11.1) ...
Setting up cloudflared (2022.11.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
2022-12-08T11:25:18Z INF Using Systemd
^C
root@***redacted-hostname***:~# systemctl status cloudflared
● cloudflared.service - cloudflared
   Loaded: loaded (/etc/systemd/system/cloudflared.service; enabled; vendor preset: enabled)
   Active: activating (start) since Thu 2022-12-08 11:25:19 UTC; 6s ago
 Main PID: 5210 (cloudflared)
    Tasks: 7 (limit: 2300)
   CGroup: /system.slice/cloudflared.service
           └─5210 /usr/bin/cloudflared --no-autoupdate tunnel run --token ***redacted-token***

Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:19Z INF Starting metrics server on 127.0.0.1:41293/metrics
Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022/12/08 11:25:19 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemen
Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:19Z ERR Failed to create new quic connection error="failed to dial to edge with quic: INTERNAL_ERROR: write udp [::]:45317->198.41.200.73:
Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:19Z INF Retrying connection in up to 2s connIndex=0 ip=198.41.200.73
Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:19Z ERR Failed to create new quic connection error="failed to dial to edge with quic: INTERNAL_ERROR: write udp [::]:45317->198.41.200.73:
Dec 08 11:25:19 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:19Z INF Retrying connection in up to 4s connIndex=0 ip=198.41.200.73
Dec 08 11:25:20 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:20Z ERR Failed to create new quic connection error="failed to dial to edge with quic: INTERNAL_ERROR: write udp [::]:45317->198.41.200.73:
Dec 08 11:25:20 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:20Z INF Retrying connection in up to 8s connIndex=0 ip=198.41.200.73
Dec 08 11:25:23 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:23Z ERR Failed to create new quic connection error="failed to dial to edge with quic: INTERNAL_ERROR: write udp [::]:45317->198.41.200.73:
Dec 08 11:25:23 ***redacted-hostname*** cloudflared[5210]: 2022-12-08T11:25:23Z INF Retrying connection in up to 16s connIndex=0 ip=198.41.200.73
root@***redacted-hostname***:~# 
root@***redacted-hostname***:~#  cloudflared --version
cloudflared version 2022.11.1 (built 2022-11-30-1048 UTC)

**Additional context**
In order to be able to download cloudflared from github I had to add the following to /etc/hosts (Because Github is still IPv4 only...):
2a01:4f8:c010:d56::2 github.com
2a01:4f8:c010:d56::3 api.github.com
2a01:4f8:c010:d56::4 codeload.github.com
2a01:4f8:c010:d56::5 objects.githubusercontent.com

**Comment by wasabipesto** [comment]
I ran into the same problem, I agree it should fail-forward to IPv6 automatically. In the meantime you can edit the service with `sudo systemctl edit --full cloudflared.service` and edit the ExecStart to include --edge-ip-version 6. This will take effect the nest time the service starts.

**Comment by Rick-McClatchie** [comment]
> I ran into the same problem, I agree it should fail-forward to IPv6 automatically. In the meantime you can edit the service with `sudo systemctl edit --full cloudflared.service` and edit the ExecStart to include --edge-ip-version 6. This will take effect the nest time the service starts.

That worked perfectly! Thanks so much for the workaround!

**Comment by DevinCarr** [comment]
For now, the only way to connect cloudflared via IPv6 to Cloudflare's Network is to use the `--edge-ip-version 6` or `--edge-ip-version auto` (which will pick between IPv4 and IPv6 on dual stack machine). Soon, we will look to enable `--edge-ip-version auto` as the default and this change will not be required for IPv6-only networks. But for now, we want to roll this out carefully as the edge connection is a vital piece of code for cloudflared and the flag is required.

**Comment by vincentcox** [comment]
2024, still same issue. And still same fix

**Comment by IrwenXYZ** [comment]
2025, still same issue, still the same fix lol.

**Comment by vincentcox** [comment]
> 2025, still same issue, still the same fix lol.

Lol 😂 hopefully we don't hit 2026 with this issue

**Comment by ehtishamsajjad** [comment]
2026, still same issue, still the same fix 🫠
