### ISSUE TITLE
Log-Info for missing configuration path when using --token flag

### ISSUE THREAD

**Issue by brenner-tobias** [cloudflare/cloudflared#845]
**Describe the bug**
When running Cloudflared with a managed tunnel from the dashboard by setting the flag `--token="${tunnel_token}"`, there is a info log that the config location could not be found:

> INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]

**To Reproduce**
1. Configure a tunnel in the Cloudflare Zero Trust Dashboard
2. Run the tunnel with the --token flag

**Expected behavior**
No log message, since no config file is needed for running with the token flag

**Comment by sudarshan-reddy** [comment]
This is because for a remotely managed tunnel (thats how you'd get a token flag) a configuration is strictly not necessary. You can still provide one with the --config flag if you want to though. You don't see the message because in this scenario, a config file is not expected.

**Comment by sudarshan-reddy** [comment]
Oh sorry... I misread it. I thought you said you weren't getting the info.

**Comment by sudarshan-reddy** [comment]
What version of cloudflared are you using?

**Comment by brenner-tobias** [comment]
Thanks for re-opening @sudarshan-reddy. I am using 2022.11.1, aarch64 / raspberrypi4-64

**Comment by sudarshan-reddy** [comment]
Should be fine from the next release: https://github.com/cloudflare/cloudflared/commit/7dee179652d91ce944eccc2c3cf0a1938efab6b3

Thanks for the report @brenner-tobias
