### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by kstruck** [cloudflare/cloudflared#851]
**Describe the bug**
Trying to install Cloudfalred on Windows 11 Pro. The installer starts and I get to the "Please wait while Windows Configures Cloudflared - Gathering requested information" and then the installer just quits. 

When I run the install

**To Reproduce**
No error, msi just quits.

Cannot find anything pertaining to Cloudflared in my event viewer.

**Expected behavior**
Installer to finish install process

**Environment and versions**
 - OS: Windows 11 Pro
 - Version: 10.0.22623 Build 22623

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by sudarshan-reddy** [comment]
What happens if you run the command `cloudflared version` on your powershell?

**Comment by sudarshan-reddy** [comment]
This means your cloudflared is installed and operational. We are aware that the MSIs are less than ideal with installation messages and have a few issues on gh already that we are tracking this on.

**Comment by kstruck** [comment]
Thank you for your response and explanation.
