### ISSUE TITLE
🐛 2022.12.0 - missing Windows builds

### ISSUE THREAD

**Issue by KianNH** [cloudflare/cloudflared#852]
The `2022.12.0` release appears to be missing Windows builds.

https://community.cloudflare.com/t/missing-cloudflared-windows-executable-file/445569

https://github.com/cloudflare/cloudflared/releases/tag/2022.12.0

**Comment by jsnel** [comment]
Can confirm, the download link from the documentation page is therefor also broken:
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation
links to
`https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe` -> `404`

**Comment by sudarshan-reddy** [comment]
Fixed by the new release: 2022.12.1.
