### ISSUE TITLE
🐛Proxy dns not working on the new version 2022.12.0

### ISSUE THREAD

**Issue by ionutz89** [cloudflare/cloudflared#853]
Hello,

I updated cloudflared to the latest version `2022.12.0`, and I am getting those errors:

```
Dec 20 10:46:15 pihole systemd[1]: Starting Cloudflare Tunnel...
Dec 20 10:46:15 pihole cloudflared[5671]: You did not specify any valid additional argument to the cloudflared tunnel command.
Dec 20 10:46:15 pihole cloudflared[5671]: If you are trying to run a Quick Tunnel then you need to explicitly pass the --url flag.
Dec 20 10:46:15 pihole cloudflared[5671]: Eg. cloudflared tunnel --url localhost:8080/.
Dec 20 10:46:15 pihole cloudflared[5671]: Please note that Quick Tunnels are meant to be ephemeral and should only be used for testing purposes.
Dec 20 10:46:15 pihole cloudflared[5671]: For production usage, we recommend creating Named Tunnels. (https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/)
Dec 20 10:46:15 pihole systemd[1]: cloudflared.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 10:46:15 pihole systemd[1]: cloudflared.service: Failed with result 'exit-code'.
Dec 20 10:46:15 pihole systemd[1]: Failed to start Cloudflare Tunnel.
```

I am using the config for cloudflared:

```
❯ cat /etc/cloudflared/config.yml
logfile: /var/log/cloudflared.log
proxy-dns: true
proxy-dns-port: 54
proxy-dns-address: 0.0.0.0
proxy-dns-upstream:
  - https://8.8.8.8/dns-query
  - https://1.1.1.2/dns-query
```

I saw this [change](https://github.com/cloudflare/cloudflared/commit/e5172421940362720083d0c723ea924bb2342351) that gave me this error above, but I am not sure how it is related to proxy DNS.

Can someone clarify what I should do? Do I have to do something new in the config file? I checked the documentation, and I did not see anything that could break my environment. 

I am using cloudflared in RPi 3 B+ using OS: Raspbian GNU/Linux 11 (bullseye)

At the moment, I changed the cloudflared version to `2022.11.0`, and it works fine.

**Comment by sudarshan-reddy** [comment]
Thanks for the report. proxy-dns is indeed broken in the new release. We are looking into this.

**Comment by sudarshan-reddy** [comment]
With the latest version , you can still run proxy-dns by running `cloudflared --config <path-to-your-proxy-dns-config.yaml>`.

**Comment by sudarshan-reddy** [comment]
The newest release should fix this.
