### ISSUE TITLE
🐛ERR Failed to serve quic connection error="Application error 0x0" 

### ISSUE THREAD

**Issue by hnauto** [cloudflare/cloudflared#856]
**Describe the bug**

**To Reproduce**
1. Configure '...'
2. Run '....'
3. See error

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 
5. cloudflared config: 

**Expected behavior**

**Environment and versions**
 - OS: [e.g. MacOS]
 - Architecture: [e.g. AMD, ARM]
 - Version: [e.g. 2022.02.0]

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

**Comment by DevinCarr** [comment]
Please provide additional details using the template that is provided. Once that is filled out, we can look to assist you further with this issue.

**Comment by sh471** [comment]
??
