### ISSUE TITLE
🐛 Cannot Install 2022.12.1 cloudflared-windows-amd64.msi (or exe) on W11 Pro 22h2

### ISSUE THREAD

**Issue by tempusthales** [cloudflare/cloudflared#865]
After I download either cloudflared-windows-amd64.exe or cloudflared-windows-amd64.msi and I try to install either, I get errors and I cannot call cloudflared.exe service install <token> getting the error: 

'cloudflared.exe' is not recognized as an internal or external command,
operable program or batch file.

**To Reproduce**
1. Download https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi (or .exe)
2. Run: msiexec.exe /I cloudflared-windows-amd64.msi /norestart /L*V "c:\tmp\msi.log"  
3. See error

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : n/a
5. cloudflared config: n/a

**Expected behavior**
I expect it to install so I can run the cloudflared.exe
[msi.log](https://github.com/cloudflare/cloudflared/files/10330250/msi.log)
 service install <token>

**Environment and versions**
 - OS: Windows 11 Pro 22H2
 - Architecture: AMD64
 - Version: 2022.12.1

**Logs and errors**
see attached log

**Comment by sudarshan-reddy** [comment]
What happens when you type “cloudflared” on powershell?

**Comment by HardChalice** [comment]
Bumping this as I'm having a similar issue. 

Running that msiexec command results in the following:
![image](https://github.com/cloudflare/cloudflared/assets/80853862/115c06f5-d0dd-4393-90f1-3eb61d6f8ad1)

Running cloudflared on powershell comes back with an error because cloudflared isn't recognized.
