### ISSUE TITLE
SRV Record Error on Raspberry Pi in docker

### ISSUE THREAD

**Issue by IwanIDev** [cloudflare/cloudflared#867]
I'm getting a rather odd error when using cloudflared on my raspberry pi in docker. I've posted the error below. I've seen some similar errors on the internet but nothing that has been suggested has worked. It is probably some silly error I made in my configuration, but I can't seem to find anything wrong.

```
tunnel-1  | 2023-01-08T17:09:44Z INF Starting tunnel tunnelID=
tunnel-1  | 2023-01-08T17:09:44Z INF Version 2022.12.1
tunnel-1  | 2023-01-08T17:09:44Z INF GOOS: linux, GOVersion: go1.19.4, GoArch: arm
tunnel-1  | 2023-01-08T17:09:44Z INF Settings: map[no-autoupdate:true]
tunnel-1  | 2023-01-08T17:09:44Z INF Environmental variables map[TUNNEL_ORIGIN_CERT:/etc/cloudflared/cert.pem TUNNEL_TOKEN:*****]
tunnel-1  | 2023-01-08T17:09:44Z INF Generated Connector ID: 
tunnel-1  | 2023-01-08T17:09:44Z INF Will be fetching remotely managed configuration from Cloudflare API. Defaulting to protocol: quic
tunnel-1  | 2023-01-08T17:09:44Z INF Initial protocol quic
tunnel-1  | 2023-01-08T17:09:44Z INF ICMP proxy will use 172.19.0.2 as source for IPv4
tunnel-1  | 2023-01-08T17:09:44Z INF ICMP proxy will use :: as source for IPv6
tunnel-1  | 2023-01-08T17:09:45Z INF Starting metrics server on 127.0.0.1:44903/metrics
tunnel-1  | 2023-01-08T17:09:45Z INF Tunnel server stopped
tunnel-1  | 2023-01-08T17:09:45Z ERR Initiating shutdown error="Couldn't resolve SRV record &{region1.v2.argotunnel.com. 7844 1 1}: lookup region1.v2.argotunnel.com. on 127.0.0.11:53: no such host"
tunnel-1  | 2023-01-08T17:09:45Z INF Metrics server stopped
tunnel-1  | Couldn't resolve SRV record &{region1.v2.argotunnel.com. 7844 1 1}: lookup region1.v2.argotunnel.com. on 127.0.0.11:53: no such host
```

Any help would be much appreciated.

**Comment by DevinCarr** [comment]
When `cloudflared` starts up, it makes a SRV request to `region1.v2.argotunnel.com` and `region2.v2.argotunnel.com` to get the IP addresses to reach the Cloudflare global network as described here: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/ports-and-ips/. You will need to make sure that your `cloudflared` can make a DNS request to retrieve these IPs.
From the error message: `...lookup region1.v2.argotunnel.com. on 127.0.0.11:53: no such host` it looks like your local DNS isn't setup properly, or `cloudflared` it isn't able to reach it for some reason. You should try and investigate that from within the docker container you are running `cloudflared`.

**Comment by sschoeppi** [comment]
Hello together, 
I have the same problem with the message : 
_Couldn't resolve SRV record &{region1.v2.argotunnel.com. 7844 1 1}: lookup region1.v2.argotunnel.com. on 127.0.0.11:53: no such host_
I believe I have a problem with my DNS configuration. Unfortunatelly I don't find correct examples.
As far as I can see there are two important  entries.

![Image](https://github.com/user-attachments/assets/a931899e-9da9-4f03-9d8c-4ccd86aa64ff)
Could someone check if this is correct in principle?
In addition: The tunnel worked in the past. 2 - 3 weeks ago I made an update "home assistant operation system" (I believe, not pritty sure) After that nothing worked anymore and I probably played around too much. :-) Cloudflared last version 5.2.9.
Hopefully for help.
Thx Stephan

**Comment by sschoeppi** [comment]
> Hallo zusammen, ich habe das gleiche Problem mit der Meldung: _SRV-Eintrag &{region1.v2.argotunnel.com. 7844 1 1} konnte nicht aufgelöst werden: Suche nach region1.v2.argotunnel.com. auf 127.0.0.11:53: kein solcher Host_ Ich glaube, ich habe ein Problem mit meiner DNS-Konfiguration. Leider finde ich keine korrekten Beispiele. Soweit ich sehen kann, gibt es zwei wichtige Einträge.
> 
> ![Image](https://github.com/user-attachments/assets/a931899e-9da9-4f03-9d8c-4ccd86aa64ff) Kann jemand mal nachschauen, ob das prinzipiell so ist? Außerdem: Der Tunnel hat früher auch funktioniert. Vor 2-3 Wochen habe ich ein Update "Home Assistant Betriebssystem" gemacht (glaube ich, bin mir nicht ganz sicher) Danach ging gar nichts mehr und ich habe wohl zu viel rumgespielt. :-) Cloudflared letzte Version 5.2.9. Hoffe auf Hilfe. Danke Stephan

problem is solved. I installed yesterday HA Core update 2025.2.2. After that I got connected.
