### ISSUE TITLE
Include Workerd APIs on Mozilla Compatibility Tables 📝

### ISSUE THREAD

**Issue by ntotten** [cloudflare/cloudflared#868]
**Available Documentation**
[Web Standards APIs](https://developers.cloudflare.com/workers/runtime-apis/web-standards/)

**Suggested Documentation**
Now that workerd is open source it seems that it would make sense to include it in the compatibility tables for Web APIs on [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Web/API). Deno is currently listed there so it seems natural that workerd would be as well.

**Additional context**
Example table
<img width="835" alt="image" src="https://user-images.githubusercontent.com/282782/211340577-f3d1e532-bf24-4d5e-8deb-193d15e3e116.png">

**Comment by sudarshan-reddy** [comment]
Did you intend to raise this in the workerd repo instead?
