### ISSUE TITLE
Can't access using smartphone

### ISSUE THREAD

**Issue by naoestu** [cloudflare/cloudflared#875]
**Describe the bug** / **To Reproduce**
Basically i'm using cloudflares zero trust tunnel to access my proxmox machines.
I can access them using a computer navigator, but if i try to access using my android phone, i can't.
It simple shows a white (empty) window.

**Expected behavior**
It was expected that i can access it in computer, smartphone, tablet webbrowsers.

**Environment and versions**
 - OS: Proxmox 7 (Debiian 11)
 - Architecture: Intel
 - Version: Latest updated version

**Comment by sudarshan-reddy** [comment]
That is not necessarily a problem with Cloudflare Tunnel. You should raise a support ticket for the zero trust client.
