### ISSUE TITLE
Cloudflared Server thinks I don't run the latest version :(

### ISSUE THREAD

**Issue by alx-xlx** [cloudflare/cloudflared#878]
I have the latest version of cloudflared 2023.1.0
I am also logged in and still can't access anything

Running this on ARM64 raspberrypi

![](https://i.imgur.com/OXRl81o.png)

**Comment by sudarshan-reddy** [comment]
Sorry for this. Can you try now?

**Comment by cFiori415** [comment]
i would like you people to realize that there are real world consequences
to your "experiments".  goodbye.

**Comment by alx-xlx** [comment]
I get this error
![](https://i.imgur.com/dfD3Aq2.png)

**Comment by obezuk** [comment]
Resolved in https://github.com/cloudflare/cloudflared/issues/880
