### ISSUE TITLE
💡restricted cloudflared for remotely managed tunnels

### ISSUE THREAD

**Issue by brucealthompson** [cloudflare/cloudflared#881]
Cloudflared currently allows display and management of remotely managed tunnels that are not hosted on the local machine. This includes the ability to delete remotely managed tunnels that are hosted on different machines.

I would like to have the ability to restrict remotely managed tunnels be managed only remotely, not locally. Is there a way to do with cloudflare tunnels?

**Comment by sudarshan-reddy** [comment]
> I would like to have the ability to restrict remotely managed tunnels be managed only remotely, not locally. Is there a way to do with cloudflare tunnels?

Hey @brucealthompson ! I don't entirely understand this question. Do you want to not be able to delete/revoke tunnels from the Dash?

**Comment by brucealthompson** [comment]
I want the ability to modify / delete tunnels ONLY from the dashboard and not from cloudflared. I thought that was the definition of a remotely managed tunnel. That seems to not be the case.

I found a work around to this issue. I have restricted the tokens I issue for the tunnels to be read only. Then cloudflared cannot modify tunnels with the restricted tunnels

**Comment by obezuk** [comment]
Simply deploy cloudflared using the token supplied from the dashboard. cloudflared can only manage tunnels if it has been authenticated and picks up a credential file from [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]. Delete these files and it will not be able to manage tunnels.
