### ISSUE TITLE
Bot Detection Breaks SSH Tunnels 🐛

### ISSUE THREAD

**Issue by sl33nyc** [cloudflare/cloudflared#885]
**Describe the bug**
[Description in Comment on Another Issue](https://github.com/cloudflare/cloudflared/issues/324#issuecomment-966038277) #324

I strongly suspect that Bot detection rules having higher rule precedence over Access rules is the culprit, so I filed this issue to request some sort of acknowledgement/documentation.  I've "done this to myself" twice because I clicked the shiny "Bot Fight Mode" toggle and had forgotten its consequences.  Luckily, I stumbled across #324 after a quick Google search and read to the end of #324's comments.

Nonetheless, enabling Bot Fight Mode breaking my SSH tunnel seems like a significant disconnect from an error saying "`websocket: bad handshake`".  Ideally, I'd like to be able to enable "Bot Fight Mode" because it's probably good to take advantage of Cloudflare's expertise in such matters.  I'm guessing that this is part of a known class of similar problems, so it'd be great to hear if the solution is a work in progress and either it will be fixed or some sort of "exception" rules can be configured.

Admittedly, I'm not on a paid plan, so if a paid tier includes the requisite automated workaround, then at least a warning somewhere would be helpful.

![cloudflare_rules_precedence](https://user-images.githubusercontent.com/207833/215269137-1f0ffae7-e05e-4f2e-b60a-d74cbabf43aa.png)

**To Reproduce**
1. Turn on "Bot Fight Mode".  (Wait a few seconds for rule propagation...)
1. Attempt to ssh into host configured per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/use_cases/ssh/#connect-to-ssh-server-with-cloudflared-access.
1. Observe `ERR failed to connect to origin error="websocket: bad handshake" originURL=...`

**Comment by obezuk** [comment]
Thanks for raising this to our attention. We're working towards improving Bot Fight Mode to offer greater granularity. This would allow you to exclude your SSH service and avoid this issue. Please subscribe to our blog for updates.

**Comment by Nikki1993** [comment]
Any update on the matter?
