### ISSUE TITLE
🐛Issues with POST requests for dns-proxy

### ISSUE THREAD

**Issue by Kia678** [cloudflare/cloudflared#892]
**Describe the bug**
error="failed to perform an HTTPS request: Post....

**Expected behavior**
perform an HTTPS request: Post....

**Environment and versions**
 - OS: [e.g. Debian11]
 - Architecture: [e.g. AMD64]
 - Version: cloudflared version 2023.2.1

**Logs and errors**
![image](https://user-images.githubusercontent.com/85081567/217651957-744bd49e-6605-40b1-9d7a-1000762957e8.png)

**Additional context**
None

**Comment by Kia678** [comment]
POST requests could be supported?

**Comment by obezuk** [comment]
Thanks for filing this request. It looks like the target DoH server is not compliant with [RFC8484](https://www.rfc-editor.org/rfc/rfc8484) compliant, which requires that POST requests are supported. You're welcome to file a PR if you'd like to see this supported short term.
