### ISSUE TITLE
🐛 CF Tunnel shuts down randomly 

### ISSUE THREAD

**Issue by showierdata9978** [cloudflare/cloudflared#897]
**Describe the bug**
With more then 1 tunnel on this specific machine (Personal, and a tunnel I don't manage)

Both tunnels shut down randomly. 

**To Reproduce**
1. Have 2 tunnels with multiple apps each 
2. Run for IDK how long
3. Tunnels disconnect, and don't reconnect 

If it's an issue with Cloudflare Tunnel:
4. Tunnel ID : 2 tunnels, one associated with https://http.meower.org/ and the other showierdata.tech
5. cloudflared config: 

**Expected behavior**
Cloudflared does not disconnect or cloudflared show automatically reconnect

**Environment and versions**
 - OS: Umbuntu 22.x.x
 - Architecture: ARM
 - Version: Unable to get (will check when I get home , however it is no less then 5 months outdated)

**Logs and errors**
Unable to get 

**Additional context**
On a RPI 400, connected with eathernet

**Comment by obezuk** [comment]
In order for us to investigate this further we will need logs from the cloudflared instance. Can you please submit a new ticket if this persists with logs and we'll be happy to take a look.

**Comment by gtang8** [comment]
![image](https://github.com/cloudflare/cloudflared/assets/74369627/5cc87c3a-e8ff-42e7-a529-a7afda99fa6c)
I have 3 Tunnels which was installed to Docker in my router, the status changes from Healthy to Down from time to time. I've tried to reinstall in Docker but unfortunately the status is Down in most of the time.
