### ISSUE TITLE
Request support for RAMIPS architecture

### ISSUE THREAD

**Issue by 676407926** [cloudflare/cloudflared#901]
MT7621AT RAMIPS

**Comment by masx200** [comment]
MediaTek MT7621 ver:1 eco:3 x 4

OpenWrt R23.2.14 @[XiaoWanSM](https://wwang.pw/)/ LuCI Master (git-23.040.60681-9fc2e34)

**Comment by DevinCarr** [comment]
I'm sorry, we will no be pursuing support for this architecture at this time. If we see enough interest in the future we can reassess this decision. In the meantime, if you are able to get support working for this architecture in a fork of the cloudflared repo, please feel free to share it here for others who are looking for this support!
