### ISSUE TITLE
Cloudflared service won't stop on Windows 2023.2.2

### ISSUE THREAD

**Issue by dgordoncal** [cloudflare/cloudflared#904]
We noticed starting with 2023.2.2 or higher, when run as a windows service, the service will not restart.  Cloudflared.exe must be killed using task manager to restart the service.

**Comment by obezuk** [comment]
There is not enough information to investigate this ticket. Can you try upgrading to the latest version of cloudflared, and file a new ticket if this issue persists including logs.
