### ISSUE TITLE
Cloudflared Stopped working on multiple servers🐛

### ISSUE THREAD

**Issue by megvadulthangya** [cloudflare/cloudflared#910]
Multiple Servers down when using config like this:
(this configs is the same till i dont know... a year and a half....)
(this config is when using the default 8080 port) 

tunnel: The tunnel UUID
credentials-file: /path/your-tunnels-credentials-file.json
warp-routing:
    enabled: true

Debian 11 AMD
cloudflared version 2023.3.0 (built 2023-03-02-0959 UTC)

Ubuntu 22.04 ARM
cloudflared version 2023.3.0 (built 2023-03-02-1001 UTC)

Outher configs/instances when  i set the ports is working ok... (Ingress rules)

**Comment by c0deright** [comment]
without logs it's a bit hard to guess your problem.

**Comment by megvadulthangya** [comment]
then tell me pls where to get the log?  
When i forwarded the webservers ports  8080 both working ...

**Comment by megvadulthangya** [comment]
Thats absolutley not a fix! Couse i using the 8080 ports with nginx webserver.... for example myhostname.com cloud.myhostname.com photoprism.myhostname.com 
AGAIN!
the older version(earlyer version) of cloudflared works fine with this config. For 1.5 -2 years....

**Comment by sudarshan-reddy** [comment]
You still can.  You will just have to set an ingress rule to proxy to 8080. 

> the older version(earlyer version) of cloudflared works fine with this config. For 1.5 -2 years....

We understand no config would have cloudflared default to 8080 before but it could be an undesirable side effect that most users dont intend to have. 

With this change you can still route to 8080 with a configuration addition whilst it remains locked unless needed.

**Comment by DevinCarr** [comment]
Yes, this is a correction to that existing behavior which was insecure. Users could have not been aware that cloudflared was routing to localhost:8080 by default if they accidentally didn't setup any ingress rules.

An easy way to address this is to simply add this part to your `config.yaml`:
```
ingress:
  - hostname: *
    service: http://localhost:8080
```

This will work for all of your hostnames exactly the way you had it before this change.

**Comment by megvadulthangya** [comment]
Thank you Devin...

When i tryed (Copy pasted what you wrote and removed this part:
warp-routing:
enabled: true)

 i get this error:

error parsing YAML in config file at /etc/cloudflared/1/config.yml: yaml: line 4: did not find expected alphabetic or numeric character
Mar 10 18:11:13 ampere systemd[1]: cloudflared.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit cloudflared.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 10 18:11:13 ampere systemd[1]: cloudflared.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit cloudflared.service has entered the 'failed' state with result 'exit-code'.
Mar 10 18:11:13 ampere systemd[1]: Failed to start cloudflared.
░░ Subject: A start job for unit cloudflared.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit cloudflared.service has finished with a failure.
░░
░░ The job identifier is 18069 and the job result is failed.
~

**Comment by DevinCarr** [comment]
Apologies, I forgot to quote the '*', I updated my comment to reflect that!

**Comment by megvadulthangya** [comment]
Both working BIG BIG BIG Thanks AgaiN!
