### ISSUE TITLE
🐛 Portainer frezees/slow to load with Cloudflare Tunnel

### ISSUE THREAD

**Issue by ToxicLand** [cloudflare/cloudflared#913]
**Describe the bug**
Tunnel of Portainer is slow to load

**To Reproduce**
1. Create a tunnel for Portainer (example service: https://portainer:9443)
2. Visit the public hostname
3. You will notice it's much slower to load than the non-proxied/tunneled variant
4. Tunnel ID : cc957d27-95ef-48f1-9b88-d1a89535cd8f
5. cloudflared config: command: tunnel run --token TOKEN

**Expected behavior**
Load as fast as the non-tunneled version

**Environment and versions**
 - OS: Debian 11, Docker 23
 - Architecture: amd64
 - Version: 2023.3.0

**Logs and errors**
There are no errors logged.

**Additional context**
Here are some images of the issue.
Without Tunnel:
![Képernyőkép 2023-03-09 010226](https://user-images.githubusercontent.com/33599104/224574375-ee7d26c6-0945-42e9-b384-c041d64b4773.png)

With Tunnel:
![Képernyőkép 2023-03-09 010233](https://user-images.githubusercontent.com/33599104/224574397-68089896-6c81-44b7-9d5e-9fb85cc4ad7a.png)

Without Tunnel:
![Képernyőkép 2023-03-09 010738](https://user-images.githubusercontent.com/33599104/224574417-b60f78a4-50e5-4f0d-91af-19a4ba754d40.png)

With Tunnel:
![Képernyőkép 2023-03-09 010751](https://user-images.githubusercontent.com/33599104/224574427-06a61320-c727-4eec-95a7-445caa31fd39.png)

**Comment by anthonydiiorio** [comment]
I've also noticed some increased latency at times on my services. It seems to fluxuate for me so maybe congestion related?

**Comment by sudarshan-reddy** [comment]
@ToxicLand , if you are having issues running your specific tunnel, I recommend opening a support ticket to get more detailed insight into it, including running traces on your requests.
