### ISSUE TITLE
metrics-server port

### ISSUE THREAD

**Issue by runningman84** [cloudflare/cloudflared#92]
I really like the integration of the metrics server. But in order to use it I would like to specify the corresponding port. Right now it looks to be running using a random port:
```
time="2019-05-03T19:14:31Z" level=info msg="Adding DNS upstream" url="https://1.1.1.1/.well-known/dns-query"
time="2019-05-03T19:14:31Z" level=info msg="Adding DNS upstream" url="https://1.0.0.1/.well-known/dns-query"
time="2019-05-03T19:14:31Z" level=info msg="Starting DNS over HTTPS proxy server" addr="dns://0.0.0.0:5054"
time="2019-05-03T19:14:31Z" level=info msg="Starting metrics server" addr="127.0.0.1:37605"
```

**Comment by adamchalmers** [comment]
Hi there! `cloudflared`'s CLI arguments let you specify what port the metrics server should listen to. 

`cloudflared tunnel --metrics localhost:8099` will start the metrics server on localhost:8099.
