### ISSUE TITLE
💡 Client certificate verify & pass through 

### ISSUE THREAD

**Issue by imZack** [cloudflare/cloudflared#924]
**Describe the feature you'd like**
Is there a method for importing a CA in order to authenticate clients using their certificates for mTLS? Once the certificate is verified, it can be injected into the header as X-CLIENT-CERT. This allows me to both trust the certificate and read it from the header. If automatic client certificate verification is not possible, I can still manually verify it by retrieving it from the header.

**Describe alternatives you've considered**

**Additional context**
With NGINX, I use http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_cert for this purpose.

**Comment by obezuk** [comment]
Thanks for your request, do you mean establishing mTLS between cloudflared and your origin server, and forwarding headers?

**Comment by imZack** [comment]
Not necessary. The mTLS connection can be terminated at cloudflare and verify...then pass the client cert via header.

**Comment by obezuk** [comment]
You can do this today by using Cloudflare Access with Cloudflare Tunnels. Cloudflare Access verifies and terminates the MTLS connection between the end-user and Cloudflare, then forwards a Cf-Access-Jwt-Assertion request header which you can decode to check the user/certificate details in your origin server. https://developers.cloudflare.com/cloudflare-one/identity/devices/access-integrations/mutual-tls-authentication/.

**Comment by imZack** [comment]
Looks like it belongs to the enterprise plan only. I'll find another way to do this for now. Thank you.
