### ISSUE TITLE
📝 Been trying to launch multiple tunnels into docker environment and attach them to different internal microservices

### ISSUE THREAD

**Issue by gospodinbodurov** [cloudflare/cloudflared#925]
**Available Documentation**
No documentation

**Suggested Documentation**
Please provide a guide how to setup multiple tunnels with loadbalancer into dockerized environments. Sample docker guide will suffice.

**Additional context**
We are using docker for 247 testing of our application and want to expose it to the Internet using multiple tunnels and Cloudflare's loadbalancer. We are experiencing problems with configuring the cloudflared docker image to point to the proper microservice. Please check and advise.

**Comment by obezuk** [comment]
We have existing documentation for using Tunnels with Load Balancing here: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/lb/.

At what point did you get stuck? Can you elaborate on what issue you're having configuring the docker image to point to a microservice?
