### ISSUE TITLE
Path and Traefik

### ISSUE THREAD

**Issue by RFlintstone** [cloudflare/cloudflared#928]
I've a few questions about cloudflared.

1) Does Cloudflared in combination with Cloudflare Tunnel replace any other ingress controller?

2) How would I use a path (``example.com/mypath``) in the ingress controller provided by cloudflared's kubernetes yaml? I'm only getting 502 or 404 errors (while the routes exist)

3) Is it recommended to use something like ~~traefik~~ kubernetes-ingress in combination with containerd and if so, how would I link those two?

**Comment by obezuk** [comment]
Hi @RFlintstone,

On points 1 and 3: You can use Cloudflare Tunnels as an alternative to Kubernetes ingress controllers by defining the ingress routes in the Zero Trust dashboard. Your public hostnames should point to your Kubernetes services. It's not necessary to layer additional ingress controller.

Regarding point two: Can you provide more context and examples about what you're doing here?

**Comment by RFlintstone** [comment]
> Hi @RFlintstone,
> 
> On points 1 and 3: You can use Cloudflare Tunnels as an alternative to Kubernetes ingress controllers by defining the ingress routes in the Zero Trust dashboard. Your public hostnames should point to your Kubernetes services. It's not necessary to layer additional ingress controller.
> 
> Regarding point two: Can you provide more context and examples about what you're doing here?

I'm basically want an option to use paths to access different services (so I don't need a subdomain for each)

So `example.com/serviceA` would serve another pod then `example.com/serviceB` or `example.com`.

**Comment by obezuk** [comment]
Tunnels can do path based routing with [ingress rules](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/).

The easiest way to do this is to specify the path parameter while managing your public hostnames in the dashboard, or you can do manage it by the config file and deploy it inside your Kubernetes cluster.

**Comment by RFlintstone** [comment]
> Tunnels can do path based routing with [ingress rules](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/).
> 
> The easiest way to do this is to specify the path parameter while managing your public hostnames in the dashboard, or you can do manage it by the config file and deploy it inside your Kubernetes cluster.

I found this post about Cloudflare's kubernetes pods earlier but the path argument doesn't work. It will default to the 404 page.
