### ISSUE TITLE
💡How to convert json to token?

### ISSUE THREAD

**Issue by fscarmen** [cloudflare/cloudflared#929]
**Describe the feature you'd like**
A clear and concise description of the feature. What problem does it solve for you?

I have fetched the json and made the dns record, can I convert it to token via command line? The url is 127.0.0.1:8080.

Now.
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/62703343/229669101-44979db6-3b9c-49d9-9fa9-f221c60b6800.png">
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/62703343/229669253-7cf0e030-27e7-46cc-96ed-6a0561c3cf5a.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/62703343/229669753-ce4cda33-502c-40c4-956c-5cbed64c4d28.png">
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/62703343/229669924-e2797ea2-fe5b-4334-a928-8ecff48c6d99.png">

After.

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/62703343/229670583-af2da394-4877-4026-843b-92f8e8b5aa69.png">
<img width="1660" alt="image" src="https://user-images.githubusercontent.com/62703343/229670671-b9f7cd17-7639-4788-9f63-247e06292d78.png">

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?

**Additional context**

**Comment by obezuk** [comment]
It's not clear to me exactly what problem this would help solve? How would obtaining the token via the command line be helpful here?

In the meantime,  you can always fetch the token via the API: https://developers.cloudflare.com/api/operations/cloudflare-tunnel-get-a-cloudflare-tunnel-token

**Comment by fscarmen** [comment]
I mean, in the past I want to create token, need to sign in the official website of Cloudflare-->Create a tunnel-->Public hostnames with the Service Type and URL
![image](https://user-images.githubusercontent.com/62703343/229911994-b8635453-7102-45b3-b9d1-bebdc3621137.png)

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/62703343/229911966-d2697341-cf08-4b90-be18-e26f72c5652b.png">

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/62703343/229912092-f339d3d4-60d5-4935-8f15-0b6a0c07e351.png">

Can i finish that job with the Cloudflared in linux ?

**Comment by obezuk** [comment]
Generating collecting the remote managed token via cloudflared is not supported at this time. We'll consider this and thank you for your request. For now, I recommend generating a credentials file as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/.

**Comment by obezuk** [comment]
Generating collecting the remote managed token via cloudflared is not supported at this time. We'll consider this and thank you for your request. For now, I recommend generating a credentials file as per https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/.

**Comment by MarSoft** [comment]
Token and JSON actually contain the same information, just in slightly different formats.

### How to convert token to JSON
1. Decode token from base64. It will become a JSON data with one-letter keys.
2. Replace keys with longer versions: `a` -> `AccountTag`, `t` -> `TunnelID`, `s` -> `TunnelSecret`.

### How to convert JSON to token
Just the opposite:
1. Convert keys to short versions: `AccountTag` -> `a`, `TunnelID` -> `t`, `TunnelSecret` -> `s`
2. Remove whitespaces and line ends, if any
3. Encode to base64, probably removing trailing `=` if any.
