### ISSUE TITLE
Issues revoking certificate and related security

### ISSUE THREAD

**Issue by berryk** [cloudflare/cloudflared#93]
Unfortunately my certificate cert.pem may have been compromised, so I wanked to revoke the certificate and generate a new one. 

I removed all certificates from the Origin Certificates section of the Crypto tab in the Cloudflare dashboard, but cloudflared could still log in with the old certificate. 

I then (at the suggestion of Cloudflare support), changed the API key associated with my account in Cloudflare profile section of the Cloudflare dashboard. 

On restarting cloudflared, I now got a message that my certificate had been revoked, but I wass surprised to find the tunnel was still created and active. 

I would suggest a new command line option such as cloudflared tunnel revoke to revoke the currect certificate.

**Comment by r4c-sutees** [comment]
I see there is an option to revoke a tunnel now but not sure is that the same thing?
https://developers.cloudflare.com/argo-tunnel/create-tunnel#revoke-and-delete-a-tunnel

**Comment by TownLake** [comment]
Revoking the Tunnel will also revoke the credentials file issued for the Tunnel. We recommend creating Tunnels with the `cert.pem` file, then distributing the credentials file only (which is all that is needed to run the Tunnel itself now).

**Comment by r4c-sutees** [comment]
> Revoking the Tunnel will also revoke the credentials file issued for the Tunnel. We recommend creating Tunnels with the `cert.pem` file, then distributing the credentials file only (which is all that is needed to run the Tunnel itself now).

@TownLake Thank you for the previous response? 
And just in case a `cert.pem` is compromised, how should we deal with this case?
I'm not sure the original in this issue meaning so, but I'm having a similar question as I after I revoke a tunnel, will it also invalidate the `cert.pem` file as well?

**Comment by TownLake** [comment]
No, it will not invalidate the `cert.pem`. Right now, the only option to invalidate the `cert.pem` would be to delete the user from your account who generated it. We're working on a way to make that easier though.

**Comment by dilsonnn** [comment]
There is still no way to invalidate the certificate?

**Comment by abelinkinbio** [comment]
Right now, we recommend removing this user from your account and rotating the associated keys.

**Comment by haneef95** [comment]
Are we still unable to change or revoke cert.pem?

thanks

**Comment by haneef95** [comment]
Wow! I even deleted the associated API tokens in: https://dash.cloudflare.com/profile/api-tokens

Yet, I'm still able to create new tunnels with the compromised `cert.pem`, which I shouldn't be able to according to this [permissions table](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/create-tunnel#:~:text=Credentials%20file-,Create%20a%20new%20Tunnel,-Required)

Revocability is key to security, @cloudflare-warp-bot please fix this soon!

**Comment by haneef95** [comment]
Also, the authorise page makes it seem like the authorisations is limited to a single zone:
![image](https://user-images.githubusercontent.com/298208/140940455-0acfd6ae-4240-44f7-b827-73a24a84d357.png)

But, the [API token details](https://dash.cloudflare.com/profile/api-tokens) shows the whole account.

Someone please tell me I'm mistaken here (about both of the above comments)

**Comment by tjstansell** [comment]
FWIW, we have a support ticket open regarding these exact issues.  What we've heard from their engineers and what we've derived from our own testing:
1. the personal api token created during the `cloudflared tunnel login` process does apply to the entire account, but also apppears to not ever get used.  After creating multiple tunnels, I can hover over the `active` label on mine and it shows `Last used: Never`.  I've also deleted this without affecting my ability to manage tunnels or run existing tunnels.  I have no idea why this is even created.
2. The origin certificate created during the `cloudflared tunnel login` also appears to be unnecessary.  Maybe it is required for certain features we're not using, but I've deleted it on our end and we're still able to restart existing tunnels and create new ones.  Similar to point 1, I'm not sure why this is even created.
3. The only thing that appears to matter in the `cert.pem` is the `ARGO TUNNEL TOKEN` section.  This is a service token that engineers claim is associated with the user who logged in and _still_ can only be revoked if the user's account is disabled.  We haven't tested this yet and I'm not sure if simply deactivating a user is enough or if re-enabling the user will also re-enable the existing token.  In our internal support ticket (2308756) we've requested that they provide some way to manage these service tokens to allow manual revocations.  Disabling the user account is an unacceptable hack.

**Comment by tv42** [comment]
This issue really should not be closed.

**Comment by mundschenk-at** [comment]
Please re-open this issue and add the possibility to revoke the certificate.

**Comment by hobbes444** [comment]
It seems the workaround does not work anymore. I have assigned domain admin rights to a second cloudflare account, and this account is unable to create a tunnel, the category "tunnels" in the Zero Trust dashboard is locked for this user...

Or am I missing something?

**Comment by mundschenk-at** [comment]
Domain admin is not enough, you need to give the account admin rights,

**Comment by hobbes444** [comment]
right, I tried to limit access to a single domain, that turns off a lot of possible roles. When selecting "all domains", it seems the role "Cloudflare Zero Trust (Can edit Cloudflare Zero Trust)" is sufficient.

**Comment by brenner-tobias** [comment]
Is there any update on this issue? Is the workaround still needed?

**Comment by dtap001** [comment]
update?

**Comment by rogerlancien** [comment]
same issue here can we please get at least a workaround ? thanks

**Comment by byurhannurula** [comment]
Any update on this issue?
@sssilver @abelinkinbio

**Comment by sirlupusdev** [comment]
This is implemented, you can revoke API Tokens (which are present in cert.pem) here: [https://dash.cloudflare.com/profile/api-tokens](https://dash.cloudflare.com/profile/api-tokens)
Do correct me if you're referring to something else.

**Comment by mo-han** [comment]
@sirlupusdev 
so if those api tokens are revoked, then the corresponding cert.pem is inactivated.
even the cert.pem still could be used to login, but it could NOT be used to do anything else.
is that correct?

**Comment by sirlupusdev** [comment]
> even the cert.pem still could be used to login, but it could NOT be used to do anything else.
> is that correct?

I'm not exactly sure what you're referring to. 
If you revoke the API token, the .pem file becomes useless - as far as I can recall from a year back. "Logging in" requires access to read data which is also revoked when deleting the token. 
Or what are you referring to with logging in using the cert?

**Comment by mo-han** [comment]
@sirlupusdev 

I think you are right. The revoked cert
couldn't do anything because it cannot login anymore.
