### ISSUE TITLE
💡Authentication login with patreon subscription

### ISSUE THREAD

**Issue by biast12** [cloudflare/cloudflared#931]
**Describe the feature you'd like**
Authentication login with patreon subscription, so people who are subscripted to my patreon can login to my domain

**Comment by sudarshan-reddy** [comment]
This is not necessarily a feature we should provide. You can still build this around tunnel or try Cloudflare's access offering.

**Comment by biast12** [comment]
also i really don't see how the argument "You can still build this around X and X" changes anything since all of the already provided Authentications on the Zero Trust Authentication panel is all things that can be build in the exact same terms (maybe minus the One-time PIN)

you're seeing if this feature is a need to have feature, while all the other Authentication methods available rn are nice to have features a patreon Authentication is a nice to have too, just one you could earn money from too, but i guess if you don't wanna earn money then idk what to tell you ¯\_(ツ)_/¯
