### ISSUE TITLE
💡Significantly reduce basic Tunnel bandwidth for cell modem

### ISSUE THREAD

**Issue by iicdev** [cloudflare/cloudflared#935]
**Overview**:  We are successfully using a Tunnel at each of 3 customer sites. Sites run a Windows 10 PC for our system which controls HVAC, lighting etc. There are very small regular data exchanges and occasional interactive access across the Tunnel. These sites are accessed via cellular modems, which charge by the MB of bandwidth.  Each site uses 2-4MB per HOUR simply to MAINTAIN the Tunnel, which exceeds what we can charge the customer.

**Objective**: Reduce Tunnel maintenance bandwidth by 5-10x. 

**Not objectives**: We don't care about reducing memory footprint, which you might for a small IoT server, but this is a full laptop. We also don't need high reliability or instant failover because our system is highly resilient.

**Methods we suggest**, controlled by command line or config.yaml params:
#1- Enable us to have only ONE connection, not 4 as is current (see details below).
#2- Reduce amount of all Tunnel maintenance data for each connection. See above - if it's 15-30 seconds until a connection failure is detected, that's acceptable to us.

**Details per #1 above** - we have defined the param proxy-dns-max-upstream-conns to be 1. This does NOT change the number of connections when cloudflared executes, that is still always 4. A brief search of the source seems to indicate that variables set from that user param are not accessed or respected.  We found the following that seem to be involved in that at various levels of execution in cmd.go, server.go, https_upstream.go, perhaps more:
- MaxConnsPerHost
- max-upstream-conns
- maxUpstreamConnections
- TUNNEL_DNS_MAX_UPSTREAM_CONNS

**_Thank you_**. We do not feel qualified to contribute to the project reliably, so we are creating this issue. We posted this on the main community bulletin board and another user has the same issue. This will also be essential for any future IoT version of cloudflared.

**Comment by joliveirinha** [comment]
Hi @iicdev,

Probably what you are looking for is --ha-connections 1 when executing cloudflared.

**Comment by iicdev** [comment]
Thank you. THIS WORKED - now 1 connection, not 4, which reduced bandwidth by 75%.

**This should be reactivated as a documentation request**. That option is not documented anywhere! Very valuable to certain use cases.

Submitted follow-on issue requesting reduction of bandwidth for each connection:
Reduce constant minimum Tunnel connection bandwidth (follow-on issue) #949
