### ISSUE TITLE
🐛Minification issue (core-js): Invalid or unexpected token (

### ISSUE THREAD

**Issue by VivantSenior** [cloudflare/cloudflared#937]
**Describe the bug**
JavaScript minification feature generates invalid javascript code (which is a part of [core-js](https://github.com/zloirock/core-js) library). Cloudflare minification feature changes `1 .toString` to `1.toString`.

**To Reproduce**
1. Speed --> Optimization --> Auto Minify --> enable "JavaScript", "CSS" and "HTML"
2. Speed --> Optimization --> enable "Rocket Loader"
3. Caching --> Configuration --> Caching Level: Standard, Browser Cache TTL: 4 hours
4. Use an application with core-js. In my case it is [zigbee2mqtt-frontend](https://github.com/nurikk/zigbee2mqtt-frontend) which is a frontend for [zigbee2mqtt](https://github.com/Koenkk/zigbee2mqtt).

**Expected behavior**
Javascripts to be minified to a working js file.

**Environment and versions**
 - OS: Home Assistant OS (zigbee2mqtt-frontend is in a docker)
 - Architecture: ARM v8
 - Version: zigbee2mqtt-fronend: 0.6.127

**Logs and errors**
```
index.c0cc3410.js:1 Uncaught SyntaxError: Invalid or unexpected token (at index.c0cc3410.js:1:5577)
    at t.activateScript (rocket-loader.min.js:1:11855)
    at rocket-loader.min.js:1:11052
    at t.run (rocket-loader.min.js:1:11259)
    at P (rocket-loader.min.js:1:3128)
    at Object.callback (rocket-loader.min.js:1:2851)
    at t.run (rocket-loader.min.js:1:11340)
    at rocket-loader.min.js:1:2907
    at rocket-loader.min.js:1:8117
```

**Additional context**
[Post on Cloudflare community](https://community.cloudflare.com/t/minification-produces-invalid-javascript/406236) describes where the issue is.

Files in question:
[rocket-loader.min.js.txt](https://github.com/cloudflare/cloudflared/files/11199103/rocket-loader.min.js.txt)
[index.c0cc3410.js.txt](https://github.com/cloudflare/cloudflared/files/11199104/index.c0cc3410.js.txt)

**Comment by sudarshan-reddy** [comment]
This is not a Cloudflare Tunnel issue. (This repository is meant for that). Could you open a support ticket with Cloudflare instead? 

@eaufavor fyi.

**Comment by VivantSenior** [comment]
Thank you for the prompt response.

Unfortunately I'm on a free account where the [support in not provided](https://developers.cloudflare.com/support/troubleshooting/general-troubleshooting/contacting-cloudflare-support/#methods-of-contacting-cloudflare-support) (just paying for the domain). The recommendation is to use the [Community](https://community.cloudflare.com/) but this issue has been already [raised by the community](https://community.cloudflare.com/t/minification-produces-invalid-javascript/406236) 6,5 months ago.

**Comment by sudarshan-reddy** [comment]
I'll see if I can get it viewed by the right people.

**Comment by VivantSenior** [comment]
@sudarshan-reddy, have you managed to contact the right people?

**Comment by MivraMe** [comment]
Hi, i have the same issues
![image](https://github.com/user-attachments/assets/57fce5b0-751d-45cc-812c-104a80141a91)
