### ISSUE TITLE
🐛 before and after name server is Same 

### ISSUE THREAD

**Issue by Mdsarowarhossain** [cloudflare/cloudflared#940]
when am add a new site in the confirmation email the before and after name server is Same 
![Screenshot_20230414-221802](https://user-images.githubusercontent.com/98280301/232101401-83d68145-e58b-4549-8561-b688db3815c3.jpg)

**Comment by obezuk** [comment]
Hi, this issue tracker is intended for tracking issues within for our open source software connector cloudflared. This looks like an issue during domain name registration. Please see this page for how to ask for help: https://developers.cloudflare.com/support/troubleshooting/general-troubleshooting/contacting-cloudflare-support/
