### ISSUE TITLE
🐛 (k8s) Image fails security validation when configured to run with `runAsNonRoot:true`

### ISSUE THREAD

**Issue by nairb774** [cloudflare/cloudflared#941]
**Describe the bug**

The published docker image is unable to be run on Kubernetes (1.22) with the security setting `runAsNonRoot:true` enabled.

**To Reproduce**
1. Start with the configuration found at: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/deployment-guides/kubernetes/#routing-with-cloudflare-tunnel 
2. Add a `securityContext` section for the container, and specify `runAsNonRoot:true`.
3. Deploy and see the pods fail to start due to the following error:

> Error: container has runAsNonRoot and image has non-numeric user (nonroot), cannot verify user is non-root

**Expected behavior**

The image would run just as if that validation setting wasn't specified.

**Environment and versions**
 - OS: Bottlerocket OS 1.22 EKS
 - Architecture: x86_64
 - Version: `cloudflare/cloudflared@sha256:5e1cc6ae480a64ad8550bf974d5e153ed85fb191f927dfa02ffb5db867dfb2b3` aka 2023.4.0

**Logs and errors**
If applicable, add logs or errors to help explain your problem.

**Additional context**

It is highly likely that the only thing that needs to be done to make this work is to actually just delete this line: https://github.com/cloudflare/cloudflared/blob/71997be90eacb046a30893bbe192592b3afd0d6e/Dockerfile#L27

The base image is already configured to run as nonroot, and I've got a few images that derive from that base which work with the `runAsNonRoot` setting turned on.

**Comment by obezuk** [comment]
Hi, thanks for raising this. This looks like something we should reconsider, you're welcome to file a pull request and we'll review it.
