### ISSUE TITLE
Is there any way I can check the status of the tunnel with python?  

### ISSUE THREAD

**Issue by kerferber** [cloudflare/cloudflared#943]
Is there any way I can check the status of the tunnel with python?

I'm using cloudflare tunnel on my raspberry pi and in the future I would like to display the status on an oled monitor to see if everything is working

**Comment by obezuk** [comment]
We have a few options depending on how you're wanting to tackle this. Myself, I use Cloudflare's built-in [notifications](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/tunnel-monitoring/notifications/) to send a webhook to a chat room if a Tunnel is offline and display Tunnel metrics via [Grafana using the Prometheus metrics](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/grafana/) endpoint.

If you're looking to build something in Python, then a good place to start would be polling the [List Cloudflare Tunnels API](https://developers.cloudflare.com/api/operations/cloudflare-tunnel-list-cloudflare-tunnels) and reading the `status` property.
