### ISSUE TITLE
Add optional flag for useing custom dns💡

### ISSUE THREAD

**Issue by MOOGAA** [cloudflare/cloudflared#944]
Im a termux user and i don't like starting hotspot for local dns to kick in every time it consume a bit of battery for kind of pointless task , i suggest there should be a flag which can be used to use the remote dns in cloudflared , so i don't hav to start hotspot every time i wanna access any tunnel

I currently don't see any alternative for solving it not a Android dev. But add some other dna other than `127.0.0.1:53` will be a nice decision.

**Comment by obezuk** [comment]
Can you explain what problem you're trying to solve and why you are installing cloudflared on a mobile device?
