### ISSUE TITLE
institute has blocked the cloudflare warp dns resolving function so cannot play games , please provide a way to bypass this . Thank you💡

### ISSUE THREAD

**Issue by Satyam54784** [cloudflare/cloudflared#947]
**Describe the feature you'd like**
A clear and concise description of the feature. What problem does it solve for you?

**Describe alternatives you've considered**
Are there any alternatives to solving this problem? If so, what was your experience with them?

**Additional context**

**Comment by obezuk** [comment]
This project is intended to track software issues relating to our server-side connector software `cloudflared`. We cannot provide guidance on how to circumvent your institutes DNS policy.
