### ISSUE TITLE
Some discontinued releases (2023.4.2)

### ISSUE THREAD

**Issue by w35l3y** [cloudflare/cloudflared#950]
Were some releases discontinued in the latest version (2023.4.2) ?

https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#linux

![Screenshot_20230424_215607_Samsung Internet](https://user-images.githubusercontent.com/963510/234149348-907c6db8-f73f-4b90-b317-c97b05f44601.jpg)

All these in red return 404 Not Found

**Comment by sudarshan-reddy** [comment]
Thanks for noticing. These aren't discontinued. It seems like we were unlucky to try to make a release during a gh incident: https://www.githubstatus.com/incidents/rcnl10p4hywg. 

The missing releases should now be present.
