### ISSUE TITLE
🐛2023.4.2 Latest version does not compile cloudflared-linux-amd64.deb.

### ISSUE THREAD

**Issue by fscarmen** [cloudflare/cloudflared#951]
**Describe the bug**
There is not include a cloudflared-linux-amd64.deb release in https://github.com/cloudflare/cloudflared/releases/tag/2023.4.2

**Comment by sudarshan-reddy** [comment]
Thanks for noticing so promptly. This is now fixed. It seems like we had issues connecting to gh at the time of the release: https://www.githubstatus.com/incidents/rcnl10p4hywg

**Comment by fscarmen2** [comment]
So do cloudflared-linux-arm64.deb. Please fix it . Thanks.

**Comment by fscarmen** [comment]
So do cloudflared-linux-arm64.deb. Please fix it . Thanks.
