### ISSUE TITLE
🐛2023.4.2 Release missing a .deb package and checksums?

### ISSUE THREAD

**Issue by JVimes** [cloudflare/cloudflared#952]
The ARM64 Debian package seems missing from [releases/tag/2023.4.2](https://github.com/cloudflare/cloudflared/releases/tag/2023.4.2) (haven't checked other packages). Also I don't see checksums.

The missing package breaks the "Install and run a connector" instructions for ARM64 when setting up a tunnel in the web interface.

![image](https://user-images.githubusercontent.com/6148201/234324457-4fda82ad-c189-449d-a341-127f6b044018.png)

**Comment by sudarshan-reddy** [comment]
Indeed. We are aware of this. This is a release that failed because of a github incident at that time. We are working on fixing it ASAP.

**Comment by JVimes** [comment]
Thanks for the great work!
