### ISSUE TITLE
💡 Possible method to make "--edge-ip-version 6" the default?

### ISSUE THREAD

**Issue by 2ndMessiah** [cloudflare/cloudflared#954]
**Describe the feature you'd like**

My machine has only ipv6...So I'd like to connect to CF using ipv6.

I'm using cmd line and config.yml to configure the tunnel and installed the CF tunnel as a service.

I only find the way to specify the edge IP version by adding "--edge-ip-version" to "cloudflared tunnel run" cmd.

Can ipv6 be the default when it runs as a service? Could I write it in config.yml or somewhere?

Thx.

**Describe alternatives you've considered**
no.

**Additional context**
no.

**Comment by obezuk** [comment]
Thanks for filing this request, you also have the option of setting this as an environment variable: `TUNNEL_EDGE_IP_VERSION=6`

Since your network is IPv6 only, it sounds like the underlying issue is it does not automatically use IPv6. It sounds like if we defaulted to auto this would have worked normally for you?

```
cloudflared --help | grep edge-ip-version
   --edge-ip-version value                      Cloudflare Edge IP address version to connect with. {4, 6, auto} (default: "4") [$TUNNEL_EDGE_IP_VERSION]
```

**Comment by 2ndMessiah** [comment]
> Thanks for filing this request, you also have the option of setting this as an environment variable: `TUNNEL_EDGE_IP_VERSION=6`
> 
> Since your network is IPv6 only, it sounds like the underlying issue is it does not automatically use IPv6. It sounds like if we defaulted to auto this would have worked normally for you?
> 
> ```
> cloudflared --help | grep edge-ip-version
>    --edge-ip-version value                      Cloudflare Edge IP address version to connect with. {4, 6, auto} (default: "4") [$TUNNEL_EDGE_IP_VERSION]
> ```

Thx for your help！ I forced it to use ipv6 by editing its systemd service conf！
