### ISSUE TITLE
🐛Release 2023.4.2 reports being version 2023.4.1

### ISSUE THREAD

**Issue by Nuru** [cloudflare/cloudflared#957]
## Some binaries released as version 2023.4.2 display other version numbers

Binary at https://github.com/cloudflare/cloudflared/releases/download/2023.4.2/cloudflared-linux-amd64 should report being version 2023.4.2 but instead:

```
$ cloudflared --version 
cloudflared version 2023.4.1-10-g38cd455e (built 2023-04-25-0705 UTC)
$ sha256sum cloudflared 
7e48b3d91f44badc1b4c2bd446ef1c4ae4c824840d594bd353cf20cba5fd1cef  cloudflared
```

## Verified correct

I did not check all the binaries. These I checked and reported being version 2023.4.2:

- https://github.com/cloudflare/cloudflared/releases/download/2023.4.2/cloudflared-darwin-amd64.tgz (unpacked binary SHA 1154f3b2c31f4727c076c3e08024887be0e0a0b68a89e4f88f286f6f6196ac74 )
- https://github.com/cloudflare/cloudflared/releases/download/2023.4.2/cloudflared-linux-arm64 (SHA e453b576d0db95e4e9b7f511bb379f6b0b0a73924da678655875c2c295b95627)

**Comment by obezuk** [comment]
Thanks for reporting, I just checked the latest version and 2023.05.0 and it reported the correct version so will close this.
