### ISSUE TITLE
cloudflared returning zero exit code on error

### ISSUE THREAD

**Issue by cblecker** [cloudflare/cloudflared#96]
If cloudflared starts up before networking and DNS resolution is up and running, it will throw an error and exit. However, this error is returning a zero/success exit code.. as such launchd on Darwin sees that the application intended to exit, and doesn't restart it.

```
$ cloudflared
INFO[0000] Build info: {GoOS:darwin GoVersion:go1.11.1 GoArch:amd64} 
INFO[0000] Version 2019.4.1                             
INFO[0000] Flags                                         hostname=example.com proxy-dns-upstream="https://1.1.1.1/dns-query, https://1.0.0.1/dns-query" url="ssh://127.0.0.1:22"
INFO[0000] cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/ 
INFO[0000] Starting metrics server                       addr="127.0.0.1:49693"
INFO[0000] Proxying tunnel requests to http://127.0.0.1:49694 
ERRO[0000] Error looking up Cloudflare edge IPs: the DNS query failed: lookup _warp._tcp.cloudflarewarp.com on [::1]:53: read udp [::1]:52309->[::1]:53: read: connection refused 
ERRO[0000] Please try the following things to diagnose this issue: 
ERRO[0000]   1. ensure that cloudflarewarp.com is returning "warp" service records. 
ERRO[0000]      Run your system's equivalent of: dig srv _warp._tcp.cloudflarewarp.com 
ERRO[0000]   2. ensure that your DNS resolver is not returning compressed SRV records. 
ERRO[0000]      See GitHub issue https://github.com/golang/go/issues/27546 
ERRO[0000]      For example, you could use Cloudflare's 1.1.1.1 as your resolver: 
ERRO[0000]      https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ 
INFO[0000] ResolveEdgeIPs err                           
ERRO[0000] Quitting due to error                         error="Could not lookup srv records on _warp._tcp.cloudflarewarp.com: lookup _warp._tcp.cloudflarewarp.com on [::1]:53: read udp [::1]:52309->[::1]:53: read: connection refused"
INFO[0000] Metrics server stopped                       
$ echo $?
0
$ 
```

If instead this reported a non-zero exit code, launchd would see that the process failed and it should attempt to restart it.

**Comment by nickvollmar** [comment]
Potential fixes:
* sticking within the context of the cli framework, we can have the "Could not lookup srv records" error implement https://godoc.org/github.com/urfave/cli#ExitCoder
* or we could fix it at a level "beneath" the cli framework by checking all the errors ourselves.

**Comment by cblecker** [comment]
I believe #99 should fix this.

**Comment by vidarak** [comment]
Cloudflared should NOT behave any different at startup than it behaves after starting up in terms of error handling. After starting up (and successfully connecting to backend), if any condition occurs, it simply keeps running and logs error to log file. This should be the behaviour on startup to: it should not exit, but instead keep attempting to reach backend and cloudflare while logging the errors.
