### ISSUE TITLE
📝Please add info about the implementation of tunnel encryption to the FAQ

### ISSUE THREAD

**Issue by CaptShmo** [cloudflare/cloudflared#962]
**Available Documentation**
FAQ: https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/
Also some wording here: https://www.cloudflare.com/products/tunnel/

**Suggested Documentation**
The cloudflare tunnel product description seems to imply that all tunnels are encrypted by default without configuration, but I wanted to double-check to make sure that I'm reading this correctly, see the next section for more info.

**Additional context**
In the product description for the Tunnel, it states: "The Tunnel daemon creates an encrypted tunnel between your origin web server and Cloudflare’s nearest data center, all without opening any public inbound ports." Great, but I have some questions and I thought maybe other people might have the same questions and maybe the FAQ should include this info. I couldn't find any info in the FAQ or elsewhere the explicitly states that encryption is ON by default and that all tunnel traffic is encrypted without having to set up anything extra after I have installed cloudflared on my server and connected it to cloudflare. Here's my situation so you can see why I need this to be clarified:

1) I have a server running with a static IP running a nodejs web application.
2) Cloudflare is managing my domain/dns. 
3) This nodejs application does NOT support using an SSL cert with its traffic natively.
4) I can't run a reverse proxy on this server to handle SSL for reasons beyond my control.
5) I have my cloudflare TLS/SSL encryption mode setting set to "FULL".

So, I currently have the tunnel set up with cloudflare managing my DNS, and the tunnel public hostname is setup to direct https://myapp.mydomain.com traffic to http://[my-server-ip-address]:8080. Please note that the receiving end is HTTP, not HTTPS. This configuration is currently working, I can access the web app though https without any browser warning. All ingress ports on [my-server-ip-address] have been disabled, so the traffic is definitely going through the tunnel or it would be unreachable. 

My question is, can I be confident that even though I am going from cloudflare HTTPS through the tunnel to HTTP on my server, that the tunnel guarantees this traffic is encrypted at all times until cloudflared unwraps it on my-server.

If yes, this is the case, please explain the mechanism cloudflared is using for the encryption (certs/ciphers/etc). If no, is there a way to set it up to be secure by providing it a certificate or some other mechanism, as doing it for the actual nodejs web app might not be possible in the short term.

Thanks so much, great product so far.

**Comment by obezuk** [comment]
All tunneled traffic is encrypted by default, there is no way to configure a non-encrypted Tunnel. The reason you do not need to set up any certificates is because cloudflared acts as a _client_, and establishes outbound connections to Cloudflare's networks, which acts as a _server_ and is configured with TLS certificates.

We'll look into making this clearer in the developer documentation.

**Comment by CaptShmo** [comment]
Okay, that is sort of what I inferred but I needed to give some cloudflare confirmed guarantees to a client before using this product, thanks so much!
