### ISSUE TITLE
💡Support UDP for public services

### ISSUE THREAD

**Issue by alexstaeding** [cloudflare/cloudflared#964]
**Describe the feature you'd like**
I attempted to create a tunnel for a public-facing game server that runs on UDP. After browsing the issues here (specifically #215) and [this](https://blog.cloudflare.com/extending-cloudflares-zero-trust-platform-to-support-udp-and-internal-dns/) blog post - it seems as though UDP is supported but only in private networks (i.e. having to install a client).

For many services it is not viable to force users to install a client.

It would be very useful if UDP is added to the supported protocols for *public* networks.

**Comment by darth-pika-hu** [comment]
It is now supporting QUIC which is UDP.

**Comment by alexstaeding** [comment]
> It is now supporting QUIC which is UDP.

QUIC is based on UDP but they are not the same. It is still not possible to select UDP in this dropdown:
![image](https://user-images.githubusercontent.com/24614463/235733686-bb2d3139-03ca-437c-9819-10a9aba58d46.png)

**Comment by darth-pika-hu** [comment]
I see. Is https possible for you?

**Comment by obezuk** [comment]
Thanks for filing this request. This issue register in this project is intended for filing issues relating to cloudflared. Today public game servers can be protected by Cloudflare using Spectrum, but it does not yet integrate with Tunnels. This is a really cool idea, so I recommend filing this under the [feedback channel](https://community.cloudflare.com/c/feedback/25) of [community.cloudflare.com](https://community.cloudflare.com/)
