### ISSUE TITLE
💡 Ability to update locally managed cloudflared configuration (without dropping connections)

### ISSUE THREAD

**Issue by basro** [cloudflare/cloudflared#965]
**Describe the feature you'd like**
I'd like to have a way of updating or reloading a locally managed cloudflared ingress configuration without having to restart it. All existing http / websockets / tcp connections should survive this process. New connections would be routed according to the new ingress rules.

**Describe alternatives you've considered**
I believe it's possible to do this using remotely managed tunnels, although I have not yet tested if an existing connection will survive an ingress configuration update using this method.

**Additional context**
I believe cloudflared has the potential to completely replace some of the use cases for automatically reconfiguring reverse proxies like [traefik](https://github.com/traefik/traefik), [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy), [nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy).

These reverse proxies will scan the docker containers that are running in the system and look for labels that indicate that the container wants to receive traffic from a given domain. That way the reverse proxy configuration is automatically updated any time you start or stop containers. They are able to do this without dropping any existing connections.

If cloudflared had a way to update the configuration it would be possible to make an easy to use cloudflared-docker-proxy container that works in the same way as these other reverse proxies.

**Comment by obezuk** [comment]
Thanks for filing this request, we'll consider this request.

Today we recommend using multiple [instances of cloudflared](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/deploy-cloudflared-replicas/) to ensure the service remains available while swapping cloudflared, or alternatively you can switch to remotely managed tunnels which automatically push configuration to your Tunnel.
