### ISSUE TITLE
💡 How to know the domain name corresponding to that certificate.

### ISSUE THREAD

**Issue by fscarmen** [cloudflare/cloudflared#969]
**Describe the feature you'd like**

I was run `cloudflared login` and then choose the domain. I got the certificate at /root/.cloudflared/cert.pem.
My question is how do I know the previous domain name via `cloudflared` if I forget the previous one I chose?

**Comment by obezuk** [comment]
You can identify the zoneId the certificate was created for decoding a subset of the certificate:

Open the cert.pem file in a text editor and find the ARGO TUNNEL TOKEN segment that looks like:

```
-----BEGIN ARGO TUNNEL TOKEN-----
ey...==
-----END ARGO TUNNEL TOKEN-----
```

Decoding this base64 encoded token returns a JSON object that includes the Zone ID. From here you may copy the zone id, or here is an example of how to extract it via the command line using JQ.

`echo "ey...==" | base64 --decode | jq -r .zoneID`

This is the Zone ID the certificate was created for, you can look up the domain for this zone ID using our API: https://developers.cloudflare.com/api/operations/zones-0-get
