### ISSUE TITLE
🐛 Can't use Path on public hostnames for TCP connections?

### ISSUE THREAD

**Issue by ShadowXVII** [cloudflare/cloudflared#971]
**Update:** It seems that there's an issue with rule precedence and path selectors for TCP connections.
At this time, a more specific rule (i.e. one with a Path, for example) doesn't correctly get picked up (but a * would when it shouldn't be picked first, whether by order priority or specificity).

Replicated by support with Cloudflare Ticket 2806181.

----

_My example below uses RDP, but in the end it's just arbitrary TCP._

_My overall thought is that a TCP (layer 4) reverse proxy doesn't have the concept of paths (layer 7), so why can't paths be used in this instance to distinguish different public hostnames from one another? Cloudflare proxy would process the L7 request..._

----

**Describe the bug**
If I don't specify a path, I can connect fine when using `cloudflared access rdp`.

If I do specify a path, then I can't connect -- I get a `"ERR failed to connect to origin error="websocket: bad handshake""` when trying using the RDP client (the RDP client sees an "internal error") 

Paths are useful to help reduce the amount of subdomains used -- in the instance of RDP, is there any reason it shouldn't work? RDP connections have no concept of paths, so they shouldn't really be passed along to the endpoint as part of the proxied request?

Does the same apply to SSH? (untested)

**To Reproduce**
1. Create a public hostname with a path pointing to an RDP endpoint
2. Run `cloudflared access rdp --hostname <path> --url localhost:50000`
3. Try connect via RDP to localhost:50000
4. Observe error in cloudflared lo

If it's an issue with Cloudflare Tunnel:
5. Tunnel ID : 
6. cloudflared config: 

**Expected behavior**
It should connect no matter if a path is used or not?

**Environment and versions**
 - OS: Windows
 - Architecture: AMD64
 - Version: 2023.5.0

**Logs and errors**
![image](https://github.com/cloudflare/cloudflared/assets/446329/b88501dc-adc0-4e1c-8c0e-5fe7bbae0025)

**Comment by ShadowXVII** [comment]
Wait, this is suddenly working. Will try come back with more testing results soon.

**Comment by obezuk** [comment]
Thanks for submitting this ticket. At this time paths are not supported with TCP applications today. Makes sense that it would be useful to reduce the number of hostnames.

**Comment by ShadowXVII** [comment]
Hi @obezuk , thanks for your reply. I saw this was closed, is it tracked internally as a suggestion for improvement?
