### ISSUE TITLE
💡SSH with key and a user account password

### ISSUE THREAD

**Issue by jacyker** [cloudflare/cloudflared#985]
Hi

Is there an option to connect to SSH through a web browser when access requires both an SSH key and a user account password?

**Comment by obezuk** [comment]
Thanks for filing this request. This issue register in this project is intended for filing issues relating to the cloudflared software. This request relates to Access's browser-based SSH terminal. This kind of requests should be submitted to the [feedback channel](https://community.cloudflare.com/c/feedback/25) of [community.cloudflare.com](https://community.cloudflare.com/), or your account manager.
