### ISSUE TITLE
💡Support for token parameter in tunnel credential file

### ISSUE THREAD

**Issue by jamurtag** [cloudflare/cloudflared#991]
**Describe the feature you'd like**
We are deploying tunnels via Kubernetes using the official image, we are also migrating to 'remote' tunnels which require passing the `--token` flag via container args. However, the image does not appear to support Kubernetes env vars (referenced from a Kubernetes secret), I assume due to the base distroless image. This means the token argument is visible in deployment / pod manifests.

Previously in 'local' tunnel configuration mode, the config file used `credentials-file` to load the tunnel secret, mapped via a Kuberntes secret volume mount to the filesystem.

It would be useful if the credential file also supported a token field, which  could be used instead of the --token argument.

**Describe alternatives you've considered**
Passing the --token argument directly, however this means it is visible in clear text in kubernetes objects.

Building an image using a different base, but that is extra overhead and removes some security benefits of distroless images.

**Additional context**
n/a

**Comment by Cyb3r-Jak3** [comment]
You can pass the token via `TUNNEL_TOKEN` environment variable if that helps.

**Comment by obezuk** [comment]
+1 to @Cyb3r-Jak3's suggestion. Store the token as a Secret in Kubernetes, and configure the cloudflared pod to use a [Secret Environment](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) variable for [TUNNEL_TOKEN](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/arguments/#token).
