### ISSUE TITLE
💡Update Cloudflared tunnel to the latest version

### ISSUE THREAD

**Issue by ProxyNery** [cloudflare/cloudflared#993]
I spinned up the ARGO Tunnel inside my Home Assistant which working fine but the tunnel version it out to date:

The following message is showing up in the log section:

version 2023.5.1 is outdated. We recommend upgrading it to 2023.6.0

When will this available?

**Comment by obezuk** [comment]
It's available now. https://github.com/cloudflare/cloudflared/releases/tag/2023.6.0 You might have seen that message while the packages were being deployed.
